### ISSUE TITLE
nmo_brooklyn clip edits for smoother gameplay

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#1003]
Found in src-r4487/dev-r8826.

![20180604190827_1](https://user-images.githubusercontent.com/15934200/40951607-a061d126-682c-11e8-943e-9e527ed0eb00.jpg)
![20180604190910_1](https://user-images.githubusercontent.com/15934200/40951608-a07c8408-682c-11e8-9ede-93c249dde51e.jpg)
![20180604190951_1](https://user-images.githubusercontent.com/15934200/40951610-a0974c66-682c-11e8-95dd-5dc5a5f3ee3b.jpg)
![20180604191002_1](https://user-images.githubusercontent.com/15934200/40951611-a0b2d954-682c-11e8-8f38-03435679b4ac.jpg)
![20180604191057_1](https://user-images.githubusercontent.com/15934200/40951612-a0cd1878-682c-11e8-90a9-c9f38aba7b16.jpg)
![20180604191118_1](https://user-images.githubusercontent.com/15934200/40951614-a0e7f6fc-682c-11e8-8711-66cfdce98571.jpg)
![20180604191132_1](https://user-images.githubusercontent.com/15934200/40951615-a10a1e80-682c-11e8-8064-afeb2c25799d.jpg)
![20180604191157_1](https://user-images.githubusercontent.com/15934200/40951617-a13673f4-682c-11e8-9ca1-0534805fe3a7.jpg)
![20180604191326_1](https://user-images.githubusercontent.com/15934200/40951618-a1633812-682c-11e8-8211-72d33da86750.jpg)
![20180604191423_1](https://user-images.githubusercontent.com/15934200/40951619-a17e2a1e-682c-11e8-93ac-b570cc2a1fce.jpg)
![20180604191447_1](https://user-images.githubusercontent.com/15934200/40951621-a19b78da-682c-11e8-9e28-49024a99bfc7.jpg)
![20180604191535_1](https://user-images.githubusercontent.com/15934200/40951622-a1c97c30-682c-11e8-8b17-b218fa87e084.jpg)
![20180604191546_1](https://user-images.githubusercontent.com/15934200/40951623-a1f936b4-682c-11e8-8046-711008ca7b8c.jpg)
![20180604191632_1](https://user-images.githubusercontent.com/15934200/40951624-a2278bf4-682c-11e8-8379-a52f53bfe592.jpg)

**Comment by AtheistNMRiH** [comment]
revisited some clips in r8964, won't fix others

**Comment by Winning117** [comment]
![40951618-a1633812-682c-11e8-8211-72d33da86750](https://user-images.githubusercontent.com/15934200/74611746-a83a9100-50b3-11ea-9c0d-e6b1eb4f7a15.jpg)
I think this one is important to fix, players expect to be able to hop down from this wall and zombies can still kill you on the wall.

**Comment by Winning117** [comment]
Confirmed fixed except for this one, I think it's important because the wall isn't very high at all and players expect to be able to jump over it 
![40951618-a1633812-682c-11e8-8211-72d33da86750](https://user-images.githubusercontent.com/15934200/74630226-f9c43980-510e-11ea-98b3-41b716a9b687.jpg)

**Comment by AtheistNMRiH** [comment]
well, you can already "confuse" zombies if you just jump over fence, if i'll remove this clip I'll need to add nav_jumps there — even more confusing for zombies and easiness for players, so I decided to leave it as it is (also I don't want to make this wall higher)

**Comment by Winning117** [comment]
Yeah I guess it's better than nav_jumps. Resolved then 👍🏼
