### ISSUE TITLE
nmo_cabin clip edits for smoother gameplay

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#1004]
Found in src-r4487/dev-r8826.

![20180604193441_1](https://user-images.githubusercontent.com/15934200/40952268-72087480-682f-11e8-8a85-bac130de7623.jpg)
![20180604193459_1](https://user-images.githubusercontent.com/15934200/40952269-72218eca-682f-11e8-86e6-26f88d7b5c95.jpg)
![20180604193552_1](https://user-images.githubusercontent.com/15934200/40952270-72389dfe-682f-11e8-97e9-b34b71cc1629.jpg)
![20180604193604_1](https://user-images.githubusercontent.com/15934200/40952271-72501128-682f-11e8-9db8-2bb9e10789ad.jpg)
![20180604193613_1](https://user-images.githubusercontent.com/15934200/40952273-726aa574-682f-11e8-88d7-93115e9ffea5.jpg)
![20180604193631_1](https://user-images.githubusercontent.com/15934200/40952274-72861872-682f-11e8-8bd6-6076ee6f5f64.jpg)
![20180604193651_1](https://user-images.githubusercontent.com/15934200/40952275-72a9295c-682f-11e8-93e9-476ea7e5e5dc.jpg)
![20180604193701_1](https://user-images.githubusercontent.com/15934200/40952277-72d009be-682f-11e8-901f-70b0d262e83f.jpg)
![20180604193710_1](https://user-images.githubusercontent.com/15934200/40952278-72f6cdce-682f-11e8-88ad-413abd983c5d.jpg)

**Comment by Winning117** [comment]
Supposedly fixed in r8917, need to check.

**Comment by Winning117** [comment]
None of these were fixed in r8917.

**Comment by Winning117** [comment]
From Dysphie: "it's not the clips that need to be removed, it's the map that needs to be edited to better reflect they're there. Like stacking boxes"

**Comment by AtheistNMRiH** [comment]
revisited some clips in r8963, won't fix others

**Comment by Winning117** [comment]
What changed exactly? I went to all locations and they appear to be the same.

**Comment by Winning117** [comment]
Confirmed fixed by r8963
