### ISSUE TITLE
[Public] Unreasonably long zombie attack range

### ISSUE THREAD

**Issue by SCHATTENSPIEL** [nmrih/source-game#1007]
So, recently I found some evidence of zombies attacking you from very far away, way past their intended range. Here is the footage: https://youtu.be/quCcOipYPcE?t=34

I think this bug is related to the "**Inconsistent pushback**" posted by **HolyCrap**. Here it's his post: 
https://github.com/nmrih/source-game/issues/831

It may be related to the schedule problems that **DDysphie** was trying to show here: "https://github.com/nmrih/source-game/issues/831"

**Comment by felis-catus** [comment]
Did #831's fix resolve this?

**Comment by essbuh** [comment]
This should be fixed by src-r4881

**Comment by Holycrapjimhox** [comment]
Confirmed fix in r8975.
