### ISSUE TITLE
Don't see Cyrylic or Japanese fonts.

### ISSUE THREAD

**Issue by Winterwolf** [nmrih/source-game#1008]
No fonts in game menu, chat or over characters (no nicknames).

![screenshot](https://user-images.githubusercontent.com/405685/41639583-0ba71f18-7467-11e8-8cdf-a57f00eae0dd.png)

... and another problem that I found today: backspace, arrows and may other buttons doesn't work. I can write in the chat (only in English) but can't erase what I wrote and can't vote with F-keys.

<details> 
  <summary>System Info</summary>

```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Phenom(tm) II X4 945 Processor
    CPU Family:  0x10
    CPU Model:  0x4
    CPU Stepping:  0x3
    CPU Type:  0x0
    Speed:  3000 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Supported
    SSE41:  Unsupported
    SSE42:  Unsupported
    AES:  Unsupported
    AVX:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "Manjaro Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.14.48-2-MANJARO
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11906000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-beta-release_2017-10-05

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 465/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 390.59
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x6c4
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 18,82" x 10,59" (21,57" diag)
                                            47,8cm x 26,9cm (54,8cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 1024 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: VIA VT1708S

Memory:
    RAM:  3948 Mb

Miscellaneous:
    UI Language:  Russian
    LANG:  ru_RU.utf8
    Total Hard Disk Space Available:  344342 Mb
    Largest Free Hard Disk Block:  146825 Mb
    VR Headset: None detected
```
</details>

**Comment by Winterwolf** [comment]
Nevermind. I already removed this shitty game. It crashes every hour and lags as hell. Not optimized and not playable on Linux at all.

**Comment by DDysphie** [comment]
Why not leave the issue opened then so things can be improved?

**Comment by Winterwolf** [comment]
@DDysphie The game has so many problems with Linux, that this issue is just a trifle. It seems that the developers simply don't care about this platform.

**Comment by DDysphie** [comment]
Linux issues are being addressed. Making assumptions isn't helpful nor is closing legitimate issues. You're free to open a separate thread for anything else you might find.

**Comment by Winterwolf** [comment]
Okay.

**Comment by Bubka3** [comment]
You can try: https://wiki.archlinux.org/index.php/Steam/Troubleshooting#Text_is_corrupt_or_missing

Keep in mind that for Source Engine on Linux, a Debian based Linux distribution (Linux Mint, Ubuntu...) is recommended.

**Comment by Winterwolf** [comment]
@Bubka3 yes, I've google this issue before posting. `steam-fonts` package is installed. It didn't help.

**Comment by Winterwolf** [comment]
Symbolic link /etc/fonts/conf.d/70-no-bitmaps.conf and file ~/.config/fontconfig/conf.d/20-no-embedded.conf also created.

**Comment by Winterwolf** [comment]
Actually, I didn't create 20-no-embedded.conf before, so now I'll try to install the game again and check it out. But my main issue is not a fonts, it is a performance! FPS falls so bad when I see another players, even on lowest settings.

**Comment by Winterwolf** [comment]
No changes after completing all instructions on the arch-wiki.

**Comment by Bubka3** [comment]
As I mentioned on the other thread -- if you experience this issue on Ubuntu please feel free to let us know.
