### ISSUE TITLE
[dev-r8832] Can't send input in-game after playing demo

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1012]
1. Play a demo where gameui_activate is called. Let it play till the end (you can change the speed)
Example: [demo_noinput.zip](https://github.com/nmrih/source-game/files/2200452/demo_noinput.zip)
(requires `nmo_subside_v5.bsp`)
2. Start a match

You should see the cursor flicker on screen and you're unable to move.
I've been getting this a lot as of late and never in the public build.

<details> 
  <summary>System info</summary>
    Computer Information:
    Manufacturer:  To Be Filled By O.E.M.
    Model:  To Be Filled By O.E.M.
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i5 CPU         650  @ 3.20GHz
    CPU Family:  0x6
    CPU Model:  0x25
    CPU Stepping:  0x5
    CPU Type:  0x0
    Speed:  3213 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Windows 10 (64 bit)
    NTFS:  Supported
    Crypto Provider Codes:  Supported 311 0x0 0x0 0x0

Video Card:
    Driver:  Intel(R) HD Graphics
    DirectX Driver Name:  igdumdx32.dll
    Driver Version:  8.15.10.2900
    DirectX Driver Version:  8.15.10.2900
    Driver Date: 11 26 2012
    OpenGL Version: 1.1
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 59 Hz
    DirectX Card: Intel(R) HD Graphics
    VendorID:  0x8086
    DeviceID:  0x42
    Revision:  0x18
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    No SLI or Crossfire Detected
    Primary Display Resolution:  1366 x 768
    Desktop Resolution: 1366 x 768
    Primary Display Size: 16.14" x 9.06" (18.50" diag)
                                            41.0cm x 23.0cm (47.0cm diag)
    Primary Bus Type Not Detected
    Primary VRAM: 731 MB
    Supported MSAA Modes Not Detected

Sound card:
    Audio device: Headphone (VIA HD Audio(Win 10)

Memory:
    RAM:  1719 Mb

Miscellaneous:
    UI Language:  English
    Media Type:  Undetermined
    Total Hard Disk Space Available:  111948 Mb
    Largest Free Hard Disk Block:  3490 Mb
    OS Install Date: Dec 31 1969
    Game Controller: None detected
    VR Headset: None detected
</details>

**Comment by Dysphie** [comment]
This is caused by demoui2, sending demoui2 when the input is being ignored solves it.

**Comment by dysphie** [comment]
Can't reproduce anymore, assuming fixed on src-r4758.
