### ISSUE TITLE
[beta-v1.1.0.0] Wrong default values for Create Server dialog

### ISSUE THREAD

**Issue by Dysphie** [nmrih/source-game#1013]
Wrong hostname, additionally many of the entries simply don't work in nmrih (flashlight, weapon stay, etc)
![20180807010006_1](https://user-images.githubusercontent.com/11559683/43754467-56994a1a-99e1-11e8-8961-a5628d057674.jpg)

**Comment by Bubka3** [comment]
fixed dev-8841
