### ISSUE TITLE
[beta-v1.1.0.0] bugs on map nmo quarantine

### ISSUE THREAD

**Issue by Pla33** [nmrih/source-game#1014]
![20180807131934_1](https://user-images.githubusercontent.com/42173955/43772044-b8c7058e-9a62-11e8-876b-5cde61c72298.jpg)
On map nmo_quarantine errors with textures in store.

**Comment by Holycrapjimhox** [comment]
You should create another post for the Russian translation errors, since they have nothing to do with map bugs.

**Comment by Bubka3** [comment]
Please do not bundle issues. I have removed the non-map related inquiry of your issue. You may create a new one for it.

**Comment by Dysphie** [comment]
the following have to be added to the build:
```
models/props_interiors/apt_walltrim_bottom01.mdl
models/props_interiors/apt_walltrim_bottom01_64.mdl
```

**Comment by Winning117** [comment]
![1](https://user-images.githubusercontent.com/15934200/74093644-993b5980-4a89-11ea-8d77-fef0f312e06a.png)
![2](https://user-images.githubusercontent.com/15934200/74093646-9c364a00-4a89-11ea-9de9-97190c20a721.png)
This map appears to be missing quite a few models (tested on r8957)

**Comment by Holycrapjimhox** [comment]
All issues fixed in dev r-8961. Needs to be closed.
