### ISSUE TITLE
[beta-v1.1.0.0] Problem in translate on russian/english language.

### ISSUE THREAD

**Issue by Pla33** [nmrih/source-game#1015]
![20180807103251_1](https://user-images.githubusercontent.com/42173955/43789436-c8dbf7f2-9a91-11e8-909c-c7e29150e39d.jpg)
![20180807102952_1](https://user-images.githubusercontent.com/42173955/43789440-caf33b22-9a91-11e8-86e3-96d8186011e1.jpg)
![20180807102317_1](https://user-images.githubusercontent.com/42173955/43789443-cc8f77d4-9a91-11e8-8a54-e74732ab894b.jpg)
Problem with localisations on russian/english language.

**Comment by Bubka3** [comment]
Thanks for the report, this will be fixed in the next beta update.

**Comment by Bubka3** [comment]
fixed src-4577
