### ISSUE TITLE
[beta-v1.1.0.0] Workshop publisher not bundling .nav and .nmo files together with BSP

### ISSUE THREAD

**Issue by Dysphie** [nmrih/source-game#1017]
~~Workshop maps with assets packet inside the BSP don't work properly~~

~~Example.vpk:~~
![gcfscape_2018-08-08_02-27-44](https://user-images.githubusercontent.com/11559683/43817952-a8f62fcc-9ab2-11e8-89be-a001282feecb.png)

~~Anything packed inside the BSP itself shows up as missing in-game.~~

~~Console output:~~
~~```Couldn't open .bsp C:\Program Files (x86)\Steam\steamapps\workshop\content\224260\1470022250\1470022250.vpk\maps\nmo_miner_detour_v3.bsp for embedded pack file check```~~

~~This check always fails, even for empty BSPs.~~

Uploading BSP files doesn't automatically pack .nmo/.nav files on the same directory

**Comment by felis-catus** [comment]
Fixed in src-r4557.

**Comment by Dysphie** [comment]
Confirming
