### ISSUE TITLE
[dev-8849] Workshop item menu won't show up second time

### ISSUE THREAD

**Issue by Dysphie** [nmrih/source-game#1025]
Just noticed a small bug that's rather annoying when updating multiple workshop entries:

**1.** Click Workshop publisher > Update existing addon > Select Item A
 _Window for item A shows up_
**2.** Agree to terms and publish changes
**3.** Click Workshop publisher again > Update existing addon > Select Item B
 _Nothing shows up_
**4.** Click Workshop publisher again > Update existing addon > Select Item B
 _Now window for item B shows up_

**Comment by Dysphie** [comment]
Seems to affect other actions as well, for instance:

1. Click Workshop publisher > Upload new addon > Publish
2. Click Workshop publisher again > Upload new addon > nothing comes up

**Comment by felis-catus** [comment]
Fixed and confirmed in src-r4599.
