### ISSUE TITLE
(code) black bar while spectating covers up important survival info

### ISSUE THREAD

**Issue by Keldorn074** [nmrih/source-game#103]
When your dead in survival mode you can't see how many zombies are left or which wave it is as the top black bar is covering over it. Obviously a problem because then you can't tell when your turn is coming back up.
My screen res: 1280 x 1024
![2013-05-09_00002](https://f.cloud.github.com/assets/3848484/484488/c4feb9e8-b8d9-11e2-9044-36b660318bcb.jpg)

**Comment by Fersigal** [comment]
I believe this is fixed

**Comment by Bubka3** [comment]
**Resolved Closure**
This issue has been closed as it has been resolved in the current dev build.
It will be available to the public in the next steam release. Thanks for reporting!

Additional comments: bars are now transparent
