### ISSUE TITLE
[dev-r8856] Workshop Publisher: "Update existing add-on" leaves last entry out

### ISSUE THREAD

**Issue by Dysphie** [nmrih/source-game#1030]
My uploaded addons sorted alphabetically (I have 53 total):

```
[...]
Snowcapped (PVP)
Subside
Torn
Tropic (PVP)
ZZZZZZ TEST
```

Publisher list:

![20180918183633_1](https://user-images.githubusercontent.com/11559683/45717985-f91e2100-bb71-11e8-8387-fbfc5cce0da4.jpg)

Removing "ZZZZZZ TEST", now "Tropic (PVP)" doesn't show up:

![20180918182648_1](https://user-images.githubusercontent.com/11559683/45718290-e5bf8580-bb72-11e8-869f-77bb8a19de63.jpg)

100% reproducible

**Comment by felis-catus** [comment]
Fixed and confirmed in src-r4594.
