### ISSUE TITLE
[public-1.10.0] Localization tokens in user input parsed by VGUI

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1034]
Users can input localization tokens and have VGUI panels parse them.

- Server browser:
`hostname #NGSurvivalBegin`

![20180918232401_1](https://user-images.githubusercontent.com/11559683/45727417-06e79c80-bb9a-11e8-872b-13e454397a51.jpg)

- Addon publisher, title and description fields:

![steam_2018-09-18_19-11-25](https://user-images.githubusercontent.com/11559683/45727499-6180f880-bb9a-11e8-9a9c-0b5747b28f3b.png)
![20180918190925_1](https://user-images.githubusercontent.com/11559683/45727515-73629b80-bb9a-11e8-8050-dad23620f619.jpg)

- MOTD
motd_text_default.txt with "#NGSurvivalBegin":

![20180918231627_1](https://user-images.githubusercontent.com/11559683/45727538-8e351000-bb9a-11e8-85ca-495a2fe4c609.jpg)

- Console
Connection message with `#NGSurvivalBegin` as nickname:

![20180919000654_1](https://user-images.githubusercontent.com/11559683/45728862-4e712700-bba0-11e8-9715-c4ecd93274f8.jpg)

- Callvote, 'map' field, `callvote changelevel #NGSurvivalBegin`:

![image](https://user-images.githubusercontent.com/11559683/45728977-d3f4d700-bba0-11e8-9859-91b8f85d2d5b.png)

There might be more that I missed

**Comment by felis-catus** [comment]
I'll consider this as an engine issue (VGUI) and it's effectively harmless, closing.
