### ISSUE TITLE
[public] No recoil when cl_vmcamera_scale set to 0

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1035]
Recoil is tied to headbobbing. Setting cl_vmcamera_scale to 0 disables visual recoil completely

https://giant.gfycat.com/PitifulBewitchedAruanas.webm

However being able to tweak/disable viewmodel headbobbing is a blessing and I wouldn't want that gone. Weapons should be made not to rely on it instead.

**Comment by felis-catus** [comment]
Not a bug, recoil is applied correctly to weapons that actually punch the aim, everything else is purely visual.
