### ISSUE TITLE
[beta] nmo_shelter spot for medical crate but no medical crates on map

### ISSUE THREAD

**Issue by ralphinader** [nmrih/source-game#1036]
That is a mean troll. I looked and looked. There is a spot for a medical crate at the respawn but there are no medical crates on the map.

**Comment by Dysphie** [comment]
health station spawns in a secret area, right below the chainsaw shown in this video: https://youtu.be/1mxboxo__lI

**Comment by ralphinader** [comment]
Those crates have been removed in the current build.  Please think before responding! =)

**Comment by Dysphie** [comment]
> Those crates have been removed in the current build. Please think before responding! =)

No need to be rude. It was a simple mistake on my end since there have been no change logs about any health crates getting removed.

**Comment by AtheistNMRiH** [comment]
fixed in r8868

**Comment by Bubka3** [comment]
We just pushed an update to the beta for this. Thanks for the report!
