### ISSUE TITLE
[Beta-v1.1.0.0] nmo_cleopas helicopter stuck during evac

### ISSUE THREAD

**Issue by Popon13** [nmrih/source-game#1037]
It's stuck right where it spawned during the cinematic, this already happened 2 times.

![20180927191612_1](https://user-images.githubusercontent.com/43651817/46164850-5d866200-c28f-11e8-8736-d5637f75f056.jpg)

![20180927191614_1](https://user-images.githubusercontent.com/43651817/46164865-68d98d80-c28f-11e8-9e74-516078f2be63.jpg)

**Comment by AtheistNMRiH** [comment]
fixed in r8868

**Comment by Holycrapjimhox** [comment]
Confirmed fix, needs to be closed
