### ISSUE TITLE
[Public/1.1.0.0] Item glows cause frame drops

### ISSUE THREAD

**Issue by SCHATTENSPIEL** [nmrih/source-game#1038]
I've found that Item glows for both objective props and items cause severe frame drops in my client. My machine is incredibly old, so the effects might be much more subtle on modern systems, but in my case, my frames drop from around 70 to 30 when glows are active. Here are some screenshots:

**_1._** [https://i.imgur.com/wFPKodt.jpg](url)
![20181004023037_1](https://user-images.githubusercontent.com/40250176/46454516-ebc18300-c77c-11e8-8eab-275262482b47.jpg)

- _FPS with item glows enabled_.

_**2.**_ [https://i.imgur.com/hfk3Mev.jpg](url)
![20181004023049_1](https://user-images.githubusercontent.com/40250176/46454571-23302f80-c77d-11e8-9519-0d35632fc5fa.jpg)

- _FPS with item glows disabled_.

**Comment by Bubka3** [comment]
Please define "incredibly old".

**Comment by SCHATTENSPIEL** [comment]
Sorry about that. This are my specs:

. System: Windows 7 x64 Home Basic
. CPU: AMD Athlon(tm) II X2 260u Processor 1.80GHz
. RAM: DDR3 3GB 1.07GHz
. Video card: AMD Mobility Radeon HD 4200 256MB

**Comment by Winning117** [comment]
Neither your CPU nor GPU meet NMRiH's minimum system requirements

**Comment by felis-catus** [comment]
Item glows were re-implemented in 1.10 with a new shader effect, so it may have quirks with lower end systems. As stated, your system doesn't meet the minimum requirements.

Unfortunately we can't optimize the rendering for these systems, or bring back the legacy effect -- so you'll have to turn off the glows for now by using `glow_outline_effect_enable 0` (not a cheat). Closing.

**Comment by felis-catus** [comment]
Reopening because of shader problems (see #536), legacy glow effect should be brought back as an option.

**Comment by felis-catus** [comment]
Walking back on legacy option, it's too convoluted to have multiple glow systems. See earlier comment for workaround.

**Comment by felis-catus** [comment]
Partially resolved in src-r6230. Item glows are now optimized by removing gaussian blur when shader quality is set to low.
