### ISSUE TITLE
(models) Few items that need removal of physics-collision against players.

### ISSUE THREAD

**Issue by ShockaPop** [nmrih/source-game#104]
Just found out, that these items still have physics-collision against players:

*item_glowstick (entity placed in Hammer)
*nmrih_safezone_supply (entity placed in Hammer)
*FEMA-duffelbag/barricade-repair

I will be adding more to this list when I bump into new ones.

**Comment by AtheistNMRiH** [comment]
I guess it is obsolete now, since noone use item_glowstick and fema bags and box hasn't collision now
