### ISSUE TITLE
[public-1.10.0] Wrong objective text on map change

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1040]
Players will see the previous map's last objective if they join the current map late into the round

I just had this happen on 1.10:
1. play Cleopas right through
2. have host change level to Broadway
3. take ~2 minutes to load up the new map and connect
4. see "Find pliers" on screen, which is Cleopas' last objective

**Comment by Holycrapjimhox** [comment]
This also happened prior to 1.10.

**Comment by felis-catus** [comment]
Fixed in src-r4926.
