### ISSUE TITLE
[public-1.10.0] Nametag issues with elevated terrain

### ISSUE THREAD

**Issue by Dysphie** [nmrih/source-game#1044]
Nametags seem to disappear for players standing on elevated terrain

In-game (this was a player not a bot):
![20181006173119_1](https://user-images.githubusercontent.com/11559683/46576040-82698c00-c997-11e8-885a-09fc210e9b1e.jpg)

Originally thought to be caused by this player clip, but check the rest of the comments:
![hammer_2018-10-06_18-39-06](https://user-images.githubusercontent.com/11559683/46576043-8f867b00-c997-11e8-9b27-88f7b532099e.png)

**Comment by Ryan-nmrih** [comment]
Player name tags also seem to disappear for no reason on broadway2 when a player stands on the sidewalks

![20181006171726_1](https://user-images.githubusercontent.com/37752555/46576751-4814e480-c9c1-11e8-94c2-7c765f3ce0a0.jpg)
![20181006171737_1](https://user-images.githubusercontent.com/37752555/46576752-4814e480-c9c1-11e8-850a-a2de29394cdd.jpg)
![broadway2-nametags](https://user-images.githubusercontent.com/37752555/46576762-75fa2900-c9c1-11e8-915d-0319349dc168.jpg)

Another spot on broadway2
![20181006173437_1](https://user-images.githubusercontent.com/37752555/46576769-8c07e980-c9c1-11e8-88bf-ab32021bc882.jpg)
![20181006173633_1](https://user-images.githubusercontent.com/37752555/46576770-8ca08000-c9c1-11e8-8dcc-bf143c8eaa21.jpg)
![broadway2-nametags2](https://user-images.githubusercontent.com/37752555/46576771-93c78e00-c9c1-11e8-8c42-3e1d9b69f516.jpg)

**Comment by Dysphie** [comment]
Seems fixed in src-r4636, closing _for now_
