### ISSUE TITLE
[public 1.10.0] - Bots persist through rounds

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#1045]
If a round restarts while a bot is in the game it doesn't respawn, it just stays there in the state that it was in when the round restarted. I know that bots aren't a huge feature or anything but figured I'd post this just so we have note of it.

Example: Bot gets bit during round restart, when the round restarts the bot is standing there with low health and stuck in the "being bit" animation

![image](https://user-images.githubusercontent.com/15934200/46576235-f137ec80-c979-11e8-9068-5fa68d9da8d7.png)

Video: https://www.youtube.com/watch?v=uxkrajo2KpI&feature=youtu.be

**Comment by felis-catus** [comment]
Resolved in src-r4648.
