### ISSUE TITLE
closecaption_english.txt missing closing quote for every "Mag22" entry

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1047]
Examples:

line 345:
```
		"Reload.Alt2.Mag22" "Twenty-two magazines remaining!
```

line 377:

```
		"Reload.Alt3.Mag22" "Twenty-two magazines remaining!
```

**Comment by AtheistNMRiH** [comment]
not only english, some other languages like french, greek, russian missing closing quote too
but I guess you can't hear that line in game anyway, only if you extended you inventoy with cheats

**Comment by Winning117** [comment]
"UN Redeker **Initative**" also has a typo, should be "UN Redeker **Initiative**"

**Comment by Winning117** [comment]
essbuh pointed out that Load22 is also missing quotes

**Comment by felis-catus** [comment]
Resolved in dev-r9040.
