### ISSUE TITLE
Fire doesn't damage/burn properly.

### ISSUE THREAD

**Issue by ShockaPop** [nmrih/source-game#105]
Fire should burn players, not only by damaging (the fire damage currently is way too low to be punishing if standing on fire), but also by setting them on fire if standing too long in fire. The fire should extinguish itself after a while if not exposed to fire during that time or if inside water.

**Comment by Winning117** [comment]
This is more of a request than a bug. Also fire damage is not too low as it can kill a player in a matter of seconds. Tested in src-r4388/dev-r8769, needs to be closed.
