### ISSUE TITLE
[public 1.10.0] - Barricade animations break sometimes

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#1051]
I'm not exactly sure what causes this but a map that I always encounter this on is nmo_boardwalk. I've heard from other users that they sometimes encounter this issue as well (but not always).

![image](https://user-images.githubusercontent.com/15934200/46932707-c139ba80-d005-11e8-9085-4f462c9e8f81.png)

Video: https://youtu.be/TsTjqycZnP4

**Comment by TheMitu97** [comment]
I belive this happens when you're using last board in your inventory, I have that issue too, it's not gamebreaking but it can make you confused (same camera bug happens with cutscenes sometimes).

**Comment by Winning117** [comment]
> I believe this happens when you're using last board in your inventory

It doesn't have to be your last board for it to happen

**Comment by Winning117** [comment]
r8883 seems to have fixed this issue even though it wasn't targeting this issue with barricades
