### ISSUE TITLE
[public 1.1.0.0] - Can't cancel barricade animation

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#1052]
If a user tries to barricade a wall there is no easy (or at least intuitive) way to cancel the animation. Pressing Esc doesn't do anything, opening the inventory doesn't do anything, and the hammer can't be dropped in order to cancel it.

This can cause the player to be mauled by zombies without being able to do anything to stop it. I think that adding an option to cancel animations would make barricades more viable and less of a penalty for players who try to use them.

**Comment by felis-catus** [comment]
Resolved in src-r4686.
