### ISSUE TITLE
[public 1.1.0.0] Custom voice sets override default ones

### ISSUE THREAD

**Issue by Dysphie** [nmrih/source-game#1053]
Given 2 clients, where A has an _extra_ voice set installed and B does not, client A will hear B as if they were using a custom voice set.

Working example:
1. Have `Player A` subscribe to [this workshop entry](https://steamcommunity.com/sharedfiles/filedetails/?id=1553026894) and host a game
2. Have `Player B` select Chippants and join `Player A`
3. Have `Player B` use the voice menu

Player A will hear the wrong voice lines play: Jessica instead of Chippants. The addon in question doesn't replace any existing sounds, just adds more of them, so this looks like a bug.

Note: Could probably use bots or Sandboxie to simulate a second player

**Comment by TheMitu97** [comment]
I can confirm that, same applies to male voices, where Player B uses default voice, but Player A hears Bill instead.

**Comment by felis-catus** [comment]
There's an error determining which voice set to use by default, causing this bug. This will be fixed in the next update.

**Comment by Dysphie** [comment]
Fixed as of src-r4660.
