### ISSUE TITLE
[public 1.1.0.0] Nms_midwest helicopter gets stuck.

### ISSUE THREAD

**Issue by TheMitu97** [nmrih/source-game#1055]
Don't know if someone already reported this, but when supplies drop comes on nms_midwest, helicopter gets stuck mid-way to the drop point (right next to gun shop). It stays there until the end of the map, making awfully loud sound for the rest of the round.

![20181103164505_1](https://user-images.githubusercontent.com/44722162/47955113-4d028f00-df93-11e8-966e-bc3ac09cc92f.jpg)

**Comment by Winning117** [comment]
As mentioned by Atheist this is caused by clips that were added to prevent god spots, but they go too high up so the helicopter hits them and gets stuck.

**Comment by AtheistNMRiH** [comment]
there is no issue in r8923, was fixed in some of previous version

**Comment by Winning117** [comment]
Confirmed fixed on dev build, needs to be closed.
