### ISSUE TITLE
[Public 1.1.0.0] Unable to read custom font files from VPKs

### ISSUE THREAD

**Issue by DoofusCockslap** [nmrih/source-game#1056]
The game couldn't read custom font files (.ttf format) packed inside of VPK archives.

Is this an engine limitation or it actually can be fixed? I guess not, but it's still worth to mention.

**Comment by Mateos81** [comment]
There might be some issues if the font has some weird copyright limitations?

**Comment by felis-catus** [comment]
Engine limitation unfortunately, closing.
