### ISSUE TITLE
[public-1.10.0] nmo_quarantine, crank keeps falling thru ground

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1057]
There have been several reports of the objective crank falling thru the floor on spawn. Seems to happen a lot when the crank is dropped on its face.

Video: https://gfycat.com/WhiteJadedHyracotherium

Screenshots:
![20181013164318_1](https://user-images.githubusercontent.com/11559683/48657463-ead47000-ea0f-11e8-9230-6461fcd214e0.jpg)
![20181116221111_1](https://user-images.githubusercontent.com/11559683/48657464-ead47000-ea0f-11e8-8b7f-38986fbb31e6.jpg)
![20181116221156_1](https://user-images.githubusercontent.com/11559683/48657465-eb6d0680-ea0f-11e8-9957-4bb89f916cf2.jpg)

**Comment by Holycrapjimhox** [comment]
Fixed in dev r-8957. Needs to be closed.

**Comment by Winning117** [comment]
Fixed in r8900 ^^
