### ISSUE TITLE
Next map on win condition

### ISSUE THREAD

**Issue by Bubka3** [nmrih/source-game#1058]
Game rules should be updated so that if you win a round, it goes to the next map instead of just resetting.

**Comment by Bubka3** [comment]
PS, this behavior will need to be tied to a cvar for legacy purposes (dodgeball comes to mind). However it should default to new behavior.

**Comment by Dysphie** [comment]
>However it should default to new behavior.
but not in Challenge mode (speedrunning). That would get frustrating

**Comment by Bubka3** [comment]
If you set the challenge mode cvar then you can also set the legacy behavior cvar in the same place

**Comment by Bubka3** [comment]
dev8883

> Added cvar "sv_nextlevel_on_round_win", on round win condition, change level to next map instead of resetting
