### ISSUE TITLE
survivors spawn problem on nms_arpley

### ISSUE THREAD

**Issue by EdmundKemper** [nmrih/source-game#1060]
Hi so there is a problem when survivors spawn/respawn in the bridge , sometimes they respawn inside parts of the bridge like this 
https://prnt.sc/lt7734
and they cant walk or run they are stuck there ,i wish this can be fixed 

P.D: sorry for my english

**Comment by AtheistNMRiH** [comment]
#733

**Comment by felis-catus** [comment]
Duplicate of #733, closed.
