### ISSUE TITLE
[dev-r8881] Demos don't record inventory or voice wheel player inputs

### ISSUE THREAD

**Issue by Holycrapjimhox** [nmrih/source-game#1061]
When playing back demos, opening both inventories or the voice command wheel are not being recorded.

Steps to reproduce:
1) Record a demo via ds_record demo
2) Open your radial wheels several times, use them to throw items out of your inventory, etc.
3) Stop recording via ds_stop
4) Play the demo via ds_playdemo

NOTE: This also occurs when using the native demo recording tool (record, playdemo). Additionally, this happens on the public 1.10 build as well, so it's not a regression.

**Comment by felis-catus** [comment]
Intended behavior, because VGUI panels such as radial wheel don't playback user interaction (such as mouse movements, commands), it opens up for nothing and steals all input (similar to #1012).

Closing.

**Comment by Holycrapjimhox** [comment]
NOTE: This has been fixed in the latest commit, dev-r8890.
