### ISSUE TITLE
[dev-r8885] 'changelevel' to any level crashes game

### ISSUE THREAD

**Issue by Dysphie** [nmrih/source-game#1069]
Might be related to the 'hostname' rich presence crash:

1. map nmo_cabin
2. changelevel nmo_broadway

Game should crash to desktop

**Comment by Dysphie** [comment]
[dumps.zip](https://github.com/nmrih/source-game/files/2743712/dumps.zip)

**Comment by Dysphie** [comment]
...and never mind that as well. It happens on any `changelevel` call. 
`changelevel` is broken.

**Comment by felis-catus** [comment]
It's the RPC crash, closing as it's fixed.
