### ISSUE TITLE
[public-1.10] Standing behind the car on nmo_brooklyn prevents map progress

### ISSUE THREAD

**Issue by Wabein** [nmrih/source-game#1074]
Found this while playing nmo_brooklyn. If you stand behind the car and another player tries to push it, you can block its path and prevent it from reaching the spot that triggers the next objective, causing a softlock.
![20190220214449_1](https://user-images.githubusercontent.com/47870163/53207884-be824e00-3613-11e9-9472-be40d981fbbd.jpg)

**Comment by AtheistNMRiH** [comment]
fixed in r8893
