### ISSUE TITLE
[public-1.10] Punching monitors that show codes prevents players from reading them

### ISSUE THREAD

**Issue by Wabein** [nmrih/source-game#1075]
You can prevent players from seeing the codes displayed on some monitor screens when hitting them with me_fists. By hitting them multiple times, several decals acumulate and completely cover up the code, causing a softlock. 
nmo_brooklyn:
![20190227202424_1](https://user-images.githubusercontent.com/47870163/53534824-2dade580-3adf-11e9-9a13-b774b47e6d80.jpg)

nmo_fema:
![20190227195145_1](https://user-images.githubusercontent.com/47870163/53534781-06571880-3adf-11e9-9f21-588cff2eca75.jpg)

nmo_junction:
![20190227203159_1](https://user-images.githubusercontent.com/47870163/53534837-38687a80-3adf-11e9-91d9-2594b5c1960c.jpg)

**Comment by Winning117** [comment]
r_cleardecals

**Comment by Holycrapjimhox** [comment]
This should be fixed even if there is a console command to reset decals. New or more casual players very likely don't know about r_cleardecals.

**Comment by Winning117** [comment]
Is it possible to disable decal overlays on certain objects?

**Comment by Holycrapjimhox** [comment]
I don't know if it's possible to selectively disable decals on objects just like that. But I know that there are some props that do not display decals at all. If this could be applied to the monitors, it could be a simple fix.

**Comment by dysphie** [comment]
Fixed in svn-8920
