### ISSUE TITLE
[public-1.10] Spectators can start callvotes when not allowed to just after dying.

### ISSUE THREAD

**Issue by Holycrapjimhox** [nmrih/source-game#1076]
If sv_vote_allow_dead_call_vote is set to 0, spectators cannot initiate callvotes. However, they can do so just after death.

Steps to reproduce:
1) Play in a server with "sv_vote_allow_dead_call_vote" set to 0 with other players or bots
2) Kill yourself
3) Immediately call any of the allowed votes before entering spectator mode

**Comment by felis-catus** [comment]
Fixed in src-r4877.

**Comment by Holycrapjimhox** [comment]
Confirmed fix in r8975.
