### ISSUE TITLE
(nmo_cleopas) The movement of the ladder is enabled before using the welder.

### ISSUE THREAD

**Issue by marcodromero** [nmrih/source-game#1077]
The movement of the ladder is enabled before using the welder. This allows you to remove the ladder and still be able to scale by the trigger that remains enabled. It does not generate any problem with the game. Only confusion.

I placed the ladder
![cleopas1](https://user-images.githubusercontent.com/46422135/54486362-25d39c80-4866-11e9-9e0d-9e1fed2b7683.jpg)
I crossed to the other side
![cleopas2](https://user-images.githubusercontent.com/46422135/54486361-25d39c80-4866-11e9-9892-1daf9a699aff.jpg)

I used noclip to step back and throw the ladder to the ground. Then I went up the texture of the staircase that was still active.
![cleopas3](https://user-images.githubusercontent.com/46422135/54486360-25d39c80-4866-11e9-97bf-e3a4e3c7a0ec.jpg)

**Comment by AtheistNMRiH** [comment]
fixed in r8892

**Comment by Holycrapjimhox** [comment]
Confirmed fix on dev-r8894. Needs to be closed.
