### ISSUE TITLE
Player takes explosive thrown by partner and causes his death

### ISSUE THREAD

**Issue by marcodromero** [nmrih/source-game#1078]
1- A player throws a grenade.
2- Another player lifts the grenade and approaches the player who threw it with it.
3- The explosive detonates and kills the player who threw it.

Explosives should be prevented from being picked up again when they have been thrown to explode.

**Comment by dysphie** [comment]
This is a high-risk mechanic that has uses in both PvE and PvP.  It's balanced by the fact you cannot sprint with it and requires good timing to pull off successfully:

![1468156371_TNT](https://user-images.githubusercontent.com/11559683/54784890-ac400380-4c03-11e9-8398-bc2e10fd3eb9.gif)

I would advise against changing it.

**Comment by Holycrapjimhox** [comment]
I agree, it's way too situational to use as a trolling method requiring very precise timing or some very lucky guess on when the player is gonna throw the explosive, as well as at what angle the explosive is thrown at. Also, the player that threw the explosive can save themselves if there is solid cover nearby like a wall, thanks to the fact that the griefer can't sptrint like Dysphie pointed out.  There is no need to remove this feature.

**Comment by felis-catus** [comment]
Not an issue, closing.
