### ISSUE TITLE
Game Crashes to desktop when getting an achievement (Mac)

### ISSUE THREAD

**Issue by TheUnstableNutcase** [nmrih/source-game#1079]
On the Mac version of the game, whenever an achievement is obtained, the game freezes for a few seconds and then crashes to desktop with no error message, however the player still gets the achievement. This happens the instant the qualifications for an achievement are met by the way.

**Comment by felis-catus** [comment]
src-r4783 may have fixed this? Needs confirm.

**Comment by felis-catus** [comment]
Mac build is gone, and so is this issue.
