### ISSUE TITLE
[public-1.10] nmo_brooklyn sequence break softlock

### ISSUE THREAD

**Issue by Holycrapjimhox** [nmrih/source-game#1081]
During the hook objective path when playing nmo_brooklyn, it's possible to put out the wall of fire on the street to the right before the car is moved out of the way of the truck. The street leads to the radio that triggers the ending sequence. If a player manages to activate the radio, the ending sequence plays without a cinematic view, no ending trigger appears and when the car is moved out of the way, a permanent black screen appears on the player's view and the map will become softlocked.

Steps to reproduce:
1) Play nmo_brooklyn until you get the “attach the hook” objective when you drop down into the repair shop
2) Complete the objective and proceed
3) When prompted to move the car out of the way, head to the tunnel to the far right where the fire extinguisher spawns
4) Grab the fire extinguisher
5) Head to the wall of fire on the street next to the tunnel and put out the fire
6) Proceed to the alleyway, enter the supermarket and use the radio. The map will softlock

Suggested solution: 
The wall of fire should be allowed to be put out after the car has been moved out of the way. Disable the fire extinguisher interaction with the wall until the previous objective is completed. Alternatively, if this can’t be achieved, then the fire extinguisher should be triggered to spawn after the car objective has been completed, however the first option is preferable since it rewards players knowing the spawn point of the fire extinguisher by allowing them to complete the map faster.

**Comment by AtheistNMRiH** [comment]
fixed in r8893
