### ISSUE TITLE
(public 1.10) blocking zombies with items

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#1085]
1) pick up any item in your hands when you don't have free space (I've used me_sledge)
2) sit down
3) observe zombie stuck
![nms_camilla0000](https://user-images.githubusercontent.com/11333747/62304510-4cf2d980-b4a8-11e9-83ad-2cbc220e93f5.jpg)
![nms_camilla0001](https://user-images.githubusercontent.com/11333747/62304511-4cf2d980-b4a8-11e9-94bf-8cd06064a907.jpg)

**Comment by essbuh** [comment]
Likely fixed by src-r4881

**Comment by Winning117** [comment]
Not solved by src-r4881

[Video](https://www.youtube.com/watch?v=8FK_YoewJa0)
