### ISSUE TITLE
[public-1.10.0] Crash when inventory is accessed and inv_maxcarry is 0

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1086]
1. Equip firearm
2. Set server's inv_maxcarry to 0
3. Open up your main inventory

[crash_hl2.exe_20190824134054_1.zip](https://github.com/nmrih/source-game/files/3536874/crash_hl2.exe_20190824134054_1.zip)
Server owners could use this to crash people, I suppose.

**Comment by Winning117** [comment]
Adding on that it crashes if you're holding anything, including melee weapons and ammo.

**Comment by dysphie** [comment]
Out of scope

**Comment by felis-catus** [comment]
For what it's worth, this was fixed in src-r5763.
