### ISSUE TITLE
[public-1.10.0] MapHack: EVENT_OUTPUT not firing

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1087]
If my understanding of events is correct, this should play a sound and print to console (it's pretty much a minified version of [test.txt](https://github.com/felis-catus/nmrih-challenges/blob/master/nmrih/maps/maphacks/test.txt)). It does neither.

```cpp
"MapHack"
{
	"precache" { "sound"	"Pain.FemaleDefault" }

	"events"
	{
		"EventStickAwakened"
		{
			"type"		"EVENT_OUTPUT"
			"targetname" 	"stick"
			"output"	"OnAwakened"
		}
	}

	"EventStickAwakened"
	{
		$playsound { "name" "Pain.FemaleDefault" }
		$console { "msg" "Hello world" }
	}

	"entities"
	{
		"item_glowstick" { "targetname" "stick" }

		$fire { "targetname" "stick"	"input" "Sleep" }
		$fire { "targetname" "stick"	"input" "Wake" }
	}
}

**Comment by felis-catus** [comment]
It seems that the "OnAwakened" output is not being called that early, triggering events later may work. Couldn't find problems with maphack's behavior, so I'm closing this.
