### ISSUE TITLE
[public-1.10.0] MapHack: Wrong event gets triggered

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1088]
1. Have point_template **melon_t** which spawns prop targetnamed **melon**
2. Have point_template **key_t** which spawns prop targetnamed **key**
3. Use this maphack:
```cpp
"MapHack"
{
	"events"
	{
		"MelonSpawned"
		{
			"type"		"EVENT_OUTPUT"
			"targetname"	"melon_t"
			"output"	"OnEntitySpawned"
		}

		"KeySpawned"
		{
			"type"		"EVENT_OUTPUT"
			"targetname"	"key_t"
			"output"	"OnEntitySpawned"
		}
	}

	"MelonSpawned" {}
	"KeySpawned" {}
}
```

4a. `ent_fire melon_t ForceSpawn`

Expected result: **MapHack: Triggered event "MelonSpawned"** 
Actual result: **MapHack: Triggered event "KeySpawned"** ❌

4b. `ent_fire key_t ForceSpawn`

Expected result: **MapHack: Triggered event "KeySpawned"** 
Actual result: **MapHack: Triggered event "KeySpawned"** ✔️

Screenshot with similar setup (nmo_canal_v2):

![unknown (6)](https://user-images.githubusercontent.com/11559683/64566737-00af7a80-d32d-11e9-8ec5-535bac082093.png)

**Comment by felis-catus** [comment]
Confirmed fixed in src-r4803.
