### ISSUE TITLE
[dev-r8912] MapHack: $respawn breaks +use

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1089]
Calling $respawn on an entity causes errors on any subsequent `+use`s

1. Have some entity targetnamed "TEST", I used a prop_physics.
2. Load up a maphack with `$respawn { "targetname" "TEST"}`
3. Try to pick up "TEST" after it's been respawned.

dev2 verbose: 
```
(32.26) input : TEST.Use()
(32.26) output: (prop_physics,TEST) -> (0.000000,Use)()
unhandled input: (Use) -> (0.000000), from (prop_physics,TEST); target entity not found
```

**Comment by felis-catus** [comment]
Resolved in src-r7636.
