### ISSUE TITLE
Non-host can change ent_text for host

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#1090]
Steps to reproduce:
1) Turn on `sv_cheats 1`
2) Have the non-host face an NPC and use the command `ent_text`
The ent_text information will be displayed for the host instead of the person who issued the command.

I believe that the "intended" way would be for the person who issued the command to be able to see the text instead of only the host.

Edit: Dysphie informed me that it's a point_message entity which is host-only, so I think that only the host should be able to issue the command.

**Comment by felis-catus** [comment]
Not really an issue, ent_text is designed for listen server host only, closing.
