### ISSUE TITLE
[public-1.10.0] Fire is not extinguished on death

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1094]
Burning players don't get put out on death. Because of this, dead clients are able to fly around with flames parented to them, hurting other entities. They'll also respawn on fire. This is a problem for maps or plugins who make use of this mechanic.

Repro steps:
1. `sv_cheats 1; ent_fire !player ignite`
2. `kill`
3. Respawn or fly around on fire

**Comment by Winning117** [comment]
Video:
https://www.youtube.com/watch?v=IZRpiFf7gZo

**Comment by felis-catus** [comment]
Fixed in src-r4879.
