### ISSUE TITLE
Rain cannot be edited without sv_cheats

### ISSUE THREAD

**Issue by Saref96** [nmrih/source-game#1096]
Hello there. Everyone knows that standard rain is terrible. And in Half-Life 2 it could be changed without using "sv_cheats". However, in NMRiH, developers intentionally or accidentally forbade editing related commands with rain without “sv_cheats” and a map developer cannot change rain through an entity “point clientcommand”.

As one of map developer, I would like you to allow editing of rain without using "sv_cheats" - it will improve beauty of rain maps (if developers will want to edit rain) and generally improve quality of maps, and I think that many developers didn’t want to make rain on their maps, without being able to change it.

Thanks to these commands, you can improve optimization on your map, and this is also very important. I was able to achieve better FPS for several dozen frames.

I don’t see any minuses if you will do this, however, as I wrote above, there are a lot of pluses and this will help developers of maps that do your game and community better.

These commands (part "Rain Related Console Commands"): https://developer.valvesoftware.com/wiki/Func_precipitation

**Comment by essbuh** [comment]
Note that we did not specifically make these cheat settings - this is how it is in the baseline SDK2013.

(see: https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/client/c_effects.cpp)

**Comment by felis-catus** [comment]
point_clientcommand usage in general is considered bad practice, if we plan to revisit this issue maybe incl. these cvars as FGD keyvalues instead?
