### ISSUE TITLE
Grenades no longer damage func_breakables

### ISSUE THREAD

**Issue by Ryan-nmrih** [nmrih/source-game#1097]
Frag grenades and TNT have stopped damaging func_breakables recently (1.10?). For example, nmo_cleopas' convenience store is barricaded with boards which could previously be destroyed in a grenade blast.  They are now immune to all explosives but the nearby glass windows still break.

This applies to all func_breakables. E.g. the padlock in nmo_brooklyn's alley.

This appears to be a regression. Prevents interesting use of grenades and map designs.

![TNT doesn't destroy boards](https://user-images.githubusercontent.com/37752555/73326458-d6952100-4217-11ea-810d-83ab2f90fb47.jpg)

**Comment by essbuh** [comment]
This should be fixed with code r4853 and included in 1.10.1

**Comment by Ryan-nmrih** [comment]
Confirmed fixed. Thanks man
