### ISSUE TITLE
[public-1.10] Practice time can be skipped via Restart callvote

### ISSUE THREAD

**Issue by Holycrapjimhox** [nmrih/source-game#1098]
Players can skip practice time before the round begins so they can start playing faster. The issue here is that players that are still connecting may not get enough time to enter the server and spawn.

Suggestion: create a new cvar that enables/disables callvotes during Practice time

**Comment by felis-catus** [comment]
Added cvar `sv_vote_allow_restart_game_skip` for admins who wish to enforce this.
