### ISSUE TITLE
[beta-1.11.0] Console font too small on GNU/Linux

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1101]
At 1366x768, the font is quite unreadable: https://i.imgur.com/klYkq2r.jpg

Relevant console output?
```
m_face->glyph->bitmap.width is 0 for ch:32 DejaVu Sans
m_face->glyph->bitmap.width is 0 for ch:32 DejaVu Sans
m_face->glyph->bitmap.width is 0 for ch:32 DejaVu Sans
```

System: Debian 10 (64-bit)

**Comment by dysphie** [comment]
Things like `cl_showpos` and `cl_showfps` are also extremely tiny: https://i.imgur.com/kYGWRx7.png

**Comment by felis-catus** [comment]
I'll look if this can be resolved by simply increasing the font size on resources.

**Comment by felis-catus** [comment]
> 
> 
> I'll look if this can be resolved by simply increasing the font size on resources.

Yup, fonts are readable now.
