### ISSUE TITLE
[beta-1.11.0] me_pickaxe incorrect icon on GNU/Linux

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1102]
The pickaxe shows an incorrect icon in the radial inventory menu. 
It displays just fine in supply crates however. I couldn't find another item with the same problem.

https://i.imgur.com/AVyFRUB.png
https://i.imgur.com/kYGWRx7.png

This only seems to affect the Linux build.

**Comment by felis-catus** [comment]
This might be a VGUI material bug...

**Comment by felis-catus** [comment]
Now tracking here #1105. (has more information)
