### ISSUE TITLE
[beta-1.11.0] Crash to desktop after splash screen (GNU/Linux)

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1103]
The game becomes completely hosed after launching it a couple of times (1 to 3 restarts). It will display the splash screen and when it's time to display the main menu, it will just crash to desktop with no dialog messages ..it will also 'randomly' start working again.

No repro steps as of now, only dumps. Needs more testing
[crashes_2020013109.zip](https://github.com/nmrih/source-game/files/4139193/crashes_2020013109.zip)

System: Debian 10 (64-bit)

**Comment by felis-catus** [comment]
Can anyone else with Debian based distro chime in? These dumps point to system libraries.

**Comment by dysphie** [comment]
Console log leading to crash:
[console.log](https://github.com/nmrih/source-game/files/4140300/console.log)

`-console -condebug -conclearlog +developer 2 -noaddons -insecure -safe`

**Comment by dysphie** [comment]
This seems to be related to the console panel and `nmrih/fontconfig`.

To crash a client:

1. Download a fresh client on Debian 10 and opt into the beta
2. Launch the game, this will generate `..common/nmrih/fontconfig`
3. Add `-console` to your launch parameters. Game will now crash post splash screen

To fix:
a. Remove `-console` from the launch params (doesn't always seem to solve it)
b. Delete the `nmrih/fontconfig` folder and relaunch the game

**Comment by Winning117** [comment]
I haven't been able to reproduce this on Linux Mint 19.1 Tessa, tried with both `-console` and `-console -condebug -conclearlog +developer 2 -noaddons -insecure -safe`. Running CPU only though, need to get it working for GPU

**Comment by felis-catus** [comment]
#1101 related, fallback to system font appears to have crashed the game. Closing as resolved.
