### ISSUE TITLE
Loading maps (LINUX/ BETA 1-11)

### ISSUE THREAD

**Issue by Ric-FR** [nmrih/source-game#1104]
Download or redownload official maps or those of the community, it takes a little time between 1 or 2:30 minutes ... it's pretty random. I use "Manjaro XFCE"

**Comment by Winning117** [comment]
What do you mean "Download or redownload official maps"? They come with the game, why would you ever need to download them?

**Comment by Ric-FR** [comment]
I expressed myself badly, sorry English is not my native language.

I just wanted to say when I'm in the game and want to join a game in progress the maps often take a long time to load (1 min to 2:30 min).

It is quite random and under Windows I do not have this problem.

I tried by deleting all the objects or maps from the "Workshop" that I had downloaded the same result ...

**Comment by felis-catus** [comment]
No problem, thanks for contributing.

Can you provide us with system information? NMRiH has huge maps with a lot of assets on them, and it can easily take a minute or longer on slower hard drives.

**Comment by Ric-FR** [comment]
My pc is quite old, it is 10 years old ^^, but when the game works under Windows, I don't have these loading problems, here are the specifications of my pc:

System:
  Host: emeric-pc Kernel: 5.5.0-1-MANJARO x86_64 bits: 64 compiler: gcc 
  v: 9.2.0 Desktop: Xfce 4.14.2 Distro: Manjaro Linux 
Machine:
  Type: Desktop System: Acer product: Veriton M430 v: N/A serial: <filter> 
  Mobo: Acer model: RS880M05 serial: <filter> BIOS: American Megatrends 
  v: P01-A2 date: 04/21/2010 
CPU:
  Topology: 6-Core model: AMD Phenom II X6 1035T bits: 64 type: MCP 
  arch: K10 L2 cache: 3072 KiB 
  flags: lm nx pae sse sse2 sse3 sse4a svm bogomips: 31216 
  Speed: 800 MHz min/max: 800/2600 MHz Core speeds (MHz): 1: 800 2: 800 
  3: 957 4: 800 5: 800 6: 800 
Graphics:
  Device-1: NVIDIA GK208B [GeForce GT 710] vendor: Micro-Star MSI 
  driver: nvidia v: 440.44 bus ID: 01:00.0 
  Display: x11 server: X.Org 1.20.7 driver: nvidia 
  resolution: 1280x1024~60Hz 
  OpenGL: renderer: GeForce GT 710/PCIe/SSE2 v: 4.6.0 NVIDIA 440.44 
  direct render: Yes 
Audio:
  Device-1: AMD SBx00 Azalia vendor: Acer Incorporated ALI 
  driver: snd_hda_intel v: kernel bus ID: 00:14.2 
  Device-2: NVIDIA GK208 HDMI/DP Audio vendor: Micro-Star MSI 
  driver: snd_hda_intel v: kernel bus ID: 01:00.1 
  Device-3: C-Media CMI8738/CMI8768 PCI Audio 
  vendor: TERRATEC Electronic Aureon 5.1 driver: snd_cmipci v: kernel 
  bus ID: 02:05.0 
  Sound Server: ALSA v: k5.5.0-1-MANJARO 
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet 
  vendor: Acer Incorporated ALI driver: r8168 v: 8.048.00-NAPI port: e800 
  bus ID: 03:00.0 
  IF: enp3s0 state: up speed: 100 Mbps duplex: full mac: <filter> 
  Device-2: Microsoft Xbox 360 Wireless Adapter type: USB driver: xpad 
  bus ID: 4-2:2 
Drives:
  Local Storage: total: 1.82 TiB used: 231.67 GiB (12.4%) 
  ID-1: /dev/sda vendor: Toshiba model: HDWD110 size: 931.51 GiB 
  ID-2: /dev/sdb vendor: Western Digital model: WD10EADS-22M2B0 
  size: 931.51 GiB 
Partition:
  ID-1: / size: 915.89 GiB used: 231.67 GiB (25.3%) fs: ext4 dev: /dev/sdb1 
Sensors:
  System Temperatures: cpu: 11.5 C mobo: N/A gpu: nvidia temp: 49 C 
  Fan Speeds (RPM): N/A gpu: nvidia fan: 50% 
Info:
  Processes: 200 Uptime: 20m Memory: 5.81 GiB used: 1.42 GiB (24.5%) 
  Init: systemd Compilers: gcc: 9.2.0 Shell: bash v: 5.0.11 inxi: 3.0.37

**Comment by Ric-FR** [comment]
When I start the game the first time or when I leave it and return to the game, here is what happens now:

-the first time I join a server to play or I create my own listening server that I join, the game takes about 1:15 min.

I don't know if all of this had an influence on all this.

-I leave the game, I join another server or I create a listening server again which I join, this time, I only wait between 20 or 25 sec!

If I leave the game, and go back to it, each time the first part takes about 1:15 min.

I removed all the games that work via Wine or Proton.
I changed my internet browser because Firefox currently has a security certificate problem ... I have installed Vivaldi for now ...

**Comment by felis-catus** [comment]
Yeah, assets are cached after first load. There are different methods that systems use for dealing with caching, for instance on Windows, it temporarily stores standby data in the RAM even after closing the game for quicker load times. This doesn't appear to be a problem in the game so I'm closing this.
