### ISSUE TITLE
Weapon icon issue (Linux/ BETA 1-11)

### ISSUE THREAD

**Issue by Texas-C** [nmrih/source-game#1105]
* Issue decript:  Weapon "sako85_iron_sight" has a wrong icon on weapon menu.
* Enviroment: Archlinux

I'm not sure other player would meet the same issue... ><

**Comment by Texas-C** [comment]
Weird... Icon become correct after reinstall beta... So.. em.. I'd close this issue.. ><

**Comment by felis-catus** [comment]
Did you have the same icon as shown in #1102?

**Comment by Texas-C** [comment]
Sry, I can't open that image link. (Seems that website unavailable in my area TuT)

But, yes, I have the similar icon issue. But not only icon of `pickaxe`. Some day is `sako85_iron_sight`'s icon missed. Some day is others....

I guess this issue is appear randomly. Cause I rember some of icon missed when playing. But they may recovery after restart.

I'll try to take screenshot when meet this issue agian ><

**Comment by dysphie** [comment]
Can confirm https://i.imgur.com/uNlLoq7.png (pickaxe is bottom left)

**Comment by Texas-C** [comment]
Sry, I can't open that photo link (`imgur.com` seems unavailable in my area), would you mind email to me? `ytexas96@yahoo.com`

Thx so much ><

**Comment by dysphie** [comment]
No worries, I have edited the post

**Comment by Texas-C** [comment]
Got screenshot: [https://texas-c.github.io/NMRIH-issue](url)

**Comment by dysphie** [comment]
Also affects `fa_sks_nobayo`

**Comment by Texas-C** [comment]
Yep, I updated screenshot. Also `me_cleaver`...

**Comment by felis-catus** [comment]
Each weapon appear to be from later versions, maybe bad materials?

**Comment by Texas-C** [comment]
I think so. I find old weapons didn't have this issue. (those weapons from code `impule 101`) ><

**Comment by Texas-C** [comment]
Got updates. Icon issue seem solved xD

**Comment by Texas-C** [comment]
Another tiny things... Is it necessary to make `fa_sks` and `fa_sks_nobayo` shows different name on weapon menu?

`fa_sks` names "Simonov SKS (Bayonet)"
![sks_1](https://user-images.githubusercontent.com/10080946/73813081-e913e980-4819-11ea-84ee-b3110e98167b.png)

`fa_sks_nobayo` names "Simonov SKS (Bayonet)" too.. ("Simonov SKS(no bayonet)" could be better? O.O)
![sks_2](https://user-images.githubusercontent.com/10080946/73813091-eb764380-4819-11ea-9163-9aac0a9da211.png)

Thx >.<

**Comment by felis-catus** [comment]
> 
> 
> Got updates. Icon issue seem solved xD

What updates? We didn't ship anything to the build.



> 
> 
> Another tiny things... Is it necessary to make `fa_sks` and `fa_sks_nobayo` shows different name on weapon menu?
> 
Tracked here: #984

**Comment by Texas-C** [comment]
what?? Really? I just notice steam is downloading something on NMRIH. Then I launched game find issue is gone... O.O

**Comment by felis-catus** [comment]
> 
> 
> what?? Really? I just notice steam is downloading something on NMRIH. Then I launched game find issue is gone... O.O

IDK, Steam might have been validating files. The issue seems to occur irregularly and the speculative material patch didn't work, so I'll assume it's a code issue (hopefully solvable).

**Comment by Texas-C** [comment]
Em.. Right, I just relaunch the game. The issue showup agian. ><

Then "verify intergrity of game files" in steam could recovery icon issue.

**Comment by essbuh** [comment]
This is fixed by code r4858 and will be in the next update.

**Comment by Texas-C** [comment]
thx :D
