### ISSUE TITLE
Creating a listening server LINUX/BETA 1-11

### ISSUE THREAD

**Issue by Ric-FR** [nmrih/source-game#1106]
Creating a listening server, by opening port 27015 or other ports recommended for NMRIH via my router, does not work for me with "Beta 1-11", but on the other hand it works with "Proton 4.12" I use " Manjaro XFCE ". 

I found a temporary solution, for native LINUX version:

Type "sv_lan 0" each time you start the games and the first time you create your own game session .

**Comment by felis-catus** [comment]
Not an issue with the game, closing.
