### ISSUE TITLE
[beta-1.11.0] Keypads can still be controlled remotely

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1107]
~~Players are still able to interact with keypads behind walls following the previous fix. Some sort of trace ray is needed, but only involving world geometry; you don't want players holding props in front of keypads to prevent usage.~~

Edit: None of the fixes seem to work currently. Life state and distance are still ignored.

**Comment by dysphie** [comment]
Note that the trace should only hit world geometry. You don't want players holding props in front of keypads to prevent usage.

**Comment by dysphie** [comment]
Dead players can still use keypads.

**Comment by felis-catus** [comment]
Fixed in src-r4864.
