### ISSUE TITLE
[beta-1.11.0] Server crash on workshop_download_collection 

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1110]
Using `workshop_download_collection <collection id>` crashes the dedicated server.

**Repro steps:**
- `workshop_download_collection 1482947440` ([this](https://steamcommunity.com/sharedfiles/filedetails/?id=1482947440))

**Console output:**
```
workshop_download_collection 1482947440
free(): double free detected in tcache 2
Wrote minidump to [...]
```

**Stack trace:**
https://crash.limetech.org/yfmcv7ulyh6w

**Dump:**
[crash_yfmcv7ulyh6w.dmp.zip](https://github.com/nmrih/source-game/files/4172021/crash_yfmcv7ulyh6w.dmp.zip)

System: Debian 10 x64

**Comment by felis-catus** [comment]
Fixed in src-r4865.
