### ISSUE TITLE
[dev-r8964] You can be bit by multiple zombies simultaneously

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#1112]
According to Felis you aren't supposed to be able to be grabbed by multiple zombies but it still happens in the game.

[Video of multiple zombies biting you](https://www.youtube.com/watch?v=ymXkTnHD3rM)

One side effect of this is that if you push only one zombie away then all of them release you, as seen in [this video](https://www.youtube.com/watch?v=Y34v3z9XDrQ).

Another side effect is that zombies can cancel the bite of other zombies which allows you to walk away without shoving them or attacking them [as seen here](https://www.youtube.com/watch?v=N-Xpcmd5GUE).

This is easy to test if you run the following command `sv_zombie_dmg_onehand = 0; sv_zombie_dmg_twohand = 0; sv_kid_dmg_onehand = 0; sv_kid_dmg_twohand = 0; sv_runner_dmg_onehand = 0; sv_runner_dmg_twohand = 0` which will disable damage so that you increase the likelihood of seeing it (it's rare in normal gameplay, but still happens)

**Comment by essbuh** [comment]
This should be fixed by src-r4882

**Comment by Holycrapjimhox** [comment]
So far it appears to be fixed in r8975. It may need further testing.
