### ISSUE TITLE
[beta-1.11.0] nmrih_game_state infinite loop

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1117]
The server gets stuck in an infinite loop after interacting with `nmrih_game_state`. It seems to happen when a player dies after the round has been reset due to `RestartRound` on `nmrih_game_state`

Repro steps:
1. `map nmo_dev_world_felis` [nmo_dev_world_felis.zip](https://github.com/nmrih/source-game/files/4235364/nmo_dev_world_felis.zip)
2. Press the button in the middle (https://i.imgur.com/8H2edu7.png). You can do this during practice mode or afterwards, it doesn't matter. Button connections:
> "OnPressed" "game_state,RestartRound,,0,-1"
3. After the round restarts, input `kill` in console

The server should hang once it attempts to restart the round again
> WatchDog! Server took too long to process (probably infinite loop).

**Comment by essbuh** [comment]
Fixed in code src-4900
