### ISSUE TITLE
Player respawns at nearby ally location even in classic mode

### ISSUE THREAD

**Issue by Lunreth** [nmrih/source-game#1119]
Just noticed that instead of using map respawns, the game searched for nearby ally locations to respawn even in classic mode.

Steps to reproduce:
1 - Fresh install a SRCDS dedicated server of NMRIH
2 - Make sure you have sv_difficulty classic
3 - sv_respawn_nearby_allowed 1 (default cfg)
4 - Wait for a respawn at any objective map and watch how you teleport to nearby ally location instead of original map respawn

Note:
You don't need to configure any token CVAR or anything, just using default configs

Solution for other server owners:
* Use sv_respawn_nearby_allowed 0

**Comment by dysphie** [comment]
Starting an NMO on Classic difficulty automatically sets `sv_respawn_nearby_allowed` to 0. If I understand correctly, you are manually setting it to 1 afterward? If so then this is intended.

**Comment by Lunreth** [comment]
Actually, i was using the following CFG (from an old NMRIH thread) that didn't set any value for that CVAR, i had to manually set it to 0 since by default its set to 1:

// ********************************************************************************
//                                                                                *
//             No More Room in Hell - Community Developed Server.cfg              *
//              Latest Version: http://avidblur.com/nmrih/server.cfg              *
//                                                                                *
// ********************************************************************************

// ............................ Basic Server Settings ............................. //

// The name of your server as you want it to show up on NMRiH's Server Browser
hostname "(ARG) Lunreth's Laboratory - [OBJ/PVP/NMS]"

// The contact email for your main server admin (more than likely your email!)
sv_contact "corsecondary@gmail.com"

// VARIABLE PASSWORD AND DIFFICULTY
sm_msay ***classic Mode ACTIVATED***
sv_password "" // Use password when setting event
sv_difficulty classic // Casual - Classic - Nightmare
sm_cvar sv_difficulty classic
sv_respawn_nearby_allowed 0
sm_cvar sv_respawn_nearby_allowed 0

// The region of the world this server will report as being located in
// -1 = World
//  0 = US East Coast
//  1 = US West Coast
//  2 = South America
//  3 = Europe
//  4 = Asia
//  5 = Australia
//  6 = Middle East
//  7 = Africa
sv_region 2

// Is this server running on LAN or is it accessable to the world wide web?
//  0 = Internet
//  1 = Local Area Network (AKA "play-with-friends-behind-a-router-mode")
sv_lan 0
sv_cheats 0

// Enable communication over voice via microphone
sv_voiceenable 1

// Players can hear all other players, no team restrictions 0=off 1=on
sv_alltalk 1

// Password for rcon (remote connection), can be left blank for no RCon, it's recommended that you make a secure password.
// Need a secure password? Check out https://www.grc.com/passwords.htm for automatically generated ones (use the first one listed as "random hexadecimal characters")
rcon_password "suzannerocks123"

// Name of the .txt file containing a list of maps the server should cycle through
// mapcycle.txt - All maps
// mapcycle_objective.txt - Objective maps only
// mapcycle_survival.txt - Survival maps only
mapcyclefile "mapcycle.txt"

// A comma seperated list of tags that will show up in the server browser & make it easier for users to find the server they're looking for
// "Official" tags:
// custom - If your server is running custom gameplay settings/configs
// objective - If your server only cycles through objective maps
// survival - If your server only cycles through survival maps
// IE: sv_tags "example1, example2, example3"
sv_tags "zombie,fastdl,arg,nmo,pvp,nms,rank,achievement,objective,survive,escape,survival,chat,voice,br,event,vanilla,official,custom,chile,peru,us,comu,run,extraction,fast,easy"


// ............................ Download Settings .................................. //

// Allow clients to upload sprays etc (NMRiH has sprays disabled by default, so 0 might be the best option)
sv_allowupload 0

// Allow clients to download files
sv_allowdownload 1

// Maximum file size allowed for downloading individual maps/textures etc (Calculated in MB)
net_maxfilesize 192

// Allow downloading of maps/textures/etc from a website for faster download speeds!
// NOTE: If left blank (sv_downloadurl "") connecting clients will download custom maps etc directly from your Gameserver.
//
// Example: 1 - Game server has a map called "nmo_example.bsp" located in the map folder
//          2 - Web server has the exact same "nmo_example.bsp" file located at "http://www.yourwebsite.com/nmrih/maps/nmo_example.bsp"
//          3 - Therefore, sv_downloadurl should be set to "http://www.yourwebsite.com/nmrih/"
//
sv_downloadurl "http://181.169.123.62:27016/fastdl/nmrih/"
//sv_downloadurl "http://www.ulreth.vastserve.com/public_html/nmrih"
//sv_downloadurl "http://ulreth-laboratory.000webhostapp.com/nmrih/"
//sv_downloadurl "http://lunreth.000webhostapp.com/fastdl/nmrih/"
//sv_downloadurl "http://lunreth.byethost9.com/public_html/nmrih/"


// ............................... Network Settings ............................... //

// Min bandwidth rate allowed on server, 0 = Unlimited
sv_minrate 196608

// Max bandwidth rate allowed on server, 0 = Unlimited
sv_maxrate 0

// Minimum updates per second that the server will allow
sv_minupdaterate 32

// Maximum updates per second that the server will allow
sv_maxupdaterate 64
sm_cvar sv_maxupdaterate 64

// Minimum commands per second that the server will allow
sv_mincmdrate 32

// Maximum commands per second that the server will allow
sv_maxcmdrate 64
sm_cvar sv_maxcmdrate 64

// Amount of seconds that need to pass without a user sending data to the server before they are dropped (AKA: Timed out)
sv_timeout 45


// ********************************************************************************
//                                                                                *
//                         Custom NMRiH Gameplay Settings                         *
//                                                                                *
//  IMPORTANT: Add "custom" to sv_tags above if your server uses custom           *
//  gameplay settings!                                                            *
//                                                                                *
//  Uncomment the line below (delete the "// ") to customize gameplay settings    *
//  by editing the "nmrih_custom.cfg" file in your /cfg/ folder.                  *
//                                                                                *
// ********************************************************************************

// exec nmrih_custom.cfg


// ********************************************************************************
//                                                                                *
//                Advanced Server Settings (Best left untouched!)                 *
//                                                                                *
// ********************************************************************************

// WORKSHOP
workshop_download_collection 2014086285

// NEW CVARS
sv_spawn_grace 60

// CLASSIC CVARS
sm_cvar sv_realism 0
sm_cvar sv_hibernate_when_empty 0
sm_cvar sv_allow_votes 1
sm_cvar sv_vote_allow_spectators 0
sm_cvar sv_vote_allow_dead_call_vote 0
sm_cvar sv_vote_issue_restart_game_allowed 1
sm_cvar sv_vote_issue_kick_allowed 0
sm_cvar sv_vote_issue_changelevel_allowed 0
sm_cvar sv_vote_issue_nextlevel_allowed 0
sm_cvar sv_vote_quorum_ratio 0.85
sm_cvar sv_allow_dead_votekick_alive 0
sm_cvar sv_practice_transtime 60
sm_cvar mp_friendlyfire 0
sm_cvar sv_killpenalty 1
sm_cvar sv_friendly_fire_factor 0.5
sm_cvar sm_stats_tkpoints "-20"
sm_cvar sm_stats_extractionpoints "100"
sm_cvar sm_stats_deathpoints "-10"
sm_cvar mp_timelimit 30
sm_cvar sv_master_legacy_mode 0
sm_cvar sv_deathnotice 0
sm_cvar sv_pausable 1
sm_cvar sv_gravity 800
sm_cvar phys_timescale 1
sm_cvar phys_pushscale 1
sm_cvar sv_stam_jumpcost 20
sm_cvar sv_stam_min_move_pct 0.85
sm_cvar sv_stam_min_sprint_pct 0.414
sm_cvar sv_stam_regen_idle 20
sm_cvar sv_stam_regen_crouch 10
sm_cvar sv_melee_require_stamina 1
sm_cvar sv_stam_regen_moving 6
sm_cvar sv_max_stamina 130
sm_cvar sv_airaccelerate 10
sm_cvar sm_whisper_distance "128.0"
sm_cvar emotes_emote_scale 0.4
sm_cvar sm_qmr_timelimit 5
sm_cvar sm_qmr_mapcycle_enabled 1
sm_cvar sm_qmr_mapcycle "nmo_cabin,nmo_broadway,nmo_lakeside,nmo_brooklyn"
sm_cvar sm_rtv_needed 0.70
sm_cvar sm_rtv_time_enabled 180
sm_cvar sm_rtv_allow_deadvoting 0
sm_cvar sv_infection_chance 1.0
sm_cvar sv_bleedout_chance_low 0.05
sm_cvar sv_bleedout_chance_high 0.15
sm_cvar mv_speed_normal 116
sm_cvar mv_speed_riflesights 60
sm_cvar mv_speed_sights 76
sm_cvar mv_speed_sprint 224
exec banned_user.cfg
exec banned_ip.cfg
writeid
writeip
heartbeat
sm plugins reload extendedmapconfig
sm plugins load "c_nmrih_diffmoder"
sm plugins load "ServerAdvertisements3"
sm plugins load "saysounds"
sm plugins load "backpack"
sm plugins load "binoculars"
sm plugins load "maprate"
sm plugins load "nmrihstats-fork"
sm plugins unload "weapon-configs"
sm plugins unload "nmrih_team_deathmatch"
sm_rcon plugins disable "weapon-configs"
sm_rcon plugins disable "nmrih_team_deathmatch"
sm_rcon plugins enable "c_nmrih_diffmoder"
sm_rcon plugins enable "ServerAdvertisements3"
sm_rcon plugins enable "saysounds"
sm_rcon plugins enable "backpack"
sm_rcon plugins enable "binoculars"
sm_rcon plugins enable "maprate"
sm_rcon plugins enable "nmrihstats-fork"

**Comment by dysphie** [comment]
The cvar is set to 1 at launch but adjusted by difficulty scripts the moment you start a new game.  

You can test this by doing the following:
- Launch nmrih
- `sv_respawn_nearby_allowed` (will be 1)
- Start a new match on Classic
- `sv_respawn_nearby_allowed` (will be 0)

Can you confirm otherwise?

**Comment by Lunreth** [comment]
Confirmed, shown in images:

![1](https://user-images.githubusercontent.com/26940632/76435858-4d384900-6396-11ea-9614-f0d58e4cc773.jpg)

![2](https://user-images.githubusercontent.com/26940632/76435863-4f020c80-6396-11ea-87c8-42ce146aa4c9.jpg)
