### ISSUE TITLE
[public-1.11.0] Subdued manhole cover outline in Toxteth

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1121]
The manhole cover in Toxteth is affected by #985 

![maenhol-deopgae](https://user-images.githubusercontent.com/11559683/75996698-04d3e380-5edd-11ea-94ca-5fddba5c02dd.png)

If you look at it carefully you can see a very faint red outline. Picking a slightly different color should make it display properly

**Comment by AtheistNMRiH** [comment]
is it related to #920 ?

**Comment by dysphie** [comment]
Could be, but I think it's more to do with the outline color (same one as nmo_subside_v5's sewer key and door, which are also subdued)

**Comment by AtheistNMRiH** [comment]
@dysphie I tried to "pick a slightly different color" and no outline, so I guess it is same issue as #920 and not related to map

**Comment by felis-catus** [comment]
Closing, #920 is tagged as wontfix.
