### ISSUE TITLE
[public-1.11.0] nmo_quarantine runs out of edicts

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1122]
Quarantine is often running out of edicts on map reset. It just crashed while trying to give a spawned player a zippo. Stack trace: https://crash.limetech.org/eyc4ht7gv5yi

This has not been seen happening prior to 1.11.0

**Comment by felis-catus** [comment]
Similar to #1082, unknown if code bug. Labeling as map issue for now.

**Comment by essbuh** [comment]
Fixed by src-4903
