### ISSUE TITLE
[public-1.11.0] nms_midwest infinite player respawn during extraction

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#1124]
from #1123 , I checked the vmf and if I understand correctly, respawn should be disabled when extraction begins, but players still respawn even if they haven't respawn tokens

**Comment by Holycrapjimhox** [comment]
This also happened prior to 1.10.

**Comment by jxc20419** [comment]
I briefly mentioned this in #1080, turns out it wasn't linked to train softlock.

> they will infinitely respawn and the change level will never be triggered.

**Comment by Winning117** [comment]
I briefly mentioned this in #1080, turns out it wasn't linked to train softlock.

>they will infinitely respawn and the change level will never be triggered.

**Comment by AtheistNMRiH** [comment]
should be fixed in r9319
