### ISSUE TITLE
[public-1.11.0] Players stuck at controls on double +use (Regression)

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1127]
Players are unable to exit an inventory box if they manage to `+use` it while its interface is already open

Repro A:
- `net_fakelag 200`
- Spawn inventory box
- Spam E on it
- Attempt to close its interface

Repro B:
- Spawn inventory box and take note of its entity index
- Walk up to it and open it
- While in the interactive screen, open console and type `+use <entity index>`
- Attempt to close its interface

You are now unable to exit the interface and consequently move.
These same repro steps don't cause the player to get stuck in 1.10

It's also been reported that a similar thing happens with keypads, though I was unable to reproduce it.

**Comment by felis-catus** [comment]
Fixed in src-r4901.
