### ISSUE TITLE
[public-1.11.0] FireOutput server crash on objective completed

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1129]
Not a lot of info atm.

Stack traces:
https://crash.limetech.org/eyqnjxwrqj4q
https://crash.limetech.org/cx2nabridhvr

[dumps.zip](https://github.com/nmrih/source-game/files/4319013/dumps.zip)

**Comment by dysphie** [comment]
Hasn't triggered in months, assuming it's fixed for now.

**Comment by felis-catus** [comment]
Consistently crashes on 1.12.2 at `CBaseEntityOutput::FireOutput(variant_t, CBaseEntity*, CBaseEntity*, float) + 0x1f7`.
Managed to repro once by leaving the server, then completing an objective after the game transitions to warm-up mode.
Reopening.

**Comment by dysphie** [comment]
Closest repro available:

https://user-images.githubusercontent.com/11559683/171992100-5b55f523-ba79-4cd6-901a-8999a52e893f.mp4

console.log [console.log](https://github.com/nmrih/source-game/files/8837322/console.log)

**Comment by felis-catus** [comment]
Fixed in src-r6356.
