### ISSUE TITLE
[public-1.11.0] Forceful disconnects when server changes to a Workshop map

### ISSUE THREAD

**Issue by Holycrapjimhox** [nmrih/source-game#1130]
When the server switches to a custom map, players will get frequently forcefully disconnected with the message "Server is full." even when the max player limit is not reached. They are forced to manually re-connect and it can also happen whether you have the map already downloaded or not. So far it's unknown if it happens with any custom map or only custom maps that are available in the Workshop.

The server's console output usually looks like this. You can see that all players were disconnected within a 1 second window.

L 03/07/2020 - 21:06:38: "Resaka<446><[U:1:85546889]><>" disconnected (reason "Disconnect by user.")
Dropped Resaka from server (Disconnect by user.)
L 03/07/2020 - 21:06:38: "Luke<453><[U:1:189262181]><>" disconnected (reason "Disconnect by user.")
Dropped Luke from server (Disconnect by user.)
L 03/07/2020 - 21:06:38: "Iván De oli<457><[U:1:117308886]><>" disconnected (reason "Disconnect by user.")
Dropped Iván De oli from server (Disconnect by user.)
L 03/07/2020 - 21:06:38: "Nadark<452><[U:1:214296802]><>" disconnected (reason "Disconnect by user.")
Dropped Nadark from server (Disconnect by user.)
L 03/07/2020 - 21:06:38: "Pipita jugo al doom<456><[U:1:329682540]><>" disconnected (reason "Disconnect by user.")
Dropped Pipita jugo al doom from server (Disconnect by user.)
L 03/07/2020 - 21:06:38: "matiasxunder<455><[U:1:847599804]><>" disconnected (reason "Disconnect by user.")
Dropped matiasxunder from server (Disconnect by user.)
L 03/07/2020 - 21:06:39: "CartonConPus<454><[U:1:396455828]><>" disconnected (reason "Disconnect by user.")
Dropped CartonConPus from server (Disconnect by user.)
L 03/07/2020 - 21:06:39: "elchancho_02<434><[U:1:850902846]><>" disconnected (reason "Disconnect by user.")
Dropped elchancho_02 from server (Disconnect by user.)
Server is hibernating

**Comment by felis-catus** [comment]
Workshop implementation requires users to disconnect in order to download the map, they'll be booted out anyway due to missing files. Because of engine restrictions this is difficult to mitigate natively, hence server plugins are better suited for a workaround. Closing.
