### ISSUE TITLE
[public-1.11.0] NMRiH randomly crashes

### ISSUE THREAD

**Issue by NoLifeGamer111** [nmrih/source-game#1133]
My game crashes completely randomly (nothing special happening on screen, sometimes after a 5 hour session and sometimes after 20 minute session) I really need some help with this I alreasy lost some opportunities to earn achievements for completion of nmo maps.
My specs are:
Window 10
GTX 1050Ti
I7 8700
32gb RAM
I verified my game files through steam
I have no addons installed
I have deleted all the files in the Steam\steamapps\common\nmrih\nmrih\custom
In Steam\steamapps\common\nmrih\nmrih\gameinfo.txt line "supportsvr" is set to 0
My GPU drivers are up to date
I am uploading steam crash dump files
[nmrih crash dumps.zip](https://github.com/nmrih/source-game/files/4345371/nmrih.crash.dumps.zip)

**Comment by IamFake** [comment]
Confirm the same behavior under linux

ubuntu 18.04 (5.3.0-42-generic)
Ryzen 7
rtx 2070 (nvidia drivers)
32gb ram

[crash_20200325215851_1.dmp.gz](https://github.com/nmrih/source-game/files/4382472/crash_20200325215851_1.dmp.gz)

**Comment by felis-catus** [comment]
Unfortunately these dumps point to engine modules, which we can't debug. Closing.
