### ISSUE TITLE
[public-1.11.1] Infection chance varies heavily on game mode chosen

### ISSUE THREAD

**Issue by Holycrapjimhox** [nmrih/source-game#1134]
Infection chance is calculated in-game by the following formula:

GRM * (( 1 - (HP / maxHP * ICM))^2)

where:
• GRM = Game Rules Modifier (hardcoded values for Objective and Survival gamemodes, "1" and "2" respectively)
• HP = the current health points the player has
• maxHP = maximum health points (100 by default)
• ICM = Infection Chance Modifier (determined by sv_infection_chance_modifier, "0.975" for Classic difficulty and "0.14" for Nightmare difficulty)

The issue here is that due to the hardcoded value of "2" in Survival gamemode, infection chances differ greatly between this and Objective mode on Classic difficulty. Even more prominent is the fact that if you select Nightmare difficulty, Survival will yield a 100% chance of infection per bite, regardless of player HP. Objective mode on Nightmare difficulty starts at 74% and gradually ramps up the lower the player HP is.

Suggestion: Change the hardcoded value for Survival gamemode to "1", the same as in Objective. This way, the infection chance will work consistently between gamemodes and it will balance Nightmare difficulty by not having a 100% chance of infection per bite.

Here's a picture essbuh took of the line of code responsible for the infection chance calculation:
![infect](https://user-images.githubusercontent.com/35630284/77572109-2bb68180-6ead-11ea-8d3a-3ea03ece6dc7.png)

**Comment by dysphie** [comment]
easier visualization https://dysphie.github.io/nmrih-infection-calculator/

**Comment by Bubka3** [comment]
I think removing the GRM part of the formula would resolve this / be fine.

**Comment by felis-catus** [comment]
Commit src-r4922 adds SurvivalInfectionChanceModifier to difficulty script, it controls the GRM value in NMS gamemode. NMO remains unchanged.

By default, the modifier stays at 2.0 for classic and casual difficulties, nightmare has it set to 1.0 to mitigate the infection chance.
