### ISSUE TITLE
I must deactivate / delete everything Steam Workshop + random crashes ... + issue create listen server Windows/Linux

### ISSUE THREAD

**Issue by Ric-FR** [nmrih/source-game#1135]
I use both Linux and Windows systems and I discovered that it was important not to download the "maps" created by the community of players on the Steam Workshop which bug ... in short ... it is necessary connect to the servers which offer almost all the cards created by the players when a card interests you it will download you will be able to play and especially NOT to have cards downloaded from the "Workshop" of "Steam" ... otherwise when you connect at a lobby you will have "Missing Cards" and you will be disconnected ... and I have noticed since update 1.11 all the parts to which I connect crash after about 15 minutes regardless of the region I choose for myself connect as well on Linux with the game in native version as on Windows 10

**Comment by dysphie** [comment]
Clients should automatically download any workshop maps that the server is subscribed to, are you saying this does not happen?

**Comment by TheUnstableNutcase** [comment]
You might wanna rephrase the title in a way that actually describes what the issue is

**Comment by Ric-FR** [comment]
Hi, all the Workshop objects that I download and subscribe to work, but when I connect to a server that has a "map" that I don't have, this is what happens: 

The map is downloaded and at the end of the download I have "Missing Maps" which is displayed and I am disconnected and returned to the NMRIH page. 

To not have all these problems I am forced to unsubscribe from the Workshop and uninstall NMRIH delete the Steam folder and reinstall NMRIH without being subscribed to the Workshop and now when I connect to any server that has a map that I don't have it downloads and works ... 

I also have other problems that I did not have with version 1.10: 

I can no longer open ports to create a "Listen" server, I may open port 27015 or other ports, for me it does not work anymore ... whether Windows or Linux. 

The game crashes every 20 minutes when I play on any server, on the other hand the games do not crash when I play in LAN, I had very rarely this type of problem before, I have a good internet connection . 

English is not my usual language, I use an online translator. Thank you for your help and for this excellent game that is NMRIH. 

----- Mail original -----

De: "dysphie" <notifications@github.com> 
À: "nmrih/source-game" <source-game@noreply.github.com> 
Cc: "Ric-FR" <captain.flip@laposte.net>, "Author" <author@noreply.github.com> 
Envoyé: Vendredi 27 Mars 2020 00:55:58 
Objet: Re: [nmrih/source-game] Steam Workshop (#1135) 






Clients should automatically download any workshop maps that the server is subscribed to, are you saying this does not happen?

**Comment by Bubka3** [comment]
The issue tracker is not appropriate for general troubleshooting or support requests.

Please use the support forums here: https://steamcommunity.com/app/224260/discussions/2/

Issues should contain a single problem and preferably have reproduction steps if possible.

**Comment by Ric-FR** [comment]
Yes and when I answer on Steam in a subject that you or other players create you tell me go to Github ... and you also delete certain player subjects that report problems to you in detail or not (I already given my pc config in previous closed topics or that you deleted) rather than solving them ...

**Comment by essbuh** [comment]
Sorry there seems to be some confusion here...

- Disconnection when downloading workshop maps is a known issue ( #1130 )

- Support for creating listen servers should be dealt with on the support forums, there is not much we can do as we don't have engine sources so there's nothing we can actually fix about it (make sure you double check everything here: https://steamcommunity.com/sharedfiles/filedetails/?id=190894151)

- If you've got crashes, please post any crash dumps you may find (instructions on how to find them are here: https://github.com/nmrih/source-game/)
