### ISSUE TITLE
[public-1.11.1] SourceTV spawned as player

### ISSUE THREAD

**Issue by extraspeed** [nmrih/source-game#1136]
When setting tv_enable 1 in startup params, SourceTV bot spawning as player.
Map: nmo_broadway
![20200328191143_1](https://user-images.githubusercontent.com/9309537/77831650-82d48480-7141-11ea-8bd9-4aa40693d8e3.jpg)

**Comment by extraspeed** [comment]
This bug happens when using a plugin AutoJoin

**Comment by felis-catus** [comment]
Closing, plugin issue.
