### ISSUE TITLE
[pubilc-1.11.1] Zephyr segfault on map reset

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1137]
Zephyr is crashing on map reset since the 1.11.1 hotfix. Looks like a code issue

Stack traces:
https://crash.limetech.org/aigk3mu4wuah
https://crash.limetech.org/i76db5jzwvcq

Dumps:
[1137_dumps.zip](https://github.com/nmrih/source-game/files/4399291/1137_dumps.zip)

Tested on both Windows and Linux

**Comment by NotRealPaz** [comment]
Same
https://crash.limetech.org/ko7uoqpo4qyy
https://crash.limetech.org/rzc4q2npgbf7
