### ISSUE TITLE
[public-1.11.1] Zombies instantly teleport to the player’s position when a cinematic ends

### ISSUE THREAD

**Issue by SCHATTENSPIEL** [nmrih/source-game#1138]
If you are walking forward while having a group of runners chasing after you and then a cinematic starts playing, you can see that every zombie is frozen, as it should be. However, once the cinematic ends and the player regains control, some of the runners will move instantly to your position as if they are teleporting. This causes you to get instantly grabbed and attacked without having even half a second to react. Shamblers also teleport but don't pose any threat unless they are too close to the player.

Here’s a video that showcases this issue in both custom maps and official maps. The last example is the most prominent: https://www.youtube.com/watch?v=FI5Paapt5Vs 

There is no consistent way to avoid this and it happens pretty regularly. This issue was already present in 1.11 and it continues to happen in 1.11.1.

**Comment by Holycrapjimhox** [comment]
Confirmed fix on dev-r9004.
