### ISSUE TITLE
Clients waste time downloading nodegraph files

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1140]
Clients attempt to download .ain files for maps that they have never played locally. As far as I can tell the game doesn't even use these files and it results in longer connection times when joining a server (sometimes by as much as half a minute)

**Comment by felis-catus** [comment]
dev-r9010 adds workaround, `nodegraph 0` to gameinfo.txt delists .ain files from download table, doesn't appear to alter any AI node behavior. Tested and confirmed on a listen server.
