### ISSUE TITLE
[public-1.11.1] Nades take ammo space

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1142]
Grenades, molotov cocktails and TNT take ammo space and I don't think they should. Reasoning for this being:

a) No other expendable does it (first aid kit, bandages, gene therapy)
b) You can't stack nades anyway
c) They already take item inventory space, no other item takes both
d) Its 'ammo' cannot be dropped on click/hover unlike every other ammo menu entry
e) The game doesn't expect it. When a nade is picked up, the game only checks that you have enough space in your item inventory, not ammo. This can lead to bugs in servers with no inventory limit, where picking up a nade while your ammo inventory is full causes it to vanish into thin air

**Comment by felis-catus** [comment]
Fixed in src-r4924.
