### ISSUE TITLE
[public-1.11.1] Item related chat inputs no longer show up

### ISSUE THREAD

**Issue by TheUnstableNutcase** [nmrih/source-game#1144]
Certain maps have a feature where if a player picks up an inventory item or an objective item, it triggers to say something in the text chat. For example, in Shelter if "username" picks up the welder it says in the chat "username: I picked up the welder."

This feature no longer seems to work as of 1.11.1

**Comment by Holycrapjimhox** [comment]
That feature was disabled in 1.11 to avoid maps spamming chat commands and other things like changing server cvars, bypassing the server owner's configuration.
