### ISSUE TITLE
[public-1.11.1] Activating the siren too early on nmo_quarantine breaks extraction camera

### ISSUE THREAD

**Issue by TheUnstableNutcase** [nmrih/source-game#1145]
On nmo_quarantine, once the failsafe activates and you get the white flash on your screen, it's possible to press the siren button before the map calls for it. Side effects of this include the helicopter arrival cutscene not playing, however the helicopter still arrives regardless.

Here is a screenshot for a little bit of additional reference:
![quarantinefinale](https://user-images.githubusercontent.com/42658874/81727689-9cf2c980-9446-11ea-871b-b32b808dcaa3.jpg)

**Comment by felis-catus** [comment]
Fixed in 1.11.2.
