### ISSUE TITLE
[1.11.1] point_servercommands still execute

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1146]
`point_servercommand`s were supposedly nuked but they still fire.

Repro steps:
1. Subscribe to https://steamcommunity.com/sharedfiles/filedetails/?id=2045397900
2. `map nmo_jurassicpark`
3. Walk towards the nearest gate and open it, it will print credits to chat

VMF uses a `point_servercommand` for this: https://hatebin.com/rqqhbmtaha

```c
entity
{
	"id" "11751"
	"origin" "-2305 1286.61 160"
	"targetname" "narrator"
	"classname" "point_servercommand"
}
```

```c
	"classname" "trigger_once"
	connections
	{
		"OnTrigger" "firstdoorlight,TurnOff,,0,-1"
		"OnTrigger" "narrator,Command,say map created by Caster Jr AKA Just Some Alien,0,-1"
	}
```

**Comment by felis-catus** [comment]
Fixed in src-r4920.
