### ISSUE TITLE
[1.11.1]Sound Cache potential crash issue on Linux

### ISSUE THREAD

**Issue by Zetabite** [nmrih/source-game#1147]
I had problems with crashes the last view days. After some investigating and File Verifying via Steam, it seems like that something generating the sound cache crashes the game, as it is re-downloaded every time and the game works fine for some time.gladly provide it asap. Since the error is reproducible (tho i don't know under which circumstances).
System Info: https://i.imgur.com/5dseVus.png
[dumps.tar.gz](https://github.com/nmrih/source-game/files/4706912/dumps.tar.gz)

**Comment by felis-catus** [comment]
Weird, the game ships with up to date sound cache and it shouldn't be rebuilt automatically. Crash dumps unfortunately point to system modules and can't be debugged.

**Comment by Zetabite** [comment]
what the hell. source engine is weird
