### ISSUE TITLE
[public-1.11.1] Playing demos recorded with closed captions on can crash the game

### ISSUE THREAD

**Issue by Holycrapjimhox** [nmrih/source-game#1149]
Recording a demo with closed captions on and effectively recording an action that prints out captions, like a voice command, will crash the game when replaying them with closed captions off.

• Steps to reproduce:
1) Turn on Closed Captions in the audio options
2) Start playing on any map
3) Type "record x" in the console (replace the "x" with the desired name for the demo file)
4) Play any voice command via the 3 key
5) After the caption shows up, type "stop" in the console to stop the recording
6) Return to the main menu by disconnecting
6) Turn off Closed Captions in the audio options
7) Type "playdemo x" in the console to play the demo, the game will crash as soon as any captions shows up

• Workaround:
Turning on closed captions and then playing the desired demo file (which was recorded with closed captions on) will prevent the game from crashing.

• Crash Dump:
[crash_dump.zip](https://github.com/nmrih/source-game/files/4841277/crash_dump.zip)

**Comment by felis-catus** [comment]
Fixed in src-r4931.
