### ISSUE TITLE
[Public 1.11.1] Players get Immortality/Invincible when spectating a player thats view a point_viewcontrol

### ISSUE THREAD

**Issue by muhtadimunshi** [nmrih/source-game#1150]
Lets say in this situation there are two players, one who is alive and who is dead. The dead player is spectating the alive player. The alive player presses a button which enables a point_viewcontrol and lets him see a cut scene (which is just one camera being on for a few seconds), and after the cut scene all players get re spawned, Except instead of the alive player seeing the cut scene, the dead player is seeing the cut scene due to the spectate. When the dead player re spawns, he is invincible and takes no damage. Even when a zombie smacks him, the revived player does not even take knock back or have his screen shake.

**Comment by dysphie** [comment]
Do you have a map to test this on? I can't get the camera view to trigger for spectators

**Comment by felis-catus** [comment]
src-r4945 should fix this.
