### ISSUE TITLE
[public-1.11.1] Server getting stuck after nmo_quarantine ending cutscene fails to trigger

### ISSUE THREAD

**Issue by Holycrapjimhox** [nmrih/source-game#1153]
I've gotten several reports that, occasionally, the ending cutscene on nmo_quarantine doesn't play. However, the helicopter does arrive as programmed, but if all players get extracted or die, the map will not end for the round to restart or to trigger a map change. The server gets permanently stuck unless an operator triggers a map change via console or plugins. So far, there's no knowledge on how to reproduce the issue.
![20200805005027_1](https://user-images.githubusercontent.com/35630284/89372163-cd4faa00-d6bb-11ea-9379-0c7f0d463560.jpg)

**Comment by TheUnstableNutcase** [comment]
Does it have something to do with Issue #1145 ?

**Comment by Holycrapjimhox** [comment]
Possibly. However there is no mention of the server getting stuck. I'll see if I can trigger the bug by doing that.

**Comment by Holycrapjimhox** [comment]
So, I tested the process explained in #1145, but the cutscene did play regardless and the map restarted as expected. I suggest fixing #1145 and see if this issue reoccurs.

**Comment by TheUnstableNutcase** [comment]
> So, I tested the process explained in #1145, but the cutscene did play regardless and the map restarted as expected. I suggest fixing #1145 and see if this issue reoccurs.

Weird. I’ll try and test out the issue to see how consistent it is

**Comment by felis-catus** [comment]
Now that #1145 is resolved, can you test if this still occurs in 1.11.2?

**Comment by Holycrapjimhox** [comment]
I'll give it a go but we never found out if these issues were related or not. I'll try to reproduce the earlier issue and see if this one pops up.

**Comment by Holycrapjimhox** [comment]
I couldn't reproduce the issue thus far. I'll re-open the post if it happens again.
