### ISSUE TITLE
[public-1.11.1] sv_realism 1 does not apply to fa_winchester 1892

### ISSUE THREAD

**Issue by T4WER1** [nmrih/source-game#1154]
Hello. I noticed this a long time ago, even before the current updates. It's not a serious mistake, but it's still a strange one. I often play on nightmare with realism and noticed that realism simply does not work on fa_winchester1892. Sv_realism 1 does not apply to Winchester and it does not always kill zombies with 1 shot, like other guns and it punches zombies as well as without realism. In the video, I clearly showed that on realism, other guns kill with one shot , but the Winchester does not. This is a bit illogical, since a .22 caliber kills zombies with a single shot, 9 mm too, but it is the Winchester with .357 does not kill with a single shot. The weapon scripts are not changed on the server, you can check this error anywhere(nightmare servers with realism or LAN server). I raised the HP of a zombie just to prove it. The moment of shots from the Winchester at 1: 16
https://www.youtube.com/watch?v=pUGnirRCcOo&feature=youtu.be

**Comment by felis-catus** [comment]
Fixed in src-r6241.
