### ISSUE TITLE
Feature Requests. Support full controller ( xbox controller )

### ISSUE THREAD

**Issue by yomox9** [nmrih/source-game#1160]
NRRiH is still "Partial Controller Support". I think that NMRiH1(and NMRiH2) should support full controller. If NMRiH support it, NMRiH will get more users.

**Comment by felis-catus** [comment]
To make that happen, we would have to redesign all the menus, UI controls (such as radial wheels), and tweak existing player controls to better suit controllers. The work required is staggering and it goes way beyond our current scope, closing.

**Comment by yomox9** [comment]
I'm sad. very sad... I edited many maps, I made Japanese server and keeping it. But I could not play comfortably...
