### ISSUE TITLE
[public-1.11.1] callvote doesn't work well(some bugs)

### ISSUE THREAD

**Issue by T4WER1** [nmrih/source-game#1162]
Hello, voting in this game works even worse after the update and I think many people agree with this(from experienced players). I want to tell you about some annoying voting problems.

The first problem is when it is impossible to understand what you need to vote for, because instead of the text, this is shown:
![20201031180857_1](https://user-images.githubusercontent.com/52475774/97782891-3fde0200-1ba5-11eb-8e44-6efe271de6a2.jpg)

The second bug with voting is that sometimes players simply can't vote and the button is not pressed, that is, voting ignores these people and because of this, for example, sometimes it is impossible to change the map and so on. I do not know what this is due to, but this bug was also in older versions.

And third, this is not a bug, but an unpleasant thing. For example, when you vote, the vote is instantly hidden and you can't see the voting status. This is especially terrible to watch when you are kicked from the server by players, and you do not even see this vote and do not see who kicked you. Please add a special command in the console or return it as it was before.

**Comment by felis-catus** [comment]
Resolved by #1295 closure.
