### ISSUE TITLE
When the player stands on an item, the zombies stop attacking.

### ISSUE THREAD

**Issue by Dayonn-dayonn** [nmrih/source-game#1163]
I've rarely used github, and I'm new to bug reports. Please forgive me if there are some things that may not be written correctly.
I found out about it today after watching other players play. I decided to report it because I thought it was a fatal and destructive bug to the game experience.

![20201112105238_1](https://user-images.githubusercontent.com/37202119/98891797-48f29b80-24e2-11eb-8d52-c26180af4b58.jpg)

 If I place an item at your feet and stand directly above it, the AI seems to stop processing the bite attack and zombies stand on a stick. The result is a temporary safety zone. I haven't tested this yet, but the size of the item seems to matter. While I could easily do this with medkit, but it didn't work with machetes.
 I can become completely invincible.However, if I move, I will be attacked. So I may get stuck in places where very many zombie respawns.

I have created plugins. Most recently I created health_and_stamina_disp. I thought it was because of a bug in the plugin to change zombie behavior. So I tried to test the behavior in a local environment with all plug-ins removed. As a result... It's done. I can become invincible anywhere. This is danger, disrupt the gaming experience.
 Is this just a problem with NMRiH, or is it a problem with all games that use SourceEngine? (I don't have any other games, so I don't know...)
 I hope NMRiH2 doesn't have the same bug.

**Comment by AtheistNMRiH** [comment]
Duplicate of #1143

**Comment by Dayonn-dayonn** [comment]
I didn't search for the word "incapacitated". Thanks for letting me know about the duplication.

**Comment by dysphie** [comment]
If you are a server operator I have a [Sourcemod plugin](https://forums.alliedmods.net/showthread.php?t=325956) that addresses this issue

**Comment by Dayonn-dayonn** [comment]
Oh, great! I'm not a server administrator, but I have a friend who is a server administrator. I will let him know about this plugin. Thanks for letting me know!
