### ISSUE TITLE
nmrih_extract_preview issues

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1165]
1. Players can move during the extraction preview while having damage immunity
2. If you die during the preview, your camera gets locked into that position until the next round, even if you respawn
3. When the next round starts, your viewmodel will be invisible

possibly related to #530 

Repro:
`map nmo_suzhou`
`thirdperson`
`ent_fire extraction_preview enable`
move around
`kill`
`ent_fire extraction_preview disable`

**Comment by AtheistNMRiH** [comment]
![image](https://user-images.githubusercontent.com/11333747/103342534-4e209f80-4abc-11eb-940c-5c156e26fdf9.png)
maybe player can move because there is no Freeze player flag?

**Comment by felis-catus** [comment]
Listed issues fixed in src-r4945.
