### ISSUE TITLE
[public-1.11.2] ambient_generic cannot be stopped + fix

### ISSUE THREAD

**Issue by Jenoxen** [nmrih/source-game#1167]
When using any kind of trigger or button you cannot stop the ambient_generic sound from playing, There's a [c++ fix](https://developer.valvesoftware.com/wiki/Ambient_generic:_stop_and_toggle_fix) on the valve wiki that helps fix this issue.

Repro:
1)Put ambient_generic on map and a toggle/multitoggle button with start stop or toggle commands
2)Trigger ambient_generic, Once it starts try to stop it again
The ambient_generic won't stop playing even if the trigger tells it to.

**Comment by felis-catus** [comment]
Unable to repro, patch from the wiki is already applied in the build. Do you have a sample .vmf or entdata with the I/O connections that induced this bug?

**Comment by Jenoxen** [comment]
Turns out this "bug" was my bad, I was following a guide to making a start stop button for a sound and I never unchecked "Is NOT Looped" (Since the guide never mentioned this) and while searching for causes I found the hammer wiki that said that it was a known bug, When it's checked the sound only restarts after pressing the button.

_PEBCAK, Please close this._

**Comment by TheUnstableNutcase** [comment]
> Turns out this "bug" was my bad, I was following a guide to making a start stop button for a sound and I never unchecked "Is NOT Looped" (Since the guide never mentioned this) and while searching for causes I found the hammer wiki that said that it was a known bug, When it's checked the sound only restarts after pressing the button.
> 
> _PEBCAK, Please close this._

You can close your own issue btw
