### ISSUE TITLE
[public-1.11.2] Dying during extraction with respawn tokens makes game entering WAVE_STATE_WIN

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#1168]
I've noticed it during mapping on custom map but then checked on arpley and notld
1) Complete nms map until extraction
2) Make sure you have respawn tokens (I've reduced amount of waves for testing)
![nms_arpley0000](https://user-images.githubusercontent.com/11333747/105365239-9f8dfb80-5c30-11eb-86f8-73fbaa9ca5b8.jpg)
3) Die during extraction (it says "Survivors have withstood the horde!"):
![nms_arpley0001](https://user-images.githubusercontent.com/11333747/105365274-a9176380-5c30-11eb-822a-0a7f63c542ba.jpg)

If you die without respawn tokens, game enters fail state and you get correct message

All maps have proper extraction setup (inputs/outputs, entities), and I didn't check if this bug happens when there are more players on server (dead or alive)

**Comment by felis-catus** [comment]
Fixed in src-r7637.
