### ISSUE TITLE
[public 1.11.3] Weapon animations get stuck while selecting them from the weapon wheel

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#1172]
I don't believe that this is a regression because there are other issues semi-related to this one, but I'm not positive.

Steps to reproduce (from what I can tell):
1. Pull out a firearm
2. Equip that same firearm from the weapon wheel while the weapon is in the middle of being pulled out

Here are a few videos that I have of this occurring:
https://www.youtube.com/watch?v=F4PR4CeH5FQ
https://www.youtube.com/watch?v=Csc2VVLR7qI
https://www.youtube.com/watch?v=4skjY7osF44

I think that #912 _might_ be related, but that issue specifically calls out using the keypad.

**Comment by felis-catus** [comment]
Fixed in src-r5098.
