### ISSUE TITLE
[public-1.11.4] "TEST" appearing on the screen during nmo_quarantine finale

### ISSUE THREAD

**Issue by TheUnstableNutcase** [nmrih/source-game#1173]
During the finale on nmo_quarantine, there's a game_text entity which displays the word "TEST" on the screen. Obviously this isn't intended

![test1](https://user-images.githubusercontent.com/42658874/109727035-e694d800-7b70-11eb-8318-abb63bb1ae28.png)

**Comment by felis-catus** [comment]
Fixed in dev-r9221.
