### ISSUE TITLE
[public-1.11.4] Players can touch Broadway2 rails and die after train arrives

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1174]
It used to be that you couldn't get shocked by the rails once the train had arrived
https://gfycat.com/shrillgrizzleddotterel

Somehow this changed with 1.11.2 and now you can accidentally die which is confusing to players
https://gfycat.com/tamedigitalblackfly

Brush dimensions are the same so I'm not sure what happened, but the trigger_hurt should be moved back a bit

**Comment by AtheistNMRiH** [comment]
maybe new doors somehow causes that, anyway gonna move back that brush

**Comment by AtheistNMRiH** [comment]
fixed in r9069
