### ISSUE TITLE
[public-1.11.4] Extraction camera showing at wrong origin

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1175]
Possibly related to #1169, something is causing extraction cameras to display at the wrong origin

1.13.1: https://gfycat.com/graveonlygonolek
1.14.1: https://gfycat.com/weesplendidkronosaurus

Repro:
- `map nmo_silo_v1` ([workshop](https://steamcommunity.com/sharedfiles/filedetails/?id=2021794219))
- `sv_cheats 1`
- `ent_fire extraction_preveiw enable` (not a typo)

Looks like `target` might be getting ignored? 

```cpp
entity
{
	"id" "307788"
	"origin" "-336 0 1063.71"
	"wait" "10"
	"targetname" "extraction_preveiw"
	"target" "rocket"
	"spawnflags" "3"
	"deceleration" "500"
	"angles" "0 0 0"
	"acceleration" "500"
	"classname" "nmrih_extract_preview"
}```

**Comment by felis-catus** [comment]
Fixed in src-r5009.
