### ISSUE TITLE
[public-1.11.4] Invisible models if round restarts during active extraction preview

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1176]
Perhaps related to #530 

Repro:
- `map nmo_silo_v1` ([workshop](https://steamcommunity.com/sharedfiles/filedetails/?id=2021794219))
- `sv_cheats 1`
- `ent_fire extraction_preveiw enable` (not a typo)
- `restartround` before the preview ends

You'll respawn and all zombies and props will be invisible

**Comment by felis-catus** [comment]
Fixed in src-r5019.
