### ISSUE TITLE
[public-1.11.4] Players respawning in the water on nmo_suzhou in casual mode

### ISSUE THREAD

**Issue by TheUnstableNutcase** [nmrih/source-game#1177]
Apparently some players have been experiencing a bug on nmo_suzhou in casual mode where players have been respawning in the water.

Here’s a link to some images from a user who’s witnessed seeing this bug:

https://imgur.com/a/hAwfMJy

**Comment by Dayonn-dayonn** [comment]
This is my experience, players can't respawn inside the tunnels in nmo-junction, but they can respawn where the key is or near the door. I suspect that the ground must be flat to be able to respawn.
Using this, I think that if the bottom of the river is tilted like a V, player can go in the river and player not be respawned in the river.

**Comment by AtheistNMRiH** [comment]
should be fixed in r9324
