### ISSUE TITLE
[public-1.11.4] Game plays "greetings" NG sound if supply drop comes after 1st wave

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#1181]
not really a big issue, but if supply drop will come after every wave including frist one, it will play and show that "break-break" message every time, not respective "supply incoming" sound and message
![nms_roadway0000](https://user-images.githubusercontent.com/11333747/113578261-b9928400-964c-11eb-99d1-01b560411253.jpg)

**Comment by felis-catus** [comment]
Fixed in src-r6242.
