### ISSUE TITLE
[public-1.11.4] Servers subscribed to a deleted workshop map become unjoinable when said map is active

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1182]
Repro:
1. Upload a map to the workshop
2. On the server-side, subscribe to said map
3. Delete or private the map from the workshop (or WS is temp unavailable)
4. Changelevel to said map
5. Attempt to join the server as a client

You'll get a "Failed to download a map from Workshop!" prompt and get kicked out, even if your client already owns the map.

![image](https://user-images.githubusercontent.com/11559683/113803121-46fbd400-9732-11eb-9d1c-c2083d408516.png)

**Comment by Holycrapjimhox** [comment]
NOTE: Even if you provide the deleted WS map through other means like fastdl, the server will keep getting stuck until you remove its entry in the "workshop_maps.txt" file inside the main server folder.

**Comment by felis-catus** [comment]
Fixed in src-r5028.
