### ISSUE TITLE
[public-1.11.4] Rare tools and weapons not spawning in supply crates

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1189]
The chance of spawning rare tools (welder, extinguisher, flare gun) and weapons (chainsaw) in supply crates seems hosed.
Neither `sv_rare_tool_chance` nor `sv_rare_weapon_chance` do anything at the moment. See `CItem_InventoryBox::Spawn`, code's weird

**Comment by felis-catus** [comment]
Fixed in src-r5059.
