### ISSUE TITLE
Microphone doesn't work in-game or even settings.

### ISSUE THREAD

**Issue by Undastelar** [nmrih/source-game#1190]
----------------------------------------------------------------------------
Microphone simply won't work in game or in settings when I try to run it in "Test Microphone" button, after pressing it, it just resets instantly.
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Next I will write what steps I took and solution I found and tried to fix my problem:
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
-Tested the microphone in other Source games in other games too, and it works great.
-Tested the mic in "Friends List Settings" -> "Voice" tab -> "Start Microphone Test", works well there.
-Had subscribed before to a lot of content in NMRiH Workshop section, and I unsubscribed to all and uninstalled them manually.
-Checked the forums that NVIDIA GeForce Experience may be the problem, uninstalled it too.
-Set my Microphone as Default Device and Default Communication Device. Tried to switch to other Microphone in the same manner.
-Disabled any other interfering device.
-Checked if there is no other application using my microphone in real time. Was no such thing.
-However in Microphone Privacy Settings, NMRiH process is not present. This might be the issue of it not being able to be implemented in System settings.
-Uninstalled audio driver, and reinstalled it again from:
-the official motherboard site,
-uninstalled again and installed from Realtek official site corresponding to my hardware compatibility,
-uninstalled again and installed thru Windows Update.
-Tried to apply specific console commands that was related to microphone/voice settings.

Running on Windows 10 Pro 20H2 (OS Build 19042.928)
GPU: NVIDIA GeForce RTX 2060 4.00 GB
CPU: Intel® Core™ i7-7700 CPU @ 3.60GHz
RAM: 16 GB DDR4

Nothing changed. If anyone knows a fix for this, I would be very happy to get some help from you.
Awaiting response from the developers too.

Thanks a lot.
-David.
Sorry, but I submitted this issue on 27th of April, but didn't get an answer since.

![121](https://user-images.githubusercontent.com/49108237/117542623-0db0cf80-b022-11eb-9e00-3b44858b8ff7.gif)

**Comment by felis-catus** [comment]
This doesn't appear to be an issue with the game, so I'm closing this. Please use Steam discussions or Discord for tech support.
