### ISSUE TITLE
[public-1.11.4]The position and angle of the camera when starting of the escape is abnormal

### ISSUE THREAD

**Issue by Dayonn-dayonn** [nmrih/source-game#1191]
When the escape begins, the camera position will be someone player's point of view. Then, the angle of the camera display will gradually change from a horizontal angle looking straight ahead to an angle looking at someone's feet.
This bug sometimes occurs. I feel like this always occurs in nmo-fema.
This bug seems to have started occurring recently. (only ver1.11.4?).

**Comment by dysphie** [comment]
This is an issue with mappers misusing extraction camera flags, it's fixed in a future release.
In the meantime you can use this [community fix](https://forums.alliedmods.net/showthread.php?t=331050)

**Comment by Dayonn-dayonn** [comment]
Thank you for letting me know.

**Comment by Dayonn-dayonn** [comment]
In the future, I will check this issue and also check your list of plugins. Sorry for starting an unnecessary thread.

**Comment by felis-catus** [comment]
Duplicate of #1175

**Comment by Dayonn-dayonn** [comment]
Oh, sorry... I was half asleep.

**Comment by felis-catus** [comment]
No worries, thanks for contributing! There's no harm in opening a new issue anyway, if it's a duplicate we simply close and mark it as such.
