### ISSUE TITLE
[public-1.11.4]No fall damage on ladder

### ISSUE THREAD

**Issue by Dayonn-dayonn** [nmrih/source-game#1193]
If you grab the ladder before you land from a high fall, you will not take fall damage.This will save you time in nmo_cabin and nmo_broadway2. Please see movie.

[https://youtu.be/gVic89W5jX0](https://youtu.be/gVic89W5jX0)

Is this an intended spec or a bug?
I don't know if there are any athletic maps that take advantage of this spec.
I hope this bug report is not a duplicate of anything.

**Comment by TheUnstableNutcase** [comment]
This isn't really an issue/bug, nor can this really be fixed

**Comment by Dayonn-dayonn** [comment]
I see. Should I close this thread?

**Comment by felis-catus** [comment]
We don't usually fix common movement tricks and glitches that add more depth to gameplay. Closing.
