### ISSUE TITLE
OnEndFollow fires twice

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#1194]
1. play nmo_fema
2. complete it until exraction
3. when camera ends follow first time, sound "come on and get in" will play first time
4. get in the chopper
5. OnEndFollow fires second time and you hear the sound again
![nmo_fema0002](https://user-images.githubusercontent.com/11333747/120065004-601d6300-c099-11eb-98be-41cc9eb466bf.jpg)
(781 and 792 seconds)
it seems like regression, because it never happened before, also sorry, I don't have a time to check if it presents in public build :p

**Comment by felis-catus** [comment]
Fixed in src-r5097.
