### ISSUE TITLE
[public-1.11.4] Viewmodel walking animation is delayed

### ISSUE THREAD

**Issue by randomperson189** [nmrih/source-game#1195]
When I start walking, the walking animation doesn't play for a few seconds and it gets a bit annoying and noticeable especially with headbob on, it also happens when I stop walking.

Steps to reproduce:
1. Load any map and spawn in
2. Walk forward for a bit and then stop

I think the issue is caused by the viewmodel waiting for the idle animation to finish before starting the walk animation, same with going from walking to idle. This doesn't occur for the sprinting animation however so this issue can be easy to fix.

**Comment by felis-catus** [comment]
Fixed in src-r6012.
