### ISSUE TITLE
NMRIH randomly crashes in Windows 10

### ISSUE THREAD

**Issue by MacReady82** [nmrih/source-game#1197]
NMRIH crashes completely randomly (nothing special happening on screen, sometimes after a 1 hour session and sometimes after 20 minute session) I leave here steam dumps crashes
[nmrih dmp files.zip](https://github.com/nmrih/source-game/files/6832700/nmrih.dmp.files.zip)

**Comment by felis-catus** [comment]
Unfortunately these dumps point to engine modules, which we can't debug. Closing.
