### ISSUE TITLE
[public-1.11.4] Multiple props on moving brushes significantly degrade performance

### ISSUE THREAD

**Issue by scanner34650** [nmrih/source-game#1198]
This bug was found by me and my friends recently. While playing, we accidentally activated this bug and during our experiments we found out how it works. Using a bug, we asked for a frame rate of up to 1 frame in 2 seconds.
instructions for use:

1) we are looking for a special thing( like a train on the nms_midwest map or a box with supplies for any survivalist).
2) we throw cartridges, weapons, objects on the train( example ) and stand there.
3) we are waiting for the reaction of others, how much it lags.

By fixing this bug or the servers are fucked up. Code red is not an exercise.

P.S.  I like No more room in hell )

**Comment by TheUnstableNutcase** [comment]
You should probably re-word the title to make it more descriptive and specific, your title for a bug report shouldn't be this vague

**Comment by felis-catus** [comment]
Fixed in src-r6314.
