### ISSUE TITLE
[public-1.11.4] nmo_fema ; Trees behind the railing are displayed in the foreground.

### ISSUE THREAD

**Issue by Dayonn-dayonn** [nmrih/source-game#1206]
This is just a visual issue and does not need to be fixed. However, since it doesn't seem to have been reported before, and since it always bothers me whenever I pass by here, I decided to report it.

![fema_tree](https://user-images.githubusercontent.com/37202119/130373333-628a2257-eaaa-4a29-aa3f-1981f3faa01d.jpg)

Also, upon closer inspection, it appears to be translucent. I used to think it was made of iron. I was wrong, it seems to be made of black glass.

![fema_pipe_edit](https://user-images.githubusercontent.com/37202119/130373422-c2466ba1-b9f8-48ce-87eb-ef6abd7b3bd9.jpg)

**Comment by AtheistNMRiH** [comment]
$translucent shader problem in standart hl2 texture, won't fix 😛
