### ISSUE TITLE
[public-1.11.5] Choppers sometimes drop supply crates out of bounds

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1211]
If you fire a flare gun with an angle the projectile can end up signaling the chopper to an unreachable position.

![hl2_tXTPr2ayX0](https://user-images.githubusercontent.com/11559683/133449808-1918a619-a922-4ca1-a66b-366d1cfe415b.png)
![hl2_cZTMehRXyU](https://user-images.githubusercontent.com/11559683/133449839-147a4f08-4016-44bc-a900-62b96d8194e1.png)

Suggestion: Use the player's X and Y for the drop point instead of the flare's

**Comment by felis-catus** [comment]
Fixed in src-r5343.
