### ISSUE TITLE
[dev-1.12.0] sv_allow_custom_balance crash/issue

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1212]
- Toggling `sv_allow_custom_balance` while no map is active crashes your game
- Toggling `sv_allow_custom_balance` makes players unable to attack and viewmodels flicker, console spams:
```
Bad pstudiohdr in GetSequenceLinearMotion()!
Bad pstudiohdr in GetSequenceLinearMotion()!
Bad pstudiohdr in GetSequenceLinearMotion()!
```

**Comment by felis-catus** [comment]
Fixed in src-r5333.
