### ISSUE TITLE
[dev-1.12.0] National Guard zombies have 100% item drop rate

### ISSUE THREAD

**Issue by Acrilyk** [nmrih/source-game#1216]
Title. NG zombies seem to be dropping *something* 100% of the time (whether it be bandages, 9mm, 5.56, grenades, etc)

**Comment by dysphie** [comment]
Can't replicate spawning and squirting multiple national guards

**Comment by felis-catus** [comment]
Unable to repro with forced spawns, and nothing in code indicates they would spawn w/ 100% chance at any point. Closing
