### ISSUE TITLE
[dev-r9235] Boardwalk Update Issues

### ISSUE THREAD

**Issue by Holycrapjimhox** [nmrih/source-game#1225]
• First run I did I had almost no shambler and runner/kid spawns on the map after the “Survive” objective (inside the shop with the radio). It looked to me like the excessive zombie spawns that are triggered with that objective never seemed to despawn when I moved far away, so the max zombie cap was reached and no new spawns were triggered in other areas. However, this didn’t happen on the other two rounds I played, so idk if this is noteworthy or not. Maybe adding some sort of failsafe to forcefully despawn those zombies could help prevent this.

• Regarding the new machine gun route: first time I did it, I didn’t know what was going to happen and the insane runner spawns mauled me instantly. So, in terms of first impressions that’s not good, but that’s a minor gripe since most NMRiH maps are unforgiving and unfair when you first play them. This is just to note that the machine gun section is almost a guaranteed instakill for most players that don’t know what will happen.

After that, I did it again with that knowledge and I still couldn’t use the machine gun against the runners. If you are playing solo, all the runners target you and they move fast enough to get behind the machine gun to grab you before you can even pop a few shots. You need another teammate to aggro them and lure them away so you can kill them, so if you are playing solo you either have to fight more than a dozen runners at the same time or possibly slip by them by going through the door on the back of the clothes shop (which seemed like it got permanently locked once I went through). That door also should be locked permanently once every player has gone through it obviously, just in case it doesn’t happen.

I’m noting this so to check if this is the intended experience. If it isn’t, I could give some advice on how to improve it.

• Next I only have a few small issues:
- These boards have collisions that can get you stuck and killed, they should be removed:
![nmo_boardwalk0000](https://user-images.githubusercontent.com/35630284/137036947-5f3bd02d-d28e-4d34-9c1b-1788bfd1fc8c.jpg)

- I noticed a few broken reflective surfaces like these:
![nmo_boardwalk0001](https://user-images.githubusercontent.com/35630284/137036963-a1f5176f-fc69-4ee0-903c-286164273905.jpg)

- I also noticed that you can see through the fog at certain angles and see the geometry popping in and out of view:
![nmo_boardwalk0003](https://user-images.githubusercontent.com/35630284/137036981-e7022cbf-bd1d-4154-a2b9-7c431dbccaca.jpg)

- The machine gun only seems to work consistently if you tap fire. If you hold fire then it stops dealing damage for some reason

- The machine gun lacks a muzzle flash, but that's probably unavoidable due to it being a map entity right?

(I'll add more issues in the comments as I find them)

**Comment by AtheistNMRiH** [comment]
don't forget that nmrih is multiplayer oriented game and map features shouldn't indulge solo players, but I agree that it is hard to reach machinegun (even if you know what to do) with teammates

**Comment by Holycrapjimhox** [comment]
Precisely. It's all up to the mapper. I'm just noting how solo play would work in case they want that to be intentional or not.

**Comment by Holycrapjimhox** [comment]
Closing due to imminent 1.12 public release. Several of these issues have been fixed. I will open a new thread after the update if necessary.
