### ISSUE TITLE
[public-1.11.5] Setting Modeloverride on specific models breaks zombie collision.

### ISSUE THREAD

**Issue by zeThijs** [nmrih/source-game#1226]
Using sourcemod 1.10:
using DispatchKeyValue() to set a modeloverride keyvalue causes zombie collision problem.
It makes the zombie non solid, collision is gone.
The models in questions are: models/nmr_zombie/tammy.mdl, models/nmr_zombie/lisa.mdl
I found the modeloverride works fine using hammer with these models.

For now I will just skip the plugin code for these models.

**Comment by felis-catus** [comment]
Fixed in dev-r9330.
