### ISSUE TITLE
[public-1.11.5] nmo-suzhou ; Stuck in the gun store

### ISSUE THREAD

**Issue by Dayonn-dayonn** [nmrih/source-game#1227]
If you open the door where the bullets are stored with your body in close proximity to the corner of the room, the door will bite into your body and get stuck.

![20211023012018_1](https://user-images.githubusercontent.com/37202119/138491594-aba89e4c-4da1-4fad-b404-aaf48b36f569.jpg)
.

**Comment by AtheistNMRiH** [comment]
fixed in r9324
