### ISSUE TITLE
[dev-r9286] Huge fps drop on nms_midwest

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#1236]
in public version I got like 60-90 fps in most laggy areas
![image](https://user-images.githubusercontent.com/11333747/139373932-0f5f5de4-12bd-444e-aeb1-41e7f6724464.png)

and here what I got in dev build - 25-35 fps
![image](https://user-images.githubusercontent.com/11333747/139373993-6f71d816-678a-4645-9e30-88d59cfbed8e.png)

No changes were made to map, so I assume some changes in materials could cause this

**Comment by felis-catus** [comment]
Changes were reverted, closing.
