### ISSUE TITLE
[public-1.12] server crashes when some entity is attacked / some map loaded

### ISSUE THREAD

**Issue by Dayonn-dayonn** [nmrih/source-game#1238]
In nmo-chinatown, Attacking the board in the first wire mesh door will cause the server to crash.
In nmo-fema, Attacking the first door will cause the server to crash.

I do not test other entity, but I think that there will be other occurrences.

**Comment by dysphie** [comment]
Please test without server-side plugins

**Comment by Dayonn-dayonn** [comment]
oh!  I was wrong. I will update sourcemod and metamod. very sorry......

**Comment by felis-catus** [comment]
Plugin issue, closing.
