### ISSUE TITLE
Broken Animations and Missing Sounds

### ISSUE THREAD

**Issue by Cowboy8** [nmrih/source-game#1247]
I downloaded a fresh version of the game and no matter the map I load into, no matter the weapon, it is buggy.

Animations do not play but you can hear the sound for melee weapons

For guns there is no sound and no animation, but it still shoots.

Here is a video showing the issue.

https://youtu.be/YfnbfB7YDFg

**Comment by dysphie** [comment]
Is your "Max Players" set to 1 in the server creation dialog? Ensure it's at least 2 else client prediction is disabled
