### ISSUE TITLE
[public-1.12.0] Max. players setting on Create Game dialog is unrestricted

### ISSUE THREAD

**Issue by felis-catus** [nmrih/source-game#1248]
Players are able to set max. players to 1, resulting in engine switching to "single player" mode, disabling client prediction etc. NMRiH is designed for "multiplayer" only, and this causes several issues incl. animations not working.

The dialog is configured correctly (2 is set as min., and 8 as max.), but it won't clamp and save the value.

**Comment by felis-catus** [comment]
#1247 related.

**Comment by Bubka3** [comment]
On steam build this is being shipped as settings_default.txt while settings on source always use a .scr extension. I believe in the past we shipped it as settings.scr to get the changes to show up.

**Comment by felis-catus** [comment]
> 
> 
> On steam build this is being shipped as settings_default.txt while settings on source always use a .scr extension. I believe in the past we shipped it as settings.scr to get the changes to show up.

We replaced the VGUI dialog with our implementation, it doesn't use .scr extension. See #1048.

**Comment by felis-catus** [comment]
Fixed in src-r5679.
