### ISSUE TITLE
[public-1.12.0] nms_drugstore issues/adjustments

### ISSUE THREAD

**Issue by Acrilyk** [nmrih/source-game#1250]
Issues or possible changes:

Zombies can get stuck here.
![image](https://user-images.githubusercontent.com/62704665/141539486-88b55375-3343-4fc3-8578-7fef3977c1f5.png)

Wrong skin.
![image](https://user-images.githubusercontent.com/62704665/141539663-ea9ffa8c-ef7a-4411-a610-e453c9b2c824.png)

Bad specular (cubemaps?)
![image](https://user-images.githubusercontent.com/62704665/141539905-ac7d36fc-11de-41ae-8467-4471a0ae6c52.png)

Fix clip (players can attract zeds from the edge)
![image](https://user-images.githubusercontent.com/62704665/141540342-f812bf93-9f1c-4185-9536-bd5b68f742e1.png)

Area could use some more obstructions, zombies can be walked in circles
![image](https://user-images.githubusercontent.com/62704665/141540488-4ac8f176-5104-4495-ae96-677de99a0de1.png)

Zombies sometimes get stuck here
![image](https://user-images.githubusercontent.com/62704665/141540542-6cac6adb-6c6a-46af-8db0-75e09cfe9e65.png)

Forgot to fix this edge(lol)
![image](https://user-images.githubusercontent.com/62704665/141540728-177146b6-3cf8-497a-8e3e-cc83da58571b.png)

Zone C burning can be seen through this wall
![image](https://user-images.githubusercontent.com/62704665/141540982-02a60515-14f1-46ae-ac7a-2e5573e9654c.png)

Some props disappeared from this barricade somehow(had some police barricades)
![image](https://user-images.githubusercontent.com/62704665/141541081-db02ff00-8c71-4cda-b42e-01f10a100420.png)

Kinda hard to get the ladder through here
![image](https://user-images.githubusercontent.com/62704665/141541128-bcffafe0-4c7d-47ae-b0ad-41ff3d6e8a0d.png)

Rebalancing required, too many weapons for amount of zombies.
- Could extend max waves and/or number of zombies per wave

Secondary purpose for zone B (?)

Rework evac.
- move helicopter crash cutscene AFTER players are extracted, remove the fire spread mechanic, current evac currently causes some confusion
- manually spawn runners (?)

Remove forced brainstem (really messes up higher ping gameplay)

Slightly more detailing to the drugstore interior. (new models)

Could make the weldable crates glow green.

Add some more melons. Yum

**Comment by AtheistNMRiH** [comment]
remove parallax cubemap brush in mall

**Comment by Acrilyk** [comment]
Fixed in latest
