### ISSUE TITLE
[public-1.12.1] Damage filters are ignored

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1255]
From svn 9170 onwards, entities will take damage from all (?) sources despite being restricted to a specific damage type via `filter_damage_type` or `SetDamageFilter`.

In this example I restricted the zed's damage to DMG_FALL, works fine in svn 9169, takes damage from firearms in newer builds

```cpp
entity
{
	"id" "4908917"
	"targetname" "damagetype_invincible"
	"Negated" "0"
	"damagetype" "32"
	"classname" "filter_damage_type"
}

entity
{
	"id" "4908990"
	"origin" "37 2757 -979.828"
	"damagefilter" "damagetype_invincible"
	"classname" "npc_nmrih_runnerzombie"
}
```

test bsp (rename to .vmf)
[filtertest.txt](https://github.com/nmrih/source-game/files/7587587/filtertest.txt)

This was originally reported by Merzarime

**Comment by felis-catus** [comment]
Fixed in src-r5709.
