### ISSUE TITLE
[public-1.12.1] Hitbox indexes have shifted

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1257]
As of the neck fix introduced in 1.10, every hitbox index has shifted.
Hitbox 0 is now hitbox 16, every other index is decreased by one, 1 is 0, 16 is 15, etc.
This causes a few issues:

- National guards no longer scale headshot damage by armor (CNMRiH_BaseZombie::TraceAttack)
- Zombies are not always getting their heads split when they should (CNMRiH_BaseZombie::CheckHeadSplit)
- Possibly more, need to revise cases where code checks for specific hitbox indexes

**Comment by felis-catus** [comment]
Code patch is necessary for backwards compatibility with mods.

**Comment by felis-catus** [comment]
Temporary code patch added in src-r5718, final fix pending.

**Comment by felis-catus** [comment]
Lowering priority, issue can be deferred to later update.

**Comment by felis-catus** [comment]
Patched in code for 1.12.2, models will be fixed in a later update, closing as resolved.
