### ISSUE TITLE
(Suggestion) Pls Add Ammo Weight Cvar.

### ISSUE THREAD

**Issue by Flammable4444** [nmrih/source-game#1258]
Since 2018 NMRiH was constantly updated, often useful cvars were added. This time i suggest to add cvar to change WEIGHT_PER_AMMO. Something like inv_ammoweight 5, so ppl can define how much ammo weight. I personally want to ammo weight nothing, but i did not found good solution atm. What i did is either ugly or laggy, that's why i'm suggesting for cvar, officialy.

**Comment by felis-catus** [comment]
Implemented in src-5753.
