### ISSUE TITLE
Zombie Floating

### ISSUE THREAD

**Issue by darkst3alth** [nmrih/source-game#126]
Seems that there were at least two cases of this happening. I have imaged one case. The zombie was able to interact with me and bite me as if it was on the ground, but seemed to me as if it was a few inches off the ground.

![](http://img829.imageshack.us/img829/7603/2013052500001.jpg)

**Comment by AtheistNMRiH** [comment]
doesn't look like a map problem

**Comment by Bubka3** [comment]
Will leave open for a couple of days, maybe he still checks this and has more info.

**Comment by Bubka3** [comment]
**Inactivity Closure**
This issue has been closed for inactivity. If you are still experiencing this issue please reply to this issue to re-open it. If you have any additional issues please open a new issue.

For technical support, you may also post in the troubleshooting forums:
http://steamcommunity.com/app/224260/discussions/2/
