### ISSUE TITLE
[public-1.12.1] CUtlRBTree Overflow

### ISSUE THREAD

**Issue by MAGISTER-PD2OR** [nmrih/source-game#1260]
I have issue when client crash with error: CUtlRBTree Overflow.

It happen with current maps nmo_insomnia_v3 or nmo_vertigo_v13.
When players vote for maps and client loading, then vote again and select this 2, client just crash but not server.
Issue happen in random time, i not shure how got 100% error.

**Comment by felis-catus** [comment]
Ambiguous issue with no repro steps, closing.

**Comment by dysphie** [comment]
This happens when you overflow the string table (`dumpgamestringtable`). It can happen when the map uses "Preserve entity names" on point_templates or there's simply too many entities.
