### ISSUE TITLE
[dev] Butcher's arm isn't long enough with crowbar

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#1261]
![nmo_shit0004](https://user-images.githubusercontent.com/11333747/144702597-bbca30d6-8ba0-4453-801f-d17e33586e10.jpg)
you can see a little gap at the right bottom corner

other hands seem fine (Roje's for example)
![nmo_shit0000](https://user-images.githubusercontent.com/11333747/144702606-bb937a86-cb62-4a20-846f-2e17277bff63.jpg)

**Comment by felis-catus** [comment]
According to Mage, Butcher's arms were replaced with default hand model, and this issue should be marked as resolved.
