### ISSUE TITLE
[dev] No arms with weapons

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#1262]
I couldn't 100% reproduce it, it happened randomly to me, I set Character select to random and sometimes it happens, got it with Roje, Hunter, Badass, Molotov (others could be affected too), sometimes you can see arms (like on the last screenshot, iirc it was Hunter)
No info related to the hands in console
![nmo_shit0006](https://user-images.githubusercontent.com/11333747/144702629-95e480b9-e527-4dda-960d-1ee2adb8f5d8.jpg)
![nmo_shit0007](https://user-images.githubusercontent.com/11333747/144702630-035bef1c-6249-41d1-8dbe-b03758708c3d.jpg)
![nmo_shit0002](https://user-images.githubusercontent.com/11333747/144702671-1726d6e0-610e-4f30-a62c-3addb58857ea.jpg)

**Comment by dysphie** [comment]
video of issue https://streamable.com/rh2wu6

**Comment by felis-catus** [comment]
Can also be a code issue, updating labels.

**Comment by AtheistNMRiH** [comment]
![nms_silence0000](https://user-images.githubusercontent.com/11333747/144748956-347ecfb6-bc71-4df6-8748-4671a9fbb91a.jpg)
it seems it can affect all weapons

**Comment by felis-catus** [comment]
Fixed in src-r5927.
