### ISSUE TITLE
[Feature Request] Random voice for character

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#1263]
it would be nice to have option "Random" for voices just like for player model

**Comment by felis-catus** [comment]
Added in src-r6376.

**Comment by AtheistNMRiH** [comment]
it doesn't seem to work, game picks previously chosen voice (for example I had Cleric, then chose Random -> there will be always Cleric)

**Comment by felis-catus** [comment]
> it doesn't seem to work, game picks previously chosen voice (for example I had Cleric, then chose Random -> there will be always Cleric)

Fixed in src-r6385.
