### ISSUE TITLE
[public-1.12.1] player_spawn event not firing 

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1266]
`player_spawn` is not firing for newly connected players

1. Start game
2. Have another player join while the spawn grace period is still active
3. They'll spawn in, but no `player_spawn` event will fire. Future respawns do trigger the event

I'm pretty sure this is a regression as I have plugins that used to rely on this event and don't work properly anymore

**Comment by felis-catus** [comment]
Fixed in src-r5756.
