### ISSUE TITLE
[public-1.12.1] npc_zombie_template_maker tries to create invalid entity

### ISSUE THREAD

**Issue by Acrilyk** [nmrih/source-game#1269]
When using the npc_zombie_template_maker with the "walker" setting, we get this error in the console:

Attempted to create unknown entity type npc_nmrih_normalzombie!

**Comment by Acrilyk** [comment]
seems to also happen with other settings, like "Runner" and "Don't care"

**Comment by felis-catus** [comment]
Fixed in src-r5752.
