### ISSUE TITLE
[public-1.12.1] No such sound Zombie.Pain

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#1271]
`CSoundEmitterSystemBase: :GetParameterForSound: No such sound Zombie.Pain`
you can get that error sometimes when hitting zombie, all zombies have Zombie.Pain in their files but there is no such sound in nmr_sounds_zombie.txt file, there are only specific pain sounds

I wonder if it was done to prevent sound spam when multiple hit zombies

![image](https://user-images.githubusercontent.com/11333747/146563112-88a7f4d9-c4ac-4572-8021-a96cfc9b358d.png)

![image](https://user-images.githubusercontent.com/11333747/146563446-e0667536-4071-49c5-8670-ef6cb3eec956.png)

**Comment by felis-catus** [comment]
Resolved in src-r6228. Zombie male pain sounds are currently missing, so the game won't attempt to play those.
