### ISSUE TITLE
Incorrect (wrong) names of sound files and their duplicates.

### ISSUE THREAD

**Issue by abizeyshn** [nmrih/source-game#1274]
Found incorrect names of music files in the game folder, examples:
1. `campblood_regge_radio` (reggAe, not regge)
2. `toxeth_store_var02`, `toxeth_store_var03` and `toxeth_store_var04` (Sort of like the map is called "toxTeth" - `nmo_toxteth`)
3. `make_your_move` from _sound\dms\tension2_ is this is a crookedly cropped version at the end of another file called `runandgunevac2` from _sound\dms\evac_. (Don't see a special need for this version and the original will be enough)

Can be change the names of the first two files and remove duplicate file from the third paragraph?
![same file](https://user-images.githubusercontent.com/80100339/147537916-5c4a5980-443e-4ca2-8361-868d8c740bcd.png)

**Comment by AtheistNMRiH** [comment]
no way to change file names because it will break all maps which use them, same with duplicate file (some maps can use both files)

**Comment by felis-catus** [comment]
> no way to change file names because it will break all maps which use them, same with duplicate file (some maps can use both files)

Echoed, we're unable to resolve this issue without breaking existing maps. Closing.
