### ISSUE TITLE
[public-1.12.1] Several game events don't work

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#1279]
Reported by Epacker2, here is his message:

`net_showevents 2`

`achievement_debug 1`

```
CAchievementMgr::Steam_OnUserStatsStored: result = 1
Server event "zombie_head_split", Tick 25259:
- "player_id" = "3"
- Server event "npc_killed", Tick 25259:
- "entidx" = "544"
- "killeridx" = "3"
- "isturned" = "0"
- "weaponid" = "6"
- "npctype" = "1"
- Server event "entity_killed", Tick 25259:
- "entindex_killed" = "544"
- "entindex_attacker" = "3"
- "entindex_inflictor" = "421"
- "damagebits" = "528386"
- Achievement count increased for KILLS_870_500: 375/500
- Server event "achievement_event", Tick 25259:
- "achievement_name" = "KILLS_870_500"
- "cur_val" = "375"
- "max_val" = "500"
- "userid" = "9"
- Achievement count increased for KILLS_ANY: 5529/1619090
- Server event "weapon_fired", Tick 25259:
- "player_id" = "3"
- "weapon_id" = "421"
...
CAchievementMgr::Steam_OnUserStatsStored: result = 1
Server event "npc_killed", Tick 36456:
- "entidx" = "446"
- "killeridx" = "3"
- "isturned" = "0"
- "weaponid" = "6"
- "npctype" = "1"
- Server event "entity_killed", Tick 36456
- :- "entindex_killed" = "446"
- "entindex_attacker" = "3"
- "entindex_inflictor" = "421
- "- "damagebits" = "528386"
- Achievement count increased for KILLS_870_500: 500/500
- Achievement awarded: KILLS_870_500
- Achievement count increased for KILLS_ANY: 5654/1619090
- Server event "weapon_fired", Tick 36456:
- "player_id" = "3"
- "weapon_id" = "421"
- CAchievementMgr::Steam_OnUserStatsStored: result = 1
```

Result:
`achievement_event` - works, server can see it
`achievement_earned` - doesn't work, server can't see it

UPD: more events which don't work (requires more testing)
teamplay_round_start
spec_target_updated
achievement_earned
object_destroyed
game_round_restart
objective_begin
WalkieSound
ammo_radial_open
ammo_radial_closed
wave_complete
objective_text_changed
zombie_spawn_enabled
zombie_spawn_updated
safe_zone_damage
tokens_changed
cure
challenge_freeze
demo_bookmark

**Comment by felis-catus** [comment]
Events that are client-side, and unavailable on server:
- cure
- demo_bookmark
- safe_zone_damage
- spec_target_updated

Events that are deprecated / unused:
- achievement_earned
- ammo_radial_closed
- ammo_radial_open
- challenge_freeze
- game_round_restart
- objective_begin
- objective_text_changed
- object_destroyed
- teamplay_round_start
- tokens_changed
- WalkieSound
- wave_complete
- zombie_spawn_enabled
- zombie_spawn_updated

**Comment by felis-catus** [comment]
ModEvents.res cleaned up in dev-r9385.
achievement_earned implemented in src-r5797.
wave_complete implemented in src-r5795.

If you need more events reimplemented, please open a feature request. Closing.
