### ISSUE TITLE
[public-1.12.1] BecomeRunner don't let shambler become real runner

### ISSUE THREAD

**Issue by clague** [nmrih/source-game#1281]
When you let a shambler become runner by call the BecomeRunner method, the runner's damage is still ruled by sv_zombie_dmg_onehand/sv_zombie_dmg_twohand, which defaults to 15. I think it should be sv_runner_dmg_xxxx.

Reproduce: Create a shambler, use plugin or anything to call BecomeRunner method, than hit by the zombie.

**Comment by clague** [comment]
I found other related questions, I think i should say here.
The sound which the "converted runner" use is the shambler's, and the death notice show "zombie" but not "runner zombie".

**Comment by felis-catus** [comment]
> I found other related problems, I think i should say here. The sound which the "converted runner" use is the shambler's, and the death notice show "zombie" but not "runner zombie".

These issues have also been fixed.
