### ISSUE TITLE
[Feature Request] Support for multi-option votes

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1282]
The vote controller supports up to 5 choices and players can already send `vote option3`, `vote option4` and `vote option5`, but the UI won't display more than 2 choices. Being able to do this would allow server plugins (such as mapchooser and rockthevote) to work with the native UI instead of using radio menus (which eat inputs)

**Comment by dysphie** [comment]
Changing the height of VoteActive in VoteHud.res already helps a bunch:

![image](https://user-images.githubusercontent.com/11559683/151729224-31827e13-768e-4a58-9be6-5d2ea8f6173d.png)

**Comment by felis-catus** [comment]
Implemented in src-r5910.

**Comment by dysphie** [comment]
It kind of works, all 5 options are now displayed, but it still shows ✔️/❌ instead of the vote count for each option

**Comment by felis-catus** [comment]
Issues resolved, closing.
