### ISSUE TITLE
[public-1.12.2] Frequent crashes on Linux

### ISSUE THREAD

**Issue by ProportionalRepresentation** [nmrih/source-game#1286]
Steam API: v020, package versions: 1642451672
Game randomly exits, without error message, after joining a server (can play for an hour or a few seconds).

> Computer Information:
>     Manufacturer:  MSI
>     Model:  Z77A-GD65 GAMING (MS-7751)
>     Form Factor: Desktop
>     No Touch Input Detected
> 
> Processor Information:
>     CPU Vendor:  GenuineIntel
>     CPU Brand:         Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
>     CPU Family:  0x6
>     CPU Model:  0x3a
>     CPU Stepping:  0x9
>     CPU Type:  0x0
>     Speed:  3400 Mhz
>     4 logical processors
>     4 physical processors
>     HyperThreading:  Unsupported
>     FCMOV:  Supported
>     SSE2:  Supported
>     SSE3:  Supported
>     SSSE3:  Supported
>     SSE4a:  Unsupported
>     SSE41:  Supported
>     SSE42:  Supported
>     AES:  Supported
>     AVX:  Supported
>     AVX2:  Unsupported
>     AVX512F:  Unsupported
>     AVX512PF:  Unsupported
>     AVX512ER:  Unsupported
>     AVX512CD:  Unsupported
>     AVX512VNNI:  Unsupported
>     SHA:  Unsupported
>     CMPXCHG16B:  Supported
>     LAHF/SAHF:  Supported
>     PrefetchW:  Unsupported
> 
> Operating System Version:
>     Linux Mint 20 (64 bit)
>     Kernel Name:  Linux
>     Kernel Version:  5.4.0-99-generic
>     X Server Vendor:  The X.Org Foundation
>     X Server Release:  12013000
>     X Window Manager:  Mutter (Muffin)
>     Steam Runtime Version:  steam-runtime_0.20211207.0
> 
> Video Card:
>     Driver:  NVIDIA Corporation NVIDIA GeForce GTX 660/PCIe/SSE2
>     Driver Version:  4.6.0 NVIDIA 470.103.01
>     OpenGL Version: 4.6
>     Desktop Color Depth: 24 bits per pixel
>     Monitor Refresh Rate: 59 Hz
>     VendorID:  0x10de
>     DeviceID:  0x11c0
>     Revision Not Detected
>     Number of Monitors:  2
>     Number of Logical Video Cards:  1
>     Primary Display Resolution:  1920 x 1200
>     Desktop Resolution: 3520 x 1200
>     Primary Display Size: 20.39" x 12.76" (24.02" diag)
>                                             51.8cm x 32.4cm (61.0cm diag)
>     Primary Bus: PCI Express 16x
>     Primary VRAM: 2048 MB
>     Supported MSAA Modes:  2x 4x 8x 16x 
> 
> Sound card:
>     Audio device: Nvidia GPU 41 HDMI/DP
> 
> Memory:
>     RAM:  7903 MB
> 
> VR Hardware:
>     VR Headset: None detected
> 
> Miscellaneous:
>     UI Language:  English
>     LANG:  en_GB.UTF-8
>     Total Hard Disk Space Available:  238836 MB
>     Largest Free Hard Disk Block:  108388 MB
> 
> Storage:
>     Number of SSDs: 0
>     Number of HDDs: 0

[nmrih crashes.zip](https://github.com/nmrih/source-game/files/8063052/nmrih.crashes.zip)

**Comment by ProportionalRepresentation** [comment]
Think it happens more often at end of level, e.g. while climbing the rope on helicopter(but before extracted).
[end game crashes.zip](https://github.com/nmrih/source-game/files/8402707/end.game.crashes.zip)

**Comment by felis-catus** [comment]
> Think it happens more often at end of level, e.g. while climbing the rope on helicopter. [end game crashes.zip](https://github.com/nmrih/source-game/files/8402707/end.game.crashes.zip)

Common Linux crash relating to achievements was fixed in src-r6172.
Leaving this open as parent issue because there are more on the line.

**Comment by ProportionalRepresentation** [comment]
Not sure if helps, but last update changed the bug slightly. I used to be able to complete the map on fema by standing under the helicopter as it lands, but just played, and the game crashed as soon as helicopter landing cutscene ended.
