### ISSUE TITLE
[public-1.12.2] Zombie attack hurts players behind it

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1288]
Zombies can damage players standing behind them because the swept attack hull clips thru the zombie's back

Here's a video that shows the difference between vanilla and a custom implementation that offsets the hull's start position forward 

https://user-images.githubusercontent.com/11559683/154812629-1f1f2b8c-4502-45f0-acaf-2e6b69db1c45.mp4

Relevant method is `CheckTraceHullAttack` in `CNMRiH_BaseZombie::ClawAttack`

**Comment by felis-catus** [comment]
Fixed in src-r7803.
