### ISSUE TITLE
[public-1.12.2] "Greenlit" background has incorrect aspect ratio

### ISSUE THREAD

**Issue by Holycrapjimhox** [nmrih/source-game#1289]
The current "Greenlit" background fills out the entire main menu, changing the aspect ratio compared to the original image

Current background:
![greenlit](https://user-images.githubusercontent.com/35630284/154818084-0c680413-0619-41f2-aedc-78bd6ef002f8.png)

Original artwork:
![NMRiH Greenlight Background](https://user-images.githubusercontent.com/35630284/154818092-98f91075-07ad-49f5-8fe0-55a107c05672.jpg)

If I recall correctly, before the 1.10 update, the background maintained the aspect ratio of the original image by cropping it to fit the screen appropriately.

**Comment by felis-catus** [comment]
Fixed in dev-r9445.
