### ISSUE TITLE
(nms_ransack) You can get stuck on the gun shop shutter

### ISSUE THREAD

**Issue by Smil3yRiley** [nmrih/source-game#129]
If you stand too close to the shutter while unwelding it, you will get stuck (the shutter will pull you up to the ceiling)

![2013-05-25_00002](https://f.cloud.github.com/assets/3606650/564577/a6ce81c8-c57d-11e2-905f-3759f7f7b480.jpg)

![2013-05-25_00003](https://f.cloud.github.com/assets/3606650/564571/70acf71e-c57d-11e2-845e-10065cf03318.jpg)

---

Steps to Reproduce
1) Stand really close to the shutter and unweld with a blow torch

**Comment by AtheistNMRiH** [comment]
looks like it was fixed ages ago, need to be closed
