### ISSUE TITLE
[public-1.12.2] Performance issues caused by gunshot/chainsaw debris

### ISSUE THREAD

**Issue by Acrilyk** [nmrih/source-game#1291]
The debris from spamming gunshots into a wall can cause some pretty big performance drops.

Broadwalk - before
![image](https://user-images.githubusercontent.com/62704665/155032276-44839534-967b-4986-b632-d8a70f35f780.png)

Broadwalk - after
![image](https://user-images.githubusercontent.com/62704665/155032307-8bf91bdc-f0d0-46ab-b5ac-93b5f3df22b4.png)
![image](https://user-images.githubusercontent.com/62704665/155032345-45144132-2ff6-4bb3-af60-5f8b96f07bab.png)

Perhaps reducing the lifetime of particles can solve this problem.

**Comment by felis-catus** [comment]
Resolved in src commits r6445-r6446, also added ability to set impact effect quality in adv. options.
