### ISSUE TITLE
[dev-r9459] exp_grenade shoving and holstering sounds missing

### ISSUE THREAD

**Issue by Holycrapjimhox** [nmrih/source-game#1293]
Steps to reproduce:

1) Equip a grenade
2) Press H to holster or V to shove while holding it
3) You'll notice that both sounds are missing.

NOTE: The drawing sound is present though (switching from any item or me_fists to the grenade)

**Comment by dysphie** [comment]
throw sfx is also missing, `weapons/slam/throw.wav` could be used

**Comment by felis-catus** [comment]
Fixed in dev-r10049.
