### ISSUE TITLE
[public-1.12.2] Players unable to cast vote after missing previous vote result

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1295]
If a player fails to render a vote result screen (VotePass/VoteFail) they'll be unable to vote in the subsequent one.
This is unrelated to the recent multi-vote addition.

Steps to reproduce:
1. Disable vote cooldowns for convenience (sv_vote_failure_timer and sv_vote_creation_timer)
2. Have a player start a vote
3. While the vote is ongoing, have a player (can be the same one) open an interface that prevents the voting panel from showing (e.g. press ESC key)
4. Wait for the vote to end and the result be shown to the rest. Now the player can close the interface
5. Start a new vote, the affected player will either:
	a. Not see the new vote (a result panel will quickly flicker)
	b. See the new vote, but be unable to pick an option via function keys

**Comment by felis-catus** [comment]
Fixed in src-r6071.
