### ISSUE TITLE
[Feature Request] Customizable Inventory_Box interface

### ISSUE THREAD

**Issue by Acrilyk** [nmrih/source-game#1296]
It would be nice to have some options regarding inventory boxes, like the ability to change the background picture, the ability to have items somewhat disorganized (no categorization) and maybe the option to adjust the size of the items, how many items there are, where they're placed on the background etc.

**Comment by Acrilyk** [comment]
More requests for the inventory box: some outputs OnOpen(when a player accesses the inventory box) OnClose(when a player leaves or grabs an item and gets forced out). 

Another cool thing would be an option to let only one player loot the inventory box at a time, and an option NOT to kick the player(s) out of the inventory box after they loot an item.

**Comment by felis-catus** [comment]
Added uncategorized inventory boxes and custom backgrounds in 1.13.5.
