### ISSUE TITLE
[Feature Request] Custom inventory items

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1297]
This is probably a tall task but here goes nothing:
A new physics item that's able to be picked up and shows up in the player's inventory with a custom icon.

Sample structure:

```
"classname" "inventory_item"
"model" "models/mykey"
"vgui_icon" "materias/mykey"
"weight" "80"
```

These could be stored in their own separate array similar to m_hMyWeapons and be included in the radial menu and carried weight calculations.

With outputs like `OnPickedUp`, `OnDropped`, etc. it could open up a whole new type of objective where you must physically carry an item through a level without holding it in front of you at all times, which I always found janky.

**Comment by felis-catus** [comment]
Implemented in src-r7304 as `item_custom`.
