### ISSUE TITLE
[public-1.12.2] VScript: TraceHullComplex() crashes the game

### ISSUE THREAD

**Issue by RaymondChen2018** [nmrih/source-game#1298]
"""
local trace = TraceHullComplex(actorEyePosition, enemyEyePosition, traceboxMin, traceboxMax, self, MASK_SHOT,COLLISION_GROUP_NONE);
local hasLOS = trace.Entity() != null && trace.Entity() == enemy;
trace.Destroy();
"""
I have this snippet run in a think function, there is no error thrown and the function does what it's supposed to, but if you reload a map the game crashes every time.

For reference, Traceline() works properly without crash, probably it doesn't do with trace handle is my theory.

**Comment by samisalreadytaken** [comment]
This is fixed in https://github.com/mapbase-source/source-sdk-2013/pull/172/commits/700ac4ed78a20c51de8435d6ff1cda75f658208a. The PR this commit is in also includes more fixes which may be needed if nmrih has more vscript features implemented from mapbase.

**Comment by felis-catus** [comment]
> This is fixed in [mapbase-source/source-sdk-2013@700ac4e](https://github.com/mapbase-source/source-sdk-2013/commit/700ac4ed78a20c51de8435d6ff1cda75f658208a). The PR this commit is in also includes more fixes which may be needed if nmrih has more vscript features implemented from mapbase.

Thank you! We'll merge the changes from your PR. 

For information, NMRiH's fork is almost identical to Mapbase's develop branch, with certain restrictions applied to better suit multiplayer (incl. restricting 'script' commands and limiting ConVar / ConCommand interface to prevent privilege escalation).

**Comment by felis-catus** [comment]
Fixed in src-r6094.
