### ISSUE TITLE
[public-1.12.2] VScript: CFilterScript/filter_script Problems

### ISSUE THREAD

**Issue by RaymondChen2018** [nmrih/source-game#1300]
A few problems with filter_script entity. Having a zombie's damage filter set to a filter_script with the following hooks, then shoot at it once with a gun:
CFilterScript->PassesFilter & CFilterScript->PassesDamageFilter occurs twice if return true, while returning false won't double call but then I can't do things such as modifying damage;
CFilterScript->DamageMod & CFilterScript->PassesFinalDamageFilter don't work(they aren't invoked upon receiving damage).

**Comment by felis-catus** [comment]
After testing, `filter_script` itself isn't bugged, it's the source entity, e.g. `trigger_hurt` tests filter twice, first on touch, then on damage; results in double invoke.

`DamageMod` and `PassesFinalDamageFilter` are Mapbase hooks that were accidentally merged without corresponding logic, those were removed in one of the 1.13 era updates.

Closing.
