### ISSUE TITLE
NMRObjective.exe targetname read failure

### ISSUE THREAD

**Issue by zeThijs** [nmrih/source-game#1302]
The following has happened several times:
After several map iterations; objectives targetnames are not read correctly in the objective tool. 'Name' value has the correct name but 'targetname' is an empty string. This causes the objectives to fail completely. 

To solve this one need to re-place the objectives. After this they are read correctly, and have a targetname again.

**Comment by felis-catus** [comment]
After investigation this appears to be an issue with a VMF, objective boundaries must be included in their respective visgroups, and sometimes those seem to get unchecked during a save. Regrouping boundaries fixes the issue, possible Hammer bug?

In the next release, NMRObjective will warn if an objective boundary isn't a member of a visgroup:
![image](https://github.com/nmrih/source-game/assets/6873987/fad5019f-d737-44e9-aa9c-3905bea63ae5)
