### ISSUE TITLE
[Feature Request] item_reload like weapon_reload

### ISSUE THREAD

**Issue by MAGISTER-PD2OR** [nmrih/source-game#1303]
Hello, need game event for sourcemod plugins.
Not works weapon_reload for items when for example try use medkit or bandage.

Example for new feature. :)

"item_reload"
{
     "player_id"			"short"
     "item_classname"	"string"
}

**Comment by dysphie** [comment]
You can check the player's active weapon sequence to detect this. Check these examples:
https://github.com/dysphie/nmrih-team-healing/blob/main/scripting/nmrih-team-healing.sp#L903
https://github.com/dysphie/nmrih-better-tools/blob/main/scripting/nmrih-bettertools.sp#L178

**Comment by felis-catus** [comment]
Added in src-r7758 as "item_medical_start" and "item_medical_apply".
