### ISSUE TITLE
Custom maps with "sm_" prefix won't download from workshop

### ISSUE THREAD

**Issue by Lunreth** [nmrih/source-game#1309]
As the title says, i tried using workshop map **sm_artificial_grass_v7** in current version **1.12.2** of dedicated server and clients won't download this map from Steam even though the keyvalue exists in **workshop_maps.txt** ("sm_artificial_grass_v7"		"1971319798")

Players can only download this map from my FastDL webserver, i didn't test other prefix like tdm_ or mg_, i know that if i change name of map to "nmo_artificial_grass_v7" server will force their download as usual, but its not a `NMO` for sure

**Comment by felis-catus** [comment]
This appears to be an issue with server configuration, FastDL takes priority over workshop when a map is missing on client, but exists on server. This is default engine behavior and can't be overridden. To enforce workshop downloads, remove the file from your server's maps directory. Closing.

**Comment by Lunreth** [comment]
try the same with server map removed from main directory but throws "missing map" error, only NMO maps are recognized by workshop auto-download for clients

**Comment by Lunreth** [comment]
maybe it has to do something with his:

`"ServerBrowserGameTypes.txt"
{
	"gametype_1"
	{
		"prefix"	"nmo_"
		"name"		"Objective"
		"name_load"	"#NMRiH_GameType_Objective"
	}
	"gametype_2"
	{
		"prefix"	"nms_"
		"name"		"Survival"
		"name_load"	"#NMRiH_GameType_Survival"
	}
	"gametype_3"
	{
		"prefix"	"pvp_"
		"name"		"PvP"
		"name_load"	"#NMRiH_GameType_PVP"
	}
}`

**Comment by felis-catus** [comment]
> just tried the same with server map removed from main directory but throws "missing map" error, only NMO maps are recognized by workshop auto-download for clients

All file names are supported regardless of prefix, there's nothing in code that would result in this behavior.

> maybe it has to do something with his:
> 
> `"ServerBrowserGameTypes.txt" { "gametype_1" { "prefix" "nmo_" "name" "Objective" "name_load" "#NMRiH_GameType_Objective" } "gametype_2" { "prefix" "nms_" "name" "Survival" "name_load" "#NMRiH_GameType_Survival" } "gametype_3" { "prefix" "pvp_" "name" "PvP" "name_load" "#NMRiH_GameType_PVP" } }`
> 
> meaning that any other gamemode is not recognized to auto-download

This file is used by server browser's simplified view, it's unrelated to workshop functionality.

**Comment by Lunreth** [comment]
i found the issue, is not the server (deleting the file from it does nothing)

apparently if a user has an old file inside: **...\steamapps\workshop\content\224260\1971319798** (map ID) then the game does NOT recognize this and does NOT update this file (`because im not subscribed to map anymore`), i deleted that folder since it had an old _v3 version and now after validating game files i can download _v8 correctly (without being subscribed to map), i dont know if this happened to anyone else but that is the solution `if you have a non-downloading workshop map (for non subscribed items)`, so clients should always check their **non-subscribed items** list and **validate game files**, or at least subscribe again to those items if you want to update those files

**Comment by felis-catus** [comment]
> i found the issue, it's not the server (deleting the file from it does nothing)
> 
> apparently if a user has an old file inside: **...\steamapps\workshop\content\224260\1971319798** (map ID) then the game does NOT recognize this and does NOT update this file (`because im not subscribed to map anymore`), i deleted that folder since it had an old _v3 version and now after validating game files i can download _v8 correctly (without being subscribed to map), i dont know if this happened to anyone else but that is the solution `if you have a non-downloading workshop map (for non subscribed items)`, so clients should always check their **non-subscribed items** list and **validate game files**, or at least subscribe again to those items if you want to update those files

Can you open a new issue with this information for easier tracking? Could be potentially fixed on client.
