### ISSUE TITLE
[VScript] OnDeath() npc hook may cause stack and entity index errors

### ISSUE THREAD

**Issue by zeThijs** [nmrih/source-game#1313]
Having an OnDeath() hook with too many/ or too long functions called may cause this sometimes. 
These errors eventually causes NPCs to error. They become invincible andstop moving, while their last animation keeps playing

This error is passed in console:
// Error: passed index 579 out of bounds!
// Unexpected double-death-cleanup
// Unexpected double-death-cleanup

Example OnDeath() function causing this:

function OnDeath()
{
    self.StopThinkFunction();
    self.DisconnectOutput("OnDamaged", "FloodSpatter")

    local entOrigin = lastLocation;
    entOrigin.z = entOrigin.z + 20;

    DispatchParticleEffect("cpt_flood_infectionexplode", entOrigin, Vector(0,0,0), null);
    DispatchParticleEffect("flood_mortar_explode_1", entOrigin, Vector(0,0,0), null);
    
    self.EmitSound("flood.explode")

    local hurt = Entities.CreateByClassname("point_hurt");
    hurt.SetOrigin(entOrigin);
    hurt.__KeyValueFromInt("DamageRadius", 200);
    hurt.__KeyValueFromInt("DamageType", 65536);
    hurt.__KeyValueFromInt("Damage", 20);
    EntFireByHandle(hurt, "Hurt", "", 0.00, null, null);
    EntFireByHandle(hurt, "Kill", "", 0.00, null, null);
}

**Comment by felis-catus** [comment]
This was resolved in src-r7171. Unable to repro now.
