### ISSUE TITLE
[public-1.12.3] Players can skip progress on trigger_progress entities by cheating

### ISSUE THREAD

**Issue by MAGISTER-PD2OR** [nmrih/source-game#1314]
So many players use trigger_progress_use for 1 second on game servers, when i try ask about not tell to me about.
Please fix if possible, thanks.

**Comment by MAGISTER-PD2OR** [comment]
> Sorry, I don't understand, can you explain the issue in more detail?

Hello, i can't reproduce current bug but see players who for 1 second with delay on 2 or more minutes use trigger_progress_use.

**Comment by MAGISTER-PD2OR** [comment]
One of players tell me how use quick without delay.

Need move back and on trigger_progress_use do quick combo: ctrl+scroll+jump+e

I think problem with new features punch zombies when hold items, weapons, props or use triggers.

Hope can help fix problem, wil tool_welder too works how players tell me but with other trigger.

**Comment by dysphie** [comment]
By 'scroll', do you mean switching between inventory items? I cannot replicate this locally
Do you know of any specific servers where the issue is present?

**Comment by dysphie** [comment]
This is definitely tickbase manipulation. Confirmed after doing it myself. 
In other words: they're cheating with external software.

**Comment by MAGISTER-PD2OR** [comment]
I try with sourcemod plugin just block all moves and only access to E or mouse1, mouse2.
But not fixed, so yeah maybe someone use bugs.

**Comment by dysphie** [comment]
This is unrelated to button combinations so it won't help you; add me on Steam if you wish to test out a potential fix that I've made
