### ISSUE TITLE
[public-1.12.3] point_message_multiplayer does not follow the parent entity

### ISSUE THREAD

**Issue by mostten** [nmrih/source-game#1316]
The point_message_multiplayer entity does not follow the parent entity？leave the text in the starting position.

**Comment by MAGISTER-PD2OR** [comment]
![Screenshot_19](https://user-images.githubusercontent.com/13406542/178186976-515dd686-3ce1-4349-b0e0-8066b565fc75.jpg)

Test map for check entity:

[test_point_message_multiplayer.zip](https://github.com/nmrih/source-game/files/9080850/test_point_message_multiplayer.zip)

**Comment by clague** [comment]
> what's probably happening is that the client receives a PointMessage user message when they get near the entity, and a RemovePointMessage when they step out of its range
if this is true then you can avoid creating the entity altogether and work solely with usermessages, but it might be a bit expensive network-wise to update the position so frequently
example of the PointMessage usermessage: https://github.com/dysphie/sm-map-translator/blob/main/scripting/map-translator.sp#L891

Maybe these can help you.

**Comment by MAGISTER-PD2OR** [comment]
There other problem parent attachment not works with moving objects, only when you no see point_message_multiplayer entity can change position. :)

**Comment by felis-catus** [comment]
Resolved in src-r6447.
