### ISSUE TITLE
[public-1.12.3] Crawlers have bad hitboxes in realism mode.

### ISSUE THREAD

**Issue by TAW3R** [nmrih/source-game#1317]
Hello, I have noticed this for a long time, crawlers have bad hitboxes and quite often its difficult to kill them with one shot to the head. You can easily kill them with your fists, but it's not so easy to do it with firearms and I have died many times because of this. My friend recorded a video and in this video he uses nightmare + realism difficulty, perhaps realism somehow affects this. My friend also said that without realism there is no such problem(but idk about this).
https://www.youtube.com/watch?reload=9&v=rDUHd6BhZno

**Comment by felis-catus** [comment]
Fixed in src-r6553.
