### ISSUE TITLE
[public-1.12.3] Progress triggers always return origin 0,0,0

### ISSUE THREAD

**Issue by Lunreth** [nmrih/source-game#1319]
When using SourceMod to loop through all entities and getting their absolute position we always get 0,0,0 for those brush entities

GetEntPropVector(entity, Prop_Send, "m_vecOrigin", origin);

For contrast, entities like trigger_multiple and trigger_once return a valid origin after using the same method

**Comment by Lunreth** [comment]
Solution:
`
public void OnMapStart()
{
    int trig = FindEntityByClassname(-1, "trigger_progress_weapon");

    float mins[3], maxs[3], center[3];
    GetEntPropVector(trig, Prop_Send, "m_vecMins", mins);
    GetEntPropVector(trig, Prop_Send, "m_vecMaxs", maxs);
    center[0] = (mins[0] + maxs[0]) / 2;
    center[1] = (mins[1] + maxs[1]) / 2;
    center[2] = (mins[2] + maxs[2]) / 2;

    PrintToServer("Trigger at %f %f %f", center[0], center[1], center[2]);
    DrawText(center, "Center", false);
}
`

**Comment by felis-catus** [comment]
Not necessarily a bug, closing.
