### ISSUE TITLE
(models) Console error messages related to props

### ISSUE THREAD

**Issue by Smil3yRiley** [nmrih/source-game#132]
This ticket will be used to list down any errors one would might get if it's related to a model

---

class C_PhysPropClientside 'models/static/nmrih_office_laptop.mdl' has a base specified as 'Metal.break2', but there is no matching entry in propdata.txt (this one was from nms_ransack)

**Comment by Winning117** [comment]
nmrih_office_laptop was fixed in dev-r6151 and the original image with the list of models is now missing so this issue needs to be closed.
