### ISSUE TITLE
[public-1.12.3] Workshop downloads are broken (error 2)

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1320]
Server-side output for `workshop_` commands: 
```
CNMRiHWorkshopManager::OnItemDownloaded() failed! EResult: 2
```

**Comment by felis-catus** [comment]
Latest Steamworks SDK redistributables have to be shipped.

Workaround:
Use SteamCMD to download appid `1007` for respective platform, and copy `steamclient.dll` (Win32) / `steamclient.so` (Linux) to `<your srcds directory>/bin`

**Comment by Lunreth** [comment]
wait, how to reproduce this bug? i can serve workshop files in my dedicated server just fine, like previous updates

**Comment by OKcf** [comment]
> Latest Steamworks SDK redistributables have to be shipped.
> 
> Workaround: Use SteamCMD to download appid `1007` for respective platform, and copy `steamclient.dll` (Win32) / `steamclient.so` (Linux) to `<your srcds directory>/bin`

not work,at least in windows os.

**Comment by Urkgrim** [comment]
> > Latest Steamworks SDK redistributables have to be shipped.
> > Workaround: Use SteamCMD to download appid `1007` for respective platform, and copy `steamclient.dll` (Win32) / `steamclient.so` (Linux) to `<your srcds directory>/bin`
> 
> not work,at least in windows os.

and for me its not working in linux os.

**Comment by zeThijs** [comment]
This fix has worked fine months ago. Had to do another installation and it's still working fine. 
- on multiple installations of different linux os'es

**Comment by felis-catus** [comment]
A patch was released in September 28 to address this issue. Server operators are recommended to update their servers.

**Comment by dysphie** [comment]
For people still having issues, make sure `sv_setsteamaccount` isn't set before using `workshop_` commands
