### ISSUE TITLE
[public-1.12.3] Broken Spanish translations

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1321]
`gameui_spanish` - Missing quotation mark on line 126 `"AmmoCheckType_HUD"			"Sólo interfaz`
`nmrih_spanish` - Missing quotation mark on line 97 `"NMRiH_VoiceCommand_ThankYou"		"¡Gracias!`

**Comment by felis-catus** [comment]
Fixed in dev-r9577.
