### ISSUE TITLE
[public-1.12.3] Zombies don't unfreeze immediately after cutscene if nmrih_extract_preview has Hold Time less than 10 seconds and have Entity to Look At filled

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#1322]
if you set Hold Time for extraction camera less than 10 (for example nms_silence, it has 3 seconds) and have Entity to Look At filled, zombies won't unfreeze when camera turns off and you can't unfreeze them with nmrih_game_state

**Comment by felis-catus** [comment]
Now tracking in #1325. This is caused by `sv_extract_previewtime` cvar.
