### ISSUE TITLE
[public-1.12.3] Players can hijack ongoing progress triggers

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1326]
Players can cancel ongoing `trigger_progress_*` interactions by using a valid weapon or inputting `+use` on them.
This is problematic on triggers that don't save progress and those where `+use` doesn't add to the total progress. 
I think the game should simply ignore interactions on triggers that are already being interacted with.

**Comment by felis-catus** [comment]
Fixed in src-r6444.
