### ISSUE TITLE
[public-1.12.3] Players who join late won't receive current objective

### ISSUE THREAD

**Issue by overmase** [nmrih/source-game#1329]
I don't see the message as in the screenshot
Specter players also don't see the message

![SnapCrab_NoName_2022-6-24_19-35-34_No-00](https://user-images.githubusercontent.com/20251057/180610148-eaac9f02-cb24-4387-a20a-7d4694fdd73d.png)
Players who do not know the progress of the purpose will not understand anything and will stuck

**Comment by felis-catus** [comment]
Fixed in src-r6428.
