### ISSUE TITLE
(nmo_chinatown) Zombies can climb up on bits of crane

### ISSUE THREAD

**Issue by Smil3yRiley** [nmrih/source-game#133]
Occasionally, a zombie may accidentally walk up on the yellow bottom bit of the crane, and stay there

![2013-05-25_00009](https://f.cloud.github.com/assets/3606650/565844/262e1626-c642-11e2-869f-d2da35262c1d.jpg)

There seems to be no nav mesh bit that tell the zombies to go there, perhaps add a npc clip around it?

**Comment by AtheistNMRiH** [comment]
fixed in r8744

**Comment by Winning117** [comment]
Confirmed fixed in src-r4388/dev-r8769, needs to be closed.
