### ISSUE TITLE
Parenting an env_sprite to trigger_progress_ (any) doesn't work

### ISSUE THREAD

**Issue by Lunreth** [nmrih/source-game#1331]
Finally i figured that a closed issue (1319) was not related to an error in Sourcemod coding, instead it was a wrong SetParent output that had a trigger_progress_use as a target

Closed issue: https://github.com/nmrih/source-game/issues/1319

As the title says, getting the correct origin of a trigger_progress_weapon is simple, the issue is now SetParent input not working when using it on those brush entities, the env_sprite always goes to origin 0,0,0 thats why i got confused on why i got the correct location but the created sprite always went to worldspawn 0 vector

Don't know if this is exclusive of NMRiH, probably happens in other source games too with very few trigger brush entities that do NOT allow any parenting at all

**Comment by felis-catus** [comment]
Closing as wontfix for same reason as #1319, fix requires changes to all maps, both past and future.
