### ISSUE TITLE
[public-1.12.3] nmo_anxiety bugged escape van

### ISSUE THREAD

**Issue by Holycrapjimhox** [nmrih/source-game#1332]
![20220610014021_1](https://user-images.githubusercontent.com/35630284/182258165-501625c0-f8f5-47ad-871e-9faf2ed27594.jpg)

The escape van in nmo_anxiety will get stuck on zombies and players as well almost every single time the map is played. It gets stuck as it turns the corner if zombies are present and players will get stuck inside too, unable to move. There's also a chance that the player will get slowly pushed towards the zombies, which can attack through the van and kill them. It's a coin toss if it gets unstuck or not.

Suggestion: Add kill triggers all around the van, similar to the train in nmo_zephyr, so that all zombies around it die instantly, preventing it from getting stuck. This should be done after the key is inserted obviously so that players can't use the van as an easy way to kill runners by luring them into it. Also the collision should be improved if possible, as players can also get it stuck even if no zombies are present.

**Comment by AtheistNMRiH** [comment]
probably fixed in r9981
