### ISSUE TITLE
[public-1.12.3] Melee swing sounds don't network to other players

### ISSUE THREAD

**Issue by randomperson189** [nmrih/source-game#1333]
Whenever another player swings a melee weapon, the swing sound doesn't network to other players. Now I see it why it doesn't because the sounds are animation events as part of the viewmodel but it would be nice to have them play for other players especially since a recent update made the medkit, bandage, etc. sounds network to other players.

Steps to reproduce:
1. Join into a game
2. Have another player swing their melee weapon
3. See that no swing sound plays

**Comment by felis-catus** [comment]
Tested weapon reload sounds and they're networked properly, how did you repro this on your end?

**Comment by randomperson189** [comment]
Ok so I tested and weapon reloads network but melee swings don't, I've updated the title and description accordingly

**Comment by felis-catus** [comment]
Fixed in src-r6575.
