### ISSUE TITLE
[public-1.12.3] Weapon outline bug

### ISSUE THREAD

**Issue by unlucky1251** [nmrih/source-game#1337]
When I pointed the sledgehammer and someone picked it up while I looking away from it, the outline bugged and it stays on another player
Example:
![20220811112959_1](https://user-images.githubusercontent.com/90997914/184134748-09215293-38fa-44f4-8a50-ea33a477174a.jpg)
![20220811113334_1](https://user-images.githubusercontent.com/90997914/184134771-5132baf5-88fa-47a3-9991-90112e3ac331.jpg)

**Comment by dysphie** [comment]
Was the server running any SourceMod plugins, particularly [Invisible Weapons Fix](https://forums.alliedmods.net/showthread.php?p=2756420)?

**Comment by unlucky1251** [comment]
I played on Official NMRiH Server, idk

**Comment by felis-catus** [comment]
Closing. No repro steps, could be a temporary networking issue.
