### ISSUE TITLE
[Feature Request] info_player_nmrih with parent

### ISSUE THREAD

**Issue by MAGISTER-PD2OR** [nmrih/source-game#1341]
Hello, i know there other way do spawn and attach to any objects with parent but maybe was cool do like on photo. :)
![Screenshot_19](https://user-images.githubusercontent.com/13406542/184242677-356bd092-9c64-4fe0-bc86-667e4fa0b41e.jpg)

**Comment by felis-catus** [comment]
Added to nmrih.fgd.
