### ISSUE TITLE
[public-1.12.3] trigger_push not works up.

### ISSUE THREAD

**Issue by MAGISTER-PD2OR** [nmrih/source-game#1343]
trigger_push - doesn't work up until you jump, when just walk nothink happen there.

**Comment by MAGISTER-PD2OR** [comment]
`#pragma semicolon 1
#include <sourcemod>
#include <sdktools>
#include <sdkhooks>

//Original author iEx, me only rewrite plugin for new syntax and modified.

public void OnClientSayCommand_Post(int client, const char[] command, const char[] sArgs)
{
	char text[192];
	int  startidx = 0;

	if (strcopy(text, sizeof(text), sArgs) < 1)
	{
		return;
	}

	if (text[0] == '"')
	{
		startidx = 1;
	}

	if ((strcmp(command, "say2", false) == 0) && strlen(sArgs) >= 4)
		startidx += 4;

	if (strcmp(text[startidx], "fix", false) == 0
	    || strcmp(text[startidx], "/fix", false) == 0
	    || strcmp(text[startidx], "!fix", false) == 0)
	{
		TryFixTriggerPush();
		PrintToChatAll("Fixed :)");
	}
}

TryFixTriggerPush()
{
    int FindMaxEntities = GetMaxEntities();
    char name[64];
    for(int i = 0; i < FindMaxEntities; i++)
    {
        if(IsValidEntity(i))
        {
            GetEdictClassname(i, name, sizeof(name));
            if(!strcmp(name, "trigger_push", false))
            {
				HookSingleEntityOutput(i, "OnStartTouch", PushTouch);
            }
        }
    }
}

public PushTouch(const char [] output, int ent, int client, float delay)
{
	if(!(1<=client<= MaxClients ) || (ent == -1) || (!IsClientInGame(client)) || !IsPlayerAlive(client))
		return;
	
	int fixflags = GetEntityFlags(client);
	if (fixflags & FL_ONGROUND)
	{
		float Pushfix[3];
		float vel[3];
		GetEntPropVector(client, Prop_Data, "m_vecAbsVelocity", vel);
		GetClientAbsOrigin(client, Pushfix);
		Pushfix[2] += 5.0;
		TeleportEntity(client, Pushfix, NULL_VECTOR, vel);
		CreateTimer(0.5, TimerFix, client);
	}
}

public Action TimerFix(Handle timer, any client)
{
	float Pushfix[3];
	GetClientAbsOrigin(client, Pushfix);
	float vel[3];
	GetEntPropVector(client, Prop_Data, "m_vecAbsVelocity", vel);
	Pushfix[2] -= 5.0;
	TeleportEntity(client, Pushfix, NULL_VECTOR, vel);
}
`

Rewrite plugin for nmrih, he can fixed current problem with trigger_push but need fixed on serverside or clientside.

**Comment by MAGISTER-PD2OR** [comment]
[trigger_push_fix.txt](https://github.com/nmrih/source-game/files/9380829/trigger_push_fix.txt)
There i rewrite plugin for nmrih on new syntax he can fixed trigger_push, but need fixed on clientside or serverside.

**Comment by MAGISTER-PD2OR** [comment]
[map_push_fix.zip](https://github.com/nmrih/source-game/files/9381056/map_push_fix.zip)
Without plugins i try fixed trigger_push on map, works but strange.
With plugin much better.

**Comment by MAGISTER-PD2OR** [comment]
More issue, i see warning when tep on trigger_push:
DataTable warning: player: Out-of-range value (1500.000000/1000.000000) in SendPropFloat 'm_vecBaseVelocity', clamping.

**Comment by felis-catus** [comment]
Won't fix to maintain backward compatibility.
