### ISSUE TITLE
Game refuses to finish loading on a new Arch installation

### ISSUE THREAD

**Issue by Rattle189** [nmrih/source-game#1346]
I just re-installed Arch Linux using the **archinstall** script with KDE Plasma as my desktop environment and NVIDIA proprietary drivers version 5.15.65.01 running on the 5.19.5-zen1-1-zen kernel.

The game would start up to the loading screen and then abruptly close before the main menu appears.

System Information:
[system_information.txt](https://github.com/nmrih/source-game/files/9470807/system_information.txt)

Dump File:
[GitHub refuses the file so it's been uploaded to Dropbox instead.](https://www.dropbox.com/s/nyhqtqa3lyd1p21/crash_20220901223102_2.dmp?dl=1)

**Comment by felis-catus** [comment]
Replaced by #1388, closing.
