### ISSUE TITLE
[public-1.12.3] there are no 2 borders for fire mode toggle icon

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#1348]
![nmo_suzhou0000](https://user-images.githubusercontent.com/11333747/188611267-366c5b0c-404a-41c7-ba86-147744b5fb8a.jpg)
![nmo_suzhou0001](https://user-images.githubusercontent.com/11333747/188611273-e1629946-d3d5-4464-bedc-60156ac08ac7.jpg)
![nmo_suzhou0002](https://user-images.githubusercontent.com/11333747/188611275-50e59318-6b36-4966-a224-be54f86996ce.jpg)

there is no left border for single mode, and no right border for auto fire mode, triple shot is fine

**Comment by felis-catus** [comment]
Will fix the border on semi-auto.
Full auto is intentional, as shown here on MP5:

![Untitled](https://user-images.githubusercontent.com/6873987/196783263-209f4897-6492-4dd9-9409-716d018e3cff.jpg)

**Comment by AtheistNMRiH** [comment]
oof
