### ISSUE TITLE
[public-1.12.3] nmo_fema electrified puddle sound playing throughout other parts of the map

### ISSUE THREAD

**Issue by TheUnstableNutcase** [nmrih/source-game#1349]
I got to the surface section towards the end of nmo_fema and I could still hear a constant electricity noise playing the whole time at what sounded like relatively high/full volume. As far as I can remember I don't think I've experienced this before

**Comment by AtheistNMRiH** [comment]
could that sound come from some zombie\zombie's corpse? I got many times that bug with other looped sounds (fire, electricity)

**Comment by AtheistNMRiH** [comment]
I can't reproduce that bug

**Comment by felis-catus** [comment]
Closing as it's not an issue with the map.
