### ISSUE TITLE
[public-1.12.3] My friend send me dmp with demo and there crash.

### ISSUE THREAD

**Issue by MAGISTER-PD2OR** [nmrih/source-game#1350]
When friend try play demo file client just crash.

[crash_nmrih.exe_20221001192815_1.zip](https://github.com/nmrih/source-game/files/9690842/crash_nmrih.exe_20221001192815_1.zip)

[2022-09-24 17.58.41 nmo_zephyr.zip](https://github.com/nmrih/source-game/files/9690840/2022-09-24.17.58.41.nmo_zephyr.zip)

**Comment by TheUnstableNutcase** [comment]
Is the demo file from a previous game version?

**Comment by AtheistNMRiH** [comment]
[democrashes.zip](https://github.com/nmrih/source-game/files/9692845/democrashes.zip)

more crashes from Gex

**Comment by MAGISTER-PD2OR** [comment]
> 

public-1.12.3

**Comment by felis-catus** [comment]
Unfortunately all crash dumps point to closed engine modules that we have no access to. Closing.
