### ISSUE TITLE
"Unlisted" option missing from Workshop publisher

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1351]
![image](https://user-images.githubusercontent.com/11559683/193429329-aa4d1329-5fba-4db7-93fc-a8f16f498274.png)
![image](https://user-images.githubusercontent.com/11559683/193429333-23b36c6c-89f3-48e4-8be4-1b155a968656.png)

**Comment by felis-catus** [comment]
Resolved in src-r7093.
