### ISSUE TITLE
Bug position in map nmo_alysum

### ISSUE THREAD

**Issue by jeeff6** [nmrih/source-game#1360]
https://youtu.be/qHsdcAY11DU
Stuck at DJ player in the lobby while trying to run through the counter.

**Comment by dysphie** [comment]
This is patched in a future game update (svn-9733). 

For server owners who want to fix this in the meantime:

1.  Create a file `maps/maphacks/nmo_asylum.txt` 
2. Paste this inside:
```cpp
"Maphack"
{
	"pre_entities"
	{
		$remove { "id" "288501" } // Remove tiny speaker
		$remove { "id" "288552" } // Remove tiny spotlight
		$remove { "id" "288542" } // Remove tiny spotlight
		$remove { "id" "288548" } // Remove tiny spotlight
		$remove { "id" "288368" } // Remove tiny corpse lid
		$remove { "id" "288348" } // Remove tiny corpse tray
	}
}
```
