### ISSUE TITLE
"No zombie respawn" mutator gets overwritten by Nightmare difficulty

### ISSUE THREAD

**Issue by SpiceySalt** [nmrih/source-game#1362]
The mutator works on Classic and Casual difficulties, however on Nightmare it doesn't.
sv_spawn_regen_target is being forced at 0.6 and changing it to 0 has no effect on the spawns. This was tested on nmo_asylum.

**Comment by TheUnstableNutcase** [comment]
You posted the same issue twice

**Comment by dysphie** [comment]
tracking in #1361
