### ISSUE TITLE
[public-1.13.0] FMOD crash when changing level

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1363]
Client side, crash dumps: 
https://discord.com/channels/211900829307895819/425310705324130304/1037182837071302776
https://discord.com/channels/211900829307895819/425310705324130304/1037183354140885053

it's `fmodex!FMOD::Sound::release+1c`

**Comment by felis-catus** [comment]
Unable to repro at will, likely caused by double release of either ambient sounds, or legacy music overlay. This issue is not limited to nmo_asylum, changed title accordingly.

**Comment by felis-catus** [comment]
Presumed fixed after changes to the system, unable to repro. Closed.
(Related commits: src-r6630, src-r6662)
