### ISSUE TITLE
(nmo_broadway) Able to open gun shop back door as soon as explosives are placed

### ISSUE THREAD

**Issue by Smil3yRiley** [nmrih/source-game#137]
You're able to open the backdoor to the gun shop immediately after you placed the gas tank by the front gate, without having to wait for the explosion

---

Steps to Reproduce
1) Get one of the orange narrow gas tanks and place it on the gate by the gun shop's front door
2) Run to the side of the gun shop and open the side door

**Comment by AtheistNMRiH** [comment]
was fixed in previous versions, need to be closed

**Comment by Fersigal** [comment]
A nice sidetrick though =p
