### ISSUE TITLE
[Feature Request] Deal with AFK griefing

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1372]
Players can AFK as the last person alive and effectively stall the server forever
Implementing something like [guaranteed spawn](https://github.com/dysphie/nmrih-guaranteedspawn) would help newcomers supersede the griefers

**Comment by felis-catus** [comment]
Added in src-r7629; improved idle player detection, idle item drop, and new cvars:
- `sv_idle_tracking_method` - "0 = old behavior, only tracks buttons; 1 = new behavior, also tracks actions that can bypass idle detection." (default: 1)
- `sv_idle_item_drop` - "Drops carried item from an idle player." (default: 1)
- `sv_idle_item_drop_time` - "How long to wait until dropping a carried item from an idle player, in seconds." (default: 60.0)
