### ISSUE TITLE
[public-1.13.1] nmo_asylum missing face on a door by the spawn of the valve in the basement

### ISSUE THREAD

**Issue by Plazehorta** [nmrih/source-game#1376]
On the objective to drain the shower.
![20221122112021_1](https://user-images.githubusercontent.com/85467329/203218379-ea9e4059-b454-4642-832c-806fedca294c.jpg)

**Comment by AtheistNMRiH** [comment]
oops, my bad

**Comment by AtheistNMRiH** [comment]
confirmed fixed in r9780
