### ISSUE TITLE
[Feature Request] Spectator Infection/Damage/Health HUD

### ISSUE THREAD

**Issue by iVoxiom** [nmrih/source-game#1377]
When one spectates a player, they should be able to see exactly what they see:

- Health colour status
- Damage indicator
- Infected status
- When taking pills, the spectator should also see the flash

This feature already exists in the hit co-op zombie game series Left 4 Dead.

**Comment by dysphie** [comment]
> Infected status
This would make it very easy to out infected people, not a good idea

**Comment by felis-catus** [comment]
Closing as rejected.

**Comment by felis-catus** [comment]
To add, spectator damage indicator and pills flash could be implemented. Forcing grayscale display is not really necessary.
