### ISSUE TITLE
[Feature Request] Realistic Throwable Explosive Mechanic Enhancements

### ISSUE THREAD

**Issue by iVoxiom** [nmrih/source-game#1382]
- When the pin on the grenade is pulled, it should explode in the player's hand(s) after ~3 seconds if they decide not to throw it. This will kill the player, potentially harm surrounding zombies and teammates (if friendly fire is enabled) while adding more realism to the game.

- When the fuse for TNT is lit, it should blow the player up should they decide to not throw it, certainly killing them and potentially killing surrounding zombies while adding more realism to the game.

- A lit molotov should explode in the player's hands should they decide to not throw it, setting them on fire similar to the on-fire-zombies in the new version of nmo_anxiety.

**Comment by felis-catus** [comment]
This was implemented in internal build during 1.10 development, and rejected after testing. We're not planning to revisit the idea.
