### ISSUE TITLE
[public-1.13.1] weapon_fired, wrong client index

### ISSUE THREAD

**Issue by MAGISTER-PD2OR** [nmrih/source-game#1384]
Wrong client 0 index and error on serverside, can't detect player_id.

#include <sourcemod>
#include <sdktools>
#include <sdkhooks>

public void OnPluginStart()
{
	HookEvent("weapon_fired", Fire);
}

public Action Fire(Event event, const char[] name, bool dontBroadcast)
{
    int client = GetClientOfUserId(event.GetInt("player_id"));
    char sWeaponName[64];
    GetClientWeapon(client, sWeaponName, sizeof(sWeaponName));

    if (client && IsClientInGame(client))
    {
		PrintToChatAll("[FIRED] %s", sWeaponName);
    }
    return Plugin_Handled;
}

**Comment by dysphie** [comment]
`player_id` is likely a client index not a userid, take out the `GetClientOfUserId` call

**Comment by MAGISTER-PD2OR** [comment]
Ah, i just look before same way use weapon_fired event in other games. :)
Well now all works.

![Screenshot_46](https://user-images.githubusercontent.com/13406542/203441434-4742d3db-4f7a-48b7-9d57-07af09322861.png)
