### ISSUE TITLE
[public-1.13.1] npc_killed, event bugged i guess

### ISSUE THREAD

**Issue by MAGISTER-PD2OR** [nmrih/source-game#1385]
When try get (exp_grenade, exp_molotov, exp_tnt) in chat only (me_fists) on event npc_killed.
With other entity all fine.

> 
> public void OnPluginStart()
> {	
> 	HookEvent("npc_killed", Event_WeaponNPCKill);
> }
> 
> public Action Event_WeaponNPCKill(Event event, const char[] name, bool dontBroadcast)
> {
> 	int client = event.GetInt("killeridx");
> 	
> 	if (client == 0 || client > MaxClients || IsFakeClient(client) || !IsClientAuthorized(client))
> 	{
> 		return Plugin_Continue;
> 	}
> 	
> 	char sWeaponName[64];
> 	GetClientWeapon(client, sWeaponName, sizeof(sWeaponName));
> 	PrintToChatAll("[TEST] %s", sWeaponName);
> 	
> 	return Plugin_Handled;
> }

**Comment by MAGISTER-PD2OR** [comment]
Found issue only with (killeridx), can't get right entity name on GetClientWeapon.
With (weaponid) all good.

**Comment by dysphie** [comment]
This isn't a bug, the nade exits your inventory and explodes, it's no longer your active weapon at that point.
