### ISSUE TITLE
[public-1.13.0] Low stamina penalty for multi-zombie melee arcs

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1386]
Hitting multiple zombies takes little stamina compared to older patches

1.13.1:

https://user-images.githubusercontent.com/11559683/203530315-b973b6a5-ac9a-49d5-b6cd-126f97dee0de.mp4

1.09.6:

https://user-images.githubusercontent.com/11559683/203530327-e82980da-507c-40c9-b225-69a2ef6ea50e.mp4

**Comment by felis-catus** [comment]
Fixed in src-r6733.
