### ISSUE TITLE
[public-1.13.1] nmo_rockpit softlock

### ISSUE THREAD

**Issue by TheUnstableNutcase** [nmrih/source-game#1394]
On the objective that requires players to use the gas can to destroy the barricade, players can throw the gas can out of bounds, as shown in these screenshots:

![20221205161737_1](https://user-images.githubusercontent.com/42658874/205764484-c9e21fb4-4712-4db6-bc89-07e055616543.jpg)

![20221205161743_1](https://user-images.githubusercontent.com/42658874/205764489-712b0cc8-ac99-4b5a-b08f-9c547a2d5b6f.jpg)

On the 2nd screenshot if you look carefully you can see the orange and yellow gas can on the ground near the corner, I probably should have went a little bit closer as it's a bit hard to see

**Comment by AtheistNMRiH** [comment]
confirmed fixed in r9792
