### ISSUE TITLE
[Feature Request] Voice Subtitles Server-Side Option

### ISSUE THREAD

**Issue by iVoxiom** [nmrih/source-game#1395]
Server owners should be able to use `cl_voicesubtitles 0` on their servers, so their players will be unable to see voice subtitles in chat.

- It is already possible to disable death and infection notices, which both will print to chat
- Disabling subtitles will add more realism relating to proximity
- Adds additional preference for those who dislike subtitles, but on a server-wide scale
- Some dislike subtitles, which is why the option is there in the first place (just not server-side currently)

**Comment by felis-catus** [comment]
1: Death and infection notices are printed by a plugin, they're not in the base game.
2: You can disable sv_alltalk to hide subtitles within proximity.
3/4: We shouldn't let server ops control user preferences, especially ones that are important for accessiblity.

Closing as rejected.
