### ISSUE TITLE
[public-1.13.1] Resolution and Display Mode Bug

### ISSUE THREAD

**Issue by iVoxiom** [nmrih/source-game#1396]
Changing either the **resolution** or **display mode** setting (under Options > Video) will cause the following bugs (which are all permanent unless the game is restarted):

- Permanent visual bug to the compass
- Objectives will no longer show
- Server name field on the scoreboard will be blank

**Comment by felis-catus** [comment]
Fixed compass visual bug on resolution change in src-r7200.

**Comment by felis-catus** [comment]
Fixed server name field on the scoreboard being empty in src-r7202.

**Comment by felis-catus** [comment]
Fixed objective text not showing in src-r7204.
Most of the HUD issues on resolution change are resolved now, so I'm closing this.
