### ISSUE TITLE
[public-1.13.1] Supply Crate Bug / Permanently Stuck

### ISSUE THREAD

**Issue by iVoxiom** [nmrih/source-game#1397]
When a player interacts with supply crates...

- They may become stuck 'inside' of the supply crate, unable to move
- The HUD may become impossible to close
- The player may become stuck in place permanently

**Comment by JergenRoss** [comment]
This happened to me with little bit far reach to interact supply crate. not close nearly.

**Comment by felis-catus** [comment]
Fixed in src-r6797.
