### ISSUE TITLE
[Issue Report] Zombie Surfing

### ISSUE THREAD

**Issue by iVoxiom** [nmrih/source-game#1398]
Regardless of the zombie type (whether it be crawlers, infected runners, runners, kids or walkers), players can stand on the heads of zombies with no risk of injury. The zombie will not attack them, it will simply become frozen while the player sits on their head. The player can use this method to 'surf' among a horde, literally running on the heads of hundreds of zombies, coming out unscathed.

Solution: If a player attempts to stand on a zombie, the zombie will enter attack mode and cause damage to the player. Or perhaps the player will slide off the zombie somehow.

**Comment by felis-catus** [comment]
Not a bug.

**Comment by felis-catus** [comment]
To add, we don't usually fix common movement tricks and glitches that add more depth to gameplay.
