### ISSUE TITLE
[public-1.13.1] Chainsaw and abrasivesaw swing hit sounds sometimes don't play

### ISSUE THREAD

**Issue by overmase** [nmrih/source-game#1400]
Chainsaw and abrasivesaw's swing hit sound in idle mode does not play the hit sound when it hits zombies or objects, sometimes it is unclear if it hits

However, it is unstable because the hit sound will play at some point.

**Comment by felis-catus** [comment]
This was fixed in src-r6790 for zombies, on world it's intentional to prevent particle / sound spam.
