### ISSUE TITLE
[Feature Request] env_timer font size

### ISSUE THREAD

**Issue by MAGISTER-PD2OR** [nmrih/source-game#1401]
In **env_timer** need feature change font size. 👍

**Comment by felis-catus** [comment]
Font size can't be changed without creating new font handles clientside, this can be costly and not something a map should have control of. It's the same reason why `point_message_multiplayer` is limited to existing font entries, that could be added to `env_timer` as well.

**Comment by felis-catus** [comment]
Won't do, for now we prefer keeping HUD timers consistent, and custom fonts are tricky to maintain as mentioned in the previous comment.
