### ISSUE TITLE
[public-1.13.1] env_timer bug with position on screen

### ISSUE THREAD

**Issue by MAGISTER-PD2OR** [nmrih/source-game#1402]
When use current values all fine:
xpos = 1
ypos = 2

But with other values not see timer.

![Screenshot_93](https://user-images.githubusercontent.com/13406542/207496494-df22f0c4-fd5f-4b87-bbc4-4da3125d49ca.png)

There test map works fine, but after changes on other values bug.

[test_timer.zip](https://github.com/nmrih/source-game/files/10223983/test_timer.zip)

**Comment by felis-catus** [comment]
Unable to repro on the latest dev build. Does this happen with add-ons disabled?

**Comment by MAGISTER-PD2OR** [comment]
> Unable to repro on the latest dev build. Does this happen with add-ons disabled?

Yeah i try with addons and without.

**Comment by felis-catus** [comment]
Unable to repro, closing for now.
