### ISSUE TITLE
Camera bug while holding K (SKS No bayonet)

### ISSUE THREAD

**Issue by Blinkyeah** [nmrih/source-game#1404]
When holding K and looking down, the camera will go beyond feet level.

I have only noticed this with SKS (no bayonet), did not try for other weapons so I don't know if this effect is present in other weapons.

**Comment by dysphie** [comment]
> the camera will go beyond feet level
Are you referring to the weapon model going out of frame? I'm not noticing any other effects

**Comment by Blinkyeah** [comment]
https://youtu.be/Iky5B0Ih_YQ

If this doesn't happen to you it might be a console command ? I do not have any viewmodel addon

**Comment by dysphie** [comment]
Thanks for the clip, yeah definitely not seeing that here, unsure about the cause

**Comment by felis-catus** [comment]
That's caused by viewmodel headbobbing, it's used to offset the camera. Not necessarily an issue.
