### ISSUE TITLE
[public-1.13.1] A prop_door_breakable might have wrong hinge axis in nms_drugstore

### ISSUE THREAD

**Issue by Klowby** [nmrih/source-game#1408]
There is a useable door located in camilla‘s restaurant, which might have wrong hinge axis.
![nms_drugstore](https://user-images.githubusercontent.com/42507880/213747929-484aa8bd-8503-4971-8549-9fed89aca295.png)

Here:
https://streamable.com/z1yxou

**Comment by AtheistNMRiH** [comment]
confirmed fixed in r9821
