### ISSUE TITLE
[public-1.13.2] Workshop Publisher displays an error on all files ("Invalid BSP")

### ISSUE THREAD

**Issue by MAGISTER-PD2OR** [nmrih/source-game#1416]
I have error with vpk when try add.
![Screenshot_21](https://user-images.githubusercontent.com/13406542/218916616-729660c9-1291-4886-8e89-36bfc48e6530.png)

**Comment by MAGISTER-PD2OR** [comment]
Vpk not broken i check before and works when in custom folder. :)

**Comment by felis-catus** [comment]
This was fixed in src-r6885, we will leave this issue open until the unversioned hotfix ships.
To reiterate, all files will falsely return an error on selection, there's no workaround.

**Comment by MAGISTER-PD2OR** [comment]
Hope fixed soon, can't upload my popular addon: Improved Chat :)

**Comment by felis-catus** [comment]
**Workaround:**
Before a hotfix ships, you can switch to the `previous` beta branch on Steam, this will revert your build to v1.13.1 that includes a functional publisher.

**Comment by felis-catus** [comment]
Closing, as the hotfix is turning out to be the next full patch release (1.13.3).
