### ISSUE TITLE
[public-1.13.2] Crash when playing a map with different values in maphack

### ISSUE THREAD

**Issue by overmase** [nmrih/source-game#1417]
I don't know if the original value is wrong because it didn't crash with public-1.13.1 and the error was passed through and there was no problem
debug spams in consoleversion and freezes until server shuts down

enable sv_maphack_debug 1 and check maphack
[nmo_anxiety.txt](https://github.com/nmrih/source-game/files/10755559/nmo_anxiety.txt)
![SnapCrab_NoName_2023-2-15_0-49-12_No-00](https://user-images.githubusercontent.com/20251057/219358617-f6ff4a43-981f-451c-acc4-9c32915b87ca.png)

**Comment by felis-catus** [comment]
Unable to repro, did you post the correct maphack script? The console message in the screenshot is not visible for pre-entity stage `$modify` function, looks like it's for `$edit_all` instead?

**Comment by overmase** [comment]
It works fine in edit, so close it
