### ISSUE TITLE
[Feature Request] Improved Chat

### ISSUE THREAD

**Issue by MAGISTER-PD2OR** [nmrih/source-game#1418]
Improved Chat - now very popular addon.

https://steamcommunity.com/sharedfiles/filedetails/?id=1747783686

I have fixed version there in zip for next update to workshop, when fixed uploading tool with "Invalid BSP".

[ImprovedChat.zip](https://github.com/nmrih/source-game/files/10759434/ImprovedChat.zip)

But maybe add official ingame, players only say thanks. :)

**Comment by felis-catus** [comment]
We're not planning on changing the chat panel at this time.
