### ISSUE TITLE
[public-1.13.2] Resize fonts and ui.

### ISSUE THREAD

**Issue by MAGISTER-PD2OR** [nmrih/source-game#1420]
1. In spectators where map name not show large text for example: nmo_test00000000000000111111111111 there only nmo_test0000000000000011 on screen.
2. In hud where sv_deathnotice 1 there large font, before was small font.

**Comment by felis-catus** [comment]
What's your current screen resolution? If you can post a screenshot that would also be helpful.

**Comment by MAGISTER-PD2OR** [comment]
I try with 2560x1440, 2560x1080, 1600x900 
![Screenshot_1](https://user-images.githubusercontent.com/13406542/220807956-0a6d21a5-0ebf-4375-8c14-386e5aca4127.png)

**Comment by MAGISTER-PD2OR** [comment]
Maybe possible auto scroll text for long names. :)

**Comment by felis-catus** [comment]
> I am also experiencing bigger fonts on HUD texts, such as when opening up your inventory and pointing at any item. Also, I don't know if it's related, but the font in the Sourcemod in-game menus in my client are also bigger than in the previous update.

That's intentional, previously "smaller" text is now proportional to support wider range of resolutions - it's still "small", but now properly adjusted to your current resolution.

**Comment by felis-catus** [comment]
Not a bug.
