### ISSUE TITLE
[public-1.13.2] Boards with "Disable item motion" flag unchecked still don't have a motion

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#1422]
![nms_house_of_forester_v30001](https://user-images.githubusercontent.com/11333747/224532097-cff7b65c-6b41-4a2f-b1c9-d06b4855b37d.jpg)
boards still float even if they shouldn;'t, you have to place them manually as close as possible to any surface

**Comment by AtheistNMRiH** [comment]
![nms_isolated0000](https://github.com/nmrih/source-game/assets/11333747/609e7977-088d-4a15-ac1b-89ccd8c04248)
![nms_isolated0001](https://github.com/nmrih/source-game/assets/11333747/ed86dbf8-7e25-40e8-b8e1-3e28b98f7851)
I can see that if board is spawned on any height it will move to the ground but still won't touch it, it will perfectly land only if  you picked it up and dropped, so they don't "float" in position like they appear to be in hammer editor

**Comment by felis-catus** [comment]
Fixed in src-r7349.
