### ISSUE TITLE
[public-1.13.2] Exhausted fema bag station prop will continually fade in and out if you will spam "use" button

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#1423]
nitpick, but anyway
1) Get third fema bag from fema bag station
2) Drop it somewhere and immediately start to spam "use" button on fema bag station
3) Observer never disappearing fema bag station
![nms_flooded0000](https://user-images.githubusercontent.com/11333747/224534300-27534f9e-240f-493f-a0ab-d7faeb31eff8.jpg)

**Comment by felis-catus** [comment]
Fixed in src-r7299.
