### ISSUE TITLE
[public-1.13.2] Maglite remains visibly equipped even though it's not present in player's inventory

### ISSUE THREAD

**Issue by ghost** [nmrih/source-game#1424]
A bug where the item 'Maglite' continues to appear in viewmodels and third-person POV when the player equips and immediately drops it via inventory whilst animation is drawn.

> _A player can see themself holding a Maglite, but it is not present in their inventory._

Steps to reproduce (Consistent):

  1. Must have _item_maglite_ and flashlight-compatible firearm(s)/melee(s) in inventory.

  2. Equip any flashlight-compatible melee or firearm, _Colt 1911 as an example_.

  3. Keep holding _+inventory_, press _+maglite_, then _mouse2_ drop the maglite from the inventory wheel as it's being drawn.

https://user-images.githubusercontent.com/120353795/226862089-06a31aea-fd84-4d21-b04d-f06e782c33bb.mp4

**Comment by felis-catus** [comment]
Fixed in src-r7352.
