### ISSUE TITLE
MapHack: Server crash on player join with $remove in "entities"

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1425]
Following maphack will crash the server when a client joins the game.

```cpp
"Maphack"
{
	"entities"
	{
		$remove { "classname" "nmrih_health_station" } // Any classname works
	}
}
```

Crash reports (public 1.13.2):
- https://crash.limetech.org/h7wl3wm3bbx3
- https://crash.limetech.org/djbajy7bizhn 

Crash dumps
- https://discord.com/channels/211900829307895819/425310705324130304/1089497252340453496

**Comment by felis-catus** [comment]
Fixed in src-r6923.
