### ISSUE TITLE
[public-1.13.2] ambient_fmod "Play everywhere" flag still has entity's sound origin

### ISSUE THREAD

**Issue by zeThijs** [nmrih/source-game#1426]
When ambient_fmod "Play everywhere" flag is on, the entity will play everywhere, but still have a sound origin. This origin being the entity's origin. It will sound like the audio comes from the ambient_fmod 's origin
With ambient_generic the sound "originates" from everywhere.

**Comment by felis-catus** [comment]
Fixed in src-r6960.

**Comment by zeThijs** [comment]
Noice! Cheers
