### ISSUE TITLE
[public-1.13.2] VScript netprop reads are wrong

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1427]
There appears to be a problem with `NetProps` reads in VScript, it's returning incorrect values and fetching data from the wrong offsets

Example:

![image](https://user-images.githubusercontent.com/11559683/232828558-36aec174-0723-48aa-8b7f-571d1c8c2af5.png)

```cpp
local mins = NetProps.GetPropVector(cart, "m_vecMins");
local maxs = NetProps.GetPropVector(cart, "m_vecMaxs");

Msg(format("Mins: %.f %.f %.f \n", mins.x, mins.y, mins.z));
Msg(format("Maxs: %.f %.f %.f \n", maxs.x, maxs.y, maxs.z));
```

This outputs non-sense like:

![image](https://user-images.githubusercontent.com/11559683/232828837-f498f8a0-0db5-4748-8d03-8e5294875f99.png)

where the maxs are actually `m_vecOrigin`

**Comment by felis-catus** [comment]
For reference, also bugged on Mapbase upstream: https://github.com/mapbase-source/source-sdk-2013/issues/175

**Comment by felis-catus** [comment]
Resolved by merging https://github.com/mapbase-source/source-sdk-2013/pull/260, thank you @samisalreadytaken !
