### ISSUE TITLE
[VSCRIPT] On linux, 'params' is not passed in ModifyEmitSoundParams(handle [params])

### ISSUE THREAD

**Issue by zeThijs** [nmrih/source-game#1428]
Works fine in windows, but breaks in linux. 
Example code:
  entity.ValidateScriptScope()
  local scope = entity.GetScriptScope()
  scope.ModifyEmitSoundParams <- function()
  {
      ModEmitSnd_Elite(params)
  }  

Example error passed into console:
AN ERROR HAS OCCURRED [the index 'params' does not exist]

CALLSTACK
*FUNCTION [unknown()] scriptname.nut line [120]

**Comment by felis-catus** [comment]
This was fixed in src-r7171.

**Comment by zeThijs** [comment]
nice!

**Comment by samisalreadytaken** [comment]
@felis-catus This is also being tracked here https://github.com/mapbase-source/source-sdk-2013/issues/244, you should consider contributing the fix upstream.
