### ISSUE TITLE
[public-1.13.2] Please return the opportunity to vote for the map change on the official servers

### ISSUE THREAD

**Issue by TAW3R** [nmrih/source-game#1430]
Hello, I think there is nothing wrong with being able to change the map by voting. (unless there are critical bugs that i dont know)
Without this, some players have to wait a long time and try to somehow skip the current map (for example, constantly dying) to play map that they want
Command: sv_vote_issue_changelevel_allowed 1

**Comment by felis-catus** [comment]
Closing as this isn't an issue with the game.
