### ISSUE TITLE
[Feature Request] CVar that establishes a minimum time to elapse to be able to vote

### ISSUE THREAD

**Issue by lobeteh** [nmrih/source-game#1431]
I have detected in the servers that I manage numerous acts in which players, immediately after entering the server, start a vote to change the map. And when they have loaded that map, they start another new vote.

According to the [CVARS list](https://developer.valvesoftware.com/wiki/List_of_No_More_Room_in_Hell_Console_Commands) there is a cvar that allows you to define the time that must elapse between voting and voting, but there is none that allows you to define a minimum time that must elapse when start a round to be able to take a vote.

The command could be called sv_vote_time_round_start and the parameter of this command would be a positive integer that would be the time in seconds.

The implementation and the idea would be similar to the one in ["RockTheVote" plugin from Sourcemod](https://github.com/alliedmodders/sourcemod/blob/master/plugins/rockthevote.sp)

```sp
g_Cvar_InitialDelay = CreateConVar("sm_rtv_initialdelay", "30.0", "Time (in seconds) before first RTV can be held", 0, true, 0.00);
```

**Comment by felis-catus** [comment]
Implemented as `sv_vote_initial_delay` in src-r6951.
