### ISSUE TITLE
[public-1.13.2] 2 Filter_Scripts hijack one another's PassesDamageFilter hook

### ISSUE THREAD

**Issue by RaymondChen2018** [nmrih/source-game#1434]
Version: Steam
Normally filter_script can serve as damage filter for npc. If I set an npc's damage filter to a filter_script in hammer and both exists on map spawn, filter_script works as intended. 

However if an npc is spawned later on (using template/maker) with the map-spawned filter_script as damage filter, the npc becomes invincible.
![Untitled1](https://github.com/nmrih/source-game/assets/36557416/90db7dc1-c72b-4018-aafe-a7536ad5ac23)

It will only resume taking damage if I clear its damagefilter (ent_fire !picker setdamagefilter "") or set it to a regular filter(non-scripted, filter_activator_class for example), implying there could be something wrong with the entity filter_script.
![Untitled2](https://github.com/nmrih/source-game/assets/36557416/11037cda-aba0-47bd-9032-e4569cc3b5d6)
![Untitled3](https://github.com/nmrih/source-game/assets/36557416/935b57f1-613b-4b5c-9204-e1b35843ae94)

No console output of interest.

vscript code on the filter_script:
```
const flagWeaponDamageBuff = 8;
function PassesDamageFilter()
{
	// No friendly fire
	printcl(255,0,0,"filter"); // WONT PRINT when the problem occurs
	local attacker = info.GetAttacker();
	if(attacker != null && attacker.IsValid() && !attacker.IsWorld() && attacker.GetClassname().tolower() == "npc_national_guard")
	{
		return false;
	}
	
	// ScaleDamage
	local dmgStat = info.GetDamageStats();
	
	if((dmgStat & flagWeaponDamageBuff) > 0)
	{
		local classname = info.GetInflictor().GetClassname().tolower();
		printcl(255,0,0,"classname: "+classname);
		if(classname == "projectile_arrow")
		{
			info.ScaleDamage(30.0);
		}
	}
	info.SetDamageStats(dmgStat | flagWeaponDamageBuff);

	return true;
}
```

Update: 
Apparently the root of the issue was that there are 2 filter_scripts in the map (different vscript, different entity name, for different purpose), and one of the filter_script hijacks the hook PassesDamageFilter and returns false, causing the other filter_script to fail with its hook as well.

**Comment by felis-catus** [comment]
Fixed in src-r7127.
