### ISSUE TITLE
[dev-1.13.3] zombies fail to attack players standing on props or other zombies

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1435]
nmo_aftermath_v2f (<https://steamcommunity.com/sharedfiles/filedetails/?id=2919433177>) - setpos 867 10543 -2976

1.13.2 - zombies attack the player as expected

https://streamable.com/6t17c8

1.13.3 - zombies no longer attack the player

https://streamable.com/961ndl

not restricted to that spot, standing on any zombie head will do:
dev world example: https://streamable.com/ip6l8h

no plugins, addons, etc
this has a huge impact on gameplay

**Comment by dysphie** [comment]
introduced in revision 9851 "Misc. code optimization"

**Comment by felis-catus** [comment]
Fixed in src-r6970.
