### ISSUE TITLE
[public-1.13.2] Lexus car model crashes clients

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1436]
unsure at this point whether this is a mapper error or a problem with the asset
`props/vehicles/lexus_is_300_trunk_open.mdl` can crash clients on high graphics settings

repro
- set model quality to high and enable HDR
- `map nmo_aftermath_v1` (https://steamcommunity.com/sharedfiles/filedetails/?id=2980679788)
- `setpos 4353 13304 58`, you'll 100% crash
- disable HDR, lower mdl quality or remove `models\props\vehicles\lexus_is_300_trunk_open.mdl` from disk, no crash

crash report https://crash.limetech.org/2nqpufoifd56

**Comment by dysphie** [comment]
this can be fixed by changing the glass bodygroup in the qc to one of the lod versions

**Comment by dysphie** [comment]
```diff
$bodygroup "glass"
{
-	studio "good_condition_glass.smd"
+	studio "good_condition_glass_lod1.smd"
}

$lod 100
{
	replacemodel "trunk_open.smd" "trunk_open_lod1.smd"
-	replacemodel "good_condition_glass.smd" "good_condition_glass_lod1.smd"
	nofacial
}
$shadowlod
{
	replacemodel "trunk_open.smd" "trunk_open_lod2.smd"
-	replacemodel "good_condition_glass.smd" "good_condition_glass_lod2.smd"
+	replacemodel "good_condition_glass_lod1.smd" "good_condition_glass_lod2.smd"
	nofacial
}
```

**Comment by felis-catus** [comment]
Fixed in dev-r9870.
