### ISSUE TITLE
[dev-1.13.3] quarantine broken areaportal

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1438]
![image](https://github.com/nmrih/source-game/assets/11559683/20c98baf-ffe5-464e-aa2e-4d0420450d2f)
![image](https://github.com/nmrih/source-game/assets/11559683/720b3a4a-0c3f-41ef-83f0-8696597526d7)
repro break door instead of opening it
other breakable doors might have the same issue, i haven't checked

**Comment by felis-catus** [comment]
This was fixed in dev-r9883.
