### ISSUE TITLE
[Feature Request] Add the ability to the servers to download materials, models, sounds to players from the steam workshop instead of using fast dl.

### ISSUE THREAD

**Issue by TAW3R** [nmrih/source-game#1440]
Greetings, it would be nice to make it possible to download server content from the steam workshop instead of using web servers because it is more convenient for server administrators (they do not need to worry about third-party web servers and in general it will simplify this moment much) and for players the download will be much faster.

**Comment by felis-catus** [comment]
Won't do. Workshop isn't designed to be a content delivery service for server assets, additionally we would have to support downloading & publishing loose files for both client and server, which can be a security risk when unsolicited files are distributed.
