### ISSUE TITLE
[dev] compass blip doesn't point to objective items

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#1441]
it seems that it doesn't update in real time? because you can change its "direction" every time you use compass
![nmo_cleopas0000](https://github.com/nmrih/source-game/assets/11333747/5578ade4-e48f-4e89-94c8-66c7e7393b85)
![nmo_cleopas0002](https://github.com/nmrih/source-game/assets/11333747/5a6ba6bf-bf9e-4fa0-8d64-52dedb485407)
![nmo_junction0001](https://github.com/nmrih/source-game/assets/11333747/cbfb5a1d-ff58-4271-91b0-f213b162d2df)
![nmo_rockpit0005](https://github.com/nmrih/source-game/assets/11333747/bb4e1148-a984-42a5-9f83-88c922892c1f)

**Comment by felis-catus** [comment]
This was fixed in src-r6977.
