### ISSUE TITLE
[Feature Request] Parallax Corrected Cubemaps?

### ISSUE THREAD

**Issue by Yankumo-Koishi** [nmrih/source-game#1442]
It would be good to implement PCC for mappers because ormally for reflections that properly line up with a rooms walls, you would need to use expensive effects like `LightmappedReflective` shader with `func_reflective_glass`, which is very expensive and easily cause performance issue for the players, The cheap alignment of PCC is amazing although it does lack to reflect the movement of dynamic objects ( such as players, vehicles, enemies )

**Comment by felis-catus** [comment]
This was attempted during 1.12 development, but due to a restriction on how engine handles default shaders (we can't override LightmappedGeneric for instance), it was cut last minute, and will unfortunately stay that way with our current technical limitations.
