### ISSUE TITLE
[public-1.13.3] func_tracktrain eats +use command

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1445]
The game consumes "+use" on func_tracktrains even when the "No user control" and "Is unblockable by player" flags aren't set. 

This makes it difficult to pick up ammo on movable platforms (elevators, rafts, etc) or interact with entities near trains. For example, I have a trigger_progress_use that's used to hotwire a tracktrain-based vehicle, and it's completely unusable at point blank range:

![hl2_h4ZH7UuwJJ](https://github.com/nmrih/source-game/assets/11559683/f1badc62-1d74-4bdf-a99e-dd379c29ee0c)
![hl2_2dBciVH5vC](https://github.com/nmrih/source-game/assets/11559683/2cfa8e39-52e5-496d-b1d0-8f54b5bb71e5)

**Comment by felis-catus** [comment]
Fixed in src-r7300.
