### ISSUE TITLE
[public-1.13.3]Viewmodel Arms&Melee Weapons not get bloody anymore.

### ISSUE THREAD

**Issue by AkitaKyoko** [nmrih/source-game#1446]
![20230826111842_1](https://github.com/nmrih/source-game/assets/143239981/4d6778dd-d1bb-4106-9bf4-5c82d7db1b36)
Viewmodel Arms&Melee Weapons not get bloody anymore.
Tried both Vanilla&Modded materials.

**Comment by felis-catus** [comment]
Duplicate of #1444
