### ISSUE TITLE
[public-1.13.3] MapHack: $remove_all not working

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1447]
$remove_all has stopped working.

1. `map nmo_rush_b_t1_4_repack` [[link]](https://steamcommunity.com/sharedfiles/filedetails/?id=2929395101)
2. `maps/nmo_rush_b_t1_4_repack.txt`
```cpp
"Maphack"
{
	"entities"
	{
		$remove_all { "targetname" "players_compare_matrixboss1" }
	}
}
```
> MapHack: Removed all entities targetnamed "players_compare_matrixboss1"

Entity remains on the level:

![image](https://github.com/nmrih/source-game/assets/11559683/1efd0e58-9714-4346-a0b6-151305eabbfe)

Roll back to 1.13.2, entity is properly removed

**Comment by felis-catus** [comment]
Fixed in src-r7055.
