### ISSUE TITLE
[public-1.13.3] nmo_quarantine, Soft lock because can't pick up objecive items.

### ISSUE THREAD

**Issue by Dayonn-dayonn** [nmrih/source-game#1451]
There is a gap between the FasEx car and the wall that the player cannot get through; the gas can was blown away by TNT and moved to a position where it just cannot be picked up.
![20230918155739_1](https://github.com/nmrih/source-game/assets/37202119/230e3fd7-7ba9-444a-97fc-f2d9fbd7a654)
![20230918155822_1](https://github.com/nmrih/source-game/assets/37202119/f7662578-bd8e-438f-a1cf-b74b2111ca8b)

**Comment by AtheistNMRiH** [comment]
fixed in r10081
