### ISSUE TITLE
[public-1.13.4] nmo_underground softlock

### ISSUE THREAD

**Issue by TheUnstableNutcase** [nmrih/source-game#1452]
![20231002205846_1](https://github.com/nmrih/source-game/assets/42658874/697cce20-e4dc-44a6-b52f-d377c8e196f7)

While the players are going around the surface collecting the items, players can throw them up here to softlock the map, since the map doesn't allow for players to climb the ladder before the players collect all 3 of the items and have to place them.

A fix to this issue would be to either allow the ladder to be climbed before, or to add a vphys clip that gets removed once players have collected all 3 items and are ready to place them.

**Comment by AtheistNMRiH** [comment]
should be fixed in r9917
