### ISSUE TITLE
[Feature Request] Allow votekick only to trusted players

### ISSUE THREAD

**Issue by sys-arch** [nmrih/source-game#1453]
## Context

Both official servers and the vast majority of community servers have disabled the in-game votekick due to continued abuse from players who have used the tool to ban other players for various reasons. The consequences of disabling it have prevented this type of griefing, however, it has allowed that, in cases where the administrators are not present (no one is connected to a server 24/7), the griefers can act with impunity without the rest of players can do nothing and have to call an administrator through the communication channels that are enabled on those servers.

## Solution

The proposed solution would be to add a cvar that could be called `sv_vote_issue_trusted_kick` whose possible values would be: `0` (zero, any player can use votekick) or `1` (one, only certain players can start votekick). This Cvar would only work when the cvar `sv_vote_issue_kick_allowed` is `1`. The list of players who can use votekick must be decided by each server owner based on their own criteria. This list must consist of a plain text file in which each line will contain the Steam ID of each player. The Steam ID format used (`STEAM_0:0:11101`, `[U:1:22202]` or `76561197960287930` formats) will be the one that is easiest to implement. The list can be called `trusted.cfg` and can be placed in the cfg folder within the nmrih folder. If the file is empty or does not exist, two behaviors could be assumed: leave votekick activated but not allow anyone to vote or the server would automatically change the cvar `sv_vote_issue_kick_allowed` to `0` (zero).

## Expected consequences

Griefers who abuse votekick won't abuse anymore, however, certain players would be allowed to ban other griefers without giving them an admin role.

## Logs

In the event that these trusted players stop being trusted and in order to verify any abuse that is done on the server, it should be implemented that if the votekick is active and no one can initiate that vote, it should be recorded in the game logs. who initiated that vote and who voted yes or no.

**Comment by lobo-web** [comment]
I close this because no answer from devs
