### ISSUE TITLE
[public-1.13.3] Firing arrow projectile to the 556 ammo box breaks physics

### ISSUE THREAD

**Issue by clague** [nmrih/source-game#1455]
When you stand on the 556 ammo box then use a bow shooting on it several times (not sure how many times), then pick up the 556 ammo box. The Server can have wrong physical behavior, such as everything you throw will pass through the ground, and then crash. 
Here is a test video in local listen server:

https://github.com/nmrih/source-game/assets/93119153/5a145f38-2ad5-49cc-a9f6-0c4777767e97

Besides, It will spam error log on the server console like
```
Ignoring unreasonable position (2732.352051,689.635498,-70772.039063) from vphysics! (entity projectile_arrow)
Ignoring unreasonable position (2732.352051,689.635498,-78076.132813) from vphysics! (entity projectile_arrow)
Ignoring unreasonable position (2732.352051,689.635498,-85380.234375) from vphysics! (entity projectile_arrow)
Ignoring unreasonable position (2732.352051,689.635498,-92698.937500) from vphysics! (entity projectile_arrow)
*** ERROR *** Excessive sizelevel (5637) for element
*** ERROR *** Excessive sizelevel (5638) for element
*** ERROR *** Excessive sizelevel (5639) for element
*** ERROR *** Excessive sizelevel (5640) for element
*** ERROR *** Excessive sizelevel (5641) for element
*** ERROR *** Excessive sizelevel (5642) for element
*** ERROR *** Excessive sizelevel (5643) for element
```
And here is a dump file: 
[crash_nmrih.exe_20231201011259_1.dmp](https://github.com/nmrih/source-game/files/13515862/crash_nmrih.exe_20231201011259_1.dmp)

**Comment by felis-catus** [comment]
Fixed in src-r7213.
