### ISSUE TITLE
[public-1.13.4] Glow disappearing while client gets close and then move away from some entities

### ISSUE THREAD

**Issue by Mart-User** [nmrih/source-game#1456]
Entities with the "Glowable" class like melee weapons lose their glow configs when a player cames near of the item, enabling the +use function / becoming green, and move away.

Steps to reproduce
- create a local server
- console input
- sv_cheats 1
- aim at a not too close distance
- console input:
- ent_create me_fubar targetname test glowable 1 glowcolor 255 glowdistance -1
- go close to the weapon
- now move away

The glow, once red, disappeared.

**Comment by felis-catus** [comment]
Fixed in src-r7295.
