### ISSUE TITLE
[public-1.13.4] Weapons have their glow (when enabled) fixed as "red" color.

### ISSUE THREAD

**Issue by Mart-User** [nmrih/source-game#1457]
Weapons have their glow (when enabled) fixed as "red" color.

Steps to reproduce

create a local server
console input
sv_cheats 1
aim at a not too close distance
console input:
ent_create item_inventory_box glowable 1 glowcolor "255 255 255" glowdistance -1
now again, console input:
ent_create me_fubar glowable 1 glowcolor "255 255 255" glowdistance -1

The glow for me_fubar is supposed to be white but show as red, while the item_inventory_box respects the color and show as white.

The behavior is the same even using the SetGlowColor input.

**Comment by felis-catus** [comment]
Fixed in src-r7296.
