### ISSUE TITLE
[public-1.13.4] Switching to a grenade after checking ammo in a shotgun will display -1 as the ammo being held

### ISSUE THREAD

**Issue by Jenoxen** [nmrih/source-game#1460]
As seen in this video, When you hold a shotgun, Check it's ammunition by holding R and then release 1 to select the grenade, It'll display the grenade name and icon followed by "-1 1" in the ammo counter. I've included in the video a live key overlay so it's replicable. Also when switching back to the shotgun the character will yell out the correct ammo count in the shotgun and not the grenade.
This bug seems to work with all grenades but was shown with a Molotov.

EDIT: Youtube link because sony vegas rendered it wrong and this video cannot be seen in Firefox. [Video](https://youtu.be/51XQ-grAiPU)

https://github.com/nmrih/source-game/assets/70504084/34034d52-0098-4472-80c5-fb8190d888e7

**Comment by felis-catus** [comment]
Fixed in src-r7348.
