### ISSUE TITLE
[Public 1.13.4] NMS_Arpley: Dropped items can block the Train and the Extraction Zone

### ISSUE THREAD

**Issue by CptHaxray** [nmrih/source-game#1461]
Unfortunately do not have a video on hand and I was unable to recreate it solo. I've seen the NMS_Arpley Extraction train get blocked by piles of guns/ammo on the rails near where it arrives. This also seems to prevent the extraction zone from being enabled, resulting in the map getting softlocked and no one being able to extract.

**Comment by AtheistNMRiH** [comment]
this should be already fixed in r9939
