### ISSUE TITLE
[dev-1.13.5] Missing inventory box background until item_inventory_box spawns

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1462]
Repro:
- Issue `sm_inv` or fire `ItemBoxOpen` some other way without spawning a supply crate first

The supply crate UI will have no background. After spawning an actual supply crate, the background will render

![image](https://github.com/nmrih/source-game/assets/11559683/ded78793-f5c7-4d68-add3-07b76c301711)

Code:
```cpp
#include <sourcemod>

public void OnPluginStart()
{
	RegConsoleCmd("sm_inv", Cmd_Inv);
}

Action Cmd_Inv(int client, int args)
{
	client		= 1;

	Handle	msg = StartMessageOne("ItemBoxOpen", client, USERMSG_RELIABLE | USERMSG_BLOCKHOOKS);
	BfWrite bf	= UserMessageToBfWrite(msg);
	bf.WriteShort(1337);

	for (int i = 0; i < 20; i++)
	{
		int id = GetRandomInt(1, 67);
		bf.WriteShort(id);
	}

	EndMessage();

	return Plugin_Handled;
}
```

**Comment by dysphie** [comment]
Additionally it will open the wrong background afterwards for `ItemBoxOpenUncategorized`

![image](https://github.com/nmrih/source-game/assets/11559683/da4ab528-4c73-4792-af04-e6a4f0587058)

**Comment by felis-catus** [comment]
Fixed in src-r7367.
