### ISSUE TITLE
[Feature Request] Proper deactivation and reactivation feature of safezones

### ISSUE THREAD

**Issue by Acrilyk** [nmrih/source-game#1467]
It would be useful if we can have the functionality for safezones to be deactivated and reactivated properly. But the best way would be to make separate functions for this functionality, since some maps might rely on Deactivate and Reactivate already.

The functionality could be as follows: when deactivated, safezones cannot be overrun, their % is saved, and they appear as such in the HUD:

ZONE A: INACTIVE, etc.

Upon reactivation, their percentage is restored and they function as normal.

**Comment by felis-catus** [comment]
Added in src-r7634; `func_safe_zone` inputs `PauseDrain` and `ResumeDrain`, and HUD status for inactive zones.
