### ISSUE TITLE
[public-1.13.5] Invisible zombies and spectators being able to be seen

### ISSUE THREAD

**Issue by DabPenBen** [nmrih/source-game#1470]
If you are on wifi or have low bandwidth and your game starts to lag due to network issues not game issues like stuttering. Theres a chance that a zombie will be completely invisible make no sound and kill you or you will see spectators flying inside of you or free camming around you depending on their spectator mode

**Comment by felis-catus** [comment]
Possibly related to #1413.

**Comment by DabPenBen** [comment]
Would like to add a comment to this due through more experimenting. Zombies that are spawned in and if you go around a corner where zombies are culled? If you drop a couple packets and go around that same corner there is a chance not always but  a chance that zombie will be completely invisible. Dropped about 3 packets shown on netgraph. They do however make growling noises but have no shadow no model and are basically completely invisible.

**Comment by felis-catus** [comment]
Duplicate of #1413
