### ISSUE TITLE
[public-1.13.5] "trigger_progress_use" and "trigger_progress_weapon" "!activator" don't work

### ISSUE THREAD

**Issue by Dexter3pl** [nmrih/source-game#1473]
"trigger_progress_use"
"OnUse" work
"OnTrigger" work
"OnEndUse" don't work

"trigger_progress_weapon"
"OnUse" work
"OnTrigger" work
"OnEndUse" don't work

![trigger_progress_use](https://github.com/nmrih/source-game/assets/171151950/3804e18b-be31-44a0-bf96-e780b244aca8)

**Comment by felis-catus** [comment]
Fixed in src-r7561.
