### ISSUE TITLE
[public-1.13.5] Zombie AI aggro issues

### ISSUE THREAD

**Issue by DabPenBen** [nmrih/source-game#1475]
![why](https://github.com/nmrih/source-game/assets/170909348/30a730fb-d270-424f-bf5d-3f0aa44bf3e5)

Any chance you could add this as a server cvar instead of it being hardcoded? When playing with experienced players all spread about speeding up map progress it can make parts too easy or too boring on most maps having ai that wanders around like you don't exist. And if a zombie does notice you it's only 1 zombie that will aggro on you. Also I've noticed that there's no dead or alive player check for this proximity thing. It takes spectators into consideration as well when doing these zombie ability checks. Meaning that if a player is alone somewhere on the map casually walking through a horde of blind zombies then you swap to them you'll notice that all of the sudden every zombie around that player finally notices them and will actually aggro usually killing them due to the unexpected aggro.

**Comment by felis-catus** [comment]
This change is used for melee attacks, not aggro, what you're describing appears to be a separate issue and it is not intentional. Do you have a map or a section where this could be reproduced more consistently? It's difficult to notice in normal gameplay.

(#1448 related?)

**Comment by DabPenBen** [comment]
Play nmo_chinatown have a player sit at spawn where you can't see them and they can't see you. Go up the stairs on chinatown after pressing the button go into the middle of the open notice how only a couple zombies will aggro on you till that other player afk at spawn gets near you or in line of sight of you to have all zombies in the area aggro on you both or just actually aggro normally.

**Comment by felis-catus** [comment]
Repro from Discord:

```
ov_spawn_per_tick 6
ov_spread_distance 25.0
sv_spawn_density 3
map nmo_chinatown
```

> Play solo, run up the stairs. You'll immediately have all zombies aggro'd to you.
> Now restart and add a single bot. They'll take a lot longer to aggro now. Its very noticeable. Apparently spectators in free cam affect it as well.

**Comment by felis-catus** [comment]
Fixed in src-r7639.
