### ISSUE TITLE
[public-1.13.5] nmo_rockpit softlock wooden planks can be destroyed and unrecoverable using a modified powerful melee

### ISSUE THREAD

**Issue by sys-arch** [nmrih/source-game#1477]
On the map, after opening the door with the welder, there are times when the second objective is to place some wooden boards because the floor is electrified.

EDIT: If you change some cvars so that some melee (like the flashlight) does a lot of damage (for example `sv_maglite_melee_factor "99999999999"`) the board breaks and is unrecoverable because it does not respawn and don't let continue because there is a invisible wall that only dissapear if you put a plank.

It is only recoverable if you use Dysphie's "NMO Guard" plugin.

**Comment by sys-arch** [comment]
I add a demo as proof
[rockpit_plank.zip](https://github.com/user-attachments/files/15522407/rockpit_plank.zip)

**Comment by AtheistNMRiH** [comment]
I don't think that it can be considered as a bug, current board's min damage to hurt is 9999, in vanilla gameplay you can't reach that damage, it is the same that if server will change player's gravity and let him jump very high, he could jump over some fence and bug a potential map, mapper created a map with idea in mind that player can't jump very high or deal 999999999 damage

**Comment by sys-arch** [comment]
> I don't think that it can be considered as a bug, current board's min damage to hurt is 9999, in vanilla gameplay you can't reach that damage, it is the same that if server will change player's gravity and let him jump very high, he could jump over some fence and bug a potential map, mapper created a map with idea in mind that player can't jump very high or deal 999999999 damage

Russian friend, I appreciate your opinion. However, I have to reject your point of view. Even if you mention that there is a minimal probability, it should be solved to avoid, as much as possible, the possible griefing that this bug could generate. Furthermore, it would involve a minimal change, just a few lines of code, to convert those planks to non-breakable and reduce that probability to absolute zero. Prevention is better than cure.

**Comment by AtheistNMRiH** [comment]
I agree that even small bugs must be fixed (I fix them by myself, and unfortunately this is not just few lines of code, you need to recompile whole map again (sometimes it takes to 30-40 minutes), rebuild cubemaps, commit it and etc), but my point is that bug isn't "minimal probability", it just can't happen in normal gameplay, because this is plugin issue, something, that mapper can't predict or handle. There are plenty of other maps with such board mechanic, and they were created in mind, that there is zero chance of 99999999 damage to happen

**Comment by felis-catus** [comment]
Closing due to modified game (issue was renamed to state that fact and I didn't notice before triaging).
You can use maphacks to tweak properties on your server without recompiling the map: 
https://developer.valvesoftware.com/wiki/Maphack_Fundamentals
