### ISSUE TITLE
[public-1.13.5] Arrow Entities Being Incorrectly Removed

### ISSUE THREAD

**Issue by mostten** [nmrih/source-game#1479]
The arrow entities have a significantly restricted trajectory. An error occurs wherein these projectiles are prematurely removed from the game environment when they surpass their intended range by even a small margin. This bug results in the failure to inflict damage on target zombies, thereby impeding gameplay progression.

https://github.com/nmrih/source-game/assets/5262327/84921c84-0164-4e76-9226-6bc23cf9c027

**Comment by felis-catus** [comment]
This was fixed in src-r7555.
