### ISSUE TITLE
[Feature Request] More possibilities for SetShootSoundOverrides

### ISSUE THREAD

**Issue by TsukasaSato1** [nmrih/source-game#1480]
Perhaps SetShootSoundOverride can be used to support more than just "Weapon_1911.Single", but more like "voice/command/default/taunt4.wav"?

**Comment by felis-catus** [comment]
Raw filenames require separate logic, and it's complicated to add support for an existing system that expects scripted entries.

The `SetShootSoundOverride()` function is designed to be used in conjunction with `custom_soundscripts` which are located in the scripts directory, these can be shipped with an add-on, map, mutator, etc. 
You can create .txt files in that directory, each file is loaded and its entries are included, see `weapons_soundscripts` for examples.

Closing.
