### ISSUE TITLE
[public-1.13.5] Broken Center-Bottom HUD Messages

### ISSUE THREAD

**Issue by botky** [nmrih/source-game#1484]
sm_hsay | basechat | chat | <message> | Sends a message to all players via a center-bottom hint box.

For example, using sm_hsay won't display any text, only a empty gray box.

First time I noticed this, was because of RTV plugin. It used to display a message in that center-bottom area. Now it's just a gray box.
Probably broken because of the font change.

![image_2024-06-07_161506715](https://github.com/nmrih/source-game/assets/98295934/2afeb41e-9255-40f0-bbef-8dd473b98f88)

**Comment by sys-arch** [comment]
Mentioned the same problem in https://github.com/nmrih/source-game/issues/1472

Is a plugin issue.

**Comment by botky** [comment]
Don't mind the RTV plugin, but "sm_hsay" won't display any text in that area. What does that mean ? basechat.smx suddenly has a problem ? I doubt it

**Comment by F1F88** [comment]
> Mentioned the same problem in #1472
> 
> Is a plugin issue.


I believe this issue is not related to the plugin. 
Here is an example from my test:

```
public void OnPluginStart()
{
    RegConsoleCmd("sm_test", CB_TestHint);
}

Action CB_TestHint(int client, int args)
{
    PrintToServer("===== Test Hint =====");
    PrintToChatAll("===== Test Hint =====");
    PrintHintTextToAll("TestHint");
    return Plugin_Handled;
}
```


![test](https://github.com/nmrih/source-game/assets/66011476/a162c47d-37b5-4b84-b143-8e6b29cb24b1)

[testHint.zip](https://github.com/user-attachments/files/15924556/testHint.zip)

**Comment by felis-catus** [comment]
Fixed in dev-r10043.
