### ISSUE TITLE
Lighter flame particle not rendered over world geometry

### ISSUE THREAD

**Issue by ProtoM0J0JOJO** [nmrih/source-game#1488]
Not sure whether this classifies as a bug or oversight. The lighter first person viewmodel is rendered over geometry when equipped, but not the attached flame particle, clipping into the wall when up close.

**Comment by felis-catus** [comment]
Closing, this is a fairly insignificant visual bug. Due to how viewmodels function, investigating and implementing a fix may require more work than anticipated.
