### ISSUE TITLE
[Feature Request] Add WebM support for startup vids

### ISSUE THREAD

**Issue by GoreTechGit** [nmrih/source-game#1490]
If it's not too difficult to implement, add webm support for startup vids, for modding purposes.

The main reason is that encoding the currently supported formats is a hassle, as shown in https://developer.valvesoftware.com/wiki/Startup_Media#Startup_Videos

AVI format is barely supported, and when it does you need to encode it with an obscure codec from the 90s. Not to mention that AVI's in general are barely used nowadays.

With BIK you need a proprietary tool to encode a video (sure the tool itself is free, but its use has licensing involved), and even then it only accepts AVI videos according to https://developer.valvesoftware.com/wiki/WebM

In that same article, they mention that WebM does a better job at compressing videos than BIK. It's also a lot easier to encode WebM videos, especially with VLC or Blender.

I think it wouldn't hurt to be able to include WebM videos at startup. That being said, I wouldn't mind if you'd rather implement other formats like MP4 or MKV instead. WebM was just an example since it's been implemented on a couple of other Source branches before.

**Comment by felis-catus** [comment]
Closing as out of scope. While this would be nice to have, implementing WebM support requires a significant amount of work and we aren't using startup videos to begin with.
