### ISSUE TITLE
[Feature Request] Official servers settings and griefing prevention

### ISSUE THREAD

**Issue by DepressedWalker** [nmrih/source-game#1492]
Please consider adding an option to vote for a change of a current map on official servers. There is only an option to vote for next map and when you finish the current map quickly, you are doomed to play the same map over and over again. A situation where 8 of us wanted to play objective map happened recetly and the map changed to survival and even though we commited suicide over and over again, the map didn't change and people left.

Additionally, could I please ask if it would be possible to turn on the setting so that people who are alive can see the chat of people who are dead?

Also met lots of people on different servers who are joining just to hold/hide the items which are needed for the tasks and sabotage others. Some servers have plugins (!votekick). Would you consider something like that to return back to the game? For example, a threshold could be set that at least 75% of people would have to vote.

**Comment by felis-catus** [comment]
Thank you for contributing. Please note that this issue tracker is for problems that affect the game out of the box, as software maintainers we can't resolve inquiries on how official servers are configured.

As an admin, you can use `sv_alltalk 1` to display chat from dead players.

Regarding griefing prevention, we have existing issues open. See #1372, #1373, #1374. Closing.
