### ISSUE TITLE
Disappearing supply drops

### ISSUE THREAD

**Issue by DepressedWalker** [nmrih/source-game#1493]
Supply drops sometimes disappear even if not all items are taken out of it. I encounter situations (both singleplayer and on servers) where I want to carry away a part of a drop and when I return the same round (or a round after), it's not there anymore (while there's no one else who would take it).

**Comment by AtheistNMRiH** [comment]
iirc if you go far away from supply drop it disappears, I thought it is intentional

**Comment by felis-catus** [comment]
Not a bug. Survival mode expires supply drops on new wave by design.
