### ISSUE TITLE
[public-1.13.6] Crash when generic_actor spawns with empty "model" keyfield

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1494]
User error but shouldn't crash

Stack: 
server.dll + 0x130066 <- Studio_GetMass
server.dll + 0x62c7d <- CAI_BaseNPC::SetupVPhysicsHull
server.dll + 0x18df09 <- CAI_BehaviorHost<CAI_BaseNPC>::NPCInit
server.dll + 0x266127
server.dll + 0x1a56f8
server.dll + 0x1a50ea

https://crash.limetech.org/hp7qixd64gv7

**Comment by felis-catus** [comment]
Fixed in src-r7612.
