### ISSUE TITLE
[public-1.13.6] VScript: CObjectiveManager::GetCurrentObjectiveBoundary always return the same value

### ISSUE THREAD

**Issue by F1F88** [nmrih/source-game#1495]
CObjectiveManager::GetCurrentObjectiveBoundary always return the objective boundary name of the first

```
script printl("CurrentObjectiveIndex = "+ObjectiveManager.GetCurrentObjectiveIndex())
script printl("CurrentObjectiveBoundary = " + ObjectiveManager.GetCurrentObjectiveBoundary())

script printl("do CompleteCurrentObjective(\"\")")
script ObjectiveManager.CompleteCurrentObjective("")

script printl("CurrentObjectiveIndex = "+ObjectiveManager.GetCurrentObjectiveIndex())
script printl("CurrentObjectiveBoundary = " + ObjectiveManager.GetCurrentObjectiveBoundary())
```

![PixPin_2024-07-21_14-19-02](https://github.com/user-attachments/assets/f92a7c63-c3b5-4acb-9cd0-9835d1da05a6)

**Comment by felis-catus** [comment]
Deprecated the function as it's non-functional. Replaced with `CNMRiH_Objective` functions `GetObjectiveBoundary()` (returns entity handle), and `GetObjectiveBoundaryName()` (returns boundary name) - also added `CNMRiH_ObjectiveManager` function `GetCurrentObjective()` for getting easy access to current `CNMRiH_Objective` instance.

(Resolved in: src-r7614 + src-r7615)
