### ISSUE TITLE
[public-1.13.6] Players when culled get their proximity voice stuck in one spot

### ISSUE THREAD

**Issue by DabPenBen** [nmrih/source-game#1503]
Not entirely sure how to reproduce it but sometimes when you are far away from teammates and they use a voiceline on the other side of the map and they say "help me" or "need ammo" or any other voiceline you'll hear it right in your ear or the area their voices got "stuck" even when that teammate is no where near you

**Comment by felis-catus** [comment]
Fixed in src-r7804.
