### ISSUE TITLE
[public-1.13.6] Game crash caused by prop_physics_override with collisionless model

### ISSUE THREAD

**Issue by RaymondChen2018** [nmrih/source-game#1504]
Vscript code:
local hGunDebris = SpawnEntityFromTable("prop_physics_override", 
{
	origin = hGun.GetOrigin(),
	angles = hGun.GetAngles(),
	model = hGun.GetModelName(),
	spawnflags = 644
});

This crashes the game if field "model" is set with a model that has no collision, otherwise it is fine.

**Comment by felis-catus** [comment]
Fixed in src-r7653.
