### ISSUE TITLE
[Feature Request] treesway

### ISSUE THREAD

**Issue by MAGISTER-PD2OR** [nmrih/source-game#1505]
**For custom maps and visual details:**
https://developer.valvesoftware.com/wiki/$treesway
There env_wind + treesway in material looks perfect but not works with nmrih.

**Example material:**
"VertexLitGeneric"
{
	"$basetexture" "grass69/grass69"
	$alphatest 1
	$nocull 1
	$model 1
	$treesway 1
	$treeswayheight 128
	$treeswayradius 300
	$treeswaystartradius 0,1
	$treeswayspeed 1
	$treeswaystrength 10
	$treeswayscrumblespeed 0.1
	$treeswayscrumblestrength 0.1
	$treeswayscrumblefrequency 0.1
	$treeswayfalloffexp 1.5
	$treeswayscrumblefalloffexp 2
	$treeswayspeedhighwindmultipler 1
	$treeswayspeedlerpstart 3
	$treeswayspeedlerpend 6
}

Alternative custom model with animations but not looks perfect.

**Comment by felis-catus** [comment]
As with #1442, this was attempted during 1.12 development, but due to a restriction on how engine handles default shaders (we can't override VertexLitGeneric), it was cut last minute, and will unfortunately stay that way with our current technical limitations.

**Comment by felis-catus** [comment]
Included in 1.15 as part of the SDK upgrade.
