### ISSUE TITLE
(nmo_broadway) Gascan spawning inside shelf

### ISSUE THREAD

**Issue by Wazanator** [nmrih/source-game#151]
This gascan is spawning inside the shelf at the beginning of broadway 
![nmo_broadway0001](https://f.cloud.github.com/assets/2752911/628056/5e8da708-d078-11e2-8c87-06eb7b50f8ef.jpg)

**Comment by AtheistNMRiH** [comment]
there is no more spawner there, looks like it was deleted in previous versions, need to be closed
