### ISSUE TITLE
[public-1.13.4] nmo_brooklyn VMF crash

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1515]
nmo_brooklyn's VMF can't be compiled with final settings because most props have `lightmapresolutionx` and `lightmapresolutiony` set to 0. A bunch of them are also set to insane values like `55763`.
This will likely confuse the maintainer unless documented or changed. They should probably be set to 32?

```
Writing leaf ambient...done
Computing static prop lighting : 0ThreadComputeStaticPropLighting: 0...
-------------------------------------------------------------------------------
Command failed with return code 0xC0000005! The program has crashed.

** Screenshot the WHOLE window when showing this compile log
** Or upload the .log file generated beside your VMF
-------------------------------------------------------------------------------
```

**Comment by AtheistNMRiH** [comment]
changed lightmapresolutionx and lightmapresolutiony values to 32 in scr-7679
