### ISSUE TITLE
[Feature Request] Medical items viemodels

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#1516]
There are animations for using items, but no for deploy, holster, idle, walk, sprint, shove and give sequences, in our case (lacking animator) would be great to implement those addons in base game

https://steamcommunity.com/sharedfiles/filedetails/?id=3092781884
https://steamcommunity.com/sharedfiles/filedetails/?id=3095368773
https://steamcommunity.com/sharedfiles/filedetails/?id=3097531251
https://steamcommunity.com/sharedfiles/filedetails/?id=3098824203

**Comment by felis-catus** [comment]
Need permission from the author first.

**Comment by felis-catus** [comment]
Added in dev-r10085 with S0kk0's permission.
