### ISSUE TITLE
[public-1.13.6] nmrih_extract_preview locks camera rotation for spectators

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1522]
Enabling an extraction camera locks all spectators at those angles permanently until they respawn or reconnect. Not sure if any specific keyvalues are causing this, so here's the full setup

![image](https://github.com/user-attachments/assets/dbdcc8fa-d4f5-4685-8b53-0e3137d0228d)
![image](https://github.com/user-attachments/assets/72808c14-251b-492c-a1e6-fa3243e93a3a)

**Comment by felis-catus** [comment]
Fixed in src-r7704.
