### ISSUE TITLE
[public-1.13.6] random_spawner_controller fails to block certain weapons

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1523]
Posting here to track a previously discussed issue. It seems like random_spawner_controller fails to block specific entities

repro
1. create a controller with all entities at 9999 count, but set the fa_fnfal to 0
2. run this debug vscript, only about 50 entries are shown and the fa_fnfal still spawns

```js
local controller = Entities.FindByClassname(null, "random_spawner_controller");
if (controller) 
{
    local spawnLimits = {};
    controller.GetSpawnLimits(spawnLimits);
    foreach(key, value in spawnLimits) printl(format("%s: %d", key, value));
}
```

**Comment by felis-catus** [comment]
Fixed in dev-r10099.
