### ISSUE TITLE
[public-1.13.6] nmo_dimension_time_b3_fixed broken since update 1.13

### ISSUE THREAD

**Issue by rtxa** [nmrih/source-game#1527]
## Description

[nmo_dimension_time_b3_fixed](https://steamcommunity.com/sharedfiles/filedetails/?id=2489653968) crashes as soon `obj16_approachTrainstation` objective starts. I tried to isolate the crash with this [MapHack](https://pastebin.com/i7FkcM0u) but I couldn't get to anywhere. If you disable the player teleport to the new train section, the whole scripts works as expected, the problem is the train, you can't touch it or get inside of it, if you do, expect crash.

I found that the maps works fine in [version 1.12.3 released on 5 July 2022](https://steamdb.info/patchnotes/9065150/)  and gets broken on [update 1.13 released on 31 October 2022 (Hell-o-ween Hellapalooza)](https://steamdb.info/patchnotes/9833229/).

You can download the old versions to test it by yourself using [DepotDownloader](https://github.com/SteamRE/DepotDownloader) with the next commands:

```
// depot 224261 is game content
// depot 224262 is Windows binaries

// Version 1.13 October 31th 2022  (NMRiH Hell-o-ween Hellapalooza) Crash
DepotDownloader.exe -app 224260 -depot 224261 -manifest 6471653382930610480 -username <your-steam-username> -password <your-pass> -remember-password
DepotDownloader.exe -app 224260 -depot 224262 -manifest 2841920879353153407 -username <your-steam-username> -password <your-pass> -remember-password

// Version 1.12.3 July 5th 2022 works here
DepotDownloader.exe -app 224260 -depot 224261 -manifest 8897570433187612811 -username <your-steam-username> -password <your-password> -remember-password
DepotDownloader.exe -app 224260 -depot 224262 -manifest 5718283844259344983 -username <your-steam-username> -password <your-password> -remember-password
```

## How to reproduce

1. Start the map (Have enabled `sv_cheats 1`, `developer 1` and `sv_practice_transtime 0` already)
2. Press E into dead body chalk outlines to remove annoying fog.
3. Use `setpos 2680 -263 -838` to go to the train station.
4. Use `script ObjectiveManager.StartNextObjective()` many times until you get to objective _"Use the clockwork to travel through time"_
5. Travel to date October 19th so the train gets visible. (I suggest using `host_timescale 4` because the crank is too slow)
6. Skip objectives until you get to _"Clockwork is now spinning, board the train"_ and board the train (Use `noclip` to go through the fences).
7. Wait until the train leaves the station and expect crash.

## Video reproducing the crash
[![YouTube](http://i.ytimg.com/vi/XnH2Fcgk8bI/hqdefault.jpg)](https://www.youtube.com/watch?v=XnH2Fcgk8bI)

I tried to fix this my self, but considering the complex logic of the map and not having any logs or way to attach a debugger to see why is crashing, makes this task almost impossible to me. I hope someone can take a look to this. Thank you very much!

**Comment by felis-catus** [comment]
Fixed in src-r7756.
