### ISSUE TITLE
How can i get "_zombiesLeft" and "_waveNumber" and "_resupplyParity"?

### ISSUE THREAD

**Issue by TsukasaSato1** [nmrih/source-game#1528]
How can i get "_zombiesLeft" and "_waveNumber" and "_resupplyParity"?

**Comment by felis-catus** [comment]
I assume this is for the `wave_status` entity, these variables are NetProps, and be retrieved with VScript via `NetProps.GetPropInt(ent, "_waveNumber")` where `ent` is a handle to the entity, or SourceMod by using its equivalent functions.

Please note, this GitHub tracker is for reproducible issues, questions can be asked in the Discord channel (you can ping @ felis in #nmrih1-custom-content), or you can send me an email. Closing.
