### ISSUE TITLE
Black screen on linux mint 21.3 with proton experimental when launching nmrih2

### ISSUE THREAD

**Issue by justinian444** [nmrih/source-game#1529]
I see a loading circle then a black screen with a red cursor but nothing else. I also don't hear any sound. The game is unplayable because of this.

**Comment by felis-catus** [comment]
This issue tracker is for the first game, closing.

**Comment by Smil3yRiley** [comment]
> Where do I post it then? I don't see a github page for the second game.

https://discord.com/channels/211900829307895819/1298096121121472593

As for the issue itself it’s currently being tracked internally, thank you for the report
