### ISSUE TITLE
[public-1.14.0] Voting messages display cut-off messages in Spanish (and possibly other languages)

### ISSUE THREAD

**Issue by Holycrapjimhox** [nmrih/source-game#1530]
![image](https://github.com/user-attachments/assets/a25cbe0f-f5f0-4748-9282-d9d720745555)
The upper portion of the voting notifications that are displayed after a voting action is performed or at least attempted seems to cut off the text. It should first allow for longer sentences on one single line to accommodate more languages, and then if a second line is used, it should display the text without cut-offs.

**Comment by Holycrapjimhox** [comment]
Another example:
![image](https://github.com/user-attachments/assets/2aa612cc-cde4-4e29-bf85-acc4d8c018eb)

The cut-off word is "votación".

**Comment by felis-catus** [comment]
Fixed in dev-r10125.
