### ISSUE TITLE
[Feature Request] Change "PLAYER LIST" button to "MUTE PLAYERS" in English

### ISSUE THREAD

**Issue by Holycrapjimhox** [nmrih/source-game#1531]
![image](https://github.com/user-attachments/assets/95b21e49-dea1-4e7e-9a2c-f028021cccab)

The "PLAYER LIST" button in the main menu doesn't describe the menu's purpose at first glance. Since the menu's only function is to mute players (as a player list can be more intuitively accessed by holding TAB in a server), it should be changed to "MUTE PLAYERS" so that newer players can easily tell what it does at first glance.

**Comment by felis-catus** [comment]
https://github.com/nmrih/nmrih-localization-files/commit/0271188078eae9d1b321377c34731a6c761535d0
