### ISSUE TITLE
[public-1.14.0] Transparent board models persist outside of building mode.

### ISSUE THREAD

**Issue by Holycrapjimhox** [nmrih/source-game#1532]
https://github.com/user-attachments/assets/a8cc2e59-c51e-49af-8a67-43b37cf20757

Found by durkhaz. The transparent board model that indicates where you can place a board will continue to be visible when exiting building mode as a result of running out of boards. If you manually exit this mode via right click when having boards, this does not occur.

**Comment by felis-catus** [comment]
Fixed in src-r7739.
