### ISSUE TITLE
[public-1.14.0] Game is constantly being minimized

### ISSUE THREAD

**Issue by sys-arch** [nmrih/source-game#1535]
I have a problem with No More Room in Hell (1 not 2), when game is executed in fullscreen mode, starting to minimize and loads Shop (Steam Client), i press game again and another time minimize and shows Steam Client with Shop again but these time says there was a problem with **SteamComponent UI** or something like that and recommends me restart Steam.

Other game that gave this kind of problem is a game called [**XII - Classic**](https://www.pcgamingwiki.com/wiki/XIII) but is an old game (from 2003). I firmly believe that if this happens in some games and not in others, it is because there is something implemented that does not work well in the latest versions of Steam.

**Comment by felis-catus** [comment]
Unable to repro, can you post your system information? (Prefer output from `nmrih_support_helper` console command in-game)

**Comment by sys-arch** [comment]
Here is the information, @felis-catus 

Operating System:
Windows 10 (Build: 19045) - Version 10.0

CPU Information:
ID: GenuineIntel
Cores: 8
Speed: 2.81GHz

Graphics Driver Information:
Name: NVIDIA GeForce GTX 1050 Ti
Version: 23.21.13.8816
DXLevel: 95 (max: 95)
VendorID: 0x10de
DeviceID: 0x1c8c
SubSys: 0x120b1462
Revision: 0xa1

Display Mode:
Resolution: 1920x1080
Refresh Rate: 120Hz
Windowed: 1

NMRiH Specific Information:
Screenspace Effects: 1
Depth of Field: 0
Lens Flare: 0
Film Grain: 0
SSAO: 0

Misc. Information:
Game Version: 1.14.0
HDR Level: 0
Specularity: 1

PD: CPU Information is bad. Correct one is: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz   2.80 GHz

**Comment by felis-catus** [comment]
Steam web helper might be crashing, tagging issue as such.

**Comment by felis-catus** [comment]
Unable to repro at all with different setups, closing as a local issue.

**Comment by sys-arch** [comment]
This is totally wrong. It's not a "local issue" because there are other players who have this problem and seeing that the developers ignore it here, they have had to resort to other social networks and forums to find a solution. I searched on Google.

**Comment by felis-catus** [comment]
From the code maintainer's point of view, I have no method to reproduce this issue, which means I'm unable to debug it, write a potential fix for it, let alone test it. Hence why I closed the issue as "local", there's nothing I can do from here to resolve it.

If the posts you found on Google have repro steps or any hints that could help track down this problem, please link them here.
