### ISSUE TITLE
[public-1.14.0] nmo_cod_verruckt_v2 crashes when someone alive disconnects

### ISSUE THREAD

**Issue by rtxa** [nmrih/source-game#1539]
[nmo_cod_verruckt_v2](https://gamebanana.com/mods/145002) is broken since [update 1.13 (Hell-o-ween Hellapalooza)](https://steamdb.info/patchnotes/9833229/) due to the new feature that kills a disconnecting player before they exit the server. This can be workarounded by changing `sv_kill_player_on_disconnect` to `0`, but of course, not everyone knows this and it took some time to figure out this was the reason. Perhaps this can be easily fixed.

## How to reproduce

1. Start the map on a dedicated server
2. Disconnect and expect crash.

**Comment by felis-catus** [comment]
Fixed in src-r7760.
