### ISSUE TITLE
[public-1.14.0] Chainsaw can be charged to deal extra damage

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1543]
Reported on the [forums](https://steamcommunity.com/app/224260/discussions/0/7264963996316365826/), the saw uses its charge length when dealing damage with the blade, repro:

1. Use the saw normally, it should deal 65 damage.
2. Stop, hold mouse1 for a few secs to charge, release, then turn it back on.
3. You'll now deal anywhere from 100 to 500 damage

https://github.com/user-attachments/assets/ff8fb39b-4e49-489d-b6b7-5133eff6df64

**Comment by felis-catus** [comment]
Fixed in src-r7771.
