### ISSUE TITLE
[public-1.14.0] Held props can confuse zombie AI

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1544]
Originally reported to me by 'jackie': Zombies can be made to stop attacking or see you as unreachable if you hold a melee weapon (any prop?) in front of them at the right angle

Video (skip to 0:20):

https://github.com/user-attachments/assets/eeda4297-3d95-4d4e-8305-9217c24d199c

**Comment by felis-catus** [comment]
Fixed in src-r7781.

**Comment by dysphie** [comment]
Is this a straightforward fix? I'd like to patch it in the current build with a plugin
