### ISSUE TITLE
[public-1.14.0] Particle precipitation overextends and overrides others

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1545]
func_precipitation volumes w/ particles extend far beyond their defined min/max and override all other func_precipitation in the level.

repro VMF with a distant snow particle precipitation that overrides the rain around the player
[precipbug.zip](https://github.com/user-attachments/files/17804147/precipbug.zip)

**Comment by felis-catus** [comment]
Fixed in src-r7772.
