### ISSUE TITLE
[public-1.14.0] VScript: GetNavAreasInRadius returns inaccurate results

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1546]
Not sure if the issue is with the base method or the binding, but the script meant to find areas near the player appears to be wildly inaccurate, returns faraway areas and skips nearby ones. Simple test script:

```c
local player = EntIndexToHScript(1);
local origin = player.GetOrigin();

local startNavs = {};
NavMesh.GetNavAreasInRadius(origin, 100.0, startNavs);

foreach (key, value in startNavs)
{
    debugoverlay.Text(value.GetCenter(), "X", 10.0);
}
```

You can fly around the map and the results won't change either

**Comment by felis-catus** [comment]
Fixed in src-r7775.
