### ISSUE TITLE
[Feature Request] "modeloverride" keyfield for weapons

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1547]
Weapons support many overrides via keyfields but the world model one still needs a manual SetWorldModelOverride vscript call. Would be handy if keyfields also handled it (along with viewmodel and sound overrides for completeness? dunno)

**Comment by felis-catus** [comment]
Added in src-r7807 as `viewmodel_override` and `worldmodel_override`

![image](https://github.com/user-attachments/assets/9a21596c-279e-4fa6-a2de-5c792ca8c6a5)
