### ISSUE TITLE
is server's steamdll outdate?

### ISSUE THREAD

**Issue by h15588** [nmrih/source-game#1549]
Server can't download workshop item after use `app_update 317670 validate` in steamcmd.Able to download workshop item after use DLLs in "Steamworks SDK Redist"(id:1007) overwrite DLLs in "No More Room in Hell Dedicated Server\bin"(my english is poor,sorry)

**Comment by felis-catus** [comment]
Unable to repro on Windows (tested Steam Stable + Beta) and Linux dedicated servers, can you post the error message?

**Comment by h15588** [comment]
if unable to repro maybe just something wrong in my server.server just report: "error: workshop download failed! no connection to steam. (eresult: 3)"after use `workshop_download` ,but steamcmd able to download workshop item.
