### ISSUE TITLE
[public-1.14.0] NMRObjective crashes due to stale objective count in .nmos

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1550]
if you create a VMF with 2 objectives and then delete one, the `.nmos` file still lists `3` as the objective+extraction count, NMRObjective reads past EOF and crashes.  the opposite (vmfObj > nmosObj) also causes issues though it doesn't crash, it ignores any future objectives you add.

`ObjectiveSettingsManager::SaveSettings` naively saving the objective count:  
```csharp
writer.Write((int)(objectives.Count + extractionZones.Count));
```

example:
- corrupted `.nmos` lists 41 objectives and crashes
  ![image](https://github.com/user-attachments/assets/c3043776-0203-4ebb-b8c4-4aa0face27a3)  
  ![image](https://github.com/user-attachments/assets/80fcaa6e-588b-43ae-8e39-f43fd7c4e6be)  

- after it's bytepatched to 40, loads without issue.  
  ![image](https://github.com/user-attachments/assets/e5a2a538-1c08-4ea0-a42f-7cb88b41761c)  
  ![image](https://github.com/user-attachments/assets/9f20f9c8-4acb-4395-8867-87ab34ffd022)

**Comment by felis-catus** [comment]
Fixed in src-r7830.
