### ISSUE TITLE
[public-1.14.0] Improper collision for weapons with worldmodel override

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#1553]
Weapons with worldmodel overrides don't update their collision box correctly.
Example: setting a kit knife to `w_me_sledge.mdl` makes it clip into walls. It's worse with rotated models.

Pics, with proper physics props on the side for comparison:

![image](https://github.com/user-attachments/assets/132fd6f7-8bd5-4af0-98ed-afb5a76f4d44)

![image](https://github.com/user-attachments/assets/76f4e833-8067-4e90-99b1-b0126f3a84da)

**Comment by felis-catus** [comment]
Fixed in src-r7844.
