### ISSUE TITLE
sv_zombie_torso_health not working

### ISSUE THREAD

**Issue by VoxiomOfficial** [nmrih/source-game#1555]
https://developer.valvesoftware.com/wiki/List_of_No_More_Room_in_Hell_Console_Commands

In-game console does not recognise `sv_zombie_torso_health` (Unknown command: `sv_zombie_torso_health`).

**Comment by dysphie** [comment]
Zombie torsos were an obsolete entity that no longer exists, so the cvar was removed as it served no purpose. The wiki is maintained by random people and doesn't always reflect the current state of the game. Closing as it's out of scope / not a game issue
