### ISSUE TITLE
Broadway door grief spot.

### ISSUE THREAD

**Issue by Keldorn074** [nmrih/source-game#157]
If this shop glass door at the diner is closed on you while entering and someone is pushing you back outside at the same time  will cause you to become stuck inside the collision of the fence around the door frame. Then the door will remain stuck and stop responding to +use. Glitch seen in 1.06 public build.

![2013-06-12_00004](https://f.cloud.github.com/assets/3848484/640952/f7855954-d318-11e2-81a2-152d5196d370.jpg)
![2013-06-12_00001](https://f.cloud.github.com/assets/3848484/640955/fd75c588-d318-11e2-92b3-d5eed0772a3b.jpg)

Yes Jello has trolled successfully with the door.
![2013-06-12_00002](https://f.cloud.github.com/assets/3848484/640956/0366e22e-d319-11e2-91fe-47cf8f32a6ef.jpg)

**Comment by AtheistNMRiH** [comment]
couldn't reproduce it, if we will get testers, they should check it

**Comment by Winning117** [comment]
This glitch was when players had solid collisions with other players so it no longer applies, needs to be closed.
