### ISSUE TITLE
Radial Wheel overlaps text chat

### ISSUE THREAD

**Issue by Smil3yRiley** [nmrih/source-game#17]
As stated in the summary, if you open any of the radial wheels (inventory,voice,etc.) it'll overlap over the chat text in the game

Steps to Reproduce:

1) Spam some text in the chat window and hit enter
2) Open your inventory

**Comment by Bubka3** [comment]
Reproduced. Feedback required @felis-catus

**Comment by felis-catus** [comment]
Is this really a significant issue? It can't be fixed properly because how VGUI deals with panel transparency. We can only set the chat text element to override the radial panel, and that would make it look even worse.

**Comment by Bubka3** [comment]
No it's not. Marking as wontfix.

**Comment by Holycrapjimhox** [comment]
Fixed in dev-r8890.
