### ISSUE TITLE
(code) Player loses infection music cue after triggering extraction camera

### ISSUE THREAD

**Issue by Smil3yRiley** [nmrih/source-game#186]
If you're infected and you managed to trigger the extraction camera, when you regain control of your character you'll notice that your infection music cue has ceased playing.

---

Steps to Reproduce
1) Play an objective map (like nmo_cabin)
2) Get infected
3) Get to the objective that triggers the extraction camera and complete it

**Comment by Winning117** [comment]
Confirmed fixed in src-r4388/dev-r8772, needs to be closed.
