### ISSUE TITLE
(models) Swiveling around with M9 allows you to see the end of your arms

### ISSUE THREAD

**Issue by Smil3yRiley** [nmrih/source-game#187]
Posting this up as a reminder: if you suddenly move your mouse around while you have the M9 equipped, your First Person view will clip through the hidden bits of your viewmodel arms.

This issue is only present for the M9

---

Steps to Reproduce
1) Get an M9 (give fa_m92fs) and equip it
2) Move your mouse around in a quick fashion

**Comment by Winning117** [comment]
Confirmed fixed in src-r4388/dev-r8769, needs to be closed.
