### ISSUE TITLE
Health Crate HP Number stays @ next round

### ISSUE THREAD

**Issue by Smil3yRiley** [nmrih/source-game#20]
If you place a crate in the previous round but did not fully use it, there's a chance that the HP counter for that crate will remain in the next round

![13354420896702398682_screenshots_2012-08-25_00001](https://f.cloud.github.com/assets/3606650/213155/d1260f4c-835e-11e2-9f16-422ab206f1bf.jpg)

---

Steps to Reproduce:

1) Go to a survival map
2) Find a health crate
3) Place it in a health station boundary
4) Die (to start a new round)

**Comment by Fersigal** [comment]
![20180122220031_1](https://user-images.githubusercontent.com/11538773/35245068-a1cd0120-ffc2-11e7-87ec-7f53db3fb427.jpg)
![20180122222000_1](https://user-images.githubusercontent.com/11538773/35245069-a1f96e4a-ffc2-11e7-9554-b7fb5874bc0a.jpg)
![20180122222128_1](https://user-images.githubusercontent.com/11538773/35245070-a21567bc-ffc2-11e7-841e-3e3fc1112234.jpg)

**Comment by Bubka3** [comment]
Unable to reproduce, probably was fixed a long time ago. Tested on same map and same way as Riley.
