### ISSUE TITLE
Zombies can grab through solid dynamic props or in cutscene

### ISSUE THREAD

**Issue by Keldorn074** [nmrih/source-game#223]
Seems that zombies can eat/punch through prop_door_rotating and prop_dynamic, I noticed it in toxteth safehouse. It makes toxteth extremely frustrating in some spots to say the least.

1.07 dev build

Prop_door_rotating with Solid Vphysics:
![2013-08-01_00003](https://f.cloud.github.com/assets/3848484/896490/ff7e78ae-fadf-11e2-9a41-6b8d13124053.jpg)

prop_dynamic fence gate with Solid Vphysics parented to func_door_rotating clip brush
![2013-08-01_00001](https://f.cloud.github.com/assets/3848484/896492/03d397fe-fae0-11e2-8f30-e9ca9e6b67b2.jpg)

**Comment by Fersigal** [comment]
#356 #274

**Comment by Bubka3** [comment]
r4287

**Comment by Fersigal** [comment]
Just to correct, they could grab and attack through solid dynamic props, another example of this would be on the tables on nmo_cabin (barricaded tables)

**Comment by Bubka3** [comment]
The fix checks if anything is blocking the "path" to the player, and it wont do this anymore.

**Comment by Bubka3** [comment]
**Resolved Closure**
This issue has been closed as it has been resolved in the current dev build.
It will be available to the public in the next steam release. Thanks for reporting!

Additional comments: source r4292 self bins
