### ISSUE TITLE
M9 world model is paired up with maglite regardless if player has maglite equipped

### ISSUE THREAD

**Issue by Smil3yRiley** [nmrih/source-game#25]
Minor minor issue but if you look at a mirror (or ask a player to look at you) with your M92FS equipped with a Maglite in your inventory but not equipped alongside your gun, your weapon's world model will show that you have the Maglite equipped and in your hand.

Possibly occurs for the Ruger Mk. 3, SW686, and 1911 as well

**Comment by Bubka3** [comment]
Don't show maglite when it is not equipped with the hand gun.

**Comment by Winning117** [comment]
Screenshot for reference:
![224260_20180401011412_1](https://user-images.githubusercontent.com/15934200/38171364-34e9de50-354d-11e8-96e6-e02c130bb1fb.png)

As of src-r4388/dev-r8770 this currently affects all melee weapons and firearms that the player can equip  a flashlight with.

**Comment by felis-catus** [comment]
Fixed in src-r6239.
