### ISSUE TITLE
Extracted survivors are marked as "Dead"

### ISSUE THREAD

**Issue by 2ndClassCitizen** [nmrih/source-game#27]
Example: Let us say there is a group of survivors. Survivor A, B, and C. If survivor A and B reach the extraction point but survivor C does not, then when the game is concluded it will say "The survivors have been overrun!" and when survivor A and B who were extracted attempt to text chat, it will mark their texts as "Dead" instead of "Extracted." The same is true even if all survivors make it, when the game says "All survivors have been extracted!" it will mark their text chats as "Deceased" instead of "Extracted."

**Comment by felis-catus** [comment]
Fixed in src-r5110.
