### ISSUE TITLE
ammo loss.

### ISSUE THREAD

**Issue by Bravo81** [nmrih/source-game#271]
I had a shotgun, two in the chamber 16 in ammo.
So I dropped it, to pick up another shotgun.

I then had 2 in the chamber and 1 in ammo? But no ammo was dropped on the floor, if I picked up the old shotgun it had 2/1 as well.

Was not impressed :( Is it a decimal point error? 16 changed to 1 dropping the 6. OR just a generic thing where the new shotgun overwrote my ammo count.

**Comment by Winning117** [comment]
Confirmed fixed in src-r4388/dev-r8769, needs to be closed.
