### ISSUE TITLE
kitchen knife is sparkling when thrown at the ground 

### ISSUE THREAD

**Issue by theghost2333** [nmrih/source-game#272]
![2013-08-03_00024](https://f.cloud.github.com/assets/5095321/905599/b9130e26-fc3c-11e2-8f84-f858ebfc98cd.jpg)
![2013-08-03_00028](https://f.cloud.github.com/assets/5095321/905600/d86045b4-fc3c-11e2-90ac-510c17c12df1.jpg)
![2013-08-03_00029](https://f.cloud.github.com/assets/5095321/905601/de359a3e-fc3c-11e2-82e8-5cf5a0e99cf5.jpg)

**Comment by Fersigal** [comment]
Not really a bug, but still cool to look at

**Comment by Winning117** [comment]
It is a bug, it's not intended. Works with any melee weapons.

**Comment by Fersigal** [comment]
What does it actually bug lol, making sparky lookalike particles pop up. Damn needs to be fixed (guess bug fixing > fun). Not everything has to feel smooth and such "bugs" aren't even worth getting fixed.

**Comment by Fersigal** [comment]
Not a bug, needs to be closed

**Comment by Bubka3** [comment]
This is handled by the engine, specifically the vphysics part. Engine bugs should go on valve's tracker.
