### ISSUE TITLE
zombie ai bug 

### ISSUE THREAD

**Issue by theghost2333** [nmrih/source-game#277]
the zombie kept walking without attacking i was following him all the team and he kept walking forward non stop.

 sorry for the picture i was infected :P

![2013-08-03_00058](https://f.cloud.github.com/assets/5095321/905663/230ca8c6-fc44-11e2-997b-1597bf9ec338.jpg)

**Comment by Winning117** [comment]
I think this should be closed, I think this was patched.

**Comment by AtheistNMRiH** [comment]
not really, sometimes zombies totally ignore you (mainly runners and kids)

**Comment by Winning117** [comment]
Oh I thought he was saying it was infinitely walking in one direction.

**Comment by felis-catus** [comment]
Way too ambiguous, closing.
