### ISSUE TITLE
Refuses to change a resolution

### ISSUE THREAD

**Issue by Caffie** [nmrih/source-game#278]
I launched this today, The default resolution is pretty bad to me, so i very slowly i went into options(horizontal look-screen). Then went ot the options--> Audio, i chose the proper resolution---> apply and okay/save, but ti keeps returns to the old one, it wont' save any change i made in the options, not evne run in the window). I have no idea how to fix it.

**Comment by Winning117** [comment]
Non-reproducible issue, needs to be closed.
