### ISSUE TITLE
viewmodel switches between anims constantly

### ISSUE THREAD

**Issue by VaTTeRGeR** [nmrih/source-game#282]
Map: NotLD

viewmodels start to switch between the holster-anim/"last action before bug starts" and the actual anim, this starts randomly at some point. this is per entity and stays active even after dropping and picking it up again, the whole movement seems to become sluggy and laggy too (ping = 50 and constant).

I experienced this with the welder(after starting to weld) and the sledgehammer(after killing a zombie) and as i said, only when playing online.

**Comment by Bubka3** [comment]
**Inactivity Closure**
This issue has been closed for inactivity. If you are still experiencing this issue please reply to this issue to re-open it. If you have any additional issues please open a new issue.

For technical support, you may also post in the troubleshooting forums:
http://steamcommunity.com/app/224260/discussions/2/
