### ISSUE TITLE
Crouch Lag

### ISSUE THREAD

**Issue by Scripts18** [nmrih/source-game#283]
Happened to me a few time already, no idea what causes it, no console error, its not the ping either, also it fixes by itself after a few minutes (like 1 or 2 maximum) It makes the screen go up and down many times before it goes to the nomral crouch view. 

Note: Only happens at the start of a match (After the "stanby" and everything) 

Happened to me on the new Church survival map and also on supermarket survival map (sorry for not knowing the name of the maps)

**Comment by AtheistNMRiH** [comment]
mainly happens when you join during respawn time ( like during supply drop event), related to discussion on discord about sliding walking

**Comment by Winning117** [comment]
Same issue as (#350)[https://github.com/nmrih/source-game/issues/350], needs to be closed.
