### ISSUE TITLE
VAC Issue

### ISSUE THREAD

**Issue by ZombehKillah** [nmrih/source-game#290]
It appears that there is an issue connecting to VAC secured 1.07 server both on Linux and Windows. Attempting to connect to a VAC secured server fails with "You are in insecure mode, you must restart to connect to a secure server"

Restarting the client does not fix this issue and it appears that the only current "fix" is to run servers with VAC disabled by adding the -insecure flag to the server startline.

**Comment by Bubka3** [comment]
**Resolved Closure**
This issue has been closed as it has been resolved in the current dev build.
It will be available to the public in the next steam release. Thanks for reporting!

Additional comments: http://steamcommunity.com/games/224260/announcements/detail/1664514171173664214
