### ISSUE TITLE
Sound of second door in Chinatown map

### ISSUE THREAD

**Issue by BigBossBastard** [nmrih/source-game#294]
In chinatown map, after the first gate, upstairs turning left there is a door. The sound of this door does not works..

**Comment by AtheistNMRiH** [comment]
![nmo_chinatown0000](https://user-images.githubusercontent.com/11333747/36585303-e650ca88-18af-11e8-85b0-d2dae071f9f3.jpg)
maybe this door (and you need to turn right, not left)
if yes then it has sounds, there are no other doors, need to be closed

**Comment by ortiixx** [comment]
@AtheistNMRiH Why are you answering this after 5 years? lol

**Comment by AtheistNMRiH** [comment]
because we need to clean it all up
