### ISSUE TITLE
Med Box is Blocked

### ISSUE THREAD

**Issue by Asellia** [nmrih/source-game#297]
When placing the med box in some maps (Flood, and in the diner in uh.. Oh god, I forgot the map name.. It has three objectives), it often times is difficult to place the med box without the "Med Box is Blocked" message

**Comment by AtheistNMRiH** [comment]
couldn't reproduce it, can place med box just fine, looks like it was fixed, need to be closed

**Comment by essbuh** [comment]
Would need more info about specific places that this happens... though this ticket is 5 years old

**Comment by AtheistNMRiH** [comment]
well I checked all places in 3 mentioned map, didn't have any problems

**Comment by Winning117** [comment]
Confirmed fixed in src-r4388/dev-r8771, needs to be closed.
