### ISSUE TITLE
Stamina affects Spectator Speed

### ISSUE THREAD

**Issue by Smil3yRiley** [nmrih/source-game#32]
If you die as a human WHILE sprinting long enough to deplete a considerable amount of Stamina, your spectator no clipping speed is affected by it (the more stamina you used up before you died, the slower you will move)

---

Steps to reproduce:

1) Join a server
2) Sprint until you run out of stamina
3) Die
4) Move around in spectator mode

**Comment by Winning117** [comment]
Confirmed fixed in src-r4388/dev-r8771, needs to be closed.
