### ISSUE TITLE
rain clipping through the roof 

### ISSUE THREAD

**Issue by theghost2333** [nmrih/source-game#320]
rain was clipping through the roof 

![2013-08-06_00019](https://f.cloud.github.com/assets/5095321/917040/51dfc688-fe9c-11e2-845c-4cb50315bfc7.jpg)

**Comment by AtheistNMRiH** [comment]
can't really recognize the map, need more info or need to be closed

**Comment by Bubka3** [comment]
**Inactivity Closure**
This issue has been closed for inactivity. If you are still experiencing this issue please reply to this issue to re-open it. If you have any additional issues please open a new issue.

For technical support, you may also post in the troubleshooting forums:
http://steamcommunity.com/app/224260/discussions/2/
