### ISSUE TITLE
(nmo_cabin) objective bugs (welder, telegraph line cable)

### ISSUE THREAD

**Issue by grasn** [nmrih/source-game#327]
I played cabin with porky two times. We reached the kitchen while objective, welder the kitchen door, as we noticed the objective door from the above floor was still highlighted red:
![nmo_cabin0000](https://f.cloud.github.com/assets/5090011/935234/76b56f34-007d-11e3-9c8f-c8bba1dec139.jpg)

We opened up the kitchen door with a welder, and still after getting the new objective " " reconnect telegraph line cable" the top floor and kitchen doors were both highlighted in red all the time:
![nmo_cabin0002](https://f.cloud.github.com/assets/5090011/935246/b806e9e0-007d-11e3-86aa-823873866173.jpg)
![nmo_cabin0003](https://f.cloud.github.com/assets/5090011/935251/bf46f128-007d-11e3-8531-cd29ee9f197a.jpg)

Another issue, the telegraph line cable is not sticking into the socket. Its above:
![nmo_cabin0004](https://f.cloud.github.com/assets/5090011/935257/e25f584e-007d-11e3-87b3-4f560ae1e3f7.jpg)

**Comment by AtheistNMRiH** [comment]
fixed telegraph line cable is not sticking into the socket in r8729

**Comment by Bubka3** [comment]
tracking glow problem under #545

**Comment by Winning117** [comment]
Confirmed glow issue is no longer present. Tested in src-r4388/dev-r8769, the kitchen door is no longer highlighted (not sure if this is intentional or not) and on the "weld kitchen door" objective there is an incorrect compass marker far off in the distance that points to nothing (see screenshot).
![224260_20180330154658_1](https://user-images.githubusercontent.com/15934200/38156382-39881bb4-3432-11e8-90b0-b32c5019740b.png)

**Comment by AtheistNMRiH** [comment]
that red marker leads to the welder, there shouldn't be any other highlighted entities

as for not glowing door, this is an brush --> #920

**Comment by Winning117** [comment]
If that is a brush entity then the lock should glow, seems weird that every other objective highlights the objects but not that one.

For the red marker then there is a different glitch related to picking up glowing items. I'll open a new issue for that.

**Comment by AtheistNMRiH** [comment]
gonna add glow for lock then

**Comment by AtheistNMRiH** [comment]
added glow for lock in r8771

**Comment by Winning117** [comment]
Confirmed fixed in src-r4388/dev-r8771, needs to be closed.
