### ISSUE TITLE
Sniper scope problems

### ISSUE THREAD

**Issue by Lebofly** [nmrih/source-game#336]
This occurs when you scope in with the sniper and disapeares after a second or two
![hl2 2013-08-11 17-04-48-27](https://f.cloud.github.com/assets/3068521/943907/812cc6b0-027b-11e3-9666-b4e30a91b3b8.jpg)
![hl2 2013-08-11 17-08-05-80](https://f.cloud.github.com/assets/3068521/943906/812ae084-027b-11e3-9105-046a2accd2a4.jpg)

**Comment by Winning117** [comment]
Changed way that sniper works, needs to be closed.
