### ISSUE TITLE
Annoying right hand on Ruger 10/22 

### ISSUE THREAD

**Issue by Ic4ru5** [nmrih/source-game#342]
![nms_isolated0004](https://f.cloud.github.com/assets/5200446/953775/f75136ac-03ff-11e3-9ab9-a1fc4a129a07.jpg) - Basically, when shooting/moving while aiming with Ruger 10/22, the right hand gets too close to the player camera.

**Comment by Winning117** [comment]
Confirmed fixed in src-r4388/dev-r8769, needs to be closed.
