### ISSUE TITLE
Strange character movement when client receives full update ("ice-skating bug")

### ISSUE THREAD

**Issue by Keldorn074** [nmrih/source-game#350]
If you alt-tab to desktop then open the game back up. Or use the video options, like changing your anti-aliasing. When back in the game the feet movement will feel very weird. Like if you move forward it should stop instantly, but instead it will move another inch or two then stop, like there is some king of input lag.

Noticed in Steam build and Dev build 1.07.

There is also another one that has plagued the game since the 1.00 release which is probably related. Sometimes while alt-tabing out the game then coming back your feet movement feels like your walking on a slippery surface like soap or ice.

**Comment by felis-catus** [comment]
Reopening this, most likely on our side. (QoL plugin references this as "ice-skating bug".)

Can be reproduced consistently by using "record" command.

**Comment by RickyFisher98** [comment]
Saying you can't and won't fix the bug is pathetic. I'm not sure how character movement works in NMRIH, but you can certainly reset the movement engine and animations when the game receives focus.

**Comment by Winning117** [comment]
@RickyFisher98 No point in saying that it's pathetic, this issue was reopened for a reason.

**Comment by felis-catus** [comment]
(Finally) fixed in src-r4703.

**Comment by Holycrapjimhox** [comment]
Confirmed fix on dev-r8890.
