### ISSUE TITLE
[nmo_chinatown] Exceeded max_decals

### ISSUE THREAD

**Issue by Keldorn074** [nmrih/source-game#351]
I seen this spamming in the console when playing nmo_chinatown.

Exceeded MAX_DECALS (2048).
R_FindDynamicDecalSlot: no slot available.
R_FindDynamicDecalSlot: no slot available.
R_FindDynamicDecalSlot: no slot available.
R_FindDynamicDecalSlot: no slot available.
R_FindDynamicDecalSlot: no slot available.
R_FindDynamicDecalSlot: no slot available.
R_FindDynamicDecalSlot: no slot available.
R_FindDynamicDecalSlot: no slot available.
R_FindDynamicDecalSlot: no slot available.
R_FindDynamicDecalSlot: no slot available.
R_FindDynamicDecalSlot: no slot available.
R_FindDynamicDecalSlot: no slot available.
R_FindDynamicDecalSlot: no slot available.
R_FindDynamicDecalSlot: no slot available.
R_FindDynamicDecalSlot: no slot available.
R_FindDynamicDecalSlot: no slot available.
R_FindDynamicDecalSlot: no slot available.
R_FindDynamicDecalSlot: no slot available.

**Comment by AtheistNMRiH** [comment]
I didn't find any solution to fix this, I have seen this error on other maps aswell, not sure if it is gamebreaking bug, looks like it appears after losing/completing and restarting round
