### ISSUE TITLE
[nmo_chinatown] Framerate drops from police cars strobes.

### ISSUE THREAD

**Issue by Keldorn074** [nmrih/source-game#352]
Those strobe particle effects on the police cars create huge framerate drop for me.

Look at the FPS from net_graph in the bottom right corner

Average FPS when not having a police car in view is very good.
![2013-08-15_00014](https://f.cloud.github.com/assets/3848484/972759/3f7c7cac-0608-11e3-916f-3391e1702e35.jpg)

Put a police car in my view centered on the strobes. Lags.
![2013-08-15_00015](https://f.cloud.github.com/assets/3848484/972767/88e6fd18-0608-11e3-9dc1-5f61b4d152fe.jpg)

Throw in a m16 with the scope. Double lags.
![2013-08-15_00013](https://f.cloud.github.com/assets/3848484/972763/6faa098a-0608-11e3-9871-c62c11138521.jpg)

**Comment by AtheistNMRiH** [comment]
this is more particle problem, I can't really do smth with it
