### ISSUE TITLE
Zombie grab at other direction.

### ISSUE THREAD

**Issue by AWMShotDead** [nmrih/source-game#356]
Im testing alone at map Broadway and I go near a net but I got grabbed by a female zombie but she look at other direction.
![bug](https://f.cloud.github.com/assets/5155129/981060/382183f6-0740-11e3-88b4-f9cb653ac17c.jpg)

**Comment by Bubka3** [comment]
**Duplicate Closure**
This issue has been closed because it has already been reported under a previous issue ID.
Please follow the issue below for further updates.

Duplicate of #223
