### ISSUE TITLE
Froze when I barricaded

### ISSUE THREAD

**Issue by s0ap13rd1g** [nmrih/source-game#357]
(mostly on isolated) i Freeze when i barricade, happened two times in a row, stayed in that state for 2 minutes first time and the second time i disconnected, no internet problems or anything like that,

**Comment by Bubka3** [comment]
Hi there, do you still require assistance? If so, do you have the crash dumps for us?

**Comment by Winning117** [comment]
Not reproducible and player hasn’t responded for over a month, needs to be closed.
