### ISSUE TITLE
Toxteth Zombie Spawning in Wall.

### ISSUE THREAD

**Issue by Kommandos0** [nmrih/source-game#375]
For Steam Closed Beta 1.07, On nmo_toxteh when you go down into the 'sewers' one of the places where zombies spawn makes them spawn in the wall. The zombies can't do anything while they're in the wall. Screenshot explains the rest (sorry for being B&W but that's the health I was on when I took the screenshot)
![2013-08-30_00001](https://f.cloud.github.com/assets/5094722/1055728/558bac2e-1144-11e3-8d8b-0d8d2cf40557.jpg)

**Comment by AtheistNMRiH** [comment]
not sure if it is possible now, I have never seen a zombie which can spawn in func_detail, maybe it was fixed so need to be closed
