### ISSUE TITLE
(nmo_toxteth) Player Stuck - disconnected

### ISSUE THREAD

**Issue by grasn** [nmrih/source-game#376]
Played new toxteth version today and got stuck (couldn't move) after playing some minutes. I could look around but not move, after some seconds i dosconnected from server.

![nmo_toxteth0004](https://f.cloud.github.com/assets/5090011/1060241/4de7a8bc-11ab-11e3-845a-63c7547657b6.jpg)

**Comment by Bubka3** [comment]
That assertion is long fixed and I cant reproduce so I will be closing this out.
