### ISSUE TITLE
Board Barricading sound plays twice for hammer

### ISSUE THREAD

**Issue by Smil3yRiley** [nmrih/source-game#38]
Reported this a while back in the original Bug Tracker, but if you have only 1 board left and you use it to barricade a door or window, the barricading hammer sound will play twice in a row (it plays normally if you have at least 2 or more boards though)

---

Steps to Reproduce

1) Pick up a hammer (tool_barricade)
2) Make sure you have ONLY 1 barricade board in your inventory
3) Place the board up)

**Comment by Winning117** [comment]
Confirmed fixed in src-r4388/dev-r8769, needs to be closed.
