### ISSUE TITLE
nmo_lakeside floating props

### ISSUE THREAD

**Issue by grasn** [nmrih/source-game#386]
floating props

![nmo_lakeside0002](https://f.cloud.github.com/assets/5090011/1111607/fbe8bfdc-19b2-11e3-9e8a-195b5b5d3b9e.jpg)

![nmo_lakeside0003](https://f.cloud.github.com/assets/5090011/1111608/009cd8e2-19b3-11e3-885a-addd6e10051a.jpg)

and the painkillers are hard to reach. maybe move them a bit.

![nmo_lakeside0005](https://f.cloud.github.com/assets/5090011/1111610/1acb0d06-19b3-11e3-98ad-46c4d922d9b1.jpg)

**Comment by Winning117** [comment]
Checked in src-r4388/dev-r8769, still has some floating items, needs to be reopened.

![224260_20180329152319_1](https://user-images.githubusercontent.com/15934200/38116667-f7cdfe7c-3365-11e8-9157-de87f3d9cea6.png)
![224260_20180329152608_1](https://user-images.githubusercontent.com/15934200/38116680-ffc1e53a-3365-11e8-9582-092f1126b62a.png)

**Comment by AtheistNMRiH** [comment]
ammoboxes often float in the air because of their collision model, gonna take a look on those meical items

**Comment by AtheistNMRiH** [comment]
medical items are floating because of hospital stretcher collision model, won't fix, needs to be closed
