### ISSUE TITLE
1.07 Maglite attack was repeating twice

### ISSUE THREAD

**Issue by Keldorn074** [nmrih/source-game#387]
I was in game (single player) and was pressing forward/backward while holding the maglite and it was repeating the animation twice for full frames or a couple frame then glitching back into place. I wonder if it could be like a flood control problem with input lag.

Also I notice these kindof animation bugs alot when playing online with all weapons/melee. It could be related, it seems like the same kind of animation bug, they just happen more often in a multiplayer game. Its really annoying I hope we can get these fixed.

**Comment by Winning117** [comment]
Same issue in [#319](url) for animations, needs to be closed.
