### ISSUE TITLE
(code) Tapping the reload key while sprinting will allow you to do both at the same time

### ISSUE THREAD

**Issue by Smil3yRiley** [nmrih/source-game#390]
This came from https://github.com/ZPSNMRiHIssues/nmrihissues/issues/388

Basically if you tap your reload key while you're sprinting, you're able to reload and sprint at the same time. It's a small oversight since the reload action doesn't cancel the sprinting action.

---

Steps to Reproduce
1) Grab a gun and some ammo and fire one or two shots
2) Sprint, and then tap the reload key while you're still holding down the sprint key.

**Comment by Winning117** [comment]
I don't think this should be removed, it's a fun game mechanic

**Comment by felis-catus** [comment]
> 
> 
> I don't think this should be removed, it's a fun game mechanic

Agreed, there is a general consensus on this. Holding off the issue.
