### ISSUE TITLE
(listen server) 1.07 nmo_cabin see through wall/door when against it with m16a4 scope

### ISSUE THREAD

**Issue by Gringos78** [nmrih/source-game#394]
No major bug, but cosmetic:

In both cases i was standing against the wall/door when this occurred.

Can see through the right door when m16a4 is zoomed out through the scope.

![nmo_cabin0000](https://f.cloud.github.com/assets/4136909/1186354/4a78e7bc-22f5-11e3-887e-f9356cfc6988.jpg)

Can see through the left and right wall (same texture type) when m16a4 is zoomed out through the scope.

![nmo_cabin0001](https://f.cloud.github.com/assets/4136909/1186363/ddd82a2c-22f5-11e3-8c98-32760ecaf29e.jpg)

![nmo_cabin0002](https://f.cloud.github.com/assets/4136909/1186364/f9d68fa2-22f5-11e3-998e-fd2cb7b57ba5.jpg)

Also through the grey doors on the right.

![nmo_cabin0003](https://f.cloud.github.com/assets/4136909/1186367/1b759bbc-22f6-11e3-8178-20672a3c94a3.jpg)

**Comment by AtheistNMRiH** [comment]
I guess it is obsolete now, since scope was chagned
