### ISSUE TITLE
1.07 nmo_toxteth Barrier Gap

### ISSUE THREAD

**Issue by Kommandos0** [nmrih/source-game#402]
On nmo_toxteth outside the store, one of the barriers has a pretty noticeable gap making it seem like you can go through it when in reality you can't. It seems pretty simple to fix with you just needing to make the two barriers closer together.
![hmusty5](https://f.cloud.github.com/assets/5094722/1251335/14ac3846-2b24-11e3-8192-bd01aa5f0816.jpg)

**Comment by AtheistNMRiH** [comment]
fixed in r8735

**Comment by Winning117** [comment]
Confirmed fixed in src-r4388/dev-r8769, needs to be closed.
