### ISSUE TITLE
1.07 Hatchet charged attack does not work with Maglite

### ISSUE THREAD

**Issue by billionlioe** [nmrih/source-game#419]
If one uses a charged attack with the hatchet while having the maglite equipped the resulting attack does not kill zombies. Interestingly the zombie "hit" with the failed charged attack will go down with one hit from a quick attack afterwards.

To replicate:
1. Find/spawn me_hatchet and item_maglite
2.Equip maglite with hatchet and charge attack a zombie

Found on steam build.

**Comment by Fersigal** [comment]
Fixed in 1.09.7 i believe (someone will have to confirm this)

**Comment by AtheistNMRiH** [comment]
checked in dev build, works fine

**Comment by Bubka3** [comment]
**Resolved Closure**
This issue has been closed as it has been resolved in the current dev build.
It will be available to the public in the next steam release. Thanks for reporting!

Additional comments: n/a
