### ISSUE TITLE
(sound) reminder: inconsistent supply chopper audio sound

### ISSUE THREAD

**Issue by Smil3yRiley** [nmrih/source-game#425]
In some nms_ maps there's a random chance that the chopper sounds do not play when there's a supply wave; nms_ransack is the only map where the supply chopper sounds consistently play with no known issue.

**Comment by AtheistNMRiH** [comment]
not really a random, I guess it depends on distance - like nms_silence is pretty big and chopper can spawn far away from player

**Comment by Winning117** [comment]
I don't think I've ever had the chopper not play sound and I almost exclusively play survival maps.

**Comment by yomox9** [comment]
I experienced it yesterday. So it happens on version1.09.7. When the issue happens, some player heard chopper's sound.

**Comment by felis-catus** [comment]
Inconclusive issue, closing.

**Comment by felis-catus** [comment]
Nvm, fixed in src-r6278.
