### ISSUE TITLE
(code) Weapons from supply crates can spawn inside the ground

### ISSUE THREAD

**Issue by Smil3yRiley** [nmrih/source-game#427]
This still exists as of 10/21/2013

If you try to pick up a weapon or item when your inventory doesn't have enough space for it (for me it happens if I try to get something that slightly exceeds my full inventory space), it'll spawn part way in the ground.

---

Steps to Reproduce
1) Go on a map that has a supply crate/drop
2) Fill up your inventory with some items from impulse 101 first, and then access the supply crate
3) Take something from the crate

This bug can also lead to the infamous broken sprint issue

**Comment by AtheistNMRiH** [comment]
iirc it was fixed in one of the felis'es commit, I tested in dev build, works fine now, need to be closed
