### ISSUE TITLE
(code) Reminder: Sprint can still break if you're messing around with the Supply Crate UI

### ISSUE THREAD

**Issue by Smil3yRiley** [nmrih/source-game#428]
The supply crate GUI can still break your sprinting ability through various ways.

Whether by replicating https://github.com/ZPSNMRiHIssues/nmrihissues/issues/427 or perhaps trying to take an item at the same time as someone else, you'll be unable to sprint until you die. Once you respawn, you're able to sprint as usual.

**Comment by AtheistNMRiH** [comment]
since #427 is fixed, this one should be closed too
