### ISSUE TITLE
(misc) Water particle effect appears after killing zombies with headshots?

### ISSUE THREAD

**Issue by Smil3yRiley** [nmrih/source-game#429]
I was playing on Revision 6086 and I scored some headshot kills that appeared to render some sort of water particle? 

It was a burst of white, and I'm guessing it was the game trying to use the blood blowback particle effect

---

Steps to Reproduce
1) Give yourself a gun
2) Kill as many zombies as you can with headshots

**Comment by Winning117** [comment]
Not reproducible in src-r4388/dev-r8771, needs to be closed.
