### ISSUE TITLE
[Objective] gas can outline floating in air

### ISSUE THREAD

**Issue by Joshikumako** [nmrih/source-game#44]
The gas can randomly lost its outline and was stuck in the air

http://dl.dropbox.com/u/14121725/2013-04-06_00001.jpg

**Comment by Bubka3** [comment]
Hi, is this still a problem? The screenshot is dead and there isn't enough info here to proceed.

**Comment by Bubka3** [comment]
**Inactivity Closure**
This issue has been closed for inactivity. If you are still experiencing this issue please reply to this issue to re-open it. If you have any additional issues please open a new issue.

For technical support, you may also post in the troubleshooting forums:
http://steamcommunity.com/app/224260/discussions/2/
