### ISSUE TITLE
(Sound) (Code) Stop Tension Music on parts of the game

### ISSUE THREAD

**Issue by CurlySparkle** [nmrih/source-game#440]
Well, i been thinking about this and well, what im trying to say is to change the music or stop the tension (danger) music when theres no zombies around you or when you are on a wall and the zombies are in the other side of the wall of the map like in broadway, on the start when you go everywhere like the upstair, the tension (danger) music will play with no zombies around you well thats because the zombies are outside but the music will still play and not the ambient ones, and well if it has a fix or not because sometimes it gets annoying when theres no danger around you and you can still hear the danger music and well thats all for now.

**Comment by Winning117** [comment]
This is a request and not a bug, needs to be closed.
