### ISSUE TITLE
(sound) Failed to load sound flaregun_hammerdown.wav

### ISSUE THREAD

**Issue by grasn** [nmrih/source-game#441]
Failed to load sound ")weapons\tools\flaregun\flaregun_hammerdown.wav", file probably missing from disk/repository

Steps to Reproduce
1. enable "developer 1" in console
2. Pick up flaregun
3. Hold R to check ammo
4. error will appear in console

**Comment by AtheistNMRiH** [comment]
looks like tool_flare_gun doesn't try to use that sound anymore, checked in dev build, there wasn't any error
also checked game file, sound with this name doesn't exist
need to be closed
