### ISSUE TITLE
charged melee

### ISSUE THREAD

**Issue by WoodyInvincible** [nmrih/source-game#442]
after testing all melee weapons,the hatchet has an issue.the charged attack never seems to hit no matter how close.furthermore,any time u miss a charged attack at a zombie , the usual "2 hit normal swing kill" weapons will be 1 hit ko at the same zombie where u missed the charged melee .eg , i missed my baseball bat charge at the zombie, then i follow it up with one normal swing.it killed it despite normally swinging twice to kill it

**Comment by Fersigal** [comment]
Neither of those are bugs

**Comment by AtheistNMRiH** [comment]
duplicate of #419

**Comment by Bubka3** [comment]
**Duplicate Closure**
This issue has been closed because it has already been reported under a previous issue ID.
Please follow the issue below for further updates.

Duplicate of #419
