### ISSUE TITLE
Video skipping / jumping frames (MAC OS 10.6.8)

### ISSUE THREAD

**Issue by mercuriusfm** [nmrih/source-game#467]
The video seems to "skip" almost as if it's going back a frame sometimes. The video itself is overall smooth/acceptable except for the fact that it is jumping frames every 1 or 2 seconds. 

Troubleshooting:
To improve performance, I've lowered all effects to the lowest settings, and also disabled steam community. I've run disk utility also to make sure it wasn't my drive.

For reference, I am able to run Counter Strike GO with out any issues (which I mention because it uses the Source Engine also). 

I haven't tried messing with the cfg file yet, but may try that later on. 

My system:

NMRIH Version 1.07

Mac OS 10.6.8

  Model Name: MacBook Pro
  Model Identifier: MacBookPro5,4
  Processor Name: Intel Core 2 Duo
  Processor Speed: 2.53 GHz
  Number Of Processors: 1
  Total Number Of Cores: 2
  L2 Cache: 3 MB
  Memory: 8 GB
  Bus Speed: 1.07 GHz
  Boot ROM Version: MBP53.00AC.B03
  SMC Version (system): 1.49f2

**Comment by Winning117** [comment]
Seems to be an issue with recording and not the actual game, needs to be closed.
