### ISSUE TITLE
Sound effects / Audio not playing right (Mac OS 10.6.8)

### ISSUE THREAD

**Issue by mercuriusfm** [nmrih/source-game#468]
Issue 1:
Sound effects seem to be not in sync. Some sound effects are either really quiet or don't seem to happen. (like weapon sounds).

Troubleshooting:
To improve performance, I've lowered all effects to the lowest settings, and also disabled steam community. I've run disk utility also to make sure it wasn't my drive.

For reference, I am able to run Counter Strike GO with out any issues (which I mention because it uses the Source Engine also). 

I haven't tried messing with the cfg file yet, but may try that later on. 

My system:

NMRIH Version 1.07

Mac OS 10.6.8

  Model Name: MacBook Pro
  Model Identifier: MacBookPro5,4
  Processor Name: Intel Core 2 Duo
  Processor Speed: 2.53 GHz
  Number Of Processors: 1
  Total Number Of Cores: 2
  L2 Cache: 3 MB
  Memory: 8 GB
  Bus Speed: 1.07 GHz
  Boot ROM Version: MBP53.00AC.B03
  SMC Version (system): 1.49f2

**Comment by Winning117** [comment]
No steps to reproduce, should be closed.
