### ISSUE TITLE
(Spectator) Pills & Walkie Talkie models underneath player arms

### ISSUE THREAD

**Issue by grasn** [nmrih/source-game#469]
This has already been reported on private tracker by Riley.

Replicate:
1. You must be dead/spectator
2. Follow player in first person view
3. Player must look down
4. You will see a Pills & Walkie Talkie model underneath the players arms

Hard to notice on the screenshot, better on melee
![nmo_chinatown0001](https://f.cloud.github.com/assets/5090011/1460471/445e3f98-443e-11e3-935b-5c96e7be95af.jpg)

this screenshot was taken while the player hit/weapon swing
![nmo_chinatown0004](https://f.cloud.github.com/assets/5090011/1460472/4b1cb788-443e-11e3-9202-1cf5f697fd00.jpg)

**Comment by Winning117** [comment]
Medical items were redone, needs to be closed.
