### ISSUE TITLE
[nmo_lakeside] Scaffolding Playerclip Issue

### ISSUE THREAD

**Issue by EArkham** [nmrih/source-game#477]
Version: Steam build

You can climb to this area here:

http://cloud-2.steampowered.com/ugc/684840005459743080/55A5CFF475E0F94C5A5AE85BFEC403D710C86546/

I stood here for a very long time, and none of the zombies even attempted to make their way up to me (is there even nav_mesh there?).  Since the back of the scaffolding wood has nodraw, I expect you are not supposed to get anywhere on the scaffolding -- there's also clipping on the OTHER side of the scaffolding where the flashlight is pointing.

1) bottom of the scaffolding, duck and walk into the wheelbarrow and cinderblocks
2) jump up against the crates to the top of the crates
3) jump to the ledge near the house
4) walk/crawl around and up the ramp to the very top
5) mock the impotence of the zombies

**Comment by Fersigal** [comment]
Screenshot does not work anymore, i suppose he means the part at the white van where u're supposed to be able to go onto if you stay at the side 
https://i.ytimg.com/vi/_oXfKo92MQI/maxresdefault.jpg
scaffolding is at the right side of the picture

**Comment by Winning117** [comment]
Reuploading screenshot of area for reference.
![224260_20180330161805_1](https://user-images.githubusercontent.com/15934200/38156862-481dceea-3436-11e8-978f-3e8dac1f60f1.png)


Confirmed fixed in src-r4388/dev-r8769, needs to be closed.
