### ISSUE TITLE
NMRIH [1.0.7.2] Ladder fastclimb

### ISSUE THREAD

**Issue by quaixor** [nmrih/source-game#478]
Turning sideways and pressing strafe key and forward lets you climb ladders twice as fast. Bug is also present in L4D2.

**Comment by Winning117** [comment]
Still present in the game, though not sure if this was closed as wont-fix. https://www.youtube.com/watch?v=a1fRNYjdGyU

**Comment by felis-catus** [comment]
Ladderstrafing is a classic Source movement trick that isn't abusable, I don't see why it should be patched.
