### ISSUE TITLE
Zombies get stuck inside ground on Lakeside

### ISSUE THREAD

**Issue by 2ndClassCitizen** [nmrih/source-game#48]
Zombies will get stuck in the ground on Lakeside. If they spawn elsewhere and walk on the ground then they will be on top of the ground, so it'll be okay. So I'm guessing perhaps this means they get stuck if they spawn inside the ground?

http://oi45.tinypic.com/35cphcx.jpg

**Comment by Winning117** [comment]
Confirmed fixed in src-r4367/dev-r8764.
