### ISSUE TITLE
[MapBug] nms_favela

### ISSUE THREAD

**Issue by Combine900** [nmrih/source-game#484]
There are some props on the map, which send this error to the console.

Error: SOLID_VPHYSICS static prop with no vphysics model!

Picture one. The errors.
![propbug](https://f.cloud.github.com/assets/5911484/1515212/f225dc6e-4afe-11e3-9aae-0743dc66e97b.jpg)

Picture two. How to fix it.
![howtofix](https://f.cloud.github.com/assets/5911484/1515217/0078e2ac-4aff-11e3-8cf3-a632e5de39e2.jpg)

The prop in the second picture also isn't visible it is under the map (nms_favela).

**Comment by AtheistNMRiH** [comment]
was fixed in previous versions, need to be closed
