### ISSUE TITLE
[public-1.11.3] Extraction Cam not working

### ISSUE THREAD

**Issue by grasn** [nmrih/source-game#485]
On nms_flooded wave 10 there was no extraction camera. The player model just stood still for some seconds when the helicopter was coming. No one actually knew where to go, cause there was no extraction camera pointing the player where to go.

Also the Extraction heli wait time was much too short and the heli sound was to quiet!

**Comment by Winning117** [comment]
Note: This issue isn't map-specific and can happen on all maps.

**Comment by AtheistNMRiH** [comment]
not my investigation:
1.1 when this bug happens (still randomly) only FIRST connected to server player will see extraction camera, others won't
1.2 if FIRST connected to server player LEAVES a server, then extraction camera will work for NEXT PLAYER IN SCORE LIST when this bug happens, others won't

**Comment by felis-catus** [comment]
Still happens on 1.11.2, renaming and bumping up priority.

**Comment by felis-catus** [comment]
src-r4945 should fix this.

**Comment by felis-catus** [comment]
Still occurs in 1.11.3, reopening.

**Comment by felis-catus** [comment]
Fixed in 1.11.4 (for real this time).
