### ISSUE TITLE
Generator makes no noise activated with lighter

### ISSUE THREAD

**Issue by 2ndClassCitizen** [nmrih/source-game#499]
When I have the lighter out and activate the generators underground in lakeside, they don't make a sound until the 3rd one is activated. Riley said the soundscapes may be bugged.

http://oi43.tinypic.com/mabd5u.jpg

**Comment by Bubka3** [comment]
We cant repro this, is this still a problem?

**Comment by Bubka3** [comment]
**Inactivity Closure**
This issue has been closed for inactivity. If you are still experiencing this issue please reply to this issue to re-open it. If you have any additional issues please open a new issue.

For technical support, you may also post in the troubleshooting forums:
http://steamcommunity.com/app/224260/discussions/2/
