### ISSUE TITLE
(maps) forward respawn bug in nmo_lakeside

### ISSUE THREAD

**Issue by Smil3yRiley** [nmrih/source-game#503]
On the new objective path (Leave the Mill > Go through the tunnel), if the entire team dies before they complete the tunnel objective, they'll still lose the round as intended but they'll respawn in the forward respawn area.

**Comment by Holycrapjimhox** [comment]
Tested it solo in src-4388/r-8769. I killed myself before touching the trigger to start the next objective to the tunnel and I didn't respawn. It needs further testing with several players.
