### ISSUE TITLE
Failed to create GL context - Linux with Intel Integrated GPU

### ISSUE THREAD

**Issue by ctodobom** [nmrih/source-game#508]
Pasting the questions from guide and answering them:

What is your issue exactly?

When try to play NMRIH It doesn't run and issue an error window

What is the exact message?

Failed to create GL context: Could not create GL context, on the console the following text appears:
Game update: AppID 224260 "No More Room in Hell", ProcID 6192, IP 0.0.0.0:0
SDL video target is 'x11'
SDL video target is 'x11'
Failed to create GL context: Could not create GL context

Do you have a screenshot?

think does't need one.

Can you reproduce this issue by repeatedly by doing one thing?

Yes, it happens everytime

What operating system are you running?

Debian Linux wheezy with updated libmesa. Other source games runs fine: TF2, HalfLife2 and Portal.

What have you tried to fix it (ie: applying tweaks to your start up line and messing with the dev console would go here)?

I couldn't find any info on something to try.

Does your computer meet the minimum requirements?

It is not exactly the same... think that the major differences is Debian and Intel Integrated GPU that aren't listed on the requirements. But I think I meet them because other source games run!

More Info:

Looks like TF2 and Dota 2 had the same problem about 4 months ago, they fixed with updates. Maybe you can look at what they changed.

A workaround can be appreciated too!

Following is the dump file pasted:

Running Steam on debian 7 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1383158641_client)
Installing breakpad exception handler for appid(steam)/version(1383158641_client)
unlinked 0 orphaned pipes
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Installing breakpad exception handler for appid(steam)/version(1383158641_client)
[1130/021325:WARNING:proxy_service.cc(958)] PAC support disabled because there is no system implementation
Installing breakpad exception handler for appid(steam)/version(1383158641_client)
Installing breakpad exception handler for appid(steam)/version(1383158641_client)
Installing breakpad exception handler for appid(steam)/version(1383158641_client)
Installing breakpad exception handler for appid(steam)/version(1383158641_client)
Generating new string page texture 2: 48x256, total string texture memory is 49,15 KB
Generating new string page texture 3: 256x256, total string texture memory is 311,30 KB
Installing breakpad exception handler for appid(steam)/version(1383158641_client)
Installing breakpad exception handler for appid(steam)/version(1383158641_client)
Installing breakpad exception handler for appid(steam)/version(1383158641_client)
local (potentially out of sync) copy of roaming config loaded - 743 bytes.
Adding license for package 0
Adding license for package 39
Adding license for package 469
Adding license for package 2483
Adding license for package 7878
Adding license for package 8041
Adding license for package 8132
Adding license for package 8462
Adding license for package 11080
Adding license for package 12122
Adding license for package 12289
Adding license for package 13054
Adding license for package 16360
Adding license for package 16586
Adding license for package 18265
Adding license for package 18620
Adding license for package 18629
Adding license for package 25835
Adding license for package 28702
roaming config store loaded successfully - 743 bytes.
migrating temporary roaming config store
Installing breakpad exception handler for appid(steam)/version(1383158641_client)
ExecCommandLine: "/home/allgood/.local/share/Steam/ubuntu12_32/steam"
System startup time: 7,48 seconds
Running Steam on debian 7 64-bit
STEAM_RUNTIME has been set by the user to: /home/allgood/.local/share/Steam/ubuntu12_32/steam-runtime
Generating new string page texture 68: 1024x256, total string texture memory is 1,36 MB
Generating new string page texture 69: 256x256, total string texture memory is 262,14 KB
Generating new string page texture 70: 64x256, total string texture memory is 1,43 MB
Generating new string page texture 71: 128x256, total string texture memory is 1,56 MB
Generating new string page texture 72: 24x256, total string texture memory is 1,58 MB
ExecCommandLine: "/home/allgood/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
Generating new string page texture 76: 128x256, total string texture memory is 1,71 MB
Generating new string page texture 77: 256x256, total string texture memory is 1,97 MB
Generating new string page texture 78: 32x256, total string texture memory is 2,01 MB
Generating new string page texture 105: 384x256, total string texture memory is 2,40 MB
Generating new string page texture 106: 512x256, total string texture memory is 2,92 MB
Game update: AppID 224260 "No More Room in Hell", ProcID 26581, IP 0.0.0.0:0
SDL video target is 'x11'
SDL video target is 'x11'
Failed to create GL context: Could not create GL contextGame removed: AppID 224260 "No More Room in Hell", ProcID 26581 
Generating new string page texture 141: 64x256, total string texture memory is 327,68 KB
unlinked 2 orphaned pipes
CAsyncIOManager: 0 threads terminating.  0 reads, 0 writes, 0 deferrals.
CAsyncIOManager: 11484 single object sleeps, 0 multi object sleeps
CAsyncIOManager: 0 single object alertable sleeps, 1 multi object alertable sleeps
[2013-11-30 02:13:24] Startup - updater built Oct 30 2013 11:07:41
[2013-11-30 02:13:24] A verificar a instalação...
[2013-11-30 02:13:24] Verification complete
Shutting down. . .
[2013-11-30 02:13:49] Shutdown

**Comment by Bubka3** [comment]
Hello,

Please try the 1.11.0 beta as we shipped a critical linux patch. If you are still having problems after that please open a new issue.

Thanks!
