### ISSUE TITLE
(zippo) flame particle appears during extraction cam

### ISSUE THREAD

**Issue by grasn** [nmrih/source-game#514]
(zippo) flame particle appears during extraction cam (tested on nms)

replicate:
1. before extraction cam triggers, pull out zippo
2. turn zippo flame on
3. wait for the extraction cam
4. the flame particle of the zippo plays during the extraction cam

![nms_campblood_steam0001](https://f.cloud.github.com/assets/5090011/1702005/e5710c36-607b-11e3-8162-b1cd90166a76.jpg)
![nms_campblood_steam0000](https://f.cloud.github.com/assets/5090011/1702006/e583dfc8-607b-11e3-88eb-6e4debe1601f.jpg)

**Comment by Winning117** [comment]
Confirmed fixed in src-r4388/dev-r8772, needs to be closed.
