### ISSUE TITLE
[Linux][1.0.7.5] Server browser window is very small and has unreadable font

### ISSUE THREAD

**Issue by gutko** [nmrih/source-game#515]
Exactly as in title. Window seems to not remember its position and dimensions set last time and has very small font.
Seems to be connected to 
https://github.com/ValveSoftware/Source-1-Games/issues/75
and this
https://github.com/ValveSoftware/Source-1-Games/issues/39

My screen:
http://steamcommunity.com/sharedfiles/filedetails/?id=204724836

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0xf
    CPU Stepping:  0xb
    CPU Type:  0x0
    Speed:  3005 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 13.10 (32 bit)
    Kernel Name:  Linux
    Kernel Version:  3.11.0-14-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11403000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2013-10-23

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 570/PCIe/SSE2

```
Driver Version:  4.4.0 NVIDIA 331.20
OpenGL Version: 4.4
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0x1086
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 32,28" x 18,11"  (37,01" diag)
                                        82,0cm x 46,0cm  (94,0cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 1280 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: AV200

Memory:
    RAM:  4038 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  230572 Mb
    Largest Free Hard Disk Block:  206966 Mb

Installed software:

Recent Failure Reports:

**Comment by Bubka3** [comment]
Hello,

Please try the 1.11.0 beta as we shipped a critical linux patch. If you are still having problems after that please open a new issue.

Thanks!

**Comment by felis-catus** [comment]
Now tracking here: #1101
