### ISSUE TITLE
Black Screen (Ubuntu)

### ISSUE THREAD

**Issue by AlphaDestroyer85** [nmrih/source-game#516]
Hi guys, I have just downloaded the game on steam. When I start it, all I get is a black screen, I cannot do much and have to restart my computer. I have tried at least 3 times all with the same results.

Specs
OS: Ubuntu 13.10
CPU: Eight Core AMD
GPU: Geforce GTX 650 Ti Boost
RAM: 8GB 
Home built Computer

Thanks in advance for your assistance! :) 
(Also posted in forum)

**Comment by Winning117** [comment]
Outdated issue, needs to be closed.
