### ISSUE TITLE
(Linux) Segmentation Fault 

### ISSUE THREAD

**Issue by konspiracy** [nmrih/source-game#518]
So if I play for a good bit I randomly experience a crash that gives me no errors other than in the terminal.

(DEAD) ™#KÕñςspiracy /home/konspiracy/.local/share/Steam/SteamApps/common/nmrih/sdk/hl2.sh: line 67: 19264 Segmentation fault      (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 224260 "No More Room in Hell", ProcID 19264 
Focused window is now 0, 0

I have messed with the hl2.sh file and tried to disable the debugging but no joy.

I can play for hours or 10 min I have no idea what sets it off.

Im using ubuntu 12.10 with kde, and nvidia drivers.

**Comment by Fohdeesha** [comment]
this still happens all the time, about every 15 hours. About 2 years now. I've ran popular dedicated servers and I've been on three totally seperate server hardware now, everything different, but still crashes. The only constant has been the software - nmrih dedicated server and linux. will this ever be addressed?

**Comment by essbuh** [comment]
Server crashes should be fixed in 1.11.  Any new client crashes feel free to open a new ticket.

**Comment by Fohdeesha** [comment]
Holy crap, I had given up hope. 6 years later but glad it's fixed! Thanks!
