### ISSUE TITLE
[NMRiH] Rare Pills Glitch

### ISSUE THREAD

**Issue by DemolitionSteve** [nmrih/source-game#520]
I have only witnessed this twice, and so far have not successfully reproduced this.

In No More Room in Hell if a player is bleeding and in possession of pills, going into their inventory and dropping the pills will stop the bleeding and heal them in very rare cases as if a bandage had been applied.

This happened to me once on nmo_toxteth, and although I was sure I had just stopped bleeding while dropping pills, I concluded that I must have somehow used bandages or a medkit without realizing it.

The second instance also happened on nmo_toxteth with my friend when he was bleeding. He had pills in his inventory but was full on equipment and not able to pick up the bandages I had thrown down for him. He went to make room for the bandages by dropping the pills, and he was immediately healed and his bleeding stopped, though he hadn't even picked up the bandages yet, much like my previous encounter with this error.

Both times were on toxteth (though I'm not sure if this would change anything), and we had used neither bandages nor first aid kits. In my case I clearly remember still having both in my inventory after the bleeding stopped (though I had still shrugged it off), and in my friend's case I was aware we had already used all first aid kits prior to the event, meaning he could not have had one with him which he unintentionally used to stop the bleeding.

**Comment by Bubka3** [comment]
# Not a Bug
It appears the issue you've created is not a bug. 
A bug is an issue with the game that can be reproduced by following a specific set of instructions.

For general or technical support regarding the game, please visit the troubleshooting forums:
http://steamcommunity.com/app/224260/discussions/2/
