### ISSUE TITLE
Wrong flashlight beam direction

### ISSUE THREAD

**Issue by jendabek** [nmrih/source-game#526]
Hi, when my buddy uses melee together with flashlight, the beam direction I can see from my view is different from which he is actually aim to. Maybe it has something to do with 3rd persion view animation which the flashlight is aligned to - it is quite different from 1st persion view anim.

This is the problem especially when one of us asks the other to illuminate a path or zombies - this is not possible for now.

When using the flashlight together with pistol the light beam is also misaligned a bit but it is definitely not as serious issue as with melee.

We would appreciate if you can have a look at it.
Thanks!

My client runs on Win7 64bit, buddy is on the newest Mac OS X.
Version: 1.07.7

**Comment by Winning117** [comment]
Still an issue in public and dev, needs to be reopened.
