### ISSUE TITLE
Game-ruining glitch on nmo_cabin

### ISSUE THREAD

**Issue by DemolitionSteve** [nmrih/source-game#527]
When entering the underground area via climbing down the ladder to the caves, it's possible to become stuck in the wall if the player jumps at the broken wall instead of crawling through. I've seen it happen twice to other players.

**Comment by Fersigal** [comment]
![20180122220031_1](https://user-images.githubusercontent.com/11538773/35244236-ca37d0f2-ffbf-11e7-8a29-8f356449db45.jpg)

**Comment by AtheistNMRiH** [comment]
source problem, waiting for @felis-catus desicion

**Comment by Winning117** [comment]
Tested in src-r4388/dev-r8772. I was unable to reproduce this and I think that the people who got "stuck" in the wall just didn't know you have to crouch to get through that wall. Needs to be closed unless someone else is able to replicate this issue.

**Comment by Fersigal** [comment]
it's not reproducible anymore because the displacement has changed
New:
![image](https://user-images.githubusercontent.com/11538773/38293091-7ebe5fce-37e6-11e8-9111-edbd958f6c47.png)

This used to be an issue in the previous patch, not this one and seems to be fixed longsince

**Comment by AtheistNMRiH** [comment]
reproducible, tested on the same version as winning

steps:
1) jump
2) crouch and uncrouch in the air
3) become stuck

![nmo_cabin0000](https://user-images.githubusercontent.com/11333747/38303895-9e713b34-3831-11e8-8561-392fa36199c2.jpg)
