### ISSUE TITLE
Can kill players by opening gate (chinatown)

### ISSUE THREAD

**Issue by Smil3yRiley** [nmrih/source-game#53]
If someone stands inside the gate while you're turning it, they can get crushed to death
## ![2013-04-10_00003](https://f.cloud.github.com/assets/3606650/365531/95ce53c0-a24c-11e2-9b46-a6ed91fc36c6.jpg)

Steps to Reproduce
1) Go to the Weld Padlock > Open Gate objective in chinatown
2) Have one person jump inside a gap inside the gate and stand there while you fully turn the wheel

The person should die the moment they get close to you

**Comment by AtheistNMRiH** [comment]
gate killing prevent players from getting stuck in gap, I guess it is not a bug

**Comment by Winning117** [comment]
Unless I am misunderstanding what's happening I believe the gate killing you is intended and should be closed.
