### ISSUE TITLE
Dying right before extraction cutscene causes invisible zombies & models for subsequent rounds

### ISSUE THREAD

**Issue by Smil3yRiley** [nmrih/source-game#530]
On a dedicated server, if the last person dies right before the extraction cutscene for a map starts, and the round restarts in the middle of said cutscene, most dynamic entities and models (view models, zombie npcs, etc.) will appear to be invisible to everyone.

---

Steps to Reproduce

1) Join a dedicated server
2) Start an objective map
3) Complete all of the objectives, but kill yourself right before the extraction cutscene starts. You have to be the last person alive.

You've done this correctly if the game restarts the round RIGHT in the middle of the extraction cutscene.

**Comment by felis-catus** [comment]
Assuming it's fixed since I've never seen it occur post 1.10.

**Comment by Holycrapjimhox** [comment]
I've gotten a report today from a player that has experienced this on public-1.11.1. He described the issue accurately and fixed it by re-joining the server. I haven't experienced this myself recently so I can't show any proof that it still happens, but I wanted to note this anyway just in case.

**Comment by felis-catus** [comment]
src-r4945 should fix this.
