### ISSUE TITLE
"Out of Rounds" glitch

### ISSUE THREAD

**Issue by pagesofdreams** [nmrih/source-game#533]
I tried this connected to my friend as a server and myself as a server...

This seems to happen more and more frequently, especially if I use all of my bullets in a mag before reloading...it will tell me I am out of rounds even though I am not and along with it, WILL NOT RELOAD ROUNDS.  At first it seemed to happen more with .9mm, but after awhile it started happening with all other guns. My friend couldn't duplicate the problem, it seems to only be happening to me. I tried repairing the game and it didn't help, tried reinstalling the game...didn't help. I am running Windows XP. 

It also seems more likely to occur when a lot of ammo is collected, especially from emptying 
guns. Happened even before 1.07.8 patch was released.

**Comment by Bubka3** [comment]
**Inactivity Closure**
This issue has been closed for inactivity. If you are still experiencing this issue please reply to this issue to re-open it. If you have any additional issues please open a new issue.

For technical support, you may also post in the troubleshooting forums:
http://steamcommunity.com/app/224260/discussions/2/
