### ISSUE TITLE
Soundscapes dont work on Debian based Linux distros

### ISSUE THREAD

**Issue by Smil3yRiley** [nmrih/source-game#535]
Posting this as a reminder to myself and ssba, but if you play on a dedicated Linux server you'll find out that the soundscapes for each map don't work at all (meaning you can't really hear ambient noises like gunshots in the distance or police alarms, etc.)

They work just fine for Windows based servers though

**Comment by Bubka3** [comment]
**Inactivity Closure**
This issue has been closed for inactivity. If you are still experiencing this issue please reply to this issue to re-open it. If you have any additional issues please open a new issue.

For technical support, you may also post in the troubleshooting forums:
http://steamcommunity.com/app/224260/discussions/2/

**Comment by AtheistNMRiH** [comment]
issues still exist, very easy to check it on random linux servers

**Comment by felis-catus** [comment]
Added workaround in code commit r4239. Should be fixed, but need a Linux dedicated server to confirm.

**Comment by felis-catus** [comment]
Closing as resolved.
