### ISSUE TITLE
FPS drop on Linux client if infected @ low health

### ISSUE THREAD

**Issue by Smil3yRiley** [nmrih/source-game#536]
If you get infected while you're at low health on the Linux Client, your FPS will drop severely to the single digits. Only real way to fix it is to fully exit the game.

Tested on Steam Beta Branch, revision 7001

---

Steps to Reproduce
1) Start up a server 
2) Get yourself hurt by a zombie (a few swings from them, or use hurtme 999)
3) Get yourself bit by a zombie

If done correctly, your FPS should plummet

**Comment by Bubka3** [comment]
Bumping this because this needs repro on the new linux build.

**Comment by felis-catus** [comment]
If this problem still occurs it might be infection shader related.

**Comment by felis-catus** [comment]
Merging with #1125.
