### ISSUE TITLE
Can remove keys from doors (nmo_broadway)

### ISSUE THREAD

**Issue by Smil3yRiley** [nmrih/source-game#54]
If you place a key inside a door (for one of those "Find key to open a door" objectives) in nmo_broadway, you can quickly take it out and toss it on the floor
![2013-04-10_00008](https://f.cloud.github.com/assets/3606650/365542/29369bae-a24d-11e2-9006-d258d0a0098b.jpg)

---

Steps to Reproduce
1) Load up broadway and get the Theater > Street Objective Path, and bring the key to the door in the projector/cinema room
2) Take the key out from by pressing E

**Comment by AtheistNMRiH** [comment]
fixed in r8724

**Comment by Winning117** [comment]
Confirmed fixed in src-r4388/dev-r8769, needs to be closed.
