### ISSUE TITLE
[nmo_junction] Players can stuck between two doors in apartment

### ISSUE THREAD

**Issue by sizeofbool** [nmrih/source-game#548]
It's possible to stuck between two doors in apartment. Players won't be able to open these doors or move.
![2014-03-09_00002](https://f.cloud.github.com/assets/6904856/2371864/105f63c4-a830-11e3-9651-015c47682f9e.jpg)
![2014-03-09_00001](https://f.cloud.github.com/assets/6904856/2371865/1060a5fe-a830-11e3-817e-e1fc162abbac.jpg)

**Comment by Fersigal** [comment]
Fixed

**Comment by Winning117** [comment]
Confirmed fixed in src-r4388/dev-r8769, needs to be closed.
