### ISSUE TITLE
Screen tears out of control

### ISSUE THREAD

**Issue by Hellfire1264** [nmrih/source-game#555]
The game is unplayable with constant screen tears. It always gets in the way. I can't see any other players, I can't even see any zombies at all. It's just invisible zombies with too many screen tears in this game. I can barely see any player, equipment, weapons, and zombies in this game. If anyone has the same problem, or if you know how I can fix the screen tears, please comment below.

**Comment by Fersigal** [comment]
No screenshot, unclear and never received an answer (are there any related issues towards this one) ?

**Comment by Bubka3** [comment]
**Inactivity Closure**
This issue has been closed for inactivity. If you are still experiencing this issue please reply to this issue to re-open it. If you have any additional issues please open a new issue.

For technical support, you may also post in the troubleshooting forums:
http://steamcommunity.com/app/224260/discussions/2/
