### ISSUE TITLE
Can place/throw objects through fire hydrants

### ISSUE THREAD

**Issue by 2ndClassCitizen** [nmrih/source-game#56]
There seems to be a lack of collision going on; you can throw objects through fire hydrants, as well as place things in them.

http://oi50.tinypic.com/2uszwoz.jpg

Pictured: An SV10 placed in a fire hydrant.

You can pull items out of them as well even if they're not visible. Quest objects, such as keys, can't be placed inside of fire hydrants, collision is on for those things.

**Comment by AtheistNMRiH** [comment]
not really a bug, need to be closed
