### ISSUE TITLE
alltalk doesn't work for dead chat

### ISSUE THREAD

**Issue by Bubka3** [nmrih/source-game#571]
alltalk should enable dead chat to been seen by alive players

currently it only affects voice comms.

**Comment by felis-catus** [comment]
Fixed in code commit r4210.

**Comment by Bubka3** [comment]
**Resolved Closure**
This issue has been closed as it has been resolved in the current dev build.
It will be available to the public in the next steam release. Thanks for reporting!

Additional comments: n/a
