### ISSUE TITLE
(models) "Badass" Character Model doesn't cast dynamic shadows

### ISSUE THREAD

**Issue by Smil3yRiley** [nmrih/source-game#587]
Shine your flashlight on the "Badass" character model, you'll realize that she won't cast any dynamic shadows at all

---

Steps to Reproduce
1) Join a server with another player playing as the Badass character model
2) Shine a maglite at them (item_maglite)

**Comment by AtheistNMRiH** [comment]
![1](https://user-images.githubusercontent.com/11333747/36477693-b34ffe0a-1734-11e8-9bd2-e19ae089d626.jpg)
this is still an issue

**Comment by felis-catus** [comment]
Fixed in dev-r10050.
