### ISSUE TITLE
No gun sprint animation if holding down fire button

### ISSUE THREAD

**Issue by Smil3yRiley** [nmrih/source-game#59]
If you equip a firearm, hold down your primary fire button, and then sprint while continuing to hold down said fire button, the gun's sprint animation doesn't play (it stays on screen as if it's in idle mode)

---

Steps to Reproduce
1) Spawn a SV10 (give fa_sv10)
2) Fire off both shells
3) Hold down your primary fire button and then sprint)

**Comment by Winning117** [comment]
Video of issue for reference https://www.youtube.com/watch?v=G-npiXNKfd8

**Comment by felis-catus** [comment]
Fixed in src-r7354.
