### ISSUE TITLE
(nmo_fema) Wheel prop seemingly collides with player

### ISSUE THREAD

**Issue by Smil3yRiley** [nmrih/source-game#594]
![2014-07-05_00011](https://cloud.githubusercontent.com/assets/3606650/3487534/6fa22fea-0485-11e4-8723-64e7c61f0dab.jpg)

When you have to pick up the turn wheel prop in nmo_fema, it feels like that the model is solid and not non solid as it should be (normally when you pick up a prop, the code temporarily makes it non solid to other players until you drop it)

**Comment by AtheistNMRiH** [comment]
looks like it is obsolete now, since crank have another model now and works fine
