### ISSUE TITLE
Climbing/jumping zombies get stuck in players.

### ISSUE THREAD

**Issue by Keldorn074** [nmrih/source-game#60]
I keep dying all the time while playing from this bug, so I feel its worth mentioning. If you're standing at a window and a zombie is climbing down it will get stuck in your body then attack you. This leaves you specially vulnerable if all you  got is melee/shove and depleted stamina.

![2013-04-12_00004](https://f.cloud.github.com/assets/3848484/375749/34f54130-a3cd-11e2-928f-7077f47feedd.jpg)

<hr>

To reproduce
2. Open nms_notld
1. Go to a window from the interior and wait for a zombie to climb in and down from it.

**Comment by Winning117** [comment]
Confirmed fixed in src-r4388/dev-r8769, needs to be closed.
