### ISSUE TITLE
(code) Odd spectator behavior if spectating someone who got extracted or died

### ISSUE THREAD

**Issue by Smil3yRiley** [nmrih/source-game#606]
This issue seems to be more common with the advent of our respawn changes, the video that'll be linked will summarize what is occuring

https://www.youtube.com/watch?v=D3jufbiSDwQ

You're essentially locked in place, and cannot move; if you try to change spectator view you'll also bring up your first person arms.

**Comment by felis-catus** [comment]
Is this still an issue?

**Comment by felis-catus** [comment]
Can't repro at all, closing.
