### ISSUE TITLE
Person won't stop looking at gun. I want to reload

### ISSUE THREAD

**Issue by acenewton1** [nmrih/source-game#608]
When ever I go to pick up a gun, my character thinks he wants to see how much ammo is in there. I do not hold R down at all. I just tap it. When i tap it, he wants to see how much ammo there is instead. I cannot fire. He thinks it's empty when it says there is 14 clips in it. 

I re-installed the game. It didn't fix.

**Comment by Winning117** [comment]
Can't be reproduced - should be closed.

**Comment by Winning117** [comment]
Not reproducible in src-r4388/dev-r8771, needs to be closed.
