### ISSUE TITLE
Chippants 12 rounds left looping

### ISSUE THREAD

**Issue by hayzzer** [nmrih/source-game#631]
When the sound "player/ammocheck/chippants/12rounds4.wav" is played, it's repeating until you don't stop it from console.

http://www.youtube.com/watch?v=hxJXOHJoRb4

**Comment by yomox9** [comment]
version 1.09.6 still have this bug....

**Comment by felis-catus** [comment]
Fixed in dev build r8714.

**Comment by Bubka3** [comment]
Issues still occurs at that build

**Comment by felis-catus** [comment]
In PVK2 we solved this issue by shipping a rebuilt sound.cache, IIRC some Valve games do this as well. If no better solution is found we could try that.

**Comment by Bubka3** [comment]
**Resolved Closure**
This issue has been closed as it has been resolved in the current dev build.
It will be available to the public in the next steam release. Thanks for reporting!

Additional comments: tested dev-r8722, windows
