### ISSUE TITLE
Spawn Points for nmo_brooklyn and nmo_cleopas

### ISSUE THREAD

**Issue by Breadman12** [nmrih/source-game#634]
nmo_cleopas: The spawn points are bugged/broken after the objective to climb over the gate. When I die, it hangs in spectate mode and has the message "Waiting for spawn point" appearing constantly.

nmo_brooklyn: The broken spawn points are after "Find the fuse to fix the elevator" and "Make way through apartments" objectives. 
My first try (fix elevator route) I died after the elevator ride, it had the massage "Waiting for spawn", then the level reset. 
Trying again (apartments) I committed suicide, then the message "Survivors have been overrun" appeared then the level reset.

I've been playing these maps solo and I had about 9-10+ re-spawn tokens in both maps.

**Comment by AtheistNMRiH** [comment]
won't fix brooklyn related issue since zombies cause that

**Comment by yomox9** [comment]
Mapper can fix respawn by force respawn. Map respawn player to far a way respawn point. and then Map teleport player to purpose zone.

**Comment by AtheistNMRiH** [comment]
but what if zombies are in spawn zone, player can get stuck in them

**Comment by AtheistNMRiH** [comment]
fixed cleopas related issue in r8721, need to be closed

**Comment by Bubka3** [comment]
We intend to to change the amount of units checked near respawns and also to fix a number of instances where you may get a "Waiting for spawn point.." sessions that will never respawn. However, that is for another code issue.

**Comment by DDysphie** [comment]
Cleopas spawns appear to be fixed in dev-r8785.

**Comment by DDysphie** [comment]
Cleopas is fixed and Brooklyn marked as wont fix (related to different code issue). Should be closed.
