### ISSUE TITLE
Achievement Toofer Pt. 2

### ISSUE THREAD

**Issue by at46** [nmrih/source-game#635]
I got "Toofer Pt. 2" without killing two zombie per bullet with a full mag of the JAE-700. Maybe I killed 12 or 13 with the 10 bullets but not 20.

**Comment by Bubka3** [comment]
We have identified the root cause of this (and another achievements). It will be fixed in the next patch. Thanks for reporting!

**Comment by AtheistNMRiH** [comment]
tested in src-r4388/dev-r8772, works fine
