### ISSUE TITLE
Hospital - flashlight bug

### ISSUE THREAD

**Issue by 2ndClassCitizen** [nmrih/source-game#638]
http://oi61.tinypic.com/9ht4y8.jpg

Not sure what to make of this.

**Comment by Winning117** [comment]
Still happens in src-r4388/dev-r8772. Need more testing to see how to reproduce it, but I am assuming it is similar to the issue with hovering names.

**Comment by felis-catus** [comment]
Link rot, closing.

**Comment by Winning117** [comment]
This was an issue with the light cone from a flashlight floating in the middle of the air without the flashlight actually being there (i.e. the player had left the area)
