### ISSUE TITLE
Name tags above players randomly float

### ISSUE THREAD

**Issue by 2ndClassCitizen** [nmrih/source-game#639]
http://oi60.tinypic.com/xfajxs.jpg

Names float and hold in mid-air even when players have left area.

**Comment by Fersigal** [comment]
#734 Duplicate

**Comment by Bubka3** [comment]
@felis-catus I believe we possibly discussed this before but I cant remember. Please advise.

**Comment by felis-catus** [comment]
It seems to occur when a player leaves PVS, as mentioned before by both me and essbuh. Will be looked into.

**Comment by Bubka3** [comment]
r4284

**Comment by Bubka3** [comment]
regression from change: - Nametags are often wrongly positioned

**Comment by felis-catus** [comment]
Should be fixed already in 1.10.
