### ISSUE TITLE
[nmo_lakeside] place you always get stuck in

### ISSUE THREAD

**Issue by Sphynxcatkillstreak** [nmrih/source-game#640]
If you walk down the stairs and jump behind the crate in one area of the map, you will automatically get stuck in there and there is nothing you can do to get out.

Screenshots:

http://steamcommunity.com/sharedfiles/filedetails/?id=310828589
http://steamcommunity.com/sharedfiles/filedetails/?id=310828633
http://steamcommunity.com/sharedfiles/filedetails/?id=310828678
http://steamcommunity.com/sharedfiles/filedetails/?id=310828711

**Comment by Fersigal** [comment]
Still works, although i have no clue why someone would want to do that lol
![20180118180126_1](https://user-images.githubusercontent.com/11538773/35110691-b864996c-fc79-11e7-845b-89a54f3b7f85.jpg)

**Comment by Winning117** [comment]
Confirmed fixed in src-r4367/dev-r8764.
