### ISSUE TITLE
sv_difficulty issue

### ISSUE THREAD

**Issue by durkhaz** [nmrih/source-game#641]
Some servers set the clientside sv_difficulty config entry to custom ones such as "pvp" and "dodgeball". 
This becomes an issue if that client tries to host their own game after joining such a server, since the corresponding .ctx file isn't present on their machine. It usually results in crashes when the player dies.

While this is probably just a minor issue, it might lead to confusion for new players.

**Comment by Bubka3** [comment]
Unable to reproduce anymore, creating a listen server sets the difficulty to the option chosen in the game settings before starting it.

If this is still an issue for you, please let us know.
