### ISSUE TITLE
Prop draw distance on arpley

### ISSUE THREAD

**Issue by Wazanator** [nmrih/source-game#648]
![2014-10-29_00002](https://cloud.githubusercontent.com/assets/2752911/4836219/c7627f96-5fc0-11e4-9b88-43c7fbe48980.jpg)
![2014-10-29_00003](https://cloud.githubusercontent.com/assets/2752911/4836218/c72f204c-5fc0-11e4-9488-412e57ebe754.jpg)

Prop pops into view while entering this house

**Comment by AtheistNMRiH** [comment]
fixed in r8729

**Comment by Winning117** [comment]
Confirmed in r8757, needs to be closed
