### ISSUE TITLE
Blowtorch sound/particle loop (nms_notld)

### ISSUE THREAD

**Issue by Smil3yRiley** [nmrih/source-game#65]
Happened to me on nms_notld, when manofwar unweld through the basement door the blowtorch particle was still playing on the weapon (along with the sound)

![2013-04-13_00001](https://f.cloud.github.com/assets/3606650/377090/379b8fd2-a479-11e2-963b-1378d8107f71.jpg)

Cleric and Sota saw the particles but didn't hear the sound.

The particle itself disappeared when he unwelded through the 2nd shed's door but the sound kept looping from the weapon itself, and wouldn't stop until the next round started.

Happened on revision 4716

**Comment by Fersigal** [comment]
#778

**Comment by Winning117** [comment]
Felis fixed this issue in dev-r8749, confirmed and needs to be closed.
