### ISSUE TITLE
A few nitpicky animation-related issues

### ISSUE THREAD

**Issue by billionlioe** [nmrih/source-game#667]
A couple of things, the molotov doesn't play the walk animation, I checked the model and it does have a walk sequence but it just does not play it. Secondly, the super x3 doesn't eject a shell when the last shot animation plays.

To recreate the first, just spawn a molotov (give exp_molotov) and walk around. For the second, spawn the gun (give fa_superx3), unload it and then reload just one shell, the following shot will not eject a shell.

**Comment by AtheistNMRiH** [comment]
not only molotov, all exp_ haven't walk animation

**Comment by Winning117** [comment]
Merged with [#927](https://github.com/nmrih/source-game/issues/927), needs to be closed.
