### ISSUE TITLE
(code) skybox doesn't render on 3d scope

### ISSUE THREAD

**Issue by Smil3yRiley** [nmrih/source-game#672]
If you have the M16A4 and look up at the skybox, it doesn't render at all.

![2015-02-05_00003](https://cloud.githubusercontent.com/assets/3606650/6072179/52f00c4a-ad64-11e4-9e8e-2c99c3880380.jpg)

**Comment by Fersigal** [comment]
can confirm, only works for 3D skybox though, bug doesn't occur with sniper rifle scopes though. It's important to note that it only affects the 3D skybox and not the "skybox" as mentioned in the title
Proof:
**Skybox**
![20180118175858_1](https://user-images.githubusercontent.com/11538773/35110550-57fc200e-fc79-11e7-8b7f-6cfac241a428.jpg)
**3D skybox**
![20180118175908_1](https://user-images.githubusercontent.com/11538773/35110566-636bae32-fc79-11e7-8c16-52669c6e48ad.jpg)

**Comment by felis-catus** [comment]
Closing as wontfix.
