### ISSUE TITLE
Brooklyn - Item underneath map

### ISSUE THREAD

**Issue by 2ndClassCitizen** [nmrih/source-game#673]
In the parking lot after you jump out of the window, in the corner there is a weapon or item, but it is underneath the map; you can drag it around somewhat but you cannot pick it up.

**Comment by AtheistNMRiH** [comment]
I've checked all corners, didn't find anything, maybe it was fixed or I need screenshot of place

**Comment by AtheistNMRiH** [comment]
maybe it is related to "item's shadow bug" which isn't fully investigated, anyway that need to be closed or change it to code
