### ISSUE TITLE
(code) Late joiner bug in casual mode, player 'spawns' in invisibly

### ISSUE THREAD

**Issue by Smil3yRiley** [nmrih/source-game#675]
There's a chance for a late joiner to initially spawn in when they fully connect into the server as an invisible survivor mid round near active players if they don't exit out of the Loading Splash Screen. The problem resolves itself the second the late joiner closes the Loading Splash Screen (they properly spawn in)

![2015-02-05_00001](https://cloud.githubusercontent.com/assets/3606650/6072829/f8f4aa9a-ad6b-11e4-9823-9eefc15ee054.jpg)

---

Steps to Reproduce
1) Join a server that's running on Casual Difficulty (sv_difficulty casual)
2) Play through a map
3) Have someone else join the server mid way through your current playthrough
4) Tell them that when their computer's finished connecting to the server, to not click on the Join Game button

If done right, you should see a floating weapon beside you and if you try to walk into it, you'll be repelled by it (soft collision from the player model that should be there but isn't there)

**Comment by felis-catus** [comment]
Tracking in #1006
