### ISSUE TITLE
(models) Pistol animations lock up when in ironsight mode and unequipping maglite

### ISSUE THREAD

**Issue by Smil3yRiley** [nmrih/source-game#684]
Reminder for this to get resolved (we know what this is)

Steps to Reproduce

1) Grab a pistol (fa_m92fs, fa_mkiii, fa_sw686, fa_glock17, fa_1911) and grab a maglite (item_maglite)
2) Equip the pistol and enter ironsight mode
3) Hit F to bring out your maglite
4) Hit F to unequip your maglite while still in ironsight mode

The pistol animation locks up for a noticeable second, leaving the player vulnerable

**Comment by Winning117** [comment]
Player no longer has an animation freeze. Confirmed fixed in src-r4388/dev-r8771, needs to be closed.

**Comment by Winning117** [comment]
Confirmed still an issue in src-r4388/dev-r8771.

**Comment by Winning117** [comment]
Video: https://www.youtube.com/watch?v=c4pbYbgkrcI

**Comment by felis-catus** [comment]
Fixed in src-r7325.
