### ISSUE TITLE
Sound bug with the Ruger 10/22, both of them.

### ISSUE THREAD

**Issue by Drottnar** [nmrih/source-game#689]
(This is for the version 1.09.4)
The sound of the Ruger rifles shooting have this weird sound bug, randomly at the end of the shot there is a screeching sound.

Not sure if you'll be able to recreate it but still wanting to show you.

All I do to get this to happen is to shoot the guns at the wall (or any thing), wait for two or three seconds and you'll be able to hear it.

https://youtu.be/_0YOHziwodc

The video should be able to show you the sound but kind of bad to show you it's the shooting and not the reload.

> Processor Information:
>     Vendor:  AuthenticAMD
>     CPU Family:  0x15
>     CPU Model:  0x1
>     CPU Stepping:  0x2
>     CPU Type:  0x0
>     Speed:  3592 Mhz
>     8 logical processors
>     4 physical processors
>     HyperThreading:  Supported
>     FCMOV:  Supported
>     SSE2:  Supported
>     SSE3:  Supported
>     SSSE3:  Supported
>     SSE4a:  Supported
>     SSE41:  Supported
>     SSE42:  Supported
> 
> Operating System Version:
>     Windows 7 (64 bit)
>     NTFS:  Supported
>     Crypto Provider Codes:  Supported 311 0x0 0x0 0x0
> 
> Video Card:
>     Driver:  NVIDIA GeForce GTX 650
>    DirectX Driver Name:  nvd3dum.dll
>     Driver Version:  9.18.13.2723
>     DirectX Driver Version:  9.18.13.2723
>    Driver Date: 12 Sept 2013
>     OpenGL Version: 4.3
>     Desktop Color Depth: 32 bits per pixel
>     Monitor Refresh Rate: 60 Hz
>     DirectX Card: NVIDIA GeForce GTX 650
>     VendorID:  0x10de
>     DeviceID:  0xfc6
>     Number of Monitors:  2
>     Number of Logical Video Cards:  2
>     No SLI or Crossfire Detected
>     Primary Display Resolution:  1920 x 1080
>     Desktop Resolution: 3200 x 1080
>     Primary Display Size: 26.65" x 15.00"  (30.55" diag)
>                                             67.7cm x 38.1cm  (77.6cm diag)
>     Primary Bus: PCI Express 16x
>     Primary VRAM: 1024 MB
>     Supported MSAA Modes:  2x 4x 8x 
> 
> Sound card:
>    Audio device: Speakers (Corsair Vengeance 2100)
> 
> Memory:
>     RAM:  16341 Mb
> 
> Miscellaneous:
>     UI Language:  English
>     Microphone:  Microphone (Corsair Vengeance 2100)
>     Media Type:  DVD
>     Total Hard Disk Space Available:  4835971 Mb
>     Largest Free Hard Disk Block:  77503 Mb
>     OS Install Date: Jan 01 1970
>     Game Controller: None detected

**Comment by Smil3yRiley** [comment]
Sound cache file needs to be deleted, thanks for the reminder
