### ISSUE TITLE
Toxeth - The wall can be blown up with random items

### ISSUE THREAD

**Issue by ThoughTMusic** [nmrih/source-game#696]
In Toxeth, instead of dropping in the gas tank to blow up the wall to the graveyard, other items can be carried and dropped in it's place which will still cause the explosion. 

Items I'm aware of:

Walkie Talkie
Water Melon
Small White Tub

**Comment by Fersigal** [comment]
#716

**Comment by AtheistNMRiH** [comment]
fixed in r8735

**Comment by Winning117** [comment]
Confirmed fixed in src-r4367/dev-r8764, needs to be closed.
