### ISSUE TITLE
minor colision bug in nmo_broadway.

### ISSUE THREAD

**Issue by Legofan94** [nmrih/source-game#702]
Near the crashed ambulance, underneath the elevated train tracks and Camilla's diner, there is a construction barrier that lacks collision. You can walk right through it. 

![image](https://cloud.githubusercontent.com/assets/11614316/6781679/ba66fe88-d145-11e4-97e1-6b4c3bca87c8.png)

**Comment by Fersigal** [comment]
Not really a bugg, but the thing used to block off zombies and you could camp there for a long time. Guess that's why they removed it :)

**Comment by AtheistNMRiH** [comment]
yes, not a bug, need to be closed
