### ISSUE TITLE
Crawling Issue

### ISSUE THREAD

**Issue by Fersigal** [nmrih/source-game#703]
You can easily jump on a crawler and go further at the back of a crawler and normal zombies are unable to hit you.
![2015-03-24_00001](https://cloud.githubusercontent.com/assets/11538773/6810152/488af9c0-d25f-11e4-8c01-80d5535dd3c2.jpg)

**Comment by AtheistNMRiH** [comment]
They are still wip, so i think it's normal

**Comment by Winning117** [comment]
Still an issue in src-r4405/dev-r8773.

**Comment by felis-catus** [comment]
This is fixed in 1.11+.
