### ISSUE TITLE
Showing zones problem on nms_northway(1.09.3)

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#705]
![nms_northway0000](https://cloud.githubusercontent.com/assets/11333747/6841379/23247180-d3bc-11e4-9f33-8559709c9de3.jpg)
Sometimes it doesn't show all zones. I dont know how to reproduce, it just happened randomly

**Comment by Bubka3** [comment]
Duplicate of #531 

Please follow that issue for all future updates.
