### ISSUE TITLE
Nmo_broadway map bugs

### ISSUE THREAD

**Issue by Fersigal** [nmrih/source-game#706]
Location Bugs Use E on the keypad (press control key and press any direction key and hold it, you can't jump though)
![2015-03-27_00035](https://cloud.githubusercontent.com/assets/11538773/6875289/a63a1212-d4bd-11e4-98a6-5df9671d866e.jpg) 
![2015-03-27_00036](https://cloud.githubusercontent.com/assets/11538773/6875292/a645bd38-d4bd-11e4-9345-c68526b2be69.jpg) 
Zombie Boosting Bugs (these ones speak for themself i guess)
![2015-03-27_00005](https://cloud.githubusercontent.com/assets/11538773/6875261/a5c860cc-d4bd-11e4-9fd1-41bd33339a00.jpg)
![2015-03-27_00015](https://cloud.githubusercontent.com/assets/11538773/6875269/a5f0aa32-d4bd-11e4-90ce-af286ea38255.jpg) 
![2015-03-27_00017](https://cloud.githubusercontent.com/assets/11538773/6875271/a5f5cb52-d4bd-11e4-936d-193065cc5837.jpg) (on the tank, this is the start point)
![2015-03-27_00021](https://cloud.githubusercontent.com/assets/11538773/6875275/a6093e4e-d4bd-11e4-9c44-5d480a1d3cc8.jpg) 
![2015-03-27_00028](https://cloud.githubusercontent.com/assets/11538773/6875282/a622ed94-d4bd-11e4-9170-fd062b9f1ca5.jpg) 
![2015-03-27_00032](https://cloud.githubusercontent.com/assets/11538773/6875286/a62d77dc-d4bd-11e4-8edf-a67b2922b47c.jpg) 
![2015-03-27_00039](https://cloud.githubusercontent.com/assets/11538773/6875294/a64f1d88-d4bd-11e4-823e-20914d2668ca.jpg) 
![2015-03-27_00040](https://cloud.githubusercontent.com/assets/11538773/6875293/a64edd14-d4bd-11e4-8428-bfda6c0cffc0.jpg) Step Image for Boosting Bugg
![2015-03-27_00041](https://cloud.githubusercontent.com/assets/11538773/6875295/a651d280-d4bd-11e4-8952-0da11e5f3d47.jpg) 

Metal Fence Bugs:
Solution: Player clipping the part above it so the player can't get onto the handle of the door
![2015-03-27_00003](https://cloud.githubusercontent.com/assets/11538773/6875256/a5c12726-d4bd-11e4-9211-9c2f172b0aea.jpg)
![2015-03-27_00011](https://cloud.githubusercontent.com/assets/11538773/6875266/a5dfa9c6-d4bd-11e4-961b-09d6bd0c2b23.jpg) 
![2015-03-27_00016](https://cloud.githubusercontent.com/assets/11538773/6875270/a5f46640-d4bd-11e4-9ba9-f959a3036816.jpg) 
![2015-03-27_00026](https://cloud.githubusercontent.com/assets/11538773/6875280/a619b062-d4bd-11e4-84b4-63afd483c3b0.jpg) 
![2015-03-27_00027](https://cloud.githubusercontent.com/assets/11538773/6875281/a6223a34-d4bd-11e4-89d9-3d57bf56e2d7.jpg) Next Image MFB
![2015-03-27_00033](https://cloud.githubusercontent.com/assets/11538773/6875287/a63829f2-d4bd-11e4-84b5-c4e569e21603.jpg) 
Invulnerable Bugs: 
![2015-03-27_00002](https://cloud.githubusercontent.com/assets/11538773/6875257/a5c13748-d4bd-11e4-9c9b-91aedae5e36b.jpg) 
![2015-03-27_00009](https://cloud.githubusercontent.com/assets/11538773/6875263/a5d9d12c-d4bd-11e4-9dbb-d51e8cade4c3.jpg) 
![2015-03-27_00010](https://cloud.githubusercontent.com/assets/11538773/6875264/a5dc6b3a-d4bd-11e4-9965-f27617e96123.jpg) 
![2015-03-27_00012](https://cloud.githubusercontent.com/assets/11538773/6875265/a5ded8fc-d4bd-11e4-8440-cfe52ec5d626.jpg) 
![2015-03-27_00018](https://cloud.githubusercontent.com/assets/11538773/6875272/a5f7dd84-d4bd-11e4-89cf-63ee53bd5537.jpg) 
![2015-03-27_00023](https://cloud.githubusercontent.com/assets/11538773/6875278/a60dc090-d4bd-11e4-8e84-9cda163a4f6e.jpg)
![2015-03-27_00025](https://cloud.githubusercontent.com/assets/11538773/6875279/a60f6404-d4bd-11e4-89f6-c3e228ff2c63.jpg)
![2015-03-27_00029](https://cloud.githubusercontent.com/assets/11538773/6875283/a6252690-d4bd-11e4-880d-6a316055b1d1.jpg) 
![2015-03-27_00030](https://cloud.githubusercontent.com/assets/11538773/6875284/a62911c4-d4bd-11e4-8413-dee938ffb3c2.jpg) You can turn the Invulnerable bugg into a Zombie Boosting Bugg.

Other Bugs:
Roof Bug at the beginning: go at the roof go on the ledge of the roof try to crouch fast and if you're lucky you can camp on the fence it's tricky though but worth mentioning cause it's a good shortcut
![2015-03-27_00004](https://cloud.githubusercontent.com/assets/11538773/6875259/a5c76884-d4bd-11e4-8de1-aa265898cc37.jpg)
Invisible Ledge you can crouch jump onto
![2015-03-27_00006](https://cloud.githubusercontent.com/assets/11538773/6875258/a5c72752-d4bd-11e4-8462-4c34e956e15c.jpg) After the closet you can drop or throw items and players won't be able to retrieve them (mostly small items)
![2015-03-27_00007](https://cloud.githubusercontent.com/assets/11538773/6875260/a5c87896-d4bd-11e4-8cdd-47f4e8b29b5e.jpg) Might look like a boosting bugg but you can actually get up the closet if you crouch jump from the window ledge.
![2015-03-27_00013](https://cloud.githubusercontent.com/assets/11538773/6875267/a5e12a44-d4bd-11e4-8411-71b0ae68c032.jpg) Welding bug: if you stay at the left side of the door and you aim at the right side with the welder you will get lifted up (also on Junction)
![2015-03-27_00022](https://cloud.githubusercontent.com/assets/11538773/6875276/a60b5710-d4bd-11e4-93d0-a0e3f8e51bf1.jpg) (could be also a zombie boosting bug but you can actually get pretty solid up the other piece just by crouch jumping)
![2015-03-27_00031](https://cloud.githubusercontent.com/assets/11538773/6875285/a6290e40-d4bd-11e4-8bee-ba390d19c97f.jpg) You can get stuck between the metal gate for example if you see the extraction point and you went of the ledge to the door and then you opened the metal gate and you see the train appearing then, next ur stuck between the metal fence and u can't get out.
![2015-03-27_00037](https://cloud.githubusercontent.com/assets/11538773/6875291/a6444b56-d4bd-11e4-9602-e212dd0f1e19.jpg) 
Go between the Doors of the train at the moment it's gonna shut down then go back and the train door should be opened.
![2015-03-27_00043](https://cloud.githubusercontent.com/assets/11538773/6875297/a65eecea-d4bd-11e4-9ea1-f72cb2dda3cc.jpg)

**Comment by Fersigal** [comment]
This might look Sloppy at first sight but i need some work first

**Comment by kilimouli** [comment]
Zombie Boosting Bugs::

![1f 1](https://cloud.githubusercontent.com/assets/11585701/6875966/914f267a-d4c3-11e4-84a0-4977ba8bf60b.jpg)

![1f 2](https://cloud.githubusercontent.com/assets/11585701/6875967/94b26f52-d4c3-11e4-939f-f042446c6783.jpg)

![1f 3](https://cloud.githubusercontent.com/assets/11585701/6875970/9760e86e-d4c3-11e4-92c8-1c6dc2945c3b.jpg)

![a5c860cc-d4bd-11e4-9fd1-41bd33339a00](https://cloud.githubusercontent.com/assets/11585701/6875972/9a244118-d4c3-11e4-9c96-63eb4e4200ea.jpg)

![a5c12726-d4bd-11e4-9211-9c2f172b0aea](https://cloud.githubusercontent.com/assets/11585701/6875973/9c63c1d8-d4c3-11e4-9349-f862f58a8ea6.jpg)

![a5c76884-d4bd-11e4-8de1-aa265898cc37](https://cloud.githubusercontent.com/assets/11585701/6875976/9fae3170-d4c3-11e4-8412-0beac97f0012.jpg)

![a5dfa9c6-d4bd-11e4-961b-09d6bd0c2b23](https://cloud.githubusercontent.com/assets/11585701/6875978/a1eb3cda-d4c3-11e4-9e94-cb3c48b90d76.jpg)

![a5f5cb52-d4bd-11e4-936d-193065cc5837](https://cloud.githubusercontent.com/assets/11585701/6875981/a69879fa-d4c3-11e4-8241-70e38e439910.jpg)

![a62d77dc-d4bd-11e4-8edf-a67b2922b47c](https://cloud.githubusercontent.com/assets/11585701/6875983/aaae58b6-d4c3-11e4-9c0d-97c77589d00a.jpg)

![a62d77dc-d4bd-11e4-8edf-a67b2922b47c](https://cloud.githubusercontent.com/assets/11585701/6875996/c279e14a-d4c3-11e4-8d95-a1e47123f80a.jpg)

![a64f1d88-d4bd-11e4-823e-20914d2668ca](https://cloud.githubusercontent.com/assets/11585701/6875998/c59b3f5e-d4c3-11e4-8f04-68da5c45ac4f.jpg)

![a619b062-d4bd-11e4-84b4-63afd483c3b0](https://cloud.githubusercontent.com/assets/11585701/6875999/c8371bfc-d4c3-11e4-9fff-965312ddddc8.jpg)

![a6223a34-d4bd-11e4-89d9-3d57bf56e2d7](https://cloud.githubusercontent.com/assets/11585701/6876001/ca870570-d4c3-11e4-9dd9-52254f0823d1.jpg)

![a6290e40-d4bd-11e4-8bee-ba390d19c97f](https://cloud.githubusercontent.com/assets/11585701/6876002/cd3c66c0-d4c3-11e4-87b9-09dd9c19f93c.jpg)

![a6384cb6-d4bd-11e4-8137-8acfff55f9bc](https://cloud.githubusercontent.com/assets/11585701/6876005/cfd0bf94-d4c3-11e4-830b-71ed101706e1.jpg)

![a62911c4-d4bd-11e4-8413-dee938ffb3c2](https://cloud.githubusercontent.com/assets/11585701/6876007/d3f8a046-d4c3-11e4-9220-223878b67ba2.jpg)

![a6252690-d4bd-11e4-880d-6a316055b1d1](https://cloud.githubusercontent.com/assets/11585701/6876009/d7928712-d4c3-11e4-9c57-74df3daa596b.jpg)

![a6223a34-d4bd-11e4-89d9-3d57bf56e2d7](https://cloud.githubusercontent.com/assets/11585701/6876011/d9c4a362-d4c3-11e4-9040-f108be5760a6.jpg)

![cin 2](https://cloud.githubusercontent.com/assets/11585701/6876015/ddbad1d0-d4c3-11e4-9e72-9c4e5f8d498b.jpg)

![cin 3](https://cloud.githubusercontent.com/assets/11585701/6876018/e10b1f8e-d4c3-11e4-83bc-26997f82a61e.jpg)

**Comment by kilimouli** [comment]
Location bug 

![a63a1212-d4bd-11e4-98a6-5df9671d866e](https://cloud.githubusercontent.com/assets/11585701/6876090/65c275d8-d4c4-11e4-89b2-24e07a3664b7.jpg)

![a645bd38-d4bd-11e4-9345-c68526b2be69](https://cloud.githubusercontent.com/assets/11585701/6876099/73ba665a-d4c4-11e4-9e9e-249f19303046.jpg)

**Comment by Smil3yRiley** [comment]
Keep them coming, and do it for the other maps if possible (will be fixing the remainder of these over the weekend

Thank you!

**Comment by Fersigal** [comment]
No thank you guys for making this game actually good up to date :+1:

**Comment by Fersigal** [comment]
I'm gonna try to do all of that tomorrow :sweat_smile:

**Comment by AtheistNMRiH** [comment]
Really good job!

**Comment by AtheistNMRiH** [comment]
What about LatisARG videos? Maybe need to write bugs from there here?

**Comment by Fersigal** [comment]
Some of em are LatisARG but i'm pretty sure i got most of em: there's also one at the fence but once the train door bug is fixed that isn't worth mentioning anymore.

**Comment by Fersigal** [comment]
![2015-10-03_00002](https://cloud.githubusercontent.com/assets/11538773/10263887/c02b4eb8-69fd-11e5-968c-e28cfb635aed.jpg)
JUS = Jump up spot

**Comment by AtheistNMRiH** [comment]
fixed in r8724

**Comment by Fersigal** [comment]
![image](https://user-images.githubusercontent.com/11538773/38453135-26fa7d0a-3a51-11e8-906c-ea1a3d6e3607.png)
still there
