### ISSUE TITLE
Nms compilation map Bugs 

### ISSUE THREAD

**Issue by Fersigal** [nmrih/source-game#710]
ZBB : Zombie boosting Bugs
OB: Other Bugs
TB: Texture Bugs
IB: Invulnerable Bugs
CB: Collision Bugs
MFB: Metal Fence Bugs
NMS CAMPBLOOD
![2015-03-28_00071](https://cloud.githubusercontent.com/assets/11538773/6882194/eba15abc-d57c-11e4-81b8-207c9a932641.jpg) OB (zombies don't seem interested in you)
There's also a piece of boat that u can pick up and use to barricade. Zombies won't be able to get in
![2015-03-28_00073](https://cloud.githubusercontent.com/assets/11538773/6882197/eba47d3c-d57c-11e4-8014-2f0eddfdd288.jpg) ZBB
![2015-03-28_00074](https://cloud.githubusercontent.com/assets/11538773/6882195/eba26678-d57c-11e4-82f8-1c5da3a56d4b.jpg) ZBB
NMS ARPLEY
![2015-03-28_00043](https://cloud.githubusercontent.com/assets/11538773/6881801/059dc788-d56f-11e4-9fd2-b32c6cbb28fa.jpg) Texturing Bug (all those gates don't have textures at the sides of the inside meaning that it's transparent)
![2015-03-28_00044](https://cloud.githubusercontent.com/assets/11538773/6881802/059ea6ee-d56f-11e4-8660-90822a52692d.jpg) IB
![2015-03-28_00045](https://cloud.githubusercontent.com/assets/11538773/6881803/05a108d0-d56f-11e4-83f5-cf6397f2709e.jpg) OB (you can get behind the gate while it's still being unwelded by going on the ledge of the bridge and jumping on the ledge of the side where the water is)
![2015-03-28_00046](https://cloud.githubusercontent.com/assets/11538773/6881805/05b2b36e-d56f-11e4-9d8e-5e2300a8a1c1.jpg) Metal Fence Bug
![2015-03-28_00047](https://cloud.githubusercontent.com/assets/11538773/6881807/05b46da8-d56f-11e4-83ce-eeb5d5ead623.jpg) IB
![2015-03-28_00048](https://cloud.githubusercontent.com/assets/11538773/6881804/05b265e4-d56f-11e4-8df1-b1c1500d3cd6.jpg) OB (you can bait zombies at the sides and they will stay there untill you get off)
![2015-03-28_00049](https://cloud.githubusercontent.com/assets/11538773/6881806/05b3e3e2-d56f-11e4-8636-f2969ac8c26a.jpg) IB (you can get up the boarding structure by going onto the table and then jumping on the barricade structure)
![2015-03-28_00050](https://cloud.githubusercontent.com/assets/11538773/6881808/05b4c23a-d56f-11e4-8f0e-4055e5db1ed7.jpg) Texture bug (If you go at the water part there's a wall and if you face the wall you should see true it)
![2015-03-28_00051](https://cloud.githubusercontent.com/assets/11538773/6881809/05b63bc4-d56f-11e4-9985-7ed11253c61c.jpg) ZBB
![2015-03-28_00052](https://cloud.githubusercontent.com/assets/11538773/6881810/05c71e3a-d56f-11e4-9e67-cb5ca1329b6f.jpg) ZBB (Most crucial bug in the map, you can get out this way and go at the roof of the pool or behind the player clipped fences)

NMS SILENCE
![2015-03-28_00061](https://cloud.githubusercontent.com/assets/11538773/6881819/05e38250-d56f-11e4-88a8-bbfbb9b8b383.jpg) IB
![2015-03-28_00062](https://cloud.githubusercontent.com/assets/11538773/6881818/05e3314c-d56f-11e4-9b0a-68a902ae65d3.jpg) IB (at the side entrance from the screenshot shown before)
![2015-03-28_00063](https://cloud.githubusercontent.com/assets/11538773/6881821/05e682de-d56f-11e4-82aa-ebf2374542ab.jpg) IB (at the front of the church)
![2015-03-28_00064](https://cloud.githubusercontent.com/assets/11538773/6881823/05f5d78e-d56f-11e4-8638-e383a086410c.jpg) Collision bug (you can take the items from the welding spot when it's not even welded)
![2015-03-28_00067](https://cloud.githubusercontent.com/assets/11538773/6881824/05f88754-d56f-11e4-931d-1d1f066c95e8.jpg) ZBB (at a zombie spawn point)
![2015-03-28_00066](https://cloud.githubusercontent.com/assets/11538773/6882619/00dac878-d58c-11e4-9a0c-040a529714f4.jpg) IB (at the extraction point where u have to blow up the gate)
NMS FLOODED
![2015-03-28_00075](https://cloud.githubusercontent.com/assets/11538773/6882130/fe8dfe9c-d57b-11e4-8d69-25cf0c8ee966.jpg) Texture Bug (i can't take screenshots while crouching but you should see why it's a texture bug, it's mainly underwater perspective)
![2015-03-28_00076](https://cloud.githubusercontent.com/assets/11538773/6882132/fe8f496e-d57b-11e4-81cf-5f064ee712ca.jpg) IB (at the car)
![2015-03-28_00077](https://cloud.githubusercontent.com/assets/11538773/6882131/fe8e2c50-d57b-11e4-9acd-8e48af43b910.jpg) IB same bug but then from a higher point
![2015-03-28_00078](https://cloud.githubusercontent.com/assets/11538773/6882129/fe8cbf3c-d57b-11e4-8979-046985187b0d.jpg) IB (also at the car)
![2015-03-28_00079](https://cloud.githubusercontent.com/assets/11538773/6882128/fe8cce0a-d57b-11e4-979a-8ebde137e231.jpg) OB Zombies tend to get stuck under Zone A  or behind the car
![2015-03-28_00080](https://cloud.githubusercontent.com/assets/11538773/6882133/fea0b38e-d57b-11e4-8d15-8a2d923cf520.jpg) IB
![2015-03-28_00081](https://cloud.githubusercontent.com/assets/11538773/6882136/fea49c4c-d57b-11e4-8a77-7bd70af34009.jpg) IB 
![2015-03-28_00082](https://cloud.githubusercontent.com/assets/11538773/6882134/fea48b08-d57b-11e4-9263-9588ed73c141.jpg) IB
![2015-03-28_00083](https://cloud.githubusercontent.com/assets/11538773/6882135/fea4cb86-d57b-11e4-8346-c4c6b04ca86f.jpg) Zombies tend to get stuck sometimes between the crank door and the wall)
![2015-03-28_00084](https://cloud.githubusercontent.com/assets/11538773/6882137/fea6f82a-d57b-11e4-9bf9-a79c814f7f56.jpg) Zombies also tend to get stuck sometimes here :cow: 
![2015-03-28_00085](https://cloud.githubusercontent.com/assets/11538773/6882138/fea9508e-d57b-11e4-9437-ff650ae3fb17.jpg) Collision bug (zombies can't dmg or grab you while you stay behind the metal railing of the stairs)
![2015-03-28_00086](https://cloud.githubusercontent.com/assets/11538773/6882139/feb8e774-d57b-11e4-9aae-cb16a941e473.jpg) Collision Bug (same as previous)
![2015-03-28_00087](https://cloud.githubusercontent.com/assets/11538773/6882141/febc978e-d57b-11e4-985b-c7412e791464.jpg) OB (you can defend the zone while you are at the corner between the crank gate and the wall)
NMS NOTLD
![2015-03-28_00098](https://cloud.githubusercontent.com/assets/11538773/6882151/feebeee4-d57b-11e4-87a3-e10799abdd42.jpg) IB
![2015-03-28_00099](https://cloud.githubusercontent.com/assets/11538773/6882154/feecee3e-d57b-11e4-8ace-b6b78199b4e1.jpg) IB
![2015-03-28_00102](https://cloud.githubusercontent.com/assets/11538773/6882155/feee1098-d57b-11e4-845e-206b802079d2.jpg) ZBB (on the small construction)
![2015-03-28_00103](https://cloud.githubusercontent.com/assets/11538773/6882156/fef5da9e-d57b-11e4-8deb-d2c63ae5a5fb.jpg) ZBB (the abandoned house)
NMS NORTHWAY 
![2015-03-28_00104](https://cloud.githubusercontent.com/assets/11538773/6882157/ff060586-d57b-11e4-8817-134f3c479083.jpg) OB Zombies get stuck here

**Comment by AtheistNMRiH** [comment]
Zombies get stuck there on nms_arpley
![nms_arpley0000](https://cloud.githubusercontent.com/assets/11333747/6884346/1c3f1178-d618-11e4-9f9f-950e5afe0433.jpg)
![nms_arpley0001](https://cloud.githubusercontent.com/assets/11333747/6884348/2c1cba50-d618-11e4-9740-93f2d5e3791a.jpg)
![nms_arpley0002](https://cloud.githubusercontent.com/assets/11333747/6884347/25317cc6-d618-11e4-890a-57f2d3c05393.jpg)

**Comment by AtheistNMRiH** [comment]
fixed ransack related issues in r8716

**Comment by Fersigal** [comment]
Alright gonna cleanse them up and put them as a seperate thread then for possible future references

**Comment by AtheistNMRiH** [comment]
fixed arpley related issues in r8729

**Comment by AtheistNMRiH** [comment]
fixed campblood related issues in r8737

**Comment by AtheistNMRiH** [comment]
fixed silence related issues in r8738

**Comment by AtheistNMRiH** [comment]
fixed northway issue in r8739

**Comment by Bubka3** [comment]
Maps left on this issue:
NMS CAMPBLOOD
NMS NOTLD

**Comment by Fersigal** [comment]
campblood was fixed

**Comment by AtheistNMRiH** [comment]
yeah, flooded and notld left only

**Comment by Fersigal** [comment]
Oh i made this long time ago, i'd say northway is perfectly fine as how the map goes, i think there are some several oddities where zombies get stuck ( back of cellar, because of it not being welded) and the fact that zombies sometimes do a nifty amount of time to get there. Another thing is that you can use certain spots inside the house to gain invulnerability over the zombies. Another thing is that zombies can  climb the windows and get stuck in people.

I love soloing notld, but personally i used to love Survival when it was more hardcore, i feel like it has lost its charm over the years a bit.

**Comment by AtheistNMRiH** [comment]
fixed notld issues in r8795, post can be marked as Completed
