### ISSUE TITLE
Nmo_lakeside map bugs 

### ISSUE THREAD

**Issue by Fersigal** [nmrih/source-game#712]
Zombie Boosting Bugs:
![2015-03-29_00001](https://cloud.githubusercontent.com/assets/11538773/6884635/0cd71a8e-d5fd-11e4-9318-69b9ef1ed7f5.jpg) 
![2015-03-29_00003](https://cloud.githubusercontent.com/assets/11538773/6884639/0ce103be-d5fd-11e4-8c8e-d4ce8f4d6b90.jpg) 
![2015-03-29_00011](https://cloud.githubusercontent.com/assets/11538773/6884646/0d3f78ae-d5fd-11e4-8459-fe398479334e.jpg) 
![2015-03-29_00014](https://cloud.githubusercontent.com/assets/11538773/6884649/0d42cc5c-d5fd-11e4-8d90-674adbcf41b7.jpg) 
![2015-03-29_00015](https://cloud.githubusercontent.com/assets/11538773/6884650/0d514af2-d5fd-11e4-917a-d21dc48f4207.jpg) 
![2015-03-29_00019](https://cloud.githubusercontent.com/assets/11538773/6884654/0d5ad860-d5fd-11e4-94d4-fe40c5f21fa3.jpg) 
![2015-03-29_00020](https://cloud.githubusercontent.com/assets/11538773/6884655/0d5d5fb8-d5fd-11e4-8075-07c19a709786.jpg) 
![2015-03-29_00021](https://cloud.githubusercontent.com/assets/11538773/6884656/0d6919ca-d5fd-11e4-8a10-a9b09beb6463.jpg) 
![2015-03-29_00041](https://cloud.githubusercontent.com/assets/11538773/6884675/0f06a2d4-d5fd-11e4-93a8-cd2824cd7e4c.jpg) 
![2015-03-29_00037](https://cloud.githubusercontent.com/assets/11538773/6884670/0e9c3ade-d5fd-11e4-93eb-14798ca57c10.jpg) [at the rare crank objective]
![2015-03-29_00038](https://cloud.githubusercontent.com/assets/11538773/6884671/0e9c8192-d5fd-11e4-9b51-8fbfaabe7b1c.jpg) 
![2015-03-29_00024](https://cloud.githubusercontent.com/assets/11538773/6884659/0d70c4fe-d5fd-11e4-8bbc-68781d0ac90c.jpg) {might look a bit mindfucked but it is at the cellar opening}
![2015-03-29_00035](https://cloud.githubusercontent.com/assets/11538773/6884669/0e96de5e-d5fd-11e4-946b-77736aed3912.jpg)
![2015-03-29_00026](https://cloud.githubusercontent.com/assets/11538773/6884672/0e9c82e6-d5fd-11e4-90a6-c7901e20a906.jpg)
![2015-03-29_00028](https://cloud.githubusercontent.com/assets/11538773/6884678/1051cdb2-d5fd-11e4-88cc-b0482701ce7d.jpg)
![2015-03-29_00033](https://cloud.githubusercontent.com/assets/11538773/6884666/0e818a4a-d5fd-11e4-8010-f84ccdb3398a.jpg) [cargo]
![2015-03-29_00043](https://cloud.githubusercontent.com/assets/11538773/6884677/103d30be-d5fd-11e4-8ee8-01d8585dd317.jpg)
Invulnerable bugs:
![2015-03-29_00004](https://cloud.githubusercontent.com/assets/11538773/6884640/0ce34070-d5fd-11e4-8db3-2aec228e0bf2.jpg) 
![2015-03-29_00008](https://cloud.githubusercontent.com/assets/11538773/6884641/0d255316-d5fd-11e4-83bb-966ec0c98ef5.jpg) 
![2015-03-29_00009](https://cloud.githubusercontent.com/assets/11538773/6884644/0d3a108a-d5fd-11e4-9732-777d68d9f5cc.jpg) 
![2015-03-29_00012](https://cloud.githubusercontent.com/assets/11538773/6884647/0d40c5ba-d5fd-11e4-9d16-ad150b811c7a.jpg) 
![2015-03-29_00016](https://cloud.githubusercontent.com/assets/11538773/6884651/0d544d6a-d5fd-11e4-8057-00911a8c3867.jpg)
![2015-03-29_00017](https://cloud.githubusercontent.com/assets/11538773/6884652/0d57073a-d5fd-11e4-93f9-1b4eecb03541.jpg) {from the window you can jump on the tree}
![2015-03-29_00018](https://cloud.githubusercontent.com/assets/11538773/6884653/0d5871ec-d5fd-11e4-8ecc-bc095a93eb43.jpg)
![2015-03-29_00022](https://cloud.githubusercontent.com/assets/11538773/6884657/0d695bd8-d5fd-11e4-8da9-8c5e71cf58fb.jpg)
![2015-03-29_00025](https://cloud.githubusercontent.com/assets/11538773/6884660/0d765bbc-d5fd-11e4-8707-080376496907.jpg)
![2015-03-29_00030](https://cloud.githubusercontent.com/assets/11538773/6884664/0e7ea3fc-d5fd-11e4-85ed-fe0f8c67004b.jpg)
![2015-03-29_00034](https://cloud.githubusercontent.com/assets/11538773/6884667/0e844ca8-d5fd-11e4-99f9-fb13c9a0fabc.jpg)
![2015-03-29_00036](https://cloud.githubusercontent.com/assets/11538773/6884668/0e9604ca-d5fd-11e4-81ff-0c82ac2580eb.jpg) [also missing textures]
![2015-03-29_00039](https://cloud.githubusercontent.com/assets/11538773/6884676/0f296454-d5fd-11e4-835e-2badf20ac863.jpg)
![2015-03-29_00040](https://cloud.githubusercontent.com/assets/11538773/6884674/0f0529cc-d5fd-11e4-8791-05bd6f440d4e.jpg)
![2015-03-29_00042](https://cloud.githubusercontent.com/assets/11538773/6884673/0efeea12-d5fd-11e4-9dcb-fa1a53dc99a4.jpg)
Texture Bugs:
![2015-03-29_00007](https://cloud.githubusercontent.com/assets/11538773/6884643/0d2c8e4c-d5fd-11e4-8c62-fda620de16ed.jpg)
![2015-03-29_00029](https://cloud.githubusercontent.com/assets/11538773/6884663/0e6c667e-d5fd-11e4-9781-93a029edadd8.jpg)
Other bugs:
![2015-03-29_00005](https://cloud.githubusercontent.com/assets/11538773/6884638/0cdf17fc-d5fd-11e4-9722-9bb3bd676634.jpg) [might be not clear but this is at the waterfalls and you can troll the key there so others [including you] will not be able to retrieve it
![2015-03-29_00013](https://cloud.githubusercontent.com/assets/11538773/6884648/0d41ebf2-d5fd-11e4-8fba-677bdc9fed89.jpg) {zombies get confused, some of em}
![2015-03-29_00031](https://cloud.githubusercontent.com/assets/11538773/6884662/0e518fac-d5fd-11e4-90bd-cd687b2455bf.jpg) {you can get the boat stuck sometimes if you can get right between the boat and a rock}
Collision Bugs:
![2015-03-29_00010](https://cloud.githubusercontent.com/assets/11538773/6884645/0d3be1c6-d5fd-11e4-8b45-5f607a543313.jpg) {you are not able to shoot it with any regular gun but only with a SW or a sniper rifle}

**Comment by Fersigal** [comment]
Junction, fema, cleopas, toxteth and zephyr remaining :lock:  then i got all maps except favela since that whole map is a bug :sweat_smile:

**Comment by thegregster101** [comment]
i will work on this

**Comment by AtheistNMRiH** [comment]
Good to hear!

**Comment by AtheistNMRiH** [comment]
Some texture bugs:
Near the car(spawn)
![nmo_lakeside0000](https://cloud.githubusercontent.com/assets/11333747/7015884/4d2555ec-dd05-11e4-82f1-5e2c0e78a984.jpg)
And near gennerator
![nmo_lakeside0001](https://cloud.githubusercontent.com/assets/11333747/7015887/58ef43f6-dd05-11e4-8444-320f05e6abfd.jpg)

**Comment by thegregster101** [comment]
I don't have Vmf

**Comment by Fersigal** [comment]
There's a program to get it though i believe

**Comment by thegregster101** [comment]
Yes but it screws up the verts on the brush work and makes it impossible to
recompile compile vvis

**Comment by AtheistNMRiH** [comment]
was fixed by coolz in r8736
