### ISSUE TITLE
nmo_toxteth map bugs

### ISSUE THREAD

**Issue by Fersigal** [nmrih/source-game#716]
You can get stuck at this door
![2015-03-29_00226](https://cloud.githubusercontent.com/assets/11538773/6886185/ea963f2a-d635-11e4-96a0-b8c8389060b4.jpg)
Still possible: might not be clear, but at the wall where u put the fuel can to the graveyard, it will explode normally but you can camp at the side and lure zombies at you, then again it's up to the mapper if he wants to punish this severely or not.
![2015-03-29_00231](https://cloud.githubusercontent.com/assets/11538773/6886190/ea9b693c-d635-11e4-8722-71cc3977f433.jpg)
Same thing previous
![2015-03-29_00232](https://cloud.githubusercontent.com/assets/11538773/6886195/eaaf30ac-d635-11e4-9036-1366eea1e754.jpg)
Not something you can fix i guess, just weird interactions with some displacements (according to my own experience)
![2015-03-29_00239](https://cloud.githubusercontent.com/assets/11538773/6886199/eac65fb6-d635-11e4-8969-7aac9bb7a9a0.jpg)
Zombies can sometimes clump up and block both doors on toxteth, so i suggest to have them be openable both ways, atleast one of them
![2015-03-29_00241](https://cloud.githubusercontent.com/assets/11538773/6886200/eac6e210-d635-11e4-87b1-414866e70108.jpg)
Same as previous
![2015-03-29_00242](https://cloud.githubusercontent.com/assets/11538773/6886201/eac7d530-d635-11e4-8ed7-12fef20e13d8.jpg)
Still works, you can use any prop_physics (since walkie also works as a prop_physics for a split second and because of no specifiers you can brin something else to it and it'll also be used as the objective) Works with walkies and melons on this map (and fuel cans of course :)  #696 
![2015-03-29_00243](https://cloud.githubusercontent.com/assets/11538773/6886202/eac95d60-d635-11e4-8daa-3189275ac610.jpg)
There's a lot of jump up spots and zombie boosting spots at the graveyard, the main ones to look out for are the tall tombstones and the small additional tree branches at the cedar trees
![2015-03-29_00244](https://cloud.githubusercontent.com/assets/11538773/6886206/eade4bbc-d635-11e4-895c-a0abd1e31801.jpg)
Small nitpicking (some doors go into the props of the door supports, but it's no necessarry fix, most people won't even notice it)
![2015-03-29_00245](https://cloud.githubusercontent.com/assets/11538773/6886203/eadba7d6-d635-11e4-9848-d812f483a668.jpg)
(see other post, well you can toss the tnt almost everywhere outside of the map at the sides)
![2015-03-29_00250](https://cloud.githubusercontent.com/assets/11538773/6886209/eaf19d0c-d635-11e4-9247-664ce8e08921.jpg)
you can get the key stuck, but also see another post with most spots on other maps
![2015-03-29_00266](https://cloud.githubusercontent.com/assets/11538773/6886224/eb26ea66-d635-11e4-8350-0bc9995dd502.jpg)
Door is slightly not adjusted to the side + displacement is not bound to the floor
![20180118100333_1](https://user-images.githubusercontent.com/11538773/35090707-c7206eb6-fc3a-11e7-8a5e-2ef28e095e7f.jpg)
small door nitpicking
![20180118100344_1](https://user-images.githubusercontent.com/11538773/35090708-c7417156-fc3a-11e7-83e1-a9afb1b5d946.jpg)
graves that are floating
![20180118100356_1](https://user-images.githubusercontent.com/11538773/35090710-c75e1112-fc3a-11e7-8b66-651cde9b9e94.jpg)
Nodraw textures on stairs, either texture it or pull it through
![20180118100416_1](https://user-images.githubusercontent.com/11538773/35090711-c777f06e-fc3a-11e7-890a-2ba0c9af08e1.jpg)
Zombies get stuck on this spot in sewer when they spawn (possibly npc_spawner)
![20180118100456_1](https://user-images.githubusercontent.com/11538773/35090714-c9832162-fc3a-11e7-92d6-400bc45ca1d4.jpg)

**Comment by AtheistNMRiH** [comment]
fixed in r8735

**Comment by Fersigal** [comment]
![image](https://user-images.githubusercontent.com/11538773/38453740-d43bd564-3a5a-11e8-985c-8d7309a01089.png)
Might be still possible if zombies are clumping also the other door zombies still tend to get stuck, could be fixed possibly by only making it so the door only goes inwards

**Comment by Fersigal** [comment]
everything is fixed in r4405, aside from maybe some door getting stuck, also zombies can hit through door, only happens if they clump up though, i didn't test the prop clips, i'll leave that for Holy Crap

**Comment by AtheistNMRiH** [comment]
door opens inwards in r8776, needs to be closed
