### ISSUE TITLE
Some bugs on fema,brooklyn and general

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#719]
deleted, since some of them are useless and some of them are fixed

**Comment by Fersigal** [comment]
It's no bug the last one i think

**Comment by Fersigal** [comment]
Here are some on the beginning of fema and untill the quarantine objective 
![2015-04-11_00002](https://cloud.githubusercontent.com/assets/11538773/7101437/bf2ca87c-e05a-11e4-85b2-1cdae6fa4a1f.jpg)
![2015-04-11_00003](https://cloud.githubusercontent.com/assets/11538773/7101438/bf2db1fe-e05a-11e4-94a0-958b49ab3b15.jpg)
![2015-04-11_00004](https://cloud.githubusercontent.com/assets/11538773/7101440/bf335d02-e05a-11e4-9f64-f33f8bc89625.jpg)
![2015-04-11_00005](https://cloud.githubusercontent.com/assets/11538773/7101442/bf347f0c-e05a-11e4-9f12-a0da6f9f9bfa.jpg)
![2015-04-11_00006](https://cloud.githubusercontent.com/assets/11538773/7101441/bf3497bc-e05a-11e4-920f-b63cb6b33b2c.jpg)
![2015-04-11_00007](https://cloud.githubusercontent.com/assets/11538773/7101439/bf336086-e05a-11e4-9245-17ca27e8f3d5.jpg)
![2015-04-11_00008](https://cloud.githubusercontent.com/assets/11538773/7101443/bf42b734-e05a-11e4-8fa8-cfbb58e06a41.jpg)
![2015-04-11_00009](https://cloud.githubusercontent.com/assets/11538773/7101444/bf43f7d4-e05a-11e4-9f2f-580252343293.jpg)
![2015-04-11_00010](https://cloud.githubusercontent.com/assets/11538773/7101446/bf47c9a4-e05a-11e4-81cb-0d1308e529fa.jpg)
![2015-04-11_00011](https://cloud.githubusercontent.com/assets/11538773/7101445/bf4659ca-e05a-11e4-9377-cc9cb78b4181.jpg)
![2015-04-11_00012](https://cloud.githubusercontent.com/assets/11538773/7101448/bf4b40a2-e05a-11e4-96a6-b33013e8d52c.jpg)
![2015-04-11_00013](https://cloud.githubusercontent.com/assets/11538773/7101447/bf4a78b6-e05a-11e4-8383-5d1a73a76eea.jpg)
![2015-04-11_00014](https://cloud.githubusercontent.com/assets/11538773/7101449/bf5b5f46-e05a-11e4-8637-07b98c40d309.jpg)
![2015-04-11_00015](https://cloud.githubusercontent.com/assets/11538773/7101450/bf5ca126-e05a-11e4-8e13-1bad4ff00dae.jpg)
![2015-04-11_00016](https://cloud.githubusercontent.com/assets/11538773/7101453/bf6076b6-e05a-11e4-932b-66187dfc3b70.jpg)
![2015-04-11_00017](https://cloud.githubusercontent.com/assets/11538773/7101451/bf5e2910-e05a-11e4-903f-d36252fa9935.jpg)
![2015-04-11_00018](https://cloud.githubusercontent.com/assets/11538773/7101452/bf5fc20c-e05a-11e4-8553-c2c6ca953225.jpg)
