### ISSUE TITLE
Linux Ubuntu 14.04 seemingly random crashes to desktop

### ISSUE THREAD

**Issue by doogie544** [nmrih/source-game#720]
I am crashing out of the game occasionally.  I am unaware of any pattern to cause these crashes.  I am crashing to the desktop with no error notification.
Below is my system info from the  Steam client.  I have tried validating the files with no success

> Processor Information:
>     Vendor:  GenuineIntel
>     CPU Family:  0x6
>     CPU Model:  0x2a
>     CPU Stepping:  0x7
>     CPU Type:  0x0
>     Speed:  3001 Mhz
>     4 logical processors
>     4 physical processors
>     HyperThreading:  Unsupported
>     FCMOV:  Supported
>     SSE2:  Supported
>     SSE3:  Supported
>     SSSE3:  Supported
>     SSE4a:  Unsupported
>     SSE41:  Supported
>     SSE42:  Supported
> 
> Network Information:
>     Network Speed:  
> 
> Operating System Version:
>     Ubuntu 14.04.2 LTS (64 bit)
>     Kernel Name:  Linux
>     Kernel Version:  3.13.0-49-generic
>     X Server Vendor:  The X.Org Foundation
>     X Server Release:  11501000
>     X Window Manager:  Compiz
>     Steam Runtime Version:  steam-runtime-release_2015-01-06
> 
> Video Card:
>     Driver:  NVIDIA Corporation GeForce GT 730/PCIe/SSE2
> 
>    Driver Version:  4.4.0 NVIDIA 331.113
>     OpenGL Version: 4.4
>     Desktop Color Depth: 24 bits per pixel
>     Monitor Refresh Rate: 59 Hz
>     VendorID:  0x10de
>     DeviceID:  0x1287
>     Number of Monitors:  1
>     Number of Logical Video Cards:  1
>     Primary Display Resolution:  1366 x 768
>     Desktop Resolution: 1366 x 768
>     Primary Display Size: 16.77" x 9.41"  (19.21" diag)
>                                             42.6cm x 23.9cm  (48.8cm diag)
>     Primary Bus: PCI Express 8x
>     Primary VRAM: 1024 MB
>     Supported MSAA Modes:  2x 4x 8x 16x 
> 
> Sound card:
>     Audio device: Conexant CX20641
> 
> Memory:
>     RAM:  7968 Mb
> 
> Miscellaneous:
>     UI Language:  English
>     LANG:  en_US.UTF-8
>     Microphone:  Not set
>     Total Hard Disk Space Available:  461349 Mb
>     Largest Free Hard Disk Block:  306744 Mb
> 
> Installed software:
> 
> Recent Failure Reports:
>     Sat Apr 11 01:33:43 2015 GMT: file ''/tmp/dumps/crash_20150410212006_1.dmp'', upload yes: ''CrashID=bp-cd3e8ade-73ac-4e39-afa3-586fc2150410''

These are the lines from the Steam log at the time of the crash....

> ERROR: ld.so: object '/home/zookeeper/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
> crash_20150410212006_1.dmp[6592]: Uploading dump (out-of-process)
> /tmp/dumps/crash_20150410212006_1.dmp
> /home/zookeeper/.local/share/Steam/SteamApps/common/nmrih/sdk/hl2.sh: line 67: 28963 Aborted                 (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
> Game removed: AppID 224260 "No More Room in Hell", ProcID 28963 
> crash_20150410212006_1.dmp[6592]: Finished uploading minidump (out-of-process): success = yes
> crash_20150410212006_1.dmp[6592]: response: CrashID=bp-cd3e8ade-73ac-4e39-afa3-586fc2150410
> crash_20150410212006_1.dmp[6592]: file ''/tmp/dumps/crash_20150410212006_1.dmp'', upload yes: ''CrashID=bp-cd3e8ade-73ac-4e39-afa3-586fc2150410''
> pid 6592 != 6590, skipping destruction (fork without exec?)

**Comment by Bubka3** [comment]
We need that /tmp/dumps/crash_20150410212006_1.dmp file.

**Comment by doogie544** [comment]
ummm, OK, but it will not let me attach it here, it just tells me "file type not supported try again with a PNG, GIF or JPG....

How do I go about posting it?

**Comment by Smil3yRiley** [comment]
Email it to support@nmrih.com with the crash file attached to it

**Comment by doogie544** [comment]
Thank you, email has been sent with this page/post referenced.

Guess it makes too much sense to be able to post them here....doesn't make a lot of sense to me but what do I know........

**Comment by Bubka3** [comment]
GitHub controls what files can or cannot be posted. We have no control over this.

**Comment by doogie544** [comment]
Yes I'm aware of that, it just doesn't make much sense that they will not allow the error reports to be posted.  They are kind of necessary for debugging....

**Comment by doogie544** [comment]
Still getting random crashes, the most recent was when trying to connect to a server.  I sent the files via email.

**Comment by untom** [comment]
HI there, jumping in to say I experience the same random crashes to desktop, on Ubuntu 15.04 x86-64. 

For me, it seems like the crashes happen more often on some servers than on others. I can play virtually crash-free on some servers, yet on some others the game crashes every 5-20 minutes.

**Comment by HalinReno** [comment]
I am having the same problem as doogie544. Game crashes randomly with every server I try. I emailed the contents of the dumps folder to you along with my system specs. Thanks.

**Comment by psychoticusrex** [comment]
Same problem.

Linux 4.6 kernel, xubuntu 16.04, nVidia GeForce 960 PCIe/SSE2, newest nVidia proprietary driver.

I just re-certified my steam install for this game, checked for updates, updated system then grabbed a random server that was on zephyr.

Never even spawned, just watching game play before hand on zephyr and got a crash
[crash dump filtered for text.txt](https://github.com/ZPSNMRiHIssues/nmrihissues/files/349137/crash.dump.filtered.for.text.txt)

**Comment by psychoticusrex** [comment]
Still ongoing as of August 21, 2015.

Linux 4.6 kernel, xUbuntu 16.04, nVidia GeForce 960 PCIe/SSE2,  nVidia v367.35 proprietary driver.

Here are a few more crashes after latest ubuntu and nvidia updates it still persists.

http://www38.zippyshare.com/v/N02yYwZP/file.html   [2016-08-12]
http://www38.zippyshare.com/v/F6fcIU7u/file.html      [2016-08-12]
http://www38.zippyshare.com/v/7RaqW29Z/file.html   [2016-08-12]
http://www38.zippyshare.com/v/9etHnlbM/file.html      [2016-08-12]
http://www38.zippyshare.com/v/9IKFC10R/file.html    [2016-08-12]
http://www38.zippyshare.com/v/hP2OkrES/file.html    [2016-08-12]
http://www38.zippyshare.com/v/c5Jcv4MW/file.html   [2016-08-12]
http://www38.zippyshare.com/v/JWZsPAzT/file.html   [2016-08-12]
http://www38.zippyshare.com/v/V5SpWzUX/file.html  [2016-08-12]
http://www38.zippyshare.com/v/qfLhpeFo/file.html     [2016-08-12]
http://www38.zippyshare.com/v/iDYqURBq/file.html   [2016-08-13]
http://www38.zippyshare.com/v/mhr7uJnY/file.html   [2016-08-13]
http://www38.zippyshare.com/v/1cB4qqSV/file.html   [2016-08-13]
http://www38.zippyshare.com/v/54kevvrr/file.html      [2016-08-13]
http://www38.zippyshare.com/v/6oohslGK/file.html    [2016-08-13]
http://www38.zippyshare.com/v/9NBwXPa3/file.html  [2016-08-13]
http://www38.zippyshare.com/v/1h2BeoyK/file.html    [2016-08-14]
http://www38.zippyshare.com/v/7lEArJXg/file.html      [2016-08-14]
http://www38.zippyshare.com/v/WfGoFLGn/file.html  [2016-08-14]
http://www38.zippyshare.com/v/XRTsAJAT/file.html   [2016-08-14]
http://www38.zippyshare.com/v/f3zmOHzB/file.html   [2016-08-14]
http://www38.zippyshare.com/v/I3ITk1Hh/file.html      [2016-08-14]
http://www38.zippyshare.com/v/1vwaqXFe/file.html    [2016-08-15]
http://www38.zippyshare.com/v/TEXxdHKw/file.html   [2016-08-15]
http://www38.zippyshare.com/v/DK4N1opx/file.html    [2016-08-15]
http://www38.zippyshare.com/v/hTjpoShp/file.html      [2016-08-16]
http://www38.zippyshare.com/v/yyq84Ft6/file.html      [2016-08-16]
http://www38.zippyshare.com/v/EP4Gr0PQ/file.html   [2016-08-16]
http://www38.zippyshare.com/v/HoZaD6GJ/file.html   [2016-08-16]
http://www38.zippyshare.com/v/txjrit77/file.html          [2016-08-16]
http://www38.zippyshare.com/v/xcusVbEm/file.html    [2016-08-17]
http://www38.zippyshare.com/v/71iI10Y2/file.html       [2016-08-17]
http://www38.zippyshare.com/v/PZfYTz2P/file.html     [2016-08-18]
http://www38.zippyshare.com/v/BaDBEU7W/file.html  [2016-08-18]
http://www38.zippyshare.com/v/ltuDrEys/file.html        [2016-08-18]
http://www38.zippyshare.com/v/vR2klNGR/file.html     [2016-08-19]
http://www38.zippyshare.com/v/ifOXYEHE/file.html     [2016-08-19]
http://www38.zippyshare.com/v/TK7G0ZFI/file.html     [2016-08-21]
http://www38.zippyshare.com/v/w43D6aGn/file.html    [2016-08-21]
http://www38.zippyshare.com/v/8YiKqjd4/file.html       [2016-08-21]
http://www38.zippyshare.com/v/HI7C65DJ/file.html     [2016-08-21]

**Comment by psychoticusrex** [comment]
From a cursory scan of the dmp files there are some erroneous things to bring to your attention:

Error: Material "debug/debugluxels" uses unknown shader "DebugLuxels"

Could be as simple as a type-o in the map scripts in so far as they're labeled "Luxels" instead of "Levels".  Or that could be a red herring.
But that' s the low hanging fruit of bugs, there are lots of others in there too take a look at. not just missing shaders or "AntLion".

**Comment by psychoticusrex** [comment]
</h2>Crashes still persist as of February 15, 2017.</h2>

<p>xUbuntu 16.10 yakkety, nVidia GeForce GTX 960 PCIe/SSE2, nVidia x86_64-375.39 proprietary driver.</p>

<p>Including links too *.dmp files.</p>
<ul><li>
<a href="http://www45.zippyshare.com/v/SDiMwO9D/file.html">crash_20170215112257_1 - [2017-02-15] - [nVidia375.39].dmp</a></li>
<li><a href="http://www45.zippyshare.com/v/dXhY6yH1/file.html">crash_20170215113734_1 - [2017-02-15] - [nVidia375.39].dmp</a></li>
</ul>

**Comment by Bubka3** [comment]
If anyone is still experiencing this issue, please open a new issue.

**Comment by psychoticusrex** [comment]
Ok, it's not on my side I don't think but can't get server staff to cooperate.  Apparently there's a mod or configuration on the server side that causes it, a stock server's fine it's the mod'ed ones that crash linux clients.  The only mods i can think of are the cheat menu and infinite ammo, there may be others but this issue is independent of maps as it happens accross the board, a random crash to desktop for linux clients on a mod'ed server need to do some testing WITH mod'ed server staff to isolate which mod might be glitched.  I like the respawn mod as waiting 20 min between games is silly and would like to see this fixed.
