### ISSUE TITLE
Nmo_Cabin Safe Bug

### ISSUE THREAD

**Issue by Wazanator** [nmrih/source-game#725]
When you shoot the family picture and quickly try to open safe it glitches and after few seconds the safe doors opens.

https://www.youtube.com/watch?v=AYWV8_5LmoU

**Comment by AtheistNMRiH** [comment]
maybe fixed in r8729, I couldn't reproduce it, need more testing

**Comment by Winning117** [comment]
Confirmed fixed in src-r4367/dev-r8764.
