### ISSUE TITLE
Nmo_Fema Electric Box Bug!

### ISSUE THREAD

**Issue by Wazanator** [nmrih/source-game#726]
Sometimes you can't shoot electric box to cut power to electrified puddle.

https://www.youtube.com/watch?v=EVZQLaigNT0

http://steamcommunity.com/app/224260/discussions/3/618459405727404302/

**Comment by AtheistNMRiH** [comment]
I guess it is same as #743

**Comment by Bubka3** [comment]
Marking as duplicate of #743 

Follow that issue for all further updates.
