### ISSUE TITLE
nms_silence (possibly some other few maps) have their supply drop broken.

### ISSUE THREAD

**Issue by X-rock-X** [nmrih/source-game#730]
The supply drop in Silence does not come at all, this issue has been speculated to be existent in some other maps.

**Comment by AtheistNMRiH** [comment]
Yeah, it happening at all maps. I dont know, how to reproduce it

**Comment by Smil3yRiley** [comment]
From what I recall this is an issue that occurs on certain servers like the ones hosted by Storm, while other servers have properly functioning supply drops

**Comment by Smil3yRiley** [comment]
Either way we'll be looking into this, and will see if this is a general Linux Server issue

**Comment by yomox9** [comment]
Maybe cause is old .ain file.
http://www.nomoreroominhell.com/forums/index.php?showtopic=12378
