### ISSUE TITLE
shader-skybox-flashlight crash

### ISSUE THREAD

**Issue by Bubka3** [nmrih/source-game#732]
I'm nicknaming it that because usually one of those things are present in the callstack.

Here's a zip with 2 different people's crashes:
https://dl.dropboxusercontent.com/u/380297115/ShaderCrashes.zip

**Comment by Smil3yRiley** [comment]
We're looking at it right now, if we can get an idea on the sort of hardware that the user was using, and the general video settings it would help

It would be greatly appreciated if we can get an idea on how this crash occurs in game, if the player is using the flashlight and pointing it at certain key areas (directly up in the sky, on a prop, etc)

**Comment by Bubka3** [comment]
Modern hardware.

Crash is completely random. I was just AFK'ing there and it happened for instance.

**Comment by Smil3yRiley** [comment]
Crashed on r8343, was on nms_ransack and was typing when I crashed on wave 2, waz had a flashlight on, may be tied to this ticket?

https://dl.dropboxusercontent.com/u/972438/nmrih/riley8343crash.dmp

**Comment by Bubka3** [comment]
That crash is in the engine. Other than we don't have the engine symbols; all of the crashes above occur in the client. At least partially.
