### ISSUE TITLE
NMO_Chinatown: No respawns

### ISSUE THREAD

**Issue by Wazanator** [nmrih/source-game#739]
https://steamcommunity.com/app/224260/discussions/2/618463738393484306/

"NMO_Chinatown in casual mode doesn't let me respawn. I play solo. I found out that sometimes any map can glitch and "disable" respawns even if I have plenty of respawn badges. Usually problem is solved when map restarts after my death from first time or when I exceed time limit and next map, which has this glitch sometimes, is loaded. However Chinatown always dotsn't let me respawn even after restart of the map or after previous map."

**Comment by Bubka3** [comment]
You won't respawn in casual mode on any map with 1 player and spawn points disabled. At that point it won't proximity spawn because there is no alive players.

I'm not sure if this "bug" is worth fixing tho.

**Comment by Bubka3** [comment]
See above condition.

We should either restart the round or re-enable spawn points (might be impossible)

**Comment by AtheistNMRiH** [comment]
fixed in r8744
