### ISSUE TITLE
Getting stuck behind a house in Lakeside

### ISSUE THREAD

**Issue by johnyukon** [nmrih/source-game#741]
In this map, there is a white van with a ramp in front of it, if you go over the van and jump to the other side you may get stuck behind the house, there is not way to exit this area since all doors are locked.

This only happens depending of the random objectives of the map.

People usually get stuck when the objective is to use the radio to call for help, they think they have to jump over the van and in the end they get stuck.

**Comment by Fersigal** [comment]
Makes no sense at all ^^

**Comment by johnyukon** [comment]
Getting stuck depends on which events (objectives) the game selects. 

If there's no way to get out of the back of the house, where the boat house resides, players get stuck on that area.

**Comment by Fersigal** [comment]
Tried this, the bug reported is no bug, the guy just had to get to a sidedoor and open that one, i really haven't found this one yet.

**Comment by Holycrapjimhox** [comment]
Confirmed fix in src-r4405/dev-r8785. Needs to be closed.
