### ISSUE TITLE
Fema- destroy electric box too early

### ISSUE THREAD

**Issue by johnyukon** [nmrih/source-game#743]
In female, if you destroy the electric box when the objective is not to destroy it, you get stuck because electricity will continue on and you can't go over the puddle.  You can't turn off electricity  because box is already destroyed.

**Comment by AtheistNMRiH** [comment]
fixed

**Comment by Holycrapjimhox** [comment]
Confirmed fix in src-r4405/dev-r8785. Needs to be closed.
