### ISSUE TITLE
[nms_campblood] Items unobtainable

### ISSUE THREAD

**Issue by junkmagnet200** [nmrih/source-game#745]
Version: steam greenlight
What happens: On the map nms_campblood there is a red key the player can get from a suitcase. The key opens a door to a bathroom stall in Zone C. Inside the stall is a medkit, bandage, and pills. The player can get the pills, but the medkit and bandage are stuck in the shelf and the player can't get to them/pick them up.
When does it happen: It has happened every time I've played campblood.
Steps to reproduce the issue (How did you do it?): get the key, open the stall door in Zone C, check to see if there is room in inventory, attempt to pick up medkit and bandage.

**Comment by Fersigal** [comment]
either it's the red key or blue key, but this issue has been fixed, tried it in game and no problem, worked perfectly fine as of patch 1.09.7

**Comment by Bubka3** [comment]
Medical item placement was fixed in r8547
