### ISSUE TITLE
[Shadow: High - Maglite Issue] Crash game when turn on maglite when added 'Weather Efffects' on server

### ISSUE THREAD

**Issue by MrHalt** [nmrih/source-game#746]
Yeah, I'm maker of 'Weather Effects' and it creates rains, snow, and fog things.
But, when I'm testing that plugin on my servers with low shadow and medium shadow,
it didn't cause game crash. But, when I modified shadow option which low to high or medium to high,
when I trying to turn on maglite, it causes game crashes.
I just let you know the bugs of you guys' game.
Even I don't know about reasons of bugs.
Anyway, I created my 'dump' file. So, here you are.
https://drive.google.com/open?id=0B7N7_II_bqbUQUFYUmJ6cG9KYVk

**Comment by Bubka3** [comment]
Hi there, please upload the file to github as that google drive is private.

**Comment by Bubka3** [comment]
**Inactivity Closure**
This issue has been closed for inactivity. If you are still experiencing this issue please reply to this issue to re-open it. If you have any additional issues please open a new issue.

For technical support, you may also post in the troubleshooting forums:
http://steamcommunity.com/app/224260/discussions/2/
