### ISSUE TITLE
SKS w/out Bayonet still has sv_sks_shove_delay enabled on it

### ISSUE THREAD

**Issue by Smil3yRiley** [nmrih/source-game#750]
The SKS without Bayonet variant still has the cvar that nerfs the time between SKS w/ Bayonet shoves

By default the SKS shove delay is at 1.5 seconds

---
- Spawn fa_sks_nobayo
- Shove with it
- Spawn fa_sks
- Shove with it
- Compare the two speeds

It occurs on r8452

**Comment by Bubka3** [comment]
QOL plugin reference:

```sourcepawn
/**
 * Fixes the SKS without bayonet using the extended shove cooldown.
 */
public MRESReturn DHook_NegateExtraShoveDelay(int this_ent, Handle return_handle)
{
    DHookSetReturn(return_handle, DEFAULT_SHOVE_DELAY);
    return MRES_Override;
}
```

**Comment by felis-catus** [comment]
Fixed on r4196.

**Comment by Bubka3** [comment]
**Resolved Closure**
This issue has been closed as it has been resolved in the current dev build.
It will be available to the public in the next steam release. Thanks for reporting!

Additional comments: dev binaries r8709
