### ISSUE TITLE
No Maglite support for Cleaver

### ISSUE THREAD

**Issue by X-rock-X** [nmrih/source-game#751]
As said in the title, you cannot equip the maglite with the Cleaver. Instead, it straight up switches to the maglite.

**Comment by X-rock-X** [comment]
Bump, this issue still persists. It is currently on the Public beta also.

**Comment by Bubka3** [comment]
QOL plugin reference code:

> /**
 * Allow maglite to be equipped with cleaver.
 *
 * Native signature:
 * CNMRiH_WeaponBase::IsFlashlightAllowed(void)
 */
public MRESReturn DHook_IsFlashlightAllowed(int this_ent, Handle return_handle)
{
    DHookSetReturn(return_handle, 1);
    return MRES_Supercede;
}

**Comment by felis-catus** [comment]
Fixed in r4193.

**Comment by Bubka3** [comment]
**Resolved Closure**
This issue has been closed as it has been resolved in the current dev build.
It will be available to the public in the next steam release. Thanks for reporting!

Additional comments: dev binaries r8709
