### ISSUE TITLE
Crashes, crashes, and more crashes

### ISSUE THREAD

**Issue by Dumbino** [nmrih/source-game#752]
https://www.dropbox.com/s/srdd0cgxusq4sf5/crash_hl2.exe_20150923193751_1.dmp?dl=0
https://www.dropbox.com/s/3f1c9fsh0b4g9fg/crash_hl2.exe_20150918150016_1.dmp?dl=0
https://www.dropbox.com/s/sgq2cpp6jjm3dg9/crash_hl2.exe_20150917161906_1.dmp?dl=0

Running the game in a borderless window, but I doubt that affects anything since several friends who I play the game with do the same and they don't crash, and I'm pretty sure I crashed once or twice before I switched from full screen to borderless windowed mode anyways. I verified my cache twice and the random crashes still persisted.

Some, if not most crashes were also on vanilla maps and servers, so it couldn't just be a custom file issue.

I don't get an "hl2.exe has stopped working" window either. The game just crashes to the desktop as if I quit the game.

**Comment by Bubka3** [comment]
What graphics card are you using, and what driver version are you using for it?

**Comment by Dumbino** [comment]
GTX 670
9.18.13.5306

**Comment by Bubka3** [comment]
This appears to be the internal driver version, we would need the human readable version.

The easiest way to obtain this (and update your drivers if needed) is by installing the Nvidia Geforce Experience application: http://www.geforce.com/geforce-experience/download

**Comment by Dumbino** [comment]
353.06, apologies.

**Comment by Bubka3** [comment]
Hi there! If you are still crashing please make a new issue with fresh crash dumps from the latest steam version. Thank you.
