### ISSUE TITLE
variant weapons with wrong name

### ISSUE THREAD

**Issue by x5566asd** [nmrih/source-game#758]
![2015-09-27_00002](https://cloud.githubusercontent.com/assets/11902227/10123036/255c51cc-655f-11e5-9bc9-1a75d4ae9bc0.jpg)
It says "Sako 85 (Scoped)" (in Tradition Chinese UI. Should I complaint about the outdated location file here?)

same problem with all the others variant weapons since 1.09.4.

**Comment by Bubka3** [comment]
We used to do translations via the wiki, but it was taken down last I checked. I will find out what we're gonna do now.

**Comment by Winning117** [comment]
"Steam\steamapps\sourcemods\nmrih_dev\resource\nmrih_schinese.txt" was never updated to accommodate weapon variants.

**Comment by Winning117** [comment]
Same with pretty much every language except english.

**Comment by Winning117** [comment]
Fixed in r8957, turned out to be caused by the same issue in https://github.com/nmrih/source-game/issues/984
