### ISSUE TITLE
superfluous spectate mode

### ISSUE THREAD

**Issue by x5566asd** [nmrih/source-game#759]
![2015-09-27_00003](https://cloud.githubusercontent.com/assets/11902227/10123118/2afdda62-6562-11e5-8ff4-15b0e5425303.jpg)
In 1.09.5, press SPACE to change spectate mode and you will change it into a mode called "spec_mode_POI", which is following camera but no player's name and health

**Comment by Bubka3** [comment]
If you close out the menu below (I believe it's CTRL) then you will see the name and health.

Space changes the point of view on that player from free-roam, 3rd person, 1st person.

Of, course not a bug.
