### ISSUE TITLE
Ammo check animation bug

### ISSUE THREAD

**Issue by x5566asd** [nmrih/source-game#761]
![2015-10-02_00001](https://cloud.githubusercontent.com/assets/11902227/10249260/e46d74ce-6956-11e5-9af1-85876f48d12f.jpg)

In 1.09.5 and previous versions
If you check your mag when ironsight is toggled, even though there is no rounds remaining, it play the animation with a bullet inside the mag.

And how about making new animation for switching fire mode while aiming down sight?

**Comment by Winning117** [comment]
Merged with [#927](https://github.com/nmrih/source-game/issues/927), needs to be closed.
