### ISSUE TITLE
nms_ransack graphical glitches

### ISSUE THREAD

**Issue by psychoorc99** [nmrih/source-game#762]
On the 1.0.9.5 beta, there are some weird graphical glitches that appear when you get close to the hanged guy on ransack (I'm not sure if this is mac-exclusive as I'm playing on a mac and don't have a PC to attempt to reproduce the issue on), they start appearing a little before you enter the alley. I've been able to reproduce this every time I've run the map, both from creating a server and joining the public ones.

Screenshots:
(Pre-glitch)-
![screen shot 2015-10-02 at 9 47 36 pm](https://cloud.githubusercontent.com/assets/14949012/10260984/a4d83e48-6951-11e5-8d25-06228ffaeb4b.png)
(Post-glitch)-
![screen shot 2015-10-02 at 9 47 43 pm](https://cloud.githubusercontent.com/assets/14949012/10260987/beaaeb9a-6951-11e5-9540-a4c59dba782f.png)
![screen shot 2015-10-02 at 9 47 48 pm](https://cloud.githubusercontent.com/assets/14949012/10260988/c04e0504-6951-11e5-99cc-def4f6b890e4.png)
![screen shot 2015-10-02 at 9 47 52 pm](https://cloud.githubusercontent.com/assets/14949012/10260990/c17fc35e-6951-11e5-9f9b-46c5e568bef4.png)

Console Output (not sure how relevant this is, just pasted everything from after server startup) -
`No More Room in Hell
Map: nms_ransack
Players: 1 / 2
Build: 0
Server Number: 5

Attemped to precache unknown particle system "achieved"!
The server is using sv_pure 0.  (Enforcing consistency for select files only)
psychoorc99 connected
Redownloading all lightmaps
prop_door_rotating has Door model (models/props_doors/door01_dynamic.mdl) with no door_options! Verify that SKIN is valid, and has a corresponding options block in the model QC file
prop_door_rotating has Door model (models/props_doors/door01_dynamic.mdl) with no door_options! Verify that SKIN is valid, and has a corresponding options block in the model QC file
prop_door_rotating has Door model (models/props/hospital/hospital_door01_dynamic.mdl) with no door_options! Verify that SKIN is valid, and has a corresponding options block in the model QC file`

System Information -
<Processor Information:
    Model:  MacBookAir6,1
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x45
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  1300 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.10.5 (64 bit)

Video Card:
    Driver:  Intel HD Graphics 5000

```
Driver Version:  1.2
Driver Date: 0  0
OpenGL Version: 2.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 0 Hz
VendorID:  0x8086
DeviceID:  0xa26
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 10.04" x 5.67"  (11.50" diag)
                                        25.5cm x 14.4cm  (29.2cm diag)
Primary VRAM: 1536 MB
```

Memory:
    RAM:  4096 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  114544 Mb
    Largest Free Hard Disk Block:  54098 Mb>

**Comment by AtheistNMRiH** [comment]
couldn't reproduce it, looks like it is mac problem and it is not related to map

**Comment by Winning117** [comment]
Need someone with a mac to test this map and see if the issue still persists.

**Comment by felis-catus** [comment]
>looks like it is mac problem 
You know what this means.
