### ISSUE TITLE
nms_ransack no melee weapons 

### ISSUE THREAD

**Issue by TeXnoFile** [nmrih/source-game#763]
NMRIH Version: 1.9.5 beta

As the title says in the lastest update players can not find any melee weapon in ransack. There are just not spawning anywhere.

**Comment by lousaffire** [comment]
Ok, not wanting to be a pain but I have changed nothing in the vmf, I'm assuming that when medical kits were altered something was changed which has effected me lee weapons, whoever changed the medical kits could you please fill me in what you did to save me some time sorting melee out?

**Comment by AtheistNMRiH** [comment]
fixed in r8716

**Comment by Winning117** [comment]
Confirmed fixed in src-r4367/dev-r8764.
