### ISSUE TITLE
Zombie attack board animation after being shoved away

### ISSUE THREAD

**Issue by Fersigal** [nmrih/source-game#765]
you can push zombies away from barricades and they'll keep attacking the boards (was also in the previous patches, just never really mentioned it anyways). But they'll eventually break it up but it looks way to weird...
![2015-10-03_00001](https://cloud.githubusercontent.com/assets/11538773/10263886/b7efe25e-69fd-11e5-8d97-567afd362349.jpg)

**Comment by TeXnoFile** [comment]
Yeah i have noticed that the Z´s were hitting the air for some reason, whenever they come close the some random obstacle (boulders, fema bags...) they start doing that

**Comment by Winning117** [comment]
Easy way to test this:
1. `sv_cheats 1; changelevel nms_northway`
2. Once the map loads type `give tool_barricade; give currentammo; setpos -1414.082520 329.568665 66.031311; setang 20.488304 -3.132785 -0.000022`
3. Place a board
4. Spawn a zombie
5. Push the zombie back and watch it try to hit the boards when it's not in reach

Video: https://www.youtube.com/watch?v=EoyE7oTJ0SQ

**Comment by felis-catus** [comment]
Fixed in src-r6240.
