### ISSUE TITLE
3D model size of shotguns look weird

### ISSUE THREAD

**Issue by Aketi** [nmrih/source-game#766]
![2015-10-04_00003](https://cloud.githubusercontent.com/assets/5096129/10265615/c14865e0-6a72-11e5-9c47-65dcfb311fb0.jpg)

Just noticed that M870 look way short(or small?) compared to Super X3.
I checked sites and at least barrel length of these shotguns are supposed to be the same.
Since I do not have access to real guns, I am not sure at all though.

**Comment by X-rock-X** [comment]
http://www.winchesterint.com/winchester/testa/images/testa_10.jpg
http://www.policemag.com/_Images/articles/ars1-2.jpg

You would be surprised on how large the X3 is compared to the 870.

Although, the 870 does look a tad small. I'll take a look.
