### ISSUE TITLE
Picking Up Thrown Weapons = Death

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#772]
This glitch works with any melee weapon so far as I know. Face the camera up, throw the weapon, face the camera down, grab the falling weapon, then spam click pick-up and drop and it will kill you. My friend showed me this one but I figured it was important to post it :D 

Video here: https://www.youtube.com/watch?v=sdQkxfZmP1M&feature=youtu.be

**Comment by Bubka3** [comment]
Not a bug, as melee weapons can be thrown.
