### ISSUE TITLE
nmo_zephyr - ragdoll in office needs readjustment

### ISSUE THREAD

**Issue by x5566asd** [nmrih/source-game#773]
Title.

Image
![2015-11-26_00001](https://cloud.githubusercontent.com/assets/11902227/11420735/0e893664-946b-11e5-905b-713c297bcf56.jpg)

**Comment by AtheistNMRiH** [comment]
lol, i thought only i saw that sheit

**Comment by Winning117** [comment]
It's beautiful :D

**Comment by Winning117** [comment]
Confirmed fixed in src-r4388/dev-r8771, needs to be closed.

**Comment by Winning117** [comment]
Confirmed fixed in src-r4388/dev-r8771, needs to be closed.

**Comment by AtheistNMRiH** [comment]
it still looks meh, I guess it is model problem

![nmo_zephyr0000](https://user-images.githubusercontent.com/11333747/38250801-e894d1f2-3779-11e8-84e7-430a4fdec6b7.jpg)
