### ISSUE TITLE
Invisible Wall on Cabin

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#781]
There's a weird invisible wall on cabin :( https://youtu.be/eEG3utAms6Q

**Comment by Fersigal** [comment]
Already submitted, useless post https://github.com/ZPSNMRiHIssues/nmrihissues/issues/708

**Comment by Winning117** [comment]
This bug isn't even mentioned in your post...

**Comment by Fersigal** [comment]
That's a prop clip and i assume it was added to prevent people from going the wrong way with certain objective items (they're annoying, but atleast they prevent people from acting like some moose and hiding the objective items for others). Would actually have to ask Nay0r, but i think it's related towards that

**Comment by AtheistNMRiH** [comment]
not a bug, as stated Fersigal it is vphysics clip, need to be closed
