### ISSUE TITLE
Zombies Voice Bug

### ISSUE THREAD

**Issue by bigstar1311** [nmrih/source-game#783]
some kid zombie voices comming out from walker, and some walker zombie voices come out from kid zombie.

The voice of Kid Zombie Walker and output without distinction as supposed.

Please click on the youtube link below.
(URL : https://youtu.be/eLMoi6Xgx7w)

**Comment by AtheistNMRiH** [comment]
I hear only female shambler zombie sonds

**Comment by bigstar1311** [comment]
Thank you for telling me.
