### ISSUE TITLE
Zombie hands beat the air

### ISSUE THREAD

**Issue by Borzalex** [nmrih/source-game#785]
Version: 1.0.9.5
What happens: zombies are suddenly stops and begin to beat the air with their hands for no reason.
When does it happen: sometimes.
Screenshots:
![2015-12-24_00010](https://cloud.githubusercontent.com/assets/16508167/12070662/bd56fb40-b08b-11e5-8aad-bb73b49088f2.jpg)
![2015-12-22_00001](https://cloud.githubusercontent.com/assets/16508167/12070664/c7b9cb30-b08b-11e5-802b-e2694ff6c8d4.jpg)

**Comment by AtheistNMRiH** [comment]
it's often happens near nav_jumps, dynamic and physics props, and maybe some triggers(like on campblood near white boards)

**Comment by Fersigal** [comment]
#765 related

**Comment by Winning117** [comment]
Related to [#358](https://github.com/nmrih/source-game/issues/358)

**Comment by Winning117** [comment]
New zombie navigation was added to prevent zombies attacking items/healthcrates. Confirmed fixed in src-r4388/dev-r8772, needs to be closed.

**Comment by DDysphie** [comment]
This still affects every other prop.

**Comment by AtheistNMRiH** [comment]
and dynamic too

**Comment by Winning117** [comment]
It does?? I haven’t seen it happen anymore. Will have to do more testing

**Comment by Winning117** [comment]
Perhaps related to these cvars:

```
"sv_zombie_physobj_swatdist" = "80" - How close to a physics object zombies try to get before swatting them
"sv_zombie_player_max_swatdist" = "200" - Zombies will not swat physics objects at players farther away than this
```

**Comment by dysphie** [comment]
That really isn't the issue, this is the activity zombies perform when they're in a combat state but can't navigate to their target. Example https://www.youtube.com/watch?v=3iiSlVJIgDE

**Comment by Winning117** [comment]
Appears to be fixed by r8968 src-r4881
