### ISSUE TITLE
Strange player models ( Neck, Wrists )

### ISSUE THREAD

**Issue by yomox9** [nmrih/source-game#786]
Version : 1.09.5, 1.09.4
What happens : Almost player model is strange ( Too long Neck / Too slender of twisted Wrist )
When does it happen : When Player stand or "grabbed". Maybe There are other case.
Steps to reproduce the issue (How did you do it?) : Watch it in game, or Use HLMV tool.
Screenshots :

When  playere stand,
![2016-01-05_00009](https://cloud.githubusercontent.com/assets/14893069/12098988/f056029a-b368-11e5-88cc-aaf764b06562.jpg) Too long neck. Buddan
![2016-01-05_00014](https://cloud.githubusercontent.com/assets/14893069/12098989/f0576162-b368-11e5-9485-70fef770e230.jpg) strange wrist. Buddas
![2016-01-05_00015](https://cloud.githubusercontent.com/assets/14893069/12098991/f05aeaa8-b368-11e5-852b-abdd70d5f769.jpg) Butcher
![2016-01-05_00016](https://cloud.githubusercontent.com/assets/14893069/12098992/f05b5254-b368-11e5-92e8-5f6153f40f8c.jpg) Roje
![2016-01-05_00019](https://cloud.githubusercontent.com/assets/14893069/12098990/f0576752-b368-11e5-8c54-5fbca51aeca3.jpg) Hunter

When grabbed in HLMV(Probably, same in game)

In many model, Wrist is too twist.
![ss20160105_041328000000](https://cloud.githubusercontent.com/assets/14893069/12099069/855d7df0-b369-11e5-8821-c12219279987.JPG)
![ss20160105_041343000000](https://cloud.githubusercontent.com/assets/14893069/12099072/85678d7c-b369-11e5-8e95-9c665336a1bb.JPG)
![ss20160105_041537000000](https://cloud.githubusercontent.com/assets/14893069/12099073/8567ae24-b369-11e5-9d85-d9e8dbe7c37e.JPG)
![ss20160105_041620000000](https://cloud.githubusercontent.com/assets/14893069/12099071/856588ec-b369-11e5-934d-84a97d847ad0.JPG)
![ss20160105_041716000000](https://cloud.githubusercontent.com/assets/14893069/12099070/856515a6-b369-11e5-8f46-06326da54e0e.JPG)
![ss20160105_041802000000](https://cloud.githubusercontent.com/assets/14893069/12099074/85698230-b369-11e5-974d-be4ad3d491ea.JPG)
![ss20160105_042013000000](https://cloud.githubusercontent.com/assets/14893069/12099075/857acb94-b369-11e5-8660-b8e94145bc3f.JPG)
![ss20160105_042028000000](https://cloud.githubusercontent.com/assets/14893069/12099076/8588da54-b369-11e5-8df4-fe86cae966c1.JPG)
![ss20160105_042123000000](https://cloud.githubusercontent.com/assets/14893069/12099079/858c00d0-b369-11e5-80b9-65380eab2e26.JPG)
![ss20160105_042337000000](https://cloud.githubusercontent.com/assets/14893069/12099077/8588e058-b369-11e5-8983-f29e22a59cfe.JPG)
![ss20160105_042345000000](https://cloud.githubusercontent.com/assets/14893069/12099078/858a2d96-b369-11e5-9bac-dda1cdd948a7.JPG)

Maybe Bateman/Jive is same. But they are wearing a long-sleeved, So player can't see wrists.

system information : 
`

> Processor Information:
>     Vendor:  GenuineIntel
>     CPU Family:  0x6
>     CPU Model:  0xf
>     CPU Stepping:  0xb
>     CPU Type:  0x0
>     Speed:  2400 Mhz
>     4 logical processors
>     4 physical processors
>     HyperThreading:  Unsupported
>     FCMOV:  Supported
>     SSE2:  Supported
>     SSE3:  Supported
>     SSSE3:  Supported
>     SSE4a:  Unsupported
>     SSE41:  Unsupported
>     SSE42:  Unsupported
> 
> Network Information:
>     Network Speed:  
> 
> Operating System Version:
>     Windows 7 (64 bit)
>     NTFS:  Supported
>     Crypto Provider Codes:  Supported 311 0x0 0x0 0x0
> 
> Video Card:
>     Driver:  NVIDIA GeForce GTX 960
> 
> ```
> DirectX Driver Name:  nvd3dum.dll
> Driver Version:  9.18.13.4725
> DirectX Driver Version:  9.18.13.4725
> Driver Date: 9 Jan 2015
> OpenGL Version: 4.5
> Desktop Color Depth: 32 bits per pixel
> Monitor Refresh Rate: 60 Hz
> DirectX Card: NVIDIA GeForce GTX 960
> VendorID:  0x10de
> DeviceID:  0x1401
> Number of Monitors:  1
> Number of Logical Video Cards:  1
> No SLI or Crossfire Detected
> Primary Display Resolution:  1920 x 1080
> Desktop Resolution: 1920 x 1080
> Primary Display Size: 26.65" x 15.00"  (30.55" diag)
>                                         67.7cm x 38.1cm  (77.6cm diag)
> Primary Bus: PCI Express 16x
> Primary VRAM: 2047 MB
> Supported MSAA Modes:  2x 4x 8x 
> ```
> 
> Sound card:
>     Audio device: ?w?b?h?z?? (2- High Definition 
> 
> Memory:
>     RAM:  8125 Mb
> 
> Miscellaneous:
>     UI Language:  English
>     Microphone:  Not set
>     Media Type:  DVD
>     Total Hard Disk Space Available:  8698855 Mb
>     Largest Free Hard Disk Block:  1249295 Mb
>     OS Install Date: 1 01 1970
>     Game Controller: XInput Controller #1 detected
> 
> Installed software:
>     かざぐるマウス 1.67 Beta
>     やります！アンコちゃん 2.2.1.0
>     Adobe Acrobat Reader DC - Japanese
>     Adobe Flash Player 20 ActiveX
>     Adobe Flash Player 20 NPAPI
>     Adobe Refresh Manager
>     Blender
>     Charamin OMP
>     Codename CURE
>     CrystalDiskInfo 6.5.2 Shizuku Edition
>     CubeExperimentalUninstaller
>     DriveAnalyzer
>     eBook Transfer for Reader
>     Evernote v. 5.9.1
>     Everything 1.3.4.686 (x86)
>     Explzh for Windows (64bit)
>     Fallout 4
>     Free DVD MP3 Ripper 1.12
>     Freemake Audio Converter バージョン 1.1.7
>     Freemake Video Downloader
>     Garry's Mod
>     giam209
>     Google デスクトップ
>     Google 日本語入力
>     Google Chrome
>     Google Drive
>     Google Update Helper
>     Half-Life
>     Half-Life 2
>     ImageMagick 6.9.2-9 Q16 (64-bit) (2015-12-19)
>     Intel(R) Integrator Toolkit
>     Intel(R) Network Connections 15.3.68.0
>     Jane Style Version 3.75
>     Java 8 Update 31
>     Java Auto Updater
>     Lhaplus
>     LoiLo Game Recorder
>     LoiLoScope 2
>     MeshLab_64b 1.3.3
>     Microsoft .NET Framework 4.5.2
>     Microsoft .NET Framework 4.5.2 (日本語)
>     Microsoft .NET Framework 4.5.2 (JPN)
>     Microsoft ASP.NET MVC 4 Runtime
>     Microsoft Games for Windows - LIVE
>     Microsoft Games for Windows - LIVE Redistributable
>     Microsoft Security Client
>     Microsoft Security Essentials
>     Microsoft Visual C++ 2005 Redistributable
>     Microsoft Visual C++ 2005 Redistributable (x64)
>     Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.17
>     Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.4148
>     Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.6161
>     Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.17
>     Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.4148
>     Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.6161
>     Microsoft Visual C++ 2010  x64 Redistributable - 10.0.40219
>     Microsoft Visual C++ 2010  x86 Redistributable - 10.0.40219
>     Microsoft Visual C++ 2012 Redistributable (x64) - 11.0.61030
>     Microsoft Visual C++ 2012 Redistributable (x86) - 11.0.61030
>     Microsoft Visual C++ 2012 x64 Additional Runtime - 11.0.61030
>     Microsoft Visual C++ 2012 x64 Minimum Runtime - 11.0.61030
>     Microsoft Visual C++ 2012 x86 Additional Runtime - 11.0.61030
>     Microsoft Visual C++ 2012 x86 Minimum Runtime - 11.0.61030
>     Microsoft Visual C++ 2013 Redistributable (x64) - 12.0.30501
>     Microsoft Visual C++ 2013 Redistributable (x86) - 12.0.30501
>     Microsoft Visual C++ 2013 x64 Additional Runtime - 12.0.21005
>     Microsoft Visual C++ 2013 x64 Minimum Runtime - 12.0.21005
>     Microsoft Visual C++ 2013 x86 Additional Runtime - 12.0.21005
>     Microsoft Visual C++ 2013 x86 Minimum Runtime - 12.0.21005
>     Microsoft XNA Framework Redistributable 4.0 Refresh
>     mylist2flvs
>     MySQL Connector C++ 1.1.6
>     MySQL Connector J
>     MySQL Connector Net 6.9.5
>     MySQL Connector/C 6.1
>     MySQL Connector/ODBC 5.3
>     MySQL Documents 5.6
>     MySQL Examples and Samples 5.6
>     MySQL Installer for Windows - Community
>     MySQL Notifier 1.1.6
>     MySQL Server 5.6
>     Nexus Mod Manager
>     No More Room in Hell
>     NVIDIA グラフィックス ドライバー 347.25
>     NVIDIA コントロール パネル 347.25
>     NVIDIA 3D Vision コントローラー ドライバー 347.09
>     NVIDIA 3D Vision ドライバー 347.25
>     NVIDIA GeForce Experience 2.4.5.44
>     NVIDIA GeForce Experience Service
>     NVIDIA HD オーディオ ドライバー 1.3.33.0
>     NVIDIA Install Application
>     NVIDIA LED Visualizer 1.0
>     NVIDIA Network Service
>     NVIDIA PhysX
>     NVIDIA PhysX システム ソフトウェア 9.14.0702
>     NVIDIA ShadowPlay 2.4.5.44
>     NVIDIA Stereoscopic 3D Driver
>     NVIDIA Update 2.4.5.44
>     NVIDIA Update Core
>     NVIDIA Virtual Audio 1.2.28
>     paint.net
>     Portal
>     RAD Video Tools
>     Security Update for Microsoft .NET Framework 4.5.2 (KB2972107)
>     Security Update for Microsoft .NET Framework 4.5.2 (KB2972216)
>     Security Update for Microsoft .NET Framework 4.5.2 (KB2978128)
>     Security Update for Microsoft .NET Framework 4.5.2 (KB2979578v2)
>     Security Update for Microsoft .NET Framework 4.5.2 (KB3023224)
>     Security Update for Microsoft .NET Framework 4.5.2 (KB3035490)
>     Security Update for Microsoft .NET Framework 4.5.2 (KB3037581)
>     Security Update for Microsoft .NET Framework 4.5.2 (KB3074230)
>     Security Update for Microsoft .NET Framework 4.5.2 (KB3074550)
>     Security Update for Microsoft .NET Framework 4.5.2 (KB3097996)
>     Security Update for Microsoft .NET Framework 4.5.2 (KB3098781)
>     SHIELD Streaming
>     SHIELD Wireless Controller Driver
>     SoundEngine Free
>     Source SDK
>     Steam
>     System Requirements Lab for Intel
>     Team Fortress 2
>     Tera Term 4.88
>     UTAU 歌声合成ツール
>     VLC media player
>     VMware Player
>     VTF Shell Extensions 1.7.5.0
>     Windows Live ID Sign-in Assistant
>     WinMerge 2.14.0.68 x64
>     WinPcap 4.1.2
>     WinSCP 5.8 beta
>     XMedia Recode バージョン 3.2.0.1
> `

**Comment by Winning117** [comment]
Those wrists though LOL

**Comment by Winning117** [comment]
Merged with [#927](https://github.com/nmrih/source-game/issues/927), needs to be closed.
