### ISSUE TITLE
[1.09.5] "We Got This" Achievement Glitch

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#788]
Apparently you can solo the maps and then have 5 other people join the map during the last wave and this will still count toward the achievement. I don't think this is intended and is kind of a bullshit way to get the achievement

I found this out on the steam forums (http://steamcommunity.com/app/224260/discussions/0/458604254466481903/?tscn=1452025873)

**Comment by AtheistNMRiH** [comment]
but u can't solo maps without losing any zones

**Comment by Winning117** [comment]
You can't solo all of the waves without losing zones but you can solo some of the waves to then have people join later
