### ISSUE TITLE
Lakeside important bug

### ISSUE THREAD

**Issue by nitrogain** [nmrih/source-game#790]
In the lakeside map, if you pick up a key and drop it to the water fall, it stuck between air and rock and you can't pick it up. You need to restart the mission. It's a game breaking bug, so if you're can fix it please. And if you're write my name to the new patch please write [Hun] lepto, thanks.

**Comment by TeXnoFile** [comment]
Write your name to the next patch?  Wth is wrong with you...

**Comment by Fersigal** [comment]
repost of waterfalls :sleeping: https://github.com/ZPSNMRiHIssues/nmrihissues/issues/712

**Comment by Fersigal** [comment]
#712

**Comment by Bubka3** [comment]
Duplicate of #712
