### ISSUE TITLE
panel.cpp error spew in console

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#791]
![nmo_lakeside0000](https://cloud.githubusercontent.com/assets/11333747/12217403/e619f0a8-b731-11e5-913c-5d0f6cf829c9.jpg)
some sheit

**Comment by Fersigal** [comment]
it's also on other maps to be honest, can't remember the other ones

**Comment by AtheistNMRiH** [comment]
i think it is not map problem

**Comment by MrHalt** [comment]
When you press TAB key, it happens.

**Comment by Bubka3** [comment]
Fixed in dev build, will be released 1.09.8
