### ISSUE TITLE
Ukrainian

### ISSUE THREAD

**Issue by Borzalex** [nmrih/source-game#793]
On store page specified lack of support for the Ukrainian language, but actually there is Ukrainian.
![shop](https://cloud.githubusercontent.com/assets/16508167/12703312/b00a3608-c848-11e5-8d3a-07fc816d7fa2.png)
![2016-01-31_00001](https://cloud.githubusercontent.com/assets/16508167/12703315/b50aa7aa-c848-11e5-97bc-47951af165e5.jpg)

**Comment by Bubka3** [comment]
This has been fixed.
