### ISSUE TITLE
nmo_junction Key behind a box Bug

### ISSUE THREAD

**Issue by bluebullet684** [nmrih/source-game#795]
I was playing nmo_junction map, and our group got through the sewers and to the part where you need to pick up the key and put it into the door to get to the next stage.

A saw a player pick up the key and throw it into a corner, behind a box. Making it impossible to get the key, and forcing all players to either kill themselves to restart the round or leave the server.

After you climb the second ladder out of the sewer, and climb down the ladder, right in front of you is the box that players can throw the key behind.

**Comment by Winning117** [comment]
https://www.youtube.com/watch?v=k-XqxMomQoQ
This is not completed as of src-r4367/dev-r8764.
