### ISSUE TITLE
Ransack Extinguisher

### ISSUE THREAD

**Issue by wasteman-nmrih** [nmrih/source-game#798]
In version 1.0.9.6, the fire extinguisher doesn't appear to spawn on ransack anymore. I loaded the map a good number of times and did find_ent in the console without success. Atheist from the forums checked in hammer and confirmed my findings. Not sure how long it's been like this.

**Comment by AtheistNMRiH** [comment]
It is from last patch, in 1.09.5 there was extinguisher

**Comment by AtheistNMRiH** [comment]
fixed in r8716

**Comment by Winning117** [comment]
Confirmed fixed in src-r4367/dev-r8759, needs to be closed.
