### ISSUE TITLE
Cutscenes

### ISSUE THREAD

**Issue by Borzalex** [nmrih/source-game#799]
Sometimes when it has to be played some cutscene the players (include observers) sees their skulls from inside instead of cutscene.
![2015-12-09_00001](https://cloud.githubusercontent.com/assets/16508167/13554554/7906ba9c-e3b3-11e5-83e2-330bf493c7e9.jpg)
![2015-12-21_00002](https://cloud.githubusercontent.com/assets/16508167/13554557/79071f64-e3b3-11e5-8ba2-0c1582c4466d.jpg)
![2015-12-24_00011](https://cloud.githubusercontent.com/assets/16508167/13554556/7906e576-e3b3-11e5-9a77-57262fea953f.jpg)
![2016-01-29_00001](https://cloud.githubusercontent.com/assets/16508167/13554559/790aa8b4-e3b3-11e5-98f5-5c87bd1128fb.jpg)
![2016-02-08_00001](https://cloud.githubusercontent.com/assets/16508167/13554558/7907493a-e3b3-11e5-9cb5-6d05c11e719a.jpg)
![2016-02-08_00002](https://cloud.githubusercontent.com/assets/16508167/13554555/7906fab6-e3b3-11e5-895a-b65f6ba5f2d3.jpg)
![2016-03-06_00001](https://cloud.githubusercontent.com/assets/16508167/13554560/791e9dce-e3b3-11e5-930f-b21c05d58490.jpg)
![2016-03-07_00004](https://cloud.githubusercontent.com/assets/16508167/13570111/f41d2128-e474-11e5-801e-b708b22a28b0.jpg)
![20160402224241_1](https://cloud.githubusercontent.com/assets/16508167/14228824/bda52626-f929-11e5-8734-a20948cfb4db.jpg)

**Comment by Bubka3** [comment]
Unfortunately this is engine related and something we can't fix.
