### ISSUE TITLE
Male zombie child missing the climbing animation

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#800]
![nms_northway0000](https://cloud.githubusercontent.com/assets/11333747/13815039/8fcbc4a6-ebbb-11e5-916f-7b51d853e61d.jpg)
Kids don't have wall pound animation, so they just stand like this. Also they haven't climbing animation, and sometimes, when u push them, they use ragdoll too.

**Comment by ihatebreakcore** [comment]
they use tpose when you push them from the side

**Comment by Fersigal** [comment]
This is the ragdoll pose so to say and mostly happens when you cancel their animation when they're about to attack

**Comment by Winning117** [comment]
Shoving kids from the side no longer causes them to t-pose but it can still happen when the kid is climbing in src-r4388/dev-r8771. https://www.youtube.com/watch?v=qDzDZlSPqOg

**Comment by AtheistNMRiH** [comment]
iirc they just don't have climbing animations

**Comment by Winning117** [comment]
The male child appears to be missing the climbing animation, but the female child is not. Video: https://www.youtube.com/watch?v=PCjZ6p4MLPI

**Comment by felis-catus** [comment]
Fixed in src-r7809.
