### ISSUE TITLE
nms_campblood item spawn problem

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#801]
![nms_campblood0000](https://cloud.githubusercontent.com/assets/11333747/13815104/d6554212-ebbb-11e5-92f0-bf751e175642.jpg)
![nms_campblood0001](https://cloud.githubusercontent.com/assets/11333747/13815107/d872bdae-ebbb-11e5-874e-2017cf199075.jpg)
This map hasn't boards now, also some weapons don't spawn

**Comment by AtheistNMRiH** [comment]
closing tis, looks like it's my bug

**Comment by AtheistNMRiH** [comment]
fixed in r8737

**Comment by Winning117** [comment]
Confirmed fixed in src-r4367/dev-r8759, needs to be closed.
