### ISSUE TITLE
NMRIH crashes every 5-10 minutes on MacBook Air

### ISSUE THREAD

**Issue by louier** [nmrih/source-game#804]
NMRIH crashes every 5-10 minutes.  This is _very_ frustrating as I am usually in the middle of an objective map on a server with other players.  I am forced to restart NMRIH and must spectate while others play.
1. Launch NMRIH
2. Connect to server
3. Play for 5-10 minutes
4. NMRIH crashes to desktop (without even bringing up the Mac "App has crashed send a crash report?" menu)
5. Re-launch NMRIH

I had thought this was the infamous "Steam auth" revoked issue, but other players tell me they do not see that message when I crash.  Therefore, I believe it is another problem in the NMRIH code.

I have no crash report when looking in the Steam app under System Information.

Computer Information:
    Manufacturer:  Apple
    Model:  MacBookAir4,2
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
Speed:  1700 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    MacOS 10.11.5 (64 bit)

Video Card:
    Driver:  Intel HD Graphics 3000

```
Driver Version:  1.2
Driver Date: 0  0
OpenGL Version: 2.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x8086
DeviceID:  0x116
Number of Monitors:  2
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1200
Desktop Resolution: 3840 x 2400
Primary Display Size: 20.39" x 12.76"  (24.02" diag)
                                        51.8cm x 32.4cm  (61.0cm diag)
Primary VRAM: 0 MB
```

Memory:
    RAM:  4096 Mb

Miscellaneous:
    UI Language:  English
    Microphone:  Not set
    Media Type:  DVD
    Total Hard Disk Space Available:  114538 Mb
    Largest Free Hard Disk Block:  5251 Mb
    VR Headset: None detected

**Comment by yomox9** [comment]
I have only windows. so this is FIY.
Delete all cash files.
　　　　modelsounds.cache
　　　　nmrih.vpk.sound.cache
　　　　sound\sound.cache
　　　　custom\*.cache
　　　　cache\downloadcache.db

**Comment by Bubka3** [comment]
# Missing Crash Dump
It appears the issue you've created is a crash.
Unfortunately, without a crash dump we are unable to provide any insight.

For general or technical support regarding the game, please visit the troubleshooting forums:
http://steamcommunity.com/app/224260/discussions/2/
