### ISSUE TITLE
nmo_cleopas Zombie Spawnpoint issue

### ISSUE THREAD

**Issue by Nicrobe** [nmrih/source-game#806]
The spawning points for the zombies in nmo_cleopas are presumably botched up. As the starting alley isn't supposed to be sardine-packed with zombies.

![sardine](https://cloud.githubusercontent.com/assets/20874497/17456764/aeac11dc-5beb-11e6-8d5f-fd9bd3794da9.jpg)

**Comment by Nicrobe** [comment]
I think I've forgotten to mention; They respawn. you can't simply hole up in one place and kill them off one by one.

**Comment by Fersigal** [comment]
I think this is intended :wink:

**Comment by Nicrobe** [comment]
Noting again, they respawn. Which makes it utterly impossible to leave as
they constantly close off the only thin alleyway you have at the start.

**Comment by AtheistNMRiH** [comment]
it is game mechanic, u can't just hole up in one place and kill all zombies, u should try to avoid them

**Comment by Nicrobe** [comment]
I repeat, You can NOT avoid them, as it is a tight TIGHT corridor sardine
packed with zombies and runners, who also keep spawning. You are going to
avoid all them, get a tnt, carry it to the other side of the alley while
avoiding?

I understand difficult. But whenever I watch videos of cleopas being
played, that starting area has a maximum of 5-6 zombies.

On Aug 15, 2016 5:16 PM, "Семён" <notifications@github.com> wrote:
>
> it is game mechanic, u can't just hole up in one place and kill all
zombies, u should try to avoid them

**Comment by AtheistNMRiH** [comment]
i played many times on this map, respawn wasn't so hard

**Comment by Fersigal** [comment]
No bug, not even a bug at all just a personal complaint about the hardness of the map

**Comment by AtheistNMRiH** [comment]
totally agreed with Fersigal, not a bug, need to be closed
