### ISSUE TITLE
Zombies turn immortal while performing attack

### ISSUE THREAD

**Issue by johnyukon** [nmrih/source-game#807]
While grabbing the player zombies will temporarily turn immortal, even shooting on their head with multiple shots of M4A1, shotgun, 1911, etc wont kill the zombie.

Maybe the zombie becomes immortal on other casions too, I'm not sure.
This is very annoying as you spend a lot of ammo and the zombie doesn't go down.

**Comment by AtheistNMRiH** [comment]
u just don't hit in hitbox, better push them then shoot

**Comment by johnyukon** [comment]
OK, but players expect a shotgun shot direct to the head would kill a zombie.

Now, I'm basicly a pro player, and I end up dying mostly because of this issue than any other reason, sometimes I spend a full clip of 1911 on a zombie head and it won't die, this ends up messing with my playtrough.

**Comment by johnyukon** [comment]
This just killed the game for me, can't play it anymore, sorry.

**Comment by AtheistNMRiH** [comment]
why u can't just shove them

**Comment by Bubka3** [comment]
Unfortunately the way grabbing and collisions/hitbox works in source engine is the cause of this issue, and not something we can fix.
