### ISSUE TITLE
nmo_chinatown missing ldr or possibly hdr

### ISSUE THREAD

**Issue by michaelryanmetzger** [nmrih/source-game#809]
When I joined a single-player game, the walls on places had a pink color to them. No black checkers, just a pink tint. I don't understand what's happening.

**Comment by AtheistNMRiH** [comment]
which map was that?

**Comment by michaelryanmetzger** [comment]
It was the Chinatown map.

**Comment by AtheistNMRiH** [comment]
when u open a game, open develop console (~ button) and type this command: mat_specular 0

**Comment by AtheistNMRiH** [comment]
checked in public build, reflections work perfect
