### ISSUE TITLE
performance issues 

### ISSUE THREAD

**Issue by mattdgold** [nmrih/source-game#810]
running on the following hardware: intel 6700k, 16GB ram, GTX 1070. The game has a framerate of 15 even on lowest graphical settings. Graphics drivers are updated to the most recent from nvidia. Other source games run just fine.

**Comment by Mateos81** [comment]
Can you check if the game actually runs on the GPU and not the CPU?

**Comment by Bubka3** [comment]
Hi there, this tracker is intended for bug reports that can be reproduced.
For technical support, please post in the troubleshooting forum:
http://steamcommunity.com/app/224260/discussions/2/
