### ISSUE TITLE
CTD On Start

### ISSUE THREAD

**Issue by Furycoat** [nmrih/source-game#811]
When the game is finished loading the main menu, it crashes. Also, when i validate files i always seem to have 1 file that says its not validated. I have not reinstalled yet.

**Comment by yomox9** [comment]
First, read READEME.me
https://github.com/ZPSNMRiHIssues/nmrihissues

> **"This repository is for submitting bugs and issues."**

You could decided your problem is bug? issues? No.

> **"click here to go to our Help & Support forum."**

**Comment by Bubka3** [comment]
# Not a Bug
It appears the issue you've created is not a bug. 
A bug is an issue with the game that can be reproduced by following a specific set of instructions.

For general or technical support regarding the game, please visit the troubleshooting forums:
http://steamcommunity.com/app/224260/discussions/2/
