### ISSUE TITLE
The Jitterbug Jig

### ISSUE THREAD

**Issue by 878544** [nmrih/source-game#812]
For whatever reason, whenever I join a server I usually end up frequently freezing; not in the sense that my computer is, but rather my character. Whenever I do freeze, (which happens quite often) I end up being locked in place, completely and utterly immobilized, also being unable the check my inventory, open any of the menus, being unable to use the voice ques, and worst of all being completely unable to attack. On top of that everything else is functional, the other players and zombies usually move and fight, unhindered, while I just jitter in place for up to 36 seconds in one case , hence why I dubbed it the "Jitterbug Jig." In this time all I can do is just hope and pray that I don't get grabbed before my guy finishes doing the Jitterbug Jig, or in the case that everything on the server appears to freeze, Jitterbug Jamboree. The odd thing is it doesn't appear to be an issue with ping as my ping is often at a steady enough 20 to 50. I sincerely hope that you know of a solution to this non-sense, because it's honestly been ruining the game for me with enumerable unfair deaths it's caused me. If you do than I would appreciate hearing it.
                                     
-Sincerely, (I don't think I'm entirely comfortable with revealing my real name online)

**Comment by Bubka3** [comment]
# Not a Bug
It appears the issue you've created is not a bug. 
A bug is an issue with the game that can be reproduced by following a specific set of instructions.

For general or technical support regarding the game, please visit the troubleshooting forums:
http://steamcommunity.com/app/224260/discussions/2/

**Comment by Bubka3** [comment]
**Duplicate Closure**
This issue has been closed because it has already been reported under a previous issue ID.
Please follow the issue below for further updates.

Duplicate of #350
