### ISSUE TITLE
Flare gun bug 

### ISSUE THREAD

**Issue by alingsteve** [nmrih/source-game#813]
Bad English sorry
If you fire a flare gun with right key (aim) pressed , then reload , there will be a shell dropping sound playing (And also there will be a ammo shell dropped)
video here : https://www.youtube.com/watch?v=OTeK_Fyq9NQ

**Comment by Bubka3** [comment]
# Not a Bug
It appears the issue you've created is not a bug. 
A bug is an issue with the game that can be reproduced by following a specific set of instructions.

For general or technical support regarding the game, please visit the troubleshooting forums:
http://steamcommunity.com/app/224260/discussions/2/
