### ISSUE TITLE
Transparent melee and inventory GUI after getting a blood splatter

### ISSUE THREAD

**Issue by Nielama** [nmrih/source-game#817]
idk why, but each time I get a blood splatter all my melee weapons turns transparent(with only blood splatter itself fully present) and both inventory menus become transparent too(which is a larger issue, I cannot use it effectively in darkness). I tried verifying/reinstalling. Pls help

**Comment by essbuh** [comment]
Are you using DirectX 8? This is the most common cause of weapons going invisible with blood splatter.

**Comment by Bubka3** [comment]
**Inactivity Closure**
This issue has been closed for inactivity. If you are still experiencing this issue please reply to this issue to re-open it. If you have any additional issues please open a new issue.

For technical support, you may also post in the troubleshooting forums:
http://steamcommunity.com/app/224260/discussions/2/
