### ISSUE TITLE
Client-server survivor hitbox desync when looking up and down

### ISSUE THREAD

**Issue by MintyDysphie** [nmrih/source-game#820]
Looking up or down causes your hitbox to rotate improperly server-side. This makes clients fall out of sync and you are unhittable by other players from your feet up.

Steps to reproduce:
1. Cvars `mp_friendlyfire 1; sv_showlagcompensation 1; sv_showimpacts 1`
2. Have player move their camera up or down and preserve that angle
3. Attempt to hurt them with a firearm, projectile or melee.
4. Observe results

Notes:
- `me_fists` will always hit, regardless of rotation.
- This bug isn't present in earlier versions of the game (like 1.06 from ModDB)

Screenshots:
![20171008223747_1](https://user-images.githubusercontent.com/11559683/31351451-84b7e212-ad01-11e7-83df-4ee934b11766.jpg)
![20171008224047_1](https://user-images.githubusercontent.com/11559683/31351458-9084f878-ad01-11e7-8450-195d793c9a78.jpg)
![20171008224341_1](https://user-images.githubusercontent.com/11559683/31351464-97ead376-ad01-11e7-925d-4f02e90e2d8c.jpg)
![20171008233518_1](https://user-images.githubusercontent.com/11559683/31351466-9eeedf0a-ad01-11e7-9d90-5883bc339a48.jpg)

**Comment by Bubka3** [comment]
@felis-catus thoughts?

**Comment by felis-catus** [comment]
For some reason server-side player's pitch angle wasn't reset, causing this issue.
Should be fixed now, needs confirm. (r4203)

**Comment by Bubka3** [comment]
**Resolved Closure**
This issue has been closed as it has been resolved in the current dev build.
It will be available to the public in the next steam release. Thanks for reporting!

Additional comments: dev binaries r8709
