### ISSUE TITLE
prop_physics causing server crash after killing a player

### ISSUE THREAD

**Issue by MintyDysphie** [nmrih/source-game#821]
Title. Steps to reproduce:
1. Have `prop_physics` with explosion damage (e.g explosive barrel)
2. Stand next to it in such a way that you will be killed by it
3. Shoot it with a firearm (`damagetype` must be `DMG_BULLET` and `DMG_NEVERGIB`, I think)
4. Server will crash after you die.

Crash log:
```
Server event "player_death", Tick 808:
- "userid" = "2"
- "attacker" = "2"
- "weapon" = "prop_physics_respawnable"
Server event "entity_killed", Tick 808:
- "entindex_killed" = "1"
- "entindex_attacker" = "1"
- "entindex_inflictor" = "145"
- "damagebits" = "134217792"
threadtools.cpp (3294) : Assertion Failed: Illegal termination of worker thread 'Thread(0x5DD81388/0x000008D8/0x'
Assert( Assertion Failed: Illegal termination of worker thread 'Thread(0x5DD81388/0x000008D8/0x' ):threadtools.cpp:3294
```

**Comment by Bubka3** [comment]
Can you provide a real world example of this happening during normal gameplay? This looks like you need to do a very specific type of modding and then run into a source engine issue.

**Comment by Nayncore** [comment]
> Can you provide a real world example of this happening during normal gameplay?

nmo_suzhou, be low on health (2 HP or so), find a fuel canister, stand near it and shoot it with a firearm:

https://i.imgur.com/oVbdTTd.jpg

Server and/or client (if self-hosting) will crash.

Also common on custom maps that utilize explosive oil drums.

**Comment by Fersigal** [comment]
Doesn't it also crash when u let's say shoot with a gun that deals higher damage than 900 onto an explosive (Smith and wesson Revolver shot onto a fuel can or a sniper shot onto a fuel can)

**Comment by felis-catus** [comment]
Fixed in r4206.

**Comment by Bubka3** [comment]
**Resolved Closure**
This issue has been closed as it has been resolved in the current dev build.
It will be available to the public in the next steam release. Thanks for reporting!

Additional comments: dev binaries r8709
