### ISSUE TITLE
Client crash on loading dialog

### ISSUE THREAD

**Issue by DDysphie** [nmrih/source-game#822]
1. Start NMRiH
2. Change screen resolution or switch from fullscreen/windowed mode.
3. Attempt to start a game
4. Observe results

**Comment by Bubka3** [comment]
Please reboot the game after changing any Video settings. This is an issue with the engine.

**Comment by felis-catus** [comment]
Reopening, this appears to be in our side.

**Comment by felis-catus** [comment]
Notice: this MIGHT be related to our loading dialog judging by the repro steps, but this is unconfirmed as of now.

**Comment by Bubka3** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Loading dialog crash](https://trello.com/c/BmMvy7NK/140-loading-dialog-crash)

**Comment by felis-catus** [comment]
Fixed in code commit r4297.

**Comment by Bubka3** [comment]
**Resolved Closure**
This issue has been closed as it has been resolved in the current dev build.
It will be available to the public in the next steam release. Thanks for reporting!

Additional comments: tested source-r4297 with self bins
