### ISSUE TITLE
[Linux] Crash when opening the game

### ISSUE THREAD

**Issue by DirtyJukebox** [nmrih/source-game#823]
My game crashes when opening the game, (it displays the wallpaper from the menu, then quits to the desktop).
I'm running Linux Mint 18.3, fully updated, using a Nvidia 960 (2GB) with the 384.98 driver and 8GB of RAM
**My system specs** (from steam): https://gist.github.com/DirtyJukebox/4c880b95aea6716bbe0b9c425eb8ce3f

**What I've tried:**
* Verifying local game files (Proprieties -> Local Files -> Verify) from steam. It sometimes says there are corrupted files, sometimes not, idk why.
* Installing ia32-libs and libtcmalloc-minimal4:i386 manually (it seemed missing when running the game from the command line).
* Re-downloading the game (worked for about 4 hours, then the game crashed and didn't open anymore).

The hard-drive I'm using is fine, so it's not corrupted files/etc. This is the only game where this happens, other hl2-based games work just fine (portal 2/tf2/etc)

I'm going to mail the .dmp files, shortly
Edit: email sent to support@nmrih.com

**Comment by DirtyJukebox** [comment]
It seems my email got flagged as spam or your support mail isn't working anymore.
[Attachments-[Linux] Crash when opening the game #823.zip](https://github.com/ZPSNMRiHIssues/nmrihissues/files/1581508/Attachments-.Linux.Crash.when.opening.the.game.823.zip)

**Comment by Bubka3** [comment]
Hello,

Please try the 1.11.0 beta as we shipped a critical linux patch. If you are still having problems after that please open a new issue.

Thanks!
