### ISSUE TITLE
Some room left in hell achievement

### ISSUE THREAD

**Issue by Bubka3** [nmrih/source-game#824]
Users are getting the 100% complete achievement w/o having all achievements completed. The check probably needs to be updated in the code for the number achievements we currently have.

**Comment by felis-catus** [comment]
This is intended according to the commit log and comments in code.

"Please don't add any new ones to this (achievement) as it can mess up players that already have it; instead we can add a "Platinum 2" or something later."

**Comment by essbuh** [comment]
This is intentional.  The "Some Room Left in Hell" meta achievement only requires the achievements that were originally shipped with the game.

**Comment by Bubka3** [comment]
Will clarify this in the achievement description and release a list of the original achievements that count for it.

**Comment by Holycrapjimhox** [comment]
I unlocked Some Room Left in Hell on 2016 I believe, and I got if after I unlocked every achievement in the game except for Manhattan Project, this includes achievements that were not present with the original build of the game. So, if you get it before that then it should be a bug. You can check the dates of my achievements if you want to corroborate.

**Comment by Bubka3** [comment]
The code for 100% achievement only checks certain achievements. This part appears to be working and intended as stated by essbuh above. It's possible you unlocked newer achievements before completing the old achievements and thats why it may seem that way to you.

**Comment by Bubka3** [comment]
Achievement text has been adjusted.

> 100% Complete! Unlock all original achievements shipped with Steam release! Thanks for playing!
