### ISSUE TITLE
sniper scope ui disappearing after opening a menu

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#825]
steps to reproduce
1) load any map
2) type sv_cheats 1 and give fa_sako85
3) right click
4) press esc
I guess menu ui overlap scope ui
![nmo_urbanhazard_v5_10017](https://user-images.githubusercontent.com/11333747/35113615-a629b7ec-fcb4-11e7-88ac-077b7b28582d.jpg)
![nmo_urbanhazard_v5_10019](https://user-images.githubusercontent.com/11333747/35113616-a657a166-fcb4-11e7-9f19-4a732ed5f85f.jpg)

**Comment by Bubka3** [comment]
Scope is still present after pressing ESC to return to the game. The scope disappearing is a engine issue and does not break the game.
