### ISSUE TITLE
nmo_cabin (map bugs)

### ISSUE THREAD

**Issue by Holycrapjimhox** [nmrih/source-game#826]
So, there are several issues on nmo_cabin, either out of bound tricks or simple lack of item clips that allow players to softlock the map. I guess some of these have already been reported, since they've been present for a long time.

![20180120101418_1](https://user-images.githubusercontent.com/35630284/35184119-19b70d6a-fdd0-11e7-9718-3076be9b4363.jpg)
![20180120101451_1](https://user-images.githubusercontent.com/35630284/35184134-4fa172a8-fdd0-11e7-8668-f9193da25889.jpg)
![20180120101536_1](https://user-images.githubusercontent.com/35630284/35184137-544b7f6a-fdd0-11e7-84bb-0b0d931b15e9.jpg)
![20180120101650_1](https://user-images.githubusercontent.com/35630284/35184141-5d118e96-fdd0-11e7-8678-78d32ebaf4c3.jpg)
![20180120101725_1](https://user-images.githubusercontent.com/35630284/35184143-6267551a-fdd0-11e7-9fd2-54c32b6be4c7.jpg)

Here you can bug the first key by just placing behind or on top of props. I suggest item clipping most furniture props that have empty spaces behind or underneath them.

![20180120102559_1](https://user-images.githubusercontent.com/35630284/35184155-92daa58a-fdd0-11e7-846a-b6af481f7662.jpg)
![20180120102534_1](https://user-images.githubusercontent.com/35630284/35184156-9d51d3ee-fdd0-11e7-9e8b-b0846a13d426.jpg)
![20180120102547_1](https://user-images.githubusercontent.com/35630284/35184158-a17c8022-fdd0-11e7-8bc9-3fc90b2cd2fe.jpg)
![20180120102715_1](https://user-images.githubusercontent.com/35630284/35184161-a9b5df18-fdd0-11e7-87ab-a4877e374bc4.jpg)
![20180120102755_1](https://user-images.githubusercontent.com/35630284/35184166-b7ee2a5e-fdd0-11e7-930d-cb437b63b3bf.jpg)

Here you can get out of bounds by jumping behind a player clip and slowly surfing to the top of the rocks. You can even take the battery with you and softlock the map.

![20180120102847_1](https://user-images.githubusercontent.com/35630284/35184186-ea0d95c4-fdd0-11e7-9e03-1aca12356800.jpg)
![20180120103247_1](https://user-images.githubusercontent.com/35630284/35184202-f888d352-fdd0-11e7-893f-481f3251beb8.jpg)
![20180120104153_1](https://user-images.githubusercontent.com/35630284/35184208-0bfe3684-fdd1-11e7-9dd4-6e9b1ed09705.jpg)
![20180120104211_1](https://user-images.githubusercontent.com/35630284/35184209-0f73187a-fdd1-11e7-98c7-34042c182d23.jpg)

The windows that face the front yard of the house need clipping, you can pass anything through. You can save time by placing the battery through the wall. But, if you get the "weld the kitchen door" objective, you can throw the welder out of the window, and the map gets softlocked.

![20180120102924_1](https://user-images.githubusercontent.com/35630284/35184227-6dea6e08-fdd1-11e7-8985-849bf0075f61.jpg)

This fence needs clipping too since you can throw the battery to the other side and cause another softlock

![20180120103052_1](https://user-images.githubusercontent.com/35630284/35184234-a5ae929c-fdd1-11e7-8c65-38ca98decb9b.jpg)
![20180120103111_1](https://user-images.githubusercontent.com/35630284/35184236-a95d316e-fdd1-11e7-9d50-86192ef92655.jpg)

The protruding roof on the porch of the house needs item clips as well, you can get the battery on top of it. It's basically a softlock for regular players, since the only way to get it back is through walkie talkie boosting or zombie boosting like in the screenshot.

![20180120103402_1](https://user-images.githubusercontent.com/35630284/35184246-d5b884ac-fdd1-11e7-9f81-b33d743fb326.jpg)
![20180120103431_1](https://user-images.githubusercontent.com/35630284/35184249-d8e4dd60-fdd1-11e7-8b7a-04af46f41162.jpg)

You can bug the red key basically anywhere you could bug the first key.

![20180120103728_1](https://user-images.githubusercontent.com/35630284/35184267-26f9e374-fdd2-11e7-874c-e5416f93adf9.jpg)

If you go through the underground and trigger the escape sequence, the kitchen door will be opened automatically, but a floating lock will remain

![20180120103740_1](https://user-images.githubusercontent.com/35630284/35184272-46453206-fdd2-11e7-8a66-0acb79745bed.jpg)
![20180120103751_1](https://user-images.githubusercontent.com/35630284/35184273-49ccc4a2-fdd2-11e7-8524-2b1d4af40fdb.jpg)

You can open the last red lock with any prop, printer paper boxes, lamps, chairs, you name it.

![20180120103917_1](https://user-images.githubusercontent.com/35630284/35184310-a772770a-fdd2-11e7-8604-e0a0070b48b3.jpg)
![20180120103925_1](https://user-images.githubusercontent.com/35630284/35184311-abac53ae-fdd2-11e7-8f56-c364554a0aa8.jpg)
![20180120103934_1](https://user-images.githubusercontent.com/35630284/35184313-afb85d76-fdd2-11e7-9c8e-d0056a01c338.jpg)
![20180120103946_1](https://user-images.githubusercontent.com/35630284/35184319-b3b1748a-fdd2-11e7-94e2-60e44f9ee8a8.jpg)
![20180120105019_1](https://user-images.githubusercontent.com/35630284/35184320-bfc02adc-fdd2-11e7-919a-4c849bca16b2.jpg)

There is an out of bounds trick where you can take the red key with you and softlock the map. To take the key, just make the first jump onto the rocks, drop the key there until it stays put, make the second jump like in the second screenshot, pick up the key, and lastly, keep going until you are out of bounds.

![20180120104939_1](https://user-images.githubusercontent.com/35630284/35184339-058bd336-fdd3-11e7-8cd5-03cafd181e6e.jpg)

You can also softlock the map by throwing the key under the stairs of the pier

EDIT: Also, if you manage to fix the lock opening with any prop, then the red key should be given a red glow, in case a player hides or misplaces it somewhere.

**Comment by Holycrapjimhox** [comment]
Note: some are duplicates of Fersigal's post 
https://github.com/nmrih/source-game/issues/708

**Comment by Bubka3** [comment]
We're not sure how we are going to handle these mega map issues just yet -- our mappers are reporting its  difficult to go through the issue when its a wall of images.

**Comment by Holycrapjimhox** [comment]
Well, then let me know about a better way to report those issues. I guess I could record each and one of them, but it will be very time consuming to produce a video for every map.

**Comment by Bubka3** [comment]
Just wanted to let you know that your newer issue for broadway with numbering and spacing is a lot easier to follow along. Thanks!

**Comment by Holycrapjimhox** [comment]
Oh yeah my bad. Gonna try to keep it cleaner for next reports.

**Comment by AtheistNMRiH** [comment]
fixed in r8729

**Comment by Winning117** [comment]
Confirmed fixed in src-r4388/dev-r8772, needs to be closed.
