### ISSUE TITLE
Dealing damage when player disconnects

### ISSUE THREAD

**Issue by Fersigal** [nmrih/source-game#827]
Steps to reproduce: 
1) Join a server
2) Throw grenade, Tnt, molotov or shoot a gun, shoot a bow
3) Leave
4) Players get killed because of leaving the server and the client can't register the source of the damage so it thinks it's confused.
This is very frustrating as of recent and a lot of people just disconnect, throw a tnt and leave. (especially frustrating on maps which have common tight spaces and explosives)

**Comment by Holycrapjimhox** [comment]
And also infuriating when there is an escape sequence that requires all players to be together in a tight space, like the train in nmo_broadway or the truck in nmo_junction. There, the troll can kill all players at the end of the map, making it more frustrating.

**Comment by felis-catus** [comment]
Fixed in code commit r4211.
