### ISSUE TITLE
You can throw items full force after they've been unequipped

### ISSUE THREAD

**Issue by Holycrapjimhox** [nmrih/source-game#828]
When you hold G any amount of time while holding an item an then unequipping it, said item can be thrown out of your inventory if you equip it again.

Steps to reproduce:
1) Hold G as long as you want
![20180121141238_1](https://user-images.githubusercontent.com/35630284/35196952-b615bac0-feb7-11e7-821c-ba422fc2bd47.jpg)
2) Press H, or Q or select any other item from your inventory
![20180121141242_1](https://user-images.githubusercontent.com/35630284/35196958-d09f42bc-feb7-11e7-976f-e45b2c7af9db.jpg)
3) Press Q or select the first item through accessing your inventory
![20180121141245_1](https://user-images.githubusercontent.com/35630284/35196966-e4e493ee-feb7-11e7-9280-7e0ecb03ece3.jpg)

The item will be thrown out. If you do this with melee weapons, you can charge up the throw a very long time, then stash your weapon. This way you can look non-threatening because you are unarmed, but as soon as you press Q you'll send a melee weapon flying full force, dealing quite a bit of damage if mp_friendlyfire is set to 1 or the target is infected. If playing on Nightmare with Realism mode enabled, you can get players down to 5 health from 100. It can be used as a tactic in the non-official gamemode PVP. I didn't bother reporting sooner because it's not very effective right now, since player hitboxes are broken. But, if they do get fixed, then it's kinda cheap to hold in your inventory a charged melee and throw it full force with the press of a single button. Could be griefed in co-op and in PVP as well.

Let me know if this has been reported before, because I couldn't find a similar post.

**Comment by felis-catus** [comment]
Fixed in r4207.

**Comment by Bubka3** [comment]
**Resolved Closure**
This issue has been closed as it has been resolved in the current dev build.
It will be available to the public in the next steam release. Thanks for reporting!

Additional comments: dev binaries r8709
