### ISSUE TITLE
Grabbing items from a supply drop can break sprinting

### ISSUE THREAD

**Issue by MintyDysphie** [nmrih/source-game#830]
Tested on v1.0.9.6 and onwards.
Video: https://youtu.be/LkN3Xwn8DA4

Steps to reproduce:

1. Have `X` space left in your inventory
2. Inspect the supply drop and grab a gun that takes `< X` when empty but `> X` when loaded.
3. Try to sprint.

To break out of this:

1. Try to pick up a gun from the ground that won't fit in your inventory.
2. Try to sprint.

You can now sprint again.

What I think happens is that the game calculates whether you have enough free space to grab the gun from the supply drop. However, it fails to account for any ammo the gun may come preloaded with.
You receive the ammo and then the weapon. The weapon can't fit though because the ammo just reduced the total space available so it just drops to the ground. You're now stuck in some sort of 'grabbing gun' stance that won't let you sprint.

**Comment by felis-catus** [comment]
Fixed in r4205.
Now checking weapon + preloaded ammo total weight before taking a weapon, thank you for the detailed report!

**Comment by Bubka3** [comment]
**Resolved Closure**
This issue has been closed as it has been resolved in the current dev build.
It will be available to the public in the next steam release. Thanks for reporting!

Additional comments: dev binaries r8709
