### ISSUE TITLE
nmo_broadway (map bugs)

### ISSUE THREAD

**Issue by Holycrapjimhox** [nmrih/source-game#834]
Here's a compilation of screenshots of several bugs found in nmo_broadway. I asked nay0r if he preferred screenshots or a video, and he preferred the first one. So, here they go:

1) Ways to bug the cinema key:
![20180121114012_1](https://user-images.githubusercontent.com/35630284/35241963-fdca2042-ff96-11e7-88a8-4516c880854c.jpg)
![20180121114007_1](https://user-images.githubusercontent.com/35630284/35241969-02780e42-ff97-11e7-9c57-6238001f689e.jpg)
![20180121114116_1](https://user-images.githubusercontent.com/35630284/35242006-20434e64-ff97-11e7-87d0-ca8b3385276d.jpg)
![20180121114112_1](https://user-images.githubusercontent.com/35630284/35242015-228199ba-ff97-11e7-8cb7-f06e691499a1.jpg)
![20180121114228_1](https://user-images.githubusercontent.com/35630284/35242021-2624ad5a-ff97-11e7-8efa-c84b2c53cb6b.jpg)

2) Ways to bug the battery (you can bug the welder as well in some of those spots):
![20180121114527_1](https://user-images.githubusercontent.com/35630284/35242052-3e9e17e0-ff97-11e7-8fc3-8662bd9d3060.jpg)
![20180121114745_1](https://user-images.githubusercontent.com/35630284/35242059-43d38236-ff97-11e7-9a5d-66c5c6ea1d58.jpg)
![20180121114908_1](https://user-images.githubusercontent.com/35630284/35242727-33715ec0-ff99-11e7-87d8-fb4644dd36a1.jpg)

3) Ways to bug the warehouse leaver:
![20180121115155_1](https://user-images.githubusercontent.com/35630284/35242088-5d1e5e8c-ff97-11e7-84cb-a9fe975d9797.jpg)
![20180121115246_1](https://user-images.githubusercontent.com/35630284/35242095-6277cfe4-ff97-11e7-9ab0-46a4e0e3aa1f.jpg)
![20180121140556_1](https://user-images.githubusercontent.com/35630284/35242627-cf13ff96-ff98-11e7-914e-11083c6798ad.jpg)
![20180121115345_1](https://user-images.githubusercontent.com/35630284/35242103-679fcb52-ff97-11e7-930b-f66b4743ad22.jpg)
![20180121115607_1](https://user-images.githubusercontent.com/35630284/35242115-6d93f51a-ff97-11e7-9f32-27c0a84233fe.jpg)
![20180121115642_1](https://user-images.githubusercontent.com/35630284/35242126-71c96386-ff97-11e7-9529-429f2441d2d9.jpg)
![20180121115747_1](https://user-images.githubusercontent.com/35630284/35242139-79038dca-ff97-11e7-8a8b-85febd384044.jpg)
![20180121115823_1](https://user-images.githubusercontent.com/35630284/35242143-7c9d09c0-ff97-11e7-9982-cd3aadb48a12.jpg)
![20180121115843_1](https://user-images.githubusercontent.com/35630284/35242147-806ef126-ff97-11e7-8060-0bc92e51f008.jpg)
![20180121115956_1
![20180121115516_1](https://user-images.githubusercontent.com/35630284/35242264-d26ed450-ff97-11e7-9a80-6528d11271bf.jpg)
](https://user-images.githubusercontent.com/35630284/35242218-b3d78bb8-ff97-11e7-8974-76c563be2ed1.jpg)
![20180121120119_1](https://user-images.githubusercontent.com/35630284/35242223-b78fd288-ff97-11e7-9946-9a5ad25d34f3.jpg)
![20180121120311_1](https://user-images.githubusercontent.com/35630284/35242234-be6337b2-ff97-11e7-8f5e-83ddeaadf723.jpg)
![20180121120352_1](https://user-images.githubusercontent.com/35630284/35242245-c1d3bfb6-ff97-11e7-876c-331abb54fd88.jpg)
![20180121115516_1](https://user-images.githubusercontent.com/35630284/35243067-617c68e0-ff9a-11e7-8f55-1463359857ab.jpg)
(on this last one, I wasn't able to get it there, but it's technically possible, so I would suggest clipping all those roll-up doors)

4) Ways to bug the bar key:
![20180121135656_1](https://user-images.githubusercontent.com/35630284/35242518-8e6c8256-ff98-11e7-95ad-777bc2e72b7a.jpg)
![20180121135746_1](https://user-images.githubusercontent.com/35630284/35242524-93e88b30-ff98-11e7-98be-e9b5f20a0bf4.jpg)
![20180121135943_1](https://user-images.githubusercontent.com/35630284/35242529-981d6bb2-ff98-11e7-96b1-7dfd07b90342.jpg)
![20180121140044_1](https://user-images.githubusercontent.com/35630284/35242532-9b31d8ec-ff98-11e7-94ad-4bc04e0c7f8d.jpg)
(this one doesn't actually cause a softlock, since you can go around and pick it back up, but it adds a lot of backtracking. It's fine if you don't think it's worth it)
![20180121140156_1](https://user-images.githubusercontent.com/35630284/35242537-9e62fffa-ff98-11e7-857f-ec758a8c6169.jpg)
![20180121140247_1](https://user-images.githubusercontent.com/35630284/35242576-b57d9ce0-ff98-11e7-8067-ba16988caf49.jpg)
![20180121140318_1](https://user-images.githubusercontent.com/35630284/35242587-bafd0732-ff98-11e7-879d-f20d7765b107.jpg)
![20180121140424_1](https://user-images.githubusercontent.com/35630284/35242592-be35f224-ff98-11e7-8625-35d2a009d3b0.jpg)

5) Visual oddities:
![20180121115048_1](https://user-images.githubusercontent.com/35630284/35242792-6bdc55ee-ff99-11e7-9e36-81d158b46b83.jpg)
(the lock falls off the door before the tank explodes)
![20180121115855_1](https://user-images.githubusercontent.com/35630284/35242821-877392b8-ff99-11e7-9fa2-5986cb6ff48e.jpg)
![20180121115904_1](https://user-images.githubusercontent.com/35630284/35242823-89e02264-ff99-11e7-9bad-107fccc4a575.jpg)
(disappearing stairs to the train tracks)

6) Escape train softlock (very well known troll bug):
![20180121120731_1](https://user-images.githubusercontent.com/35630284/35242856-ad2503b6-ff99-11e7-9a39-b540a090b9fa.jpg)
![20180121120842_1](https://user-images.githubusercontent.com/35630284/35242872-b564c430-ff99-11e7-93bb-e9642135fc0d.jpg)
![20180121120844_1](https://user-images.githubusercontent.com/35630284/35242873-b82553e2-ff99-11e7-9991-0dd46720df34.jpg)
![20180121120910_1](https://user-images.githubusercontent.com/35630284/35242880-bb77be36-ff99-11e7-8824-99b82f71962b.jpg)
How to reproduce:
• Stand half way inside and outside the train
• Wait until the doors close (they will open back up when they hit you)
• The train will get stuck with your body between the doors and the wall of the station

**Comment by Fersigal** [comment]
as far as i know the train doors can easily be fixed with a trigger_push when the doors close, might be a little bit unorthodox but it'll fix the issue :à, make a trigger_push at that gap thingey aswell in front of the train.

**Comment by AtheistNMRiH** [comment]
fixed in r8724

**Comment by Winning117** [comment]
Confirmed fixed in atheist's new version, needs to be closed.
