### ISSUE TITLE
Achievement: NIGHTMARE_SURVIVAL

### ISSUE THREAD

**Issue by Bubka3** [nmrih/source-game#837]
This was defined in the enum but no logic is present for it. I believe the idea was complete 3 survival maps on nightmare mode. Maxx has already created the images for it. Just need it in code.

**Comment by Fersigal** [comment]
"the idea was complete 3 survival maps on survival mode" -> nightmare mode

**Comment by Bubka3** [comment]
Actually going to attempt this myself. Will kick it back for code review.
