### ISSUE TITLE
The safe zone of nmo_suzhou

### ISSUE THREAD

**Issue by yomox9** [nmrih/source-game#839]
Version : 1.09.7
What happens : Player don't recieve attack from zombie
When does it happen : Player ride on the chair
Steps to reproduce the issue (How did you do it?) : Ride on the chair
Screenshots : 
![20180122213941_1](https://user-images.githubusercontent.com/14893069/35255212-4b63e24e-0031-11e8-86df-2dcaaccee330.jpg)
![804](https://user-images.githubusercontent.com/14893069/35255186-32488350-0031-11e8-8285-322566cee7b0.png)

**Comment by Fersigal** [comment]
that's called a god spot, there's also another one on the table right behind you (i believe it should be fixed, but i'll need confirmation from Billione)

**Comment by AtheistNMRiH** [comment]
can confirm, it is fixed

**Comment by Winning117** [comment]
Confirmed fixed in src-r4367/dev-r8759, needs to be closed.
