### ISSUE TITLE
nmo_shelter bugs and slight problems

### ISSUE THREAD

**Issue by Fersigal** [nmrih/source-game#840]
![20180123105425_1](https://user-images.githubusercontent.com/11538773/35269736-2d93ee34-002d-11e8-8db8-f990cda5d61d.jpg)
![20180123105542_1](https://user-images.githubusercontent.com/11538773/35269737-2dae5b66-002d-11e8-80a3-460ae71f83c7.jpg)
![20180123105709_1](https://user-images.githubusercontent.com/11538773/35269738-2dca0dac-002d-11e8-92a4-4ee0a5ee5b2a.jpg)
![20180123105731_1](https://user-images.githubusercontent.com/11538773/35269740-2de39858-002d-11e8-9e3a-9a645e4511b8.jpg)
![20180123105806_1](https://user-images.githubusercontent.com/11538773/35269741-2dfd29bc-002d-11e8-8dbc-c48301cd0e13.jpg)
![20180123105941_1](https://user-images.githubusercontent.com/11538773/35269742-2e15e588-002d-11e8-9130-ee74e7fa399f.jpg)
![20180123110005_1](https://user-images.githubusercontent.com/11538773/35269743-2e307092-002d-11e8-9aff-8262699274a8.jpg)
![20180123110045_1](https://user-images.githubusercontent.com/11538773/35269744-2e486486-002d-11e8-9aaf-f95a74d35601.jpg)
![20180123110223_1](https://user-images.githubusercontent.com/11538773/35269745-2e7d2270-002d-11e8-961f-0bbb0097f7b1.jpg)
Mainly a self reminder (wall of JPEGS for life)

**Comment by AtheistNMRiH** [comment]
lol, but why did you post it here? if it is self reminder, you can have it on your pc

**Comment by Fersigal** [comment]
Damn you right :D"

**Comment by Fersigal** [comment]
Ima close this roflmao
