### ISSUE TITLE
Demo's bug complaints / issues about nmo_broadway2

### ISSUE THREAD

**Issue by Fersigal** [nmrih/source-game#841]
Demo's complaints from the steam forums about broadway 2, although i think some of these are a bit unjustified or unclear:

"broadway2 has this the worst runner spawn imo:

- On every objective map you spawn on the other side of a door from zombies and you can leave and engage when you're ready. Broadway 2 has them already pouring in through the first floor of the apartments heading upstairs to your room. This is a major problem for people who load into the map late and before they can even find a wrench there's already runners in their room (I've seen this happen first-hand).

- The first 5 minutes of the map are designated to just slowly clearing out the 30-something zombies that spawn in the alleyway with melee weapons (most of which aren't even random, so have fun with your wrench, knife, bat, and stamina-draining fubar), so you're already paying combat tax right out the gate.

- Lowest distribution of healing items (I only know of 2 medkit spawns on the entire map).  

- Least weapon variety of any map (still haven't seen a chainsaw, SKS, bow, etc).

- Way too much reliance on the cutting torch to the point it's practically mandatory for the whole team to be carrying one.

- Chokepoints refill and clog with respawning zombies too quickly (climbing the ladder outside the cinema to the basketball court, that in-between area that's fenced off like a rectangular arena).

- Too many kids. Kids by themselves aren't powerful, but when there's 20 on-screen at any given time and their fingers are razors that make you bleed and slow to a crawl, throwing runners into the mix and infinite-respawning chokepoints really exacerbates things.

- The fact that some of the wooden military crates can be cut open with the torch, but only some and the map doesn't tell you which ones, further re-inforcing point 5.

- Sometimes the helicopter in the basketball court will leave despite what the count down timer says. I have had TWO occassions where it said "1 (or 2) MINUTES LEFT" but the helicopter took off a few seconds after that text popping up on-screen. If the map says I have two minutes to get there, but the helicopter insists I have 11 seconds, I kinda need to know which to trust.

plz nerf broadway2"

**Comment by Fersigal** [comment]
Out of demo his thoughts i think it's unclear for newbies that you have to weld the crates, but then again i think the medkits spawns are fairly O.K. 
Aside from that there's something annoying about zombies grabbing you through breakable doors, but that might be something related to zombies being able to attack through prop_dynamics

**Comment by Fersigal** [comment]
Something that might help in the map is having a little secret that players will have to fight for, like let's say they have the chance of gaining guns from a gun shop, just like you once did for broadway 1 with a fuel canister (that would be a cool and nostalgic feature in my eyes). I think the main problem that people have is that this map is to dependant on melee and knowing some people they like to use guns on freewill. I know i might've suggested to weld the crate thingies, but i think it has proven so far very frustrating for most players, as some don't even know and without those supplies the map becomes a lot harder

**Comment by Fersigal** [comment]
Ah on another note, if a player gets at the position where the wall blows up (at the tank), the player won't die eventhough it showing off a tnt particle.

**Comment by Holycrapjimhox** [comment]
I disagree with all points except:

• On every objective map you spawn on the other side of a door from zombies and you can leave and engage when you're ready. Broadway 2 has them already pouring in through the first floor of the apartments heading upstairs to your room. This is a major problem for people who load into the map late and before they can even find a wrench there's already runners in their room (I've seen this happen first-hand).

• The fact that some of the wooden military crates can be cut open with the torch, but only some and the map doesn't tell you which ones

I think the general map balancing is fine. If you nerf the basketball court section, the difficulty goes down the drain. Also, I'm fine with maps that force you to kill zombies, not like you can't rush the rest of the map pretty much if you are fast enough and conserve ammo to skip the chokepoints. I'm also OK with the reliance on the welder. Several other maps do this and it's never tedious IMO, like nmo_cleopas. As long as there are several welders in the level, all easily accessible and impossible to throw out of bounds, which in nmo_broadway2 they are setup that way.

Also, the "X MINUTES LEFT" warning is the timer before the explosion occurs. Yes, it can be a bit confusing, so I suggest changing the message to something similar to: "X MINUTES LEFT UNTIL DETONATION".

**Comment by nay0r** [comment]
ok guys ill be going through any problems soon and adding secondary spawns in the map :)

**Comment by Fersigal** [comment]
![20180303215541_1](https://user-images.githubusercontent.com/11538773/36948627-d9381f10-1fdd-11e8-9204-523798cd1238.jpg)
Occasionally they'll spawn inside ladder

**Comment by AtheistNMRiH** [comment]
r9006:
- added "detonation" to final text
- tank now deals damage to players
- fixed zombie stuck in ladder
won't fix other points
