### ISSUE TITLE
Flare gun issues

### ISSUE THREAD

**Issue by Fersigal** [nmrih/source-game#842]
Steps to reproduce: 
1) Load up a game
2) Find a flare gun
3) Have a zombie stand behind a glass texture, breakable, a door or prop_physics it to test it properly
4) Shoot it at doors, glass textures, breakables and prop_physics
5) The flare will go thru it and ignite the zombie

**Comment by AtheistNMRiH** [comment]
I swear there was a post about this issues, can't find it

**Comment by Fersigal** [comment]
I can't recall a bug like this when flares shoot through doors, glass and breakables, i've never seen that one 🤔

**Comment by felis-catus** [comment]
FYI, Flare gun behavior is changed in 1.11.5:
    - The projectile now generates a small explosion that affects props, windows, players/NPCs and so on, replacing the previous damage model that simply dealt direct damage
    - The projectile now breaks through glass and won't explode on contact

Might as well call this bug a feature now, closing!
