### ISSUE TITLE
Shotgun reload sound spam

### ISSUE THREAD

**Issue by Holycrapjimhox** [nmrih/source-game#843]
When a player reloads a shotgun, they can spam the corresponding "X rounds left" voice line over and over, without any cooldown. It's pretty annoying and it can be griefed.

• Steps to reproduce:
1) Find a shotgun with ammo (except the double-barreled SV10)
2) Unload it by pressing U
3) Once unloaded press R to reload
4) Immediately cancel the reload with RMB
5) Keep pressing RMB slightly after R and repeat ad infinitum
6) You will continuously spam the "X rounds left" voice line.

A similar thing can be done with every weapon, but shotguns are the only ones which their reload can be cancelled by hitting RMB, and can almost immediately be reloaded again. Therefore, they are the ones that cause spam, other weapons do it much slower, and I wouldn't call it spam.

• Here's a video demonstration:
https://www.youtube.com/watch?v=AI4f_WukreE

• Suggestion:
Do not change the way the reloads work, maybe just add a cooldown for those voice lines. The RMB reload cancelling works fine.

**Comment by felis-catus** [comment]
Fixed in src-r5912.
