### ISSUE TITLE
Can't exit keypad menu

### ISSUE THREAD

**Issue by Jesse-Culver** [nmrih/source-game#844]
Version: Steam

If a player enters the keypad menu screen they can not exit it unless they input a code making it an issue if they find themselves under attack and need to react.

**Comment by Holycrapjimhox** [comment]
This is not a bug as far as I know, the game lacks a feature to cancel keypad usage. Just be careful when you use it and type the correct code quickly.

**Comment by felis-catus** [comment]
You can currently exit by right-clicking the outer area of the keypad. Planning to improve this in the next update by adding a keyboard shortcut.
