### ISSUE TITLE
Male voice when female model randomly chosen

### ISSUE THREAD

**Issue by Bubka3** [nmrih/source-game#849]
If you select your character as random and get badass, her voice radial menu is correct but other things like ammo check happen in whatever male voice you had.

Theres a video in the programming channel for this

**Comment by Fersigal** [comment]
Maybe it's a shemale =o

**Comment by felis-catus** [comment]
Fixed in code commit r4246.

**Comment by Bubka3** [comment]
**Resolved Closure**
This issue has been closed as it has been resolved in the current dev build.
It will be available to the public in the next steam release. Thanks for reporting!

Additional comments: tested on bins r8726
