### ISSUE TITLE
Listen server settings do not  read/write properly

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#851]
File location: Steam\steamapps\common\nmrih\nmrih\cfg

The settings.scr file is missing the following options that are present in settings_default.scr:

`"sv_difficulty"
	{
		"#NMRiH_Difficulty"
		{ LIST 
			"#NMRiH_Difficulty_Classic" 	"classic" 
			"#NMRiH_Difficulty_Casual"  	"casual" 
			"#NMRiH_Difficulty_Nightmare"	"nightmare" 
		}
		{ "0" }
	}`

and
`"sv_lan_only"
	{
		"#NMRiH_LAN"
		{ BOOL }
		{ "0" }
	}`

**Comment by Bubka3** [comment]
Confirmed failure to read or write the automatically generated file in dev build.

**Comment by Bubka3** [comment]
Greetings. It appears the active settings.scr is actually stored in this path:
Steam\steamapps\common\nmrih\sdk\nmrih\cfg

Please let us know if this is still a problem.

**Comment by Winning117** [comment]
It appears that there is still a failure to write `"sv_lan_only" { "#NMRiH_LAN" { BOOL } { "0" } }` in Steam\steamapps\common\nmrih\sdk\nmrih\cfg

**Comment by Bubka3** [comment]
Please delete the settings.scr file there and it should re-generate from settings_default.scr in the main dir when you restart game.

**Comment by Winning117** [comment]
I deleted it and restarted the game and now I have no file LOL rip

**Comment by Bubka3** [comment]
You need actually create a server for it to re-generate.

**Comment by Winning117** [comment]
Oh there we go, thanks Bubka
