### ISSUE TITLE
nms_favela Map Bugs (Out of bounds/invincible spots/clipping errors)

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#852]
I decided to make a video of the bugs I've found because the out of bounds glitches are hard to capture in a screenshot if you don't know the route. These are all really quick fixes, most clips just need to be extended upward. Let me know if you need clarification on any of them. https://www.youtube.com/watch?v=9PjE1TYcJZQ&feature=youtu.be

**Comment by AtheistNMRiH** [comment]
iirc there will be favela2 which will REPLACE current version, so it is not necessary to fix current map

**Comment by Fersigal** [comment]
I don't want to be the naughty boy here, but i don't think that this is that much gamebreaking, considering that the objective is to defend the zones

**Comment by AtheistNMRiH** [comment]
that's why we will fix that last :stuck_out_tongue:

**Comment by AtheistNMRiH** [comment]
fixed in r8746

**Comment by Winning117** [comment]
Confirmed fixed in src-r4367/dev-r8764.
