### ISSUE TITLE
(public) throw grenade sound error

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#854]
steps to reproduce
1) give exp_grenade
2) throw it
3) check console and see this:
Failed to load sound ")weapons\firearms\exp_frag\frag_throw.wav", file probably missing from disk/repository

**Comment by Fersigal** [comment]
Same works for the lighter btw, it spews something in console

**Comment by Bubka3** [comment]
Please remember to mention if this is dev build or public.

Looks like a typo. Will take care of it!

**Comment by AtheistNMRiH** [comment]
iirc it was always in game, sorry for not mentioning

**Comment by felis-catus** [comment]
No wave file exist for this, script comments say "not yet made".

**Comment by DDysphie** [comment]
`{hl2_sound_misc_dir}/weapons/slam/throw.wav`could be used
