### ISSUE TITLE
tnt/molotov sounds don't loop

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#856]
1) give exp_molotov and exp_tnt
2) press LMB and hold it
3) listen --> rag fire sound and spark sound work, but they **DON'T LOOP**

**Comment by AtheistNMRiH** [comment]
checked in dev build, fire sound works fine, but still no rag fire sound

**Comment by Bubka3** [comment]
commit src-4371

**Comment by Winning117** [comment]
Confirmed initial light sound works in src-r4367/dev-r8764 but there is not a continuous light/spark noise while holding it in your hands.

**Comment by AtheistNMRiH** [comment]
check first comment please

**Comment by Winning117** [comment]
Confirmed fixed in src-r4388/dev-r8769, needs to be closed.
