### ISSUE TITLE
When extraction,players status is wrong ( ALIVE / DECEASED )

### ISSUE THREAD

**Issue by yomox9** [nmrih/source-game#858]
Player status inverted.

Example. When all player could extract
![20180212183206_1](https://user-images.githubusercontent.com/14893069/36131436-1e78c7ba-10b5-11e8-9388-d7c8220dcd5a.jpg)
It should be "ALIVE".

**Comment by Fersigal** [comment]
Duplicate #27

**Comment by Bubka3** [comment]
**Duplicate Closure**
This issue has been closed because it has already been reported under a previous issue ID.
Please follow the issue below for further updates.

Duplicate of #27
