### ISSUE TITLE
nms_ransack map bugs

### ISSUE THREAD

**Issue by Fersigal** [nmrih/source-game#859]
NMS RANSACK
![2015-03-28_00068](https://cloud.githubusercontent.com/assets/11538773/6881827/05fc8bc4-d56f-11e4-91e8-6bf4a75ee2ca.jpg) IB (at the small alley)
![2015-03-28_00069](https://cloud.githubusercontent.com/assets/11538773/6881825/05faf3fe-d56f-11e4-8e21-c59b9281ff69.jpg) ZBB 
![2015-03-28_00070](https://cloud.githubusercontent.com/assets/11538773/6881828/060c0cc0-d56f-11e4-80f2-889aa90cd700.jpg) IB

**Comment by Fersigal** [comment]
See #710 
Fixed,  cleaned up because the thread became really confusing

**Comment by Bubka3** [comment]
Im not sure what the intent of this issue is.

**Comment by AtheistNMRiH** [comment]
yeah, no need to open new issues, I'm working fine with original one

**Comment by Smil3yRiley** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/nmrih/source-game/issues/870](https://trello.com/c/GAYDqT9y/135-https-githubcom-nmrih-source-game-issues-870)
