### ISSUE TITLE
(dev) cleric voice line doesn't work for empty gun

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#860]
1) get empty gun
2) check ammo -> CLERIC doesn't say anything (also no HUD when you have plenty of magazines),
3) reload or check ammo when you have 1 or more bullets -> character says respective voice lines

**Comment by Bubka3** [comment]
Go to C:\Program Files (x86)\Steam\steamapps\common\Source SDK Base 2013 Multiplayer\nmrih\sound and delete the sound.cache file. Does the problem still occur?

**Comment by AtheistNMRiH** [comment]
yes

**Comment by Bubka3** [comment]
what character and voice set do you have set?

**Comment by AtheistNMRiH** [comment]
molotov and cleric

**Comment by AtheistNMRiH** [comment]
made a little investigation, check first comment

**Comment by felis-catus** [comment]
I accidentally removed the empty line in the script, will be fixed.

**Comment by Bubka3** [comment]
**Resolved Closure**
This issue has been closed as it has been resolved in the current dev build.
It will be available to the public in the next steam release. Thanks for reporting!

Additional comments: dev-r8734
