### ISSUE TITLE
(public) welding through walls

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#863]
![nmo_toxteth0022](https://user-images.githubusercontent.com/11333747/36372095-93533fee-1596-11e8-97b8-f7322574213d.jpg)
looks like trigger activates in some radius, ignoring brushes
I tried to use func_brush to prevent it, but it doesn't help
is it possible to fix this?

**Comment by felis-catus** [comment]
Going to leave this as is to avoid map breakage.
