### ISSUE TITLE
TFG voice set missing round left 11 thru 15

### ISSUE THREAD

**Issue by Bubka3** [nmrih/source-game#865]
It doesn't appear these files existed at any point. We can either remove the voice set or set 11 - 15 to play the "about half" voice line.

**Comment by Bubka3** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [TFG voice set missing rounds left 11-15](https://trello.com/c/0SfSt8MM/139-tfg-voice-set-missing-rounds-left-11-15)

**Comment by AtheistNMRiH** [comment]
"missing round left 11 thru 15" files exist in path player/ammocheck/alt1

**Comment by Bubka3** [comment]
commited dev-8798

**Comment by DDysphie** [comment]
Seems to work but I thought I would mention: `12rounds_02` and `12rounds_03` are the same file

**Comment by Bubka3** [comment]
Removed duplicate file in dev-8802
