### ISSUE TITLE
Name tag color commands are cheat protected

### ISSUE THREAD

**Issue by MintyDysphie** [nmrih/source-game#867]
```
"cl_full_health_color_r" = "0"
 client cheat
"cl_full_health_color_g" = "255"
 client cheat
"cl_full_health_color_b" = "0"
 client cheat
"cl_half_health_color_r" = "255"
 client cheat
"cl_half_health_color_g" = "255"
 client cheat
"cl_half_health_color_b" = "0"
 client cheat
"cl_low_health_color_r" = "255"
 client cheat
"cl_low_health_color_g" = "0"
 client cheat
"cl_low_health_color_b" = "0"
 client cheat
```

Although not necessarily a bug I see no real reason for the cheat flag to be there. I can't distinguish between certain colors very well and so I think we should be able to change them.

(This was already pointed out on Discord but I thought I would archive it)

**Comment by felis-catus** [comment]
Already in dev build. (code commit r4283)

**Comment by Bubka3** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [herp derp I am test](https://trello.com/c/yNzhXqHK/136-herp-derp-i-am-test)
