### ISSUE TITLE
Spectator mode: Shove animation is played multiple times

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#872]
Affects first person spectating. When a player pushes zombies away, others will see the shove animation being played multiple times in a quick succession. AFAIK repeatability is 100%

**Comment by dysphie** [comment]
Could this be caused by the game checking for stamina before a shove? I get a similar effect if I shove on every frame while exhausted. Spectators have no stamina so the game might get confused and repeatedly try to cancel the activity even though it's not theirs.

**Comment by felis-catus** [comment]
Bringing this up, now that stamina has been tampered with.

**Comment by felis-catus** [comment]
Fixed in src-r4942.
