### ISSUE TITLE
Crawler bite chance too low

### ISSUE THREAD

**Issue by yomox9** [nmrih/source-game#876]
version 1.09.7
I saw this issue without sourcemod/metamod.
Reproduce : Vanira or sv_zombie_shambler_crawler_chance 1.00
![20180227095847_1](https://user-images.githubusercontent.com/14893069/36705082-bd12c6d6-1ba6-11e8-934c-4a5116ffb134.jpg)

**Comment by DDysphie** [comment]
That ConVar controls the chance for shamblers to spawn as crawlers, not how often they will bite.
It's true, though, that crawlers are overly dumb when it comes to biting people.

**Comment by yomox9** [comment]
ah- yes, I know. I wrote "sv_zombie_shambler_crawler_chance 1.00" for reproduce.

**Comment by Winning117** [comment]
Players also don't get stuck in place while being bit like they are with shamblers. Tested in src-r4405/dev-r8773.

**Comment by DDysphie** [comment]
Players do lose mobility while being bit by crawlers. Can you specify an instance where they not?

**Comment by Winning117** [comment]
https://www.youtube.com/watch?v=Mz0svwKV9mg
Not losing mobility here

**Comment by DDysphie** [comment]
>https://www.youtube.com/watch?v=Mz0svwKV9mg
>Not losing mobility here

You are **not** being bitten in this video.

**Comment by Ryan-nmrih** [comment]
I think there are some oddities with the grab mechanic when multiple zombies are involved. For example, If you're grabbed by a crawler and then a shambler tries to grab you, you will break free of the crawler.

**Comment by Winning117** [comment]
Video of me being bitten fully by crawler (holding down backpedal the entire time) and then I just walk away. Testing repro steps with multiple zombies

**Comment by Ryan-nmrih** [comment]
Demo [grab.zip](https://github.com/nmrih/source-game/files/1879167/grab.zip)

**Comment by felis-catus** [comment]
Coming back to this, there is a cooldown where players won't be grabbed again for a short period of time, during that zombies will attempt to attack the player instead. Crawlers have no such functionality and will stare at your feet until the timer expires.

A solution would either be a separate timer or making crawlers immune to the cooldown, although this may negatively affect the gameplay balance.

**Comment by felis-catus** [comment]
Not necessarily a bug, closing.
