### ISSUE TITLE
Boardwalk, excessive zombie spawning 

### ISSUE THREAD

**Issue by DDysphie** [nmrih/source-game#877]
Boardwalk will often spawn 1k+ zombies in the span of about 3 minutes, causing a no free edicts exception

```
L 02/26/2018 - 07:03:59: (53.10%) 1088	npc_nmrih_shamblerzombie
L 02/26/2018 - 07:03:59: Total edicts: 2049
L 02/26/2018 - 07:03:59: Engine error: ED_Alloc: no free edicts
```
[Full console log](https://pastebin.com/raw/iXh0aXFt)

```
L 02/27/2018 - 07:55:40: (53.54%) 1097	npc_nmrih_shamblerzombie
L 02/27/2018 - 07:55:40: Total edicts: 2049
L 02/27/2018 - 07:55:40: Engine error: ED_Alloc: no free edicts
```
[Full console log](https://pastebin.com/raw/7rNFjAXL)

**Comment by AtheistNMRiH** [comment]
is it problem without entity remover plugin? never had a crash on this map

**Comment by DDysphie** [comment]
This is on servers without entity-fiddling plugins. Those logs you see are from the [Crash Helper extension](https://forums.alliedmods.net/showthread.php?p=2031093)

**Comment by AtheistNMRiH** [comment]
oh, ok then

**Comment by Bubka3** [comment]
All crash issues must be accompanied by a dump file when posting on Github. Thanks.

**Comment by DDysphie** [comment]
Servers don't crash on low edicts, they just hang up and must be manually rebooted.
There are no crash dumps for it.

**Comment by DDysphie** [comment]
`developer 1`
Seems like it gets stuck in a spawning loop:

```Making NPC in radius..
1)There
2)There
1)Here we are...
2)Here we are...
3)Here we are...
Found a valid spawn point !
Found a valid spawn point !
Found a valid spawn point !
Found a valid spawn point !
4)Here we are...
Here we go...
Failed to find a spawn destination
Making NPC in radius..
1)There
2)There
1)Here we are...
2)Here we are...
3)Here we are...
Found a valid spawn point !
Found a valid spawn point !
Found a valid spawn point !
4)Here we are...
Here we go...
Failed to find a spawn destination
Making NPC in radius..
1)There
2)There
1)Here we are...
2)Here we are...
3)Here we are...
Found a valid spawn point !
Found a valid spawn point !
Found a valid spawn point !
Found a valid spawn point !
4)Here we are...
Here we go...
Failed to find a spawn destination
 ```
with zombies spawning after each iteration until it consumes all edicts.

**Comment by DDysphie** [comment]
Fixed and confirmed in src-r4469.
