### ISSUE TITLE
nmo_chinatown (map bugs)

### ISSUE THREAD

**Issue by Holycrapjimhox** [nmrih/source-game#878]
NOTE: this is the public version of nmo_chinatown available on version 1.9.0.7.

**• Item softlocks:**

1) Gas can bugs:
![20180220221835_1](https://user-images.githubusercontent.com/35630284/36756988-56b830ee-1bef-11e8-9b4b-a9628e9e44c5.jpg)
(not really a softlock, but it's rather tricky to get it out of there, and a regular player might think it's a softlock)
![20180220221937_1](https://user-images.githubusercontent.com/35630284/36756989-56e0a8d0-1bef-11e8-9f46-6efcbaa67eb6.jpg)
(same thing here as before)
![20180220222617_1](https://user-images.githubusercontent.com/35630284/36756992-5729a54e-1bef-11e8-83f1-d93077531653.jpg)
![20180220223414_1](https://user-images.githubusercontent.com/35630284/36756994-57545e2e-1bef-11e8-9025-5691d14862b0.jpg)
(here you have to jump on top of the car's rear-view mirror and jump straight in the direction of the roof)
![20180220223659_1](https://user-images.githubusercontent.com/35630284/36756995-577a7d2a-1bef-11e8-863b-1f5df05f33a6.jpg)
(this can be done on most shelves)
![20180220223738_1](https://user-images.githubusercontent.com/35630284/36756996-57a5893e-1bef-11e8-9bd3-2e45eaa86177.jpg)
(this one may look tricky, since you have to do a jump and a zombie boost, but it's actually easy, because there are many zombies in that alley constantly)
![20180220223833_1](https://user-images.githubusercontent.com/35630284/36756997-57d46402-1bef-11e8-8272-8b4f7920d873.jpg)
(same bug as before, it can be done everywhere up on that ledge)
![20180220221653_1](https://user-images.githubusercontent.com/35630284/36756999-5bdfb650-1bef-11e8-8860-8c6440e6c0fa.jpg)
(on this one, the gas can CAN fall behind the shelf, but I haven't been able to do it legit, might be worth noting though)

2) Welder bugs (this one is not too high priority, since there are three welders on the map, but technically a really dedicated troll could softlock it):
![20180220224342_1](https://user-images.githubusercontent.com/35630284/36757539-a6a37126-1bf0-11e8-9185-8789b9f5ea31.jpg)
![20180220224345_1](https://user-images.githubusercontent.com/35630284/36757540-a6cd4d16-1bf0-11e8-9fa4-ec8131e832df.jpg)
![20180220224357_1](https://user-images.githubusercontent.com/35630284/36757543-a6f09852-1bf0-11e8-98bc-8e8055d23e62.jpg)
![20180220224519_1](https://user-images.githubusercontent.com/35630284/36757544-a7152fa0-1bf0-11e8-978a-c17f3b2d46d5.jpg)
![20180220224703_1](https://user-images.githubusercontent.com/35630284/36757545-a73a6cc0-1bf0-11e8-95c8-4b1eadac5470.jpg)
![20180220224730_1](https://user-images.githubusercontent.com/35630284/36757546-a766c04a-1bf0-11e8-850a-5d92d0817907.jpg)
![20180220224804_1](https://user-images.githubusercontent.com/35630284/36757547-a790afc2-1bf0-11e8-83c3-ec1f922a00f9.jpg)
![20180220224811_1](https://user-images.githubusercontent.com/35630284/36757548-a7b3dc04-1bf0-11e8-89bc-a3ac3c104f57.jpg)
![20180220225140_1](https://user-images.githubusercontent.com/35630284/36757549-a7d55fe6-1bf0-11e8-9f18-a0449b906b34.jpg)
![20180220225253_1](https://user-images.githubusercontent.com/35630284/36757550-a7fa0dc8-1bf0-11e8-85cd-494052377063.jpg)
![20180220225304_1](https://user-images.githubusercontent.com/35630284/36757551-a840add2-1bf0-11e8-9bf5-fefc8a890c7f.jpg)
![20180220225354_1](https://user-images.githubusercontent.com/35630284/36757552-a865d030-1bf0-11e8-9a4d-bf8b3fad09ac.jpg)
![20180220225408_1](https://user-images.githubusercontent.com/35630284/36757553-a89835c0-1bf0-11e8-838c-bed020442043.jpg)
![20180220225912_1](https://user-images.githubusercontent.com/35630284/36757554-a8b99242-1bf0-11e8-8f6b-41d4e3d0a137.jpg)
![20180220225923_1](https://user-images.githubusercontent.com/35630284/36757555-a8dcf0f2-1bf0-11e8-8458-c79ace4716cb.jpg)
![20180220225945_1](https://user-images.githubusercontent.com/35630284/36757556-a8fe56a2-1bf0-11e8-8a95-60b09590bca6.jpg)

3) Radio cable bugs
![20180220230157_1](https://user-images.githubusercontent.com/35630284/36757717-13156abc-1bf1-11e8-8a5d-803c28a468c1.jpg)
![20180220230206_1](https://user-images.githubusercontent.com/35630284/36757718-133b6636-1bf1-11e8-8882-f2d45d5d45ad.jpg)

**• Other softlocks:**
This is a pretty obscure troll bug, but we had a horrible player in our servers a few years back, who used to do this to newbies. This door has health associated with it, so if you manage to get that health to 0, it will stop opening/closing. This way you can permanently trap someone inside.

-First step: wait for a player to enter the first room next to spawn
![20180227183135_1](https://user-images.githubusercontent.com/35630284/36757831-4eaee0e4-1bf1-11e8-8131-4e3f8f8d94bc.jpg)
-Second step: stand on the door frame, touching it on the left side
![20180227183144_1](https://user-images.githubusercontent.com/35630284/36757832-4ed2c2fc-1bf1-11e8-9a4b-9b23245c743a.jpg)
-Third step: close the door, it will get stuck
![20180227183146_1](https://user-images.githubusercontent.com/35630284/36757834-4ef5f6c8-1bf1-11e8-9d53-23bfb9e7cbc9.jpg)
-Fourth step: start spamming E (use) to open and close it quickly, while at the same time shooting it with a firearm or hitting it with melee, until its health reaches 0 (you would have to calculate offline how many hits it takes from each weapon, before attempting to trap a player)
![20180227183149_1](https://user-images.githubusercontent.com/35630284/36757836-4f207240-1bf1-11e8-9a27-f61814f843ec.jpg)
-Fifth step: keep spamming E (use) until you know which button press closes the door towards you.
![20180227183210_1](https://user-images.githubusercontent.com/35630284/36757837-4f492ea6-1bf1-11e8-8518-be4831dbb066.jpg)
-Final step: once you are certain the door is moving towards you, move away from it and it will remain closed forever.
![20180227183215_1](https://user-images.githubusercontent.com/35630284/36757839-4f6d87e2-1bf1-11e8-92a1-b1c14ecfaf62.jpg)

**• Map oddities:**
1) Players clip into the rubble to the right of the subway exit:
![20180220222118_1](https://user-images.githubusercontent.com/35630284/36758234-a1cb1062-1bf2-11e8-8810-12625a84549e.jpg)

2) If you stand right next to where the chopper lands, it will crush you after the cinematic:
![20180220230302_1](https://user-images.githubusercontent.com/35630284/36758297-cb192ff8-1bf2-11e8-8773-4616341268fb.jpg)
![20180220230337_1](https://user-images.githubusercontent.com/35630284/36758298-cb3bf646-1bf2-11e8-96ef-0372ce14e898.jpg)
![20180220230344_1](https://user-images.githubusercontent.com/35630284/36758299-cb5e5902-1bf2-11e8-996a-24e69efbfc21.jpg)

**• Difficulty balancing (suggestion):**
The chainsaw here is incredibly overpowered. It's a trivial map overall, but the chainsaw just makes the difficulty non-existent. You can literally walk to the end of the map. IMO it should be removed entirely, or left with little fuel to kill runners or get past crowded chokepoints.

**Comment by AtheistNMRiH** [comment]
fixed in r8744

**Comment by Winning117** [comment]
Confirmed fixed in src-r4388/dev-r8769.
