### ISSUE TITLE
(public) Ammo checking

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#879]
1) get two weapons
2) check ammo with first weapon
![nmo_chinatown0006](https://user-images.githubusercontent.com/11333747/36943825-b1b2f58e-1fc2-11e8-85e7-3d176c38fec5.jpg)

3) quickly switch to another weapon
![nmo_chinatown0007](https://user-images.githubusercontent.com/11333747/36943832-bfe09e54-1fc2-11e8-85ef-d52ab2c47271.jpg)

4) you can see ammo for another weapon without checking sequence
![nmo_chinatown0008](https://user-images.githubusercontent.com/11333747/36943837-dd4925d8-1fc2-11e8-9923-2271a33abdac.jpg)

**Comment by felis-catus** [comment]
Resolved in src-r4321.

**Comment by AtheistNMRiH** [comment]
checked in dev build, works fine, need to be closed
