### ISSUE TITLE
InfectionChanceModifier in difficulty scripts not working

### ISSUE THREAD

**Issue by Jesse-Culver** [nmrih/source-game#882]
InfectionChanceModifier should do what it sounds like, set the infection chance. At the moment it doesn't. Applies to both public and dev.

**Comment by Jesse-Culver** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [InfectionChanceModifier not working in difficulty scripts](https://trello.com/c/Y3byaUkH/149-infectionchancemodifier-not-working-in-difficulty-scripts)

**Comment by Bubka3** [comment]
Unable to reproduce, it appears to be setting correctly:
```
] sv_difficulty 
"sv_difficulty" = "casual" ( def. "classic" )
 game archive replicated
 - Difficulty mode
] sv_infect_chance_modifier 

"sv_infect_chance_modifier" = "0.975" game cheat replicated
 - Modifier for infect chance formula
] sv_difficulty test
] sv_infect_chance_modifier
 ( def. "0.975" )"sv_infect_chance_modifier" = "0.123000"
 game cheat replicated
 - Modifier for infect chance formula
```
