### ISSUE TITLE
RemoveInflictionsOnNewWave not working in difficulty scripts

### ISSUE THREAD

**Issue by Jesse-Culver** [nmrih/source-game#883]
When enabled it should cure the player if they are infected at the end of a wave, currently it does not. Applies to both public and dev builds.

**Comment by Jesse-Culver** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [RemoveInflictionsOnNewWave not working in difficulty scripts](https://trello.com/c/B1A0pc8I/150-removeinflictionsonnewwave-not-working-in-difficulty-scripts)

**Comment by felis-catus** [comment]
Works on my end, and the code looks ok to me. How did you encounter this issue?

**Comment by felis-catus** [comment]
Closing, this is working correctly on my end and the actual issue was never clarified.
