### ISSUE TITLE
nms_camilla has two nonsolid door frames

### ISSUE THREAD

**Issue by Jesse-Culver** [nmrih/source-game#884]
At the front of the diner there are two door frames side by side that lack collision.
![20180314145402_1](https://user-images.githubusercontent.com/14971400/37430420-0d45aac4-27a0-11e8-9e55-6fbfd85aa7ac.jpg)
![20180314145407_1](https://user-images.githubusercontent.com/14971400/37430423-0e670a88-27a0-11e8-9c33-caddc3bb2312.jpg)

**Comment by Jesse-Culver** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [nms_camilla non solid door frames](https://trello.com/c/XQgTCCrt/153-nmscamilla-non-solid-door-frames)

**Comment by Winning117** [comment]
I thought that these were made non-solid to prevent zombies from getting stuck in the doorway.

**Comment by Holycrapjimhox** [comment]
I think that it's intentional. Those non-solid door frames are present from early versions like _v2 and their purpose is probably what Winning has explained.

**Comment by AtheistNMRiH** [comment]
yes, it was intetional, but I reworked this part anyway because why would u have 3 doors there lol

**Comment by Fersigal** [comment]
I think his main point is that you can see through the nodraw clip, you can just easily fix it by putting a player clip there. That's the main complaint as shown in the pictures, i don't think it has any affiliation with the fact that it's non solid, but more with the fact that it's shown as a simple nodraw brush
