### ISSUE TITLE
(public) Non-empty supply crate prevents calling another supply drop via flares

### ISSUE THREAD

**Issue by Holycrapjimhox** [nmrih/source-game#885]
Steps to reproduce:

1) Play any NMS map
2) Get a flare gun + ammo
3) Call a supply drop
4) Call another supply drop again while the old crate is full

The flare gun won't do anything until you empty the old supply crate. The same thing happens if the non-empty supply crate comes from a scripted drop during one of the waves, the flare still won't be able to call another one until the old one is emptied.

I do wonder though, is this intentional or not? My guess is that it's not, since it's pretty gimmicky and unrealistic, and from a server stability point of view it's also dumb, because you force players to empty many, many items into the ground. This has caused an immense amount of lag during certain matches in my experience.

**Comment by yomox9** [comment]
I also agree with that. "Why does not the helicopter come?". It's difficult that player guess cause.

**Comment by Holycrapjimhox** [comment]
I'm guessing that it would make sense from a game balance point of view, since you would be able to get a lot of good weapons and melee from round 1, as soon as you find the flaregun and some flares.

But on the other hand, you can kinda still do that, since you just have to empty the supply drop you got first, and then repeat. You could have like 5 supply drops on the first wave.

**Comment by Bubka3** [comment]
We can probably make the current supply drop despawn, and probably some sort of cooldown on the flares summoning a supply drop.

**Comment by Holycrapjimhox** [comment]
In my opinion, the best way to balance it is to cap the amount of times you can call a supply drop to a maximum of 2. There are already many supply drops in official maps, and they are pretty trivial to complete, except maybe isolated and ransack.

**Comment by essbuh** [comment]
I'm pretty sure this was intentional.  There are other options like allowing 2 crates at once, despawning the oldest crate, etc.

**Comment by Holycrapjimhox** [comment]
Well, if it's intentional, then take this as a re-balance suggestion. My opinion stands, there should be 1 or 2 maximum extra supply drops per round by using the flaregun. Any more than that can make servers unstable and it makes the maps trivial.

**Comment by DDysphie** [comment]
Else this happens:

![7n1shm](https://user-images.githubusercontent.com/11559683/37726832-1244127a-2d15-11e8-8c31-c877b0267402.jpg)

**Comment by Winning117** [comment]
I agree, this needs to be rebalanced because it’s very overpowered. You could possibly have a voiceover with something along the lines of “Hang tight survivors, we don’t have enough supplies to drop more off yet.”

**Comment by Holycrapjimhox** [comment]
Balance issue resolved in dev r-8885. A new cvar was added "sv_flare_gun_supply_limit" which sets the max amount of supplies that can be spawned via flare gun. Default value is 1, set to -1 for no limit.
