### ISSUE TITLE
Broken animations for water 

### ISSUE THREAD

**Issue by Fersigal** [nmrih/source-game#888]
Steps to reproduce:
1)Play official maps that have water (nms_arpley, nmo_shelter, nmo_lakeside)
2) Hit water (mainly underwater)
3) Animations freeze, sometimes they even ragdoll

Uncertain whether if this will ever get fixed, since there's no animator, but might be able to circumvent it by adding code to it to force the player to not freeze 
By freezing i mean, if you run and you hit water or you're out of stamina you'll keep that effect unless you leave the water.

Just to be complete, this issue is more severe if the player can go under water, but still appears if the body is half above and slightly under the water.

**Comment by felis-catus** [comment]
No, this is a separate issue.

**Comment by Fersigal** [comment]
this is the clarifications in screenshots:
![20180318133638_1](https://user-images.githubusercontent.com/11538773/37864003-843b8a0c-2f68-11e8-9203-e7bb7a041ad2.jpg)
![20180318133646_1](https://user-images.githubusercontent.com/11538773/37864005-8450ef82-2f68-11e8-94b7-d95bc495b7ba.jpg)
![20180318133738_1](https://user-images.githubusercontent.com/11538773/37864006-8468972c-2f68-11e8-9494-1d6f6433e673.jpg)

**Comment by felis-catus** [comment]
Fixed in src-r5039.
