### ISSUE TITLE
(dev) new error spew in console when pressing anything

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#890]
but it works only with "developer 2", so it isn't noticeable for average players

looks like it happens with all menu tabs (choosing voice set, add-ons and etc.)

p.s. @felis-catus , is that grey bar intentional?

![nmo_fema0001](https://user-images.githubusercontent.com/11333747/37587133-fc20d1b6-2b90-11e8-9d50-30895d2fc137.jpg)

![snapshot0002](https://user-images.githubusercontent.com/11333747/37587477-056769e6-2b92-11e8-918b-5b98375a2335.jpg)

**Comment by felis-catus** [comment]
Not really an issue. I silenced one noisy assert by changing it to spew, didn't know it was this widespread though. I should just squelch it for good because this is only a wasted call at worst.

Scoreboard selection has incorrect color by accident after I merged the scheme files, will fix.
