### ISSUE TITLE
Srcds crash: server.dll + 0x1aeb66

### ISSUE THREAD

**Issue by DDysphie** [nmrih/source-game#892]
Server will randomly crash on this function, at least once a day, even on a fresh install.
Doesn't seem to be map-specific or game mode-specific.

Game build: 1.0.9.7
OS: Windows 7 Service Pack 1
Metamod version: 1.10 - build 961
Sourcemod version: Many, 1.8+ (currently 1.9.0.6151)

Below 11 crash dumps for it:
[Minidumps.zip](https://github.com/nmrih/source-game/files/1827649/Minidumps.zip)

**Comment by felis-catus** [comment]
Thanks, located the issue and resolved for 1.10.

Note for QA: r4350 deals with this issue, not # 893 that I mistakenly referenced in the commit log. 👌

**Comment by Bubka3** [comment]
Closing. There's no way to test this and the SVN server hasn't crashed with it. Additionally the code does what the commit log says it does.
