### ISSUE TITLE
Hitbox

### ISSUE THREAD

**Issue by Nikitos365** [nmrih/source-game#894]
Fix it
![Hitbox](https://steamuserimages-a.akamaihd.net/ugc/924801101765087609/7068DA9FF79B0982F45F2AED4550723D7EEFE73A/)
![Hitbox](https://steamuserimages-a.akamaihd.net/ugc/924801101765088219/A6E19E93AB006EB279486BA0E6C5B5A910CFA7C2/)

**Comment by felis-catus** [comment]
Duplicate of #820, already resolved.
