### ISSUE TITLE
hud_draw_fixed_reticle has no cheat flag

### ISSUE THREAD

**Issue by DDysphie** [nmrih/source-game#895]
`hud_draw_fixed_reticle` should be cheat protected as it adds a crosshair to the screen

**Comment by Fersigal** [comment]
You need to clarify whether if it is in dev build or public build or both

**Comment by felis-catus** [comment]
Confirmed in both builds.

**Comment by Bubka3** [comment]
**Resolved Closure**
This issue has been closed as it has been resolved in the current dev build.
It will be available to the public in the next steam release. Thanks for reporting!

Additional comments: r4357
