### ISSUE TITLE
Ammo shows green outline even if inventory is full

### ISSUE THREAD

**Issue by DDysphie** [nmrih/source-game#896]
Repro:
1. Pick up weapon, givecurrentammo
2. Spawn ammo box

![20180323195815_1](https://user-images.githubusercontent.com/11559683/37856734-df53f800-2ed4-11e8-9543-483b1dee4275.jpg)

**Comment by Winning117** [comment]
Confirmed fixed in src-r4405/dev-r8773, needs to be closed.

**Comment by dysphie** [comment]
This still affects arrows
