### ISSUE TITLE
nms_camilla areaportals issue

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#899]
![20180324151254_1](https://user-images.githubusercontent.com/15934200/37869531-2998694a-2f76-11e8-8106-75c0b6704ea3.jpg)
When standing in Zone A in nms_camilla and looking out to the street you can't see anything. I think this was done to increase performance but I think it takes away immersion when you see these big black windows

**Comment by Bubka3** [comment]
Last commit log on this map shows
```unplayable version, mostly visual changes (for testing purpose)```

WIP content shouldn't really be shipped to dev build, especially without dropping a note somewhere.

**Comment by Winning117** [comment]
Just as a note this is on public branch as well, doesn't have to do with recent commit.

**Comment by AtheistNMRiH** [comment]
it is intentional, I understand that it doesn't look good but if there weren't any areaportals, it would be laggy as hell, I don't think that I can fix that since map has big open space geometry
