### ISSUE TITLE
Compass error on changing settings

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#900]
Version: 1.0.9.7 public and dev build

Steps to reproduce:
1) Open settings in game and change your resolution or turn vsync on
2) Apply settings
3) Look at compass, it'll be glitched

![20180324145703_1](https://user-images.githubusercontent.com/15934200/37870544-90353ef0-2f8d-11e8-97c6-f0b8d48e3226.jpg)

https://www.youtube.com/watch?v=WtMiLJ6xrYY

**Comment by Bubka3** [comment]
Bumped priority because it is my intention that changing the resolution no longer causes extra features in the game going forward.

**Comment by Fersigal** [comment]
#12 
Duplicate

**Comment by Winning117** [comment]
From @felis-catus: "it's a vgui issue"
