### ISSUE TITLE
nms_operation_halloween Map Bugs (Out of bounds/invincible spots/clipping errors)

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#901]
Most of these are trivial except the one at 0:38 allows the player to stand in the safe zone without taking damage and the one at 0:08 allows the player to bypass the welder gate (https://www.youtube.com/watch?v=J-6Bnm7JDoY)

**Comment by AtheistNMRiH** [comment]
unfortunately we don't have latest vmf, so we won't fix that, need to be closed

**Comment by Winning117** [comment]
:(
