### ISSUE TITLE
Moving while welding

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#902]
Version: dev build r-4348

Steps to reproduce:
1) Start welding something
2) Hold the walk-backwards key and spam jump

https://www.youtube.com/watch?v=b4XZruNwG9E

**Comment by Winning117** [comment]
That was patched, how is it related?

**Comment by Bubka3** [comment]
because you can still use the welder in a way is not intended?

**Comment by AtheistNMRiH** [comment]
yeah, these bugs seems different

**Comment by Bubka3** [comment]
Movement will be disable when using tools src-r4373

**Comment by Winning117** [comment]
Confirmed fixed in src-r4388/dev-r8769.
