### ISSUE TITLE
(dev) score board overlaps chat

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#905]
public:

![nmo_shit0001](https://user-images.githubusercontent.com/11333747/37873995-836354e0-3051-11e8-90f9-40b4bb512740.jpg)

dev:

![nms_arpley0003](https://user-images.githubusercontent.com/11333747/37874028-88dd070e-3051-11e8-9351-ee04bf24ae50.jpg)

**Comment by Bubka3** [comment]
Dev build behavior is consistent with #17 
Likely what @felis-catus said there applies here as well.

**Comment by felis-catus** [comment]
Correct, decided to keep it as is for now.

The scoreboard panel is now a VGUI "Frame", like the radial wheel. This allows mouse input but overlaps with elements on HUD surface.

**Comment by Holycrapjimhox** [comment]
Confirmed fix on dev-r8890.
