### ISSUE TITLE
(public) kills with "new" variants of weapons don't count in achievement

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#909]
killing with fa_sks:

![nms_favela0004](https://user-images.githubusercontent.com/11333747/37902334-56dce634-311e-11e8-8cc9-5a1ac3a9c433.jpg)

killing with fa_sks_nobayo

![nms_favela0005](https://user-images.githubusercontent.com/11333747/37902348-621c878e-311e-11e8-912d-263d11336361.jpg)

same with fa_sako85_ironsights, fa_1022_25mag and fa_m16a4_carryhandle

**Comment by felis-catus** [comment]
Fixed in src-r4935.
