### ISSUE TITLE
(Dev) lighter LMB issues

### ISSUE THREAD

**Issue by Fersigal** [nmrih/source-game#911]
Steps to reproduce: 
1 Equip Lighter
2 Keep spamming left mouse button
3 Have a weird interaction with the animations and they appear to happen to fast, every 0.4 seconds or so
4 You can dequip the lighter and quickly equip it again and it should always get lit if you keep doing the same stuff over and over.

i'd say this is not that important as of a fix, but still kinda gimmicky

**Comment by Winning117** [comment]
Is this what you're referring to? https://www.youtube.com/watch?v=DnB6OKTnSNY

Also the title says sprinting, what does this have to do with sprinting? Wasn't able to find any sprinting issues but could have missed them.

**Comment by Winning117** [comment]
Confirmed no bugs with Felis, needs to be closed.
