### ISSUE TITLE
(Public) Animations sometimes freeze when using

### ISSUE THREAD

**Issue by Fersigal** [nmrih/source-game#912]
note: also happens in dev build
1) Perform an animation while using a keypad, using a func_trigger_use entity
2) Get the animation stuck in a certain timeframe
3) tu tu tu tu tu, animation gets stuck in the specific time interval
4) Profit $$$
https://www.dropbox.com/s/yf6su8tu3oob0df/animationfersy101.dem?dl=0
playdemo animationfersy101 (3rd attempt though)

**Comment by felis-catus** [comment]
Fixed in src-r6383.
