### ISSUE TITLE
Items don't interpolate after leaving inventory

### ISSUE THREAD

**Issue by Ryan-nmrih** [nmrih/source-game#915]
Items and physics props normally interpolate very smoothly when the player carries them: https://i.imgur.com/WEStY7V.gifv

But items that have been in a player's inventory won't interpolate which causes this jitter: https://i.imgur.com/bf5lyVz.gifv

This is also apparent when throwing melee weapons. Occurs in both the public and dev builds.

**Comment by Winning117** [comment]
Note: god awful interpolation with 200ms+ ping (from Felis in-game)

**Comment by essbuh** [comment]
This should be fixed with code r4854 and included in 1.10.1

**Comment by Ryan-nmrih** [comment]
Nice job. Can confirm it's working in dev
