### ISSUE TITLE
(Public) Use interaction with suicide 

### ISSUE THREAD

**Issue by Fersigal** [nmrih/source-game#921]
Steps to reproduce:

1) Start up nmo_brooklyn (easiest to start with a keypad)
2) Hope you get the right objective chain (Key -> Keypad, not key -> computer)
3) Get the code from the computer
4) Get to the keypad
5) Press K with a loaded or empty gun
6) Don't shoot
7) Use "e" on the keypad
8) Run around forever

**Comment by Winning117** [comment]
Easy to replicate on nms_northway as well.

Suggested fix: cancel suicide when interacting with things, or disable interacting while in the "preparing suicide" state

**Comment by essbuh** [comment]
Fixed by src-r4883
