### ISSUE TITLE
(Dev Build) Molotovs disappear when thrown down

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#922]
I know that Felis introduced a patch to prevent fires from starting in the middle of the air but it appears that it also makes it so that the player can not throw molotovs at the ground. Found in src-r4388/dev-r8769. https://www.youtube.com/watch?v=rVYeRjT5jPY

**Comment by Bubka3** [comment]
@felis-catus regression from Molotov overhaul

**Comment by felis-catus** [comment]
Fixed in src-r4389.
