### ISSUE TITLE
Picking up glowing items creates a broken compass marker

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#925]
Tested in src-r4388/dev-r8769. This seems to be a code related issue that doesn't check to see if the item has been picked up and probably puts the marker at the default origin.

Steps to reproduce:
1) Go on a map that has a tool highlighted (ex: welder) as part of an objective
2) Look at compass and pick up the highlighted tool
3) Observe compass highlight moving to seemingly "random" location

Video of issue: https://www.youtube.com/watch?v=-oAgRw1WQ0o

**Comment by Fersigal** [comment]
No bug, see it like this if you have an item in ur inventory it's located in every wind direction, north, south, west and east. 
This can be visualized, by picking up a crowbar, the crowbar is in the exact same position, so it's located north, west, east and south

**Comment by AtheistNMRiH** [comment]
well iirc on public compas blip was always directed with your sight, and here it is not

**Comment by dysphie** [comment]
Fixed in 1.12
