### ISSUE TITLE
Picking up walkie talkie breaks character animations

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#926]
Version: src-r4388/dev-r8770. Tried in public and this is dev build only, meaning it's a regression from walkie-talkie boost change.

Notes: Code related issue, not having walkie-talkie in inventory shows models just fine. Disappears when the walkie-talkie is dropped.

Steps to reproduce:
1) Pick up walkie-talkie
2) Pick up any item that can go in your inventory
3) Animation will break (and it looks pretty funny)

Video: https://www.youtube.com/watch?v=hj8G8IdZ9hI

**Comment by DDysphie** [comment]
Note: Only affects client-side model rendering

**Comment by Winning117** [comment]
Confirmed fixed in src-r4405/dev-r8773.
