### ISSUE TITLE
Character can't switch to flashlight while having explosives equipped

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#928]
Tested in src-r4388/dev-r8770

Steps to reproduce:
1. `sv_cheats 1; give item_maglite; give exp_grenade; give exp_tnt; give exp_molotov`
2. Switch to one of the explosive items
3. Try to press the button to equip flashlight (default f) and you will see that you can't equip the flashlight
4. Drop the flashlight and try to equip your lighter and you will see it works just fine

**Comment by TheUnstableNutcase** [comment]
This issue is still present as of 1.11.2

**Comment by Winning117** [comment]
> This issue is still present as of 1.11.2

There haven't been any code updates for this so the error is still going to be present.

**Comment by felis-catus** [comment]
Fixed in src-r5043.
