### ISSUE TITLE
(dev) Hammering sound repeats if you immediately sprint after placing a board

### ISSUE THREAD

**Issue by Holycrapjimhox** [nmrih/source-game#929]
Tested in src-r4388/8770. Steps to reproduce:

1) Pick up a barricade hammer
2) Pick up ammo, you need not to trigger the automatic animation where the character moves the board downwards
3) Place a board and start holding your sprint button and any direction key besides S.
4) When you manage to place the board, flick your mouse to a direction where you can sprint to
5) The hammering sound will be played a second time.

**Comment by Winning117** [comment]
Apparently it plays the animation sometimes too LOL https://www.youtube.com/watch?v=PIY_fkU1u4k

**Comment by felis-catus** [comment]
Unable to repro after #1114 closure, assumed fixed.
