### ISSUE TITLE
[public/dev-r8771] Arrows won't pass through multiple entities

### ISSUE THREAD

**Issue by dysphie** [nmrih/source-game#932]
The cvar `sv_arrow_max_passthroughs` determines the number of entities a single arrow can pass through but it doesn't seem to do anything.

Repro steps:

- `sv_arrow_passthrough_chance 1; sv_arrow_max_passthroughs 5`
- Shoot an arrow through a line of zombies or any other group of entities

Arrow will never pass through.

**Comment by essbuh** [comment]
This appears to be intentional; arrows only pass through when hitting the head and stick to bodies.
