### ISSUE TITLE
nmo_cabin Softlocks

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#936]
Wall of images instead of video as requested by Atheist:

![224260_20180403014825_1](https://user-images.githubusercontent.com/15934200/38244205-c55c99d0-36ee-11e8-80ca-3bbc28cb717c.png)

![224260_20180403015322_1](https://user-images.githubusercontent.com/15934200/38244209-c9b9a950-36ee-11e8-912c-67e650e7e56a.png)

![224260_20180403020757_1](https://user-images.githubusercontent.com/15934200/38244216-cea2bec0-36ee-11e8-8d1e-54dbc33d737e.png)

![224260_20180403021158_1](https://user-images.githubusercontent.com/15934200/38244227-dbba212a-36ee-11e8-9db2-6082895140cd.png)

![224260_20180403021838_1](https://user-images.githubusercontent.com/15934200/38244229-dfdc4e5e-36ee-11e8-8222-27d3fea7dcec.png)

![224260_20180403022050_1](https://user-images.githubusercontent.com/15934200/38244231-e1c494c4-36ee-11e8-9b58-22ad90f1d9ea.png)

![224260_20180403022759_1](https://user-images.githubusercontent.com/15934200/38244234-e43e06f4-36ee-11e8-8ff6-b1f50a8ecbf8.png)

![224260_20180403022921_1](https://user-images.githubusercontent.com/15934200/38244240-e5bda192-36ee-11e8-8f14-b7cb7939c18b.png)

![224260_20180403023903_1](https://user-images.githubusercontent.com/15934200/38244242-e7504442-36ee-11e8-9d0a-06409b616ba7.png)

**Comment by AtheistNMRiH** [comment]
fixed in r8775

**Comment by Winning117** [comment]
Confirmed fixed in src-r4405/dev-r8775.
