### ISSUE TITLE
(dev) welder using bugs

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#937]
1) you can't properly use welder when you **look up**

example map: nmo_zephyr

![nmo_zephyr0002](https://user-images.githubusercontent.com/11333747/38252141-a12d20d6-377d-11e8-8eb8-279562ae30f3.jpg)

here **I look up** (ignore ladder brush, it doesn't cause problem)

![nmo_shit0000](https://user-images.githubusercontent.com/11333747/38252642-ec03b466-377e-11e8-8284-3b38e9deba47.jpg)

and here **I look on it on some angle**

![nmo_shit0001](https://user-images.githubusercontent.com/11333747/38252267-e4eb8592-377d-11e8-848d-ac7b9c9a8326.jpg)

2) if trigger_progress_weapon is located on ground, you can't use it if your sight is directed right under you

example map: nmo_toxteth manhole objective (probably on nmo_subside too (custom map)

if you sit like this, you can use trigger

![nmo_shit0002](https://user-images.githubusercontent.com/11333747/38252361-1c1e376c-377e-11e8-839f-5e6c4e7efbe1.jpg)

![nmo_shit0003](https://user-images.githubusercontent.com/11333747/38252370-1f7a107a-377e-11e8-919e-c8319814587d.jpg)

but you can't use it if you sit like this

![nmo_shit0004](https://user-images.githubusercontent.com/11333747/38252394-34d1f8e8-377e-11e8-99b2-1a189e417823.jpg)

**Comment by Bubka3** [comment]
I'm trying to think of what change could of caused this regression. @felis-catus thoughts?

**Comment by AtheistNMRiH** [comment]
my apologize, second bug exist on public too, so only first one is regression

**Comment by AtheistNMRiH** [comment]
check first comment, ladder brush doesn't cause bug, only when you look up on trigger

**Comment by felis-catus** [comment]
Resolved in src-r4606.
