### ISSUE TITLE
Incorrect hitting subtitles leftover from half-life 2

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#938]
When the player hits with their fists the subtitles say [Crowbar Swoosh]. And don't tell me "fists of steel"

![224260_20180404023628_1](https://user-images.githubusercontent.com/15934200/38300214-132d0ef2-37b1-11e8-8ba9-a2e107bafbaf.png)

To see subtitles:
1.  Press `Esc` and click "Options"
2. Go to the "Audio" tab
3. Change "Captions" from "No captions" to "Closed Captions"

**Comment by felis-catus** [comment]
Fixed in dev-r9941.
