### ISSUE TITLE
Gene therapy blindness persists through death

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#941]
Version: src-r4405/dev-r8773

Steps to reproduce:
1) Get gene therapy
2) Use gene therapy and get blindness from it
3) Die while having blindness
4) Your spectate mode will have blindness and even when you respawn you will still be blind

Video: https://www.youtube.com/watch?v=f1lPagpSLs4

**Comment by DDysphie** [comment]
Permanent or just for the ~30 seconds it takes for it to wear off? Still a bug regardless

**Comment by Winning117** [comment]
I thought it was permanent but cranked up time scale and saw that it's only for the 30s. Good catch

**Comment by felis-catus** [comment]
Resolved in src-r4692.
