### ISSUE TITLE
[dev-r8773] New demo overlay not tied to cl_showdemooverlay

### ISSUE THREAD

**Issue by DDysphie** [nmrih/source-game#942]
New demo overlay cannot be hidden with `cl_showdemooverlay`

![i4yl5j](https://user-images.githubusercontent.com/11559683/38434209-ebded318-39a3-11e8-82a7-a47fdf4cde65.png)

This is bad for people who use `startmovie` to render demos, since it shows up in the final product.

Also, the game already provided visual feedback for demos in a less flashy way (top right corner):

![20180406142139_1](https://user-images.githubusercontent.com/11559683/38434763-e510b482-39a5-11e8-97fb-220e0a17eec0.jpg)

![20180406141520_1](https://user-images.githubusercontent.com/11559683/38434508-018d3758-39a5-11e8-94bd-3a90c16013f8.jpg)

Wouldn't it be possible to simply add the timer up there?

**Comment by felis-catus** [comment]
New timer can be disabled with cvar "hud_showdemotimer". "cl_showdemooverlay" is locked behind engine so we can't do much about it. Closing.
