### ISSUE TITLE
Incorrect backpedal speed

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#944]
While testing I noticed that the backpedal speed for crouching isn't proportional:
Forward walk velocity: 116
Backpedal walk velocity: 58
Forward crouch velocity: 49.3
**Backward crouch velocity: 58**

This ties into the [ironsighting bug](https://github.com/nmrih/source-game/issues/744) in that crouching speeds are messed up. Doesn't make much sense to me that backpedaling while crouched is faster than walking forward while crouched, and especially while having ironsights.

My proposal to fix backpedal speeds:
Forward walk velocity: 116
Backpedal walk velocity: 58
**Forward crouch velocity: 50** (make it an even number like the rest and easier to split)
**Backward crouch velocity: 25** (half of the forward crouch, just like how backpedal walk is half the speed of forward walk)

**Comment by Fersigal** [comment]
#685 related

**Comment by AtheistNMRiH** [comment]
I think issue should be tracked here, since it has numbers

**Comment by Holycrapjimhox** [comment]
Please check Discord, this issue should not be fixed in my opinion. The reasoning is written on #tester.

**Comment by Fersigal** [comment]
My proposal is to keep the backcrouching speed the same and make the forward crouching speed slightly faster

**Comment by Holycrapjimhox** [comment]
It should just be left unchanged. If you have the same movement speed while crouching regardless of direction, then then dominating the crouched melee attacks becomes too easy.

**Comment by DDysphie** [comment]
As pointed out above, current backpedal speed allows for some cool melee mechanics. I'd not change it.

**Comment by Winning117** [comment]
Closing cause the mechanics are cool the way they are
