### ISSUE TITLE
nmo_broadway softlocks/errors

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#945]
![224260_20180406221025_1](https://user-images.githubusercontent.com/15934200/38463582-4f08874e-3ab3-11e8-857c-d2f761cf2a50.png)
![224260_20180406221139_1](https://user-images.githubusercontent.com/15934200/38463583-4f215bac-3ab3-11e8-89e3-21c32a8f777c.png)
![224260_20180406221502_1](https://user-images.githubusercontent.com/15934200/38463584-4f39e1e0-3ab3-11e8-88ac-5cf23ff44d5d.png)
![224260_20180406221844_1](https://user-images.githubusercontent.com/15934200/38463585-4f531732-3ab3-11e8-954f-1d6eb763d1be.png)
![224260_20180406222839_1](https://user-images.githubusercontent.com/15934200/38463586-4f6d5c5a-3ab3-11e8-8f38-2193c19bc04c.png)
![224260_20180406222909_1](https://user-images.githubusercontent.com/15934200/38463587-4f8a4f54-3ab3-11e8-8c59-d274f58e0fb5.png)
![224260_20180406223151_1](https://user-images.githubusercontent.com/15934200/38463588-4fabf8a2-3ab3-11e8-839a-1cbd994e656e.png)
![224260_20180406223427_1](https://user-images.githubusercontent.com/15934200/38463589-4fd43326-3ab3-11e8-8dcd-1429ec0702da.png)
![224260_20180406223522_1](https://user-images.githubusercontent.com/15934200/38463590-5003edf0-3ab3-11e8-8afb-b70a74709897.png)
![224260_20180406223712_1](https://user-images.githubusercontent.com/15934200/38463591-503044d6-3ab3-11e8-8b4e-e7bb9e1ab95c.png)
![224260_20180406223847_1](https://user-images.githubusercontent.com/15934200/38463592-504d23bc-3ab3-11e8-9795-1727b04bda42.png)
![224260_20180406224013_1](https://user-images.githubusercontent.com/15934200/38463593-506f12c4-3ab3-11e8-9a1c-185c5c880a81.png)
![224260_20180406224143_1](https://user-images.githubusercontent.com/15934200/38463594-508fabba-3ab3-11e8-896c-30bd03c168c4.png)
![224260_20180406224304_1](https://user-images.githubusercontent.com/15934200/38463595-50ae4200-3ab3-11e8-9c97-6c03a253da39.png)
![224260_20180406224419_1](https://user-images.githubusercontent.com/15934200/38463596-50ce1ddc-3ab3-11e8-830a-81acbbd54dbc.png)
![224260_20180406224608_1](https://user-images.githubusercontent.com/15934200/38463597-50ed711e-3ab3-11e8-9996-c3a9176a61e0.png)
![224260_20180406224730_1](https://user-images.githubusercontent.com/15934200/38463605-72047776-3ab3-11e8-90d7-83608fbcfa7e.png)
![224260_20180406224826_1](https://user-images.githubusercontent.com/15934200/38463606-7226a684-3ab3-11e8-88db-3cab6f726fc5.png)
![224260_20180406225157_1](https://user-images.githubusercontent.com/15934200/38463607-724af03e-3ab3-11e8-821b-e7208242476f.png)
![224260_20180406225434_1](https://user-images.githubusercontent.com/15934200/38463608-7276ae7c-3ab3-11e8-86e7-4d85ac48020e.png)
![224260_20180406225458_1](https://user-images.githubusercontent.com/15934200/38463609-729660dc-3ab3-11e8-8879-366e94a487f6.png)
![224260_20180406225523_1](https://user-images.githubusercontent.com/15934200/38463610-72b65dba-3ab3-11e8-8bce-e6a473439a1b.png)
![224260_20180406225619_1](https://user-images.githubusercontent.com/15934200/38463611-72d7d454-3ab3-11e8-825b-643c7d4f00af.png)
![224260_20180406230135_1](https://user-images.githubusercontent.com/15934200/38463612-72f35fee-3ab3-11e8-933a-7fd6b5163fc3.png)
![224260_20180407215959_1](https://user-images.githubusercontent.com/15934200/38463613-732c626c-3ab3-11e8-9284-b04b794831f2.png)
![224260_20180407220316_1](https://user-images.githubusercontent.com/15934200/38463614-7349d84c-3ab3-11e8-9f5b-78b2158430af.png)
![224260_20180407220639_1](https://user-images.githubusercontent.com/15934200/38463615-736a5982-3ab3-11e8-8799-673f900d5d7d.png)
![224260_20180407221233_1](https://user-images.githubusercontent.com/15934200/38463616-7388534c-3ab3-11e8-99a3-c318e7e8be1f.png)
![224260_20180407221617_1](https://user-images.githubusercontent.com/15934200/38463617-73a954de-3ab3-11e8-8da1-9e3c72aa1878.png)
![224260_20180407221657_1](https://user-images.githubusercontent.com/15934200/38463618-73c83750-3ab3-11e8-94a2-95e75e2ad162.png)
![224260_20180407221742_1](https://user-images.githubusercontent.com/15934200/38463619-73e577b6-3ab3-11e8-993c-192728664a72.png)
![224260_20180407221903_1](https://user-images.githubusercontent.com/15934200/38463620-740848ea-3ab3-11e8-9389-e5e1e6f8ebef.png)
![224260_20180407222048_1](https://user-images.githubusercontent.com/15934200/38463621-742b11b8-3ab3-11e8-8bb4-71f4df3815d3.png)
![224260_20180407222141_1](https://user-images.githubusercontent.com/15934200/38463622-744cf7ba-3ab3-11e8-91d2-049cd5cdacc2.png)

And these need fixed highlights:
![224260_20180407222341_1](https://user-images.githubusercontent.com/15934200/38463655-69662a6e-3ab4-11e8-9867-a67ebcc1c5db.png)
![224260_20180406224700_1](https://user-images.githubusercontent.com/15934200/38463659-75307250-3ab4-11e8-8726-6c78c516d525.png)

**Comment by Winning117** [comment]
Confirmed fixed in atheist's new version.

**Comment by Winning117** [comment]
Tested some oob in src-r4469/dev-r8821 and found these:
![224260_20180522152629_1](https://user-images.githubusercontent.com/15934200/40393899-1bfc5470-5dd6-11e8-85dd-262b907a80c0.png)
![224260_20180522152850_1](https://user-images.githubusercontent.com/15934200/40393900-1c1afb0a-5dd6-11e8-81f3-2f68a34fe7ed.png)
![224260_20180522152922_1](https://user-images.githubusercontent.com/15934200/40393901-1c3a1396-5dd6-11e8-9e88-566e12ff39a5.png)
![224260_20180522153034_1](https://user-images.githubusercontent.com/15934200/40393903-1c5bf56a-5dd6-11e8-9edd-3535d1d1fc79.png)
![224260_20180522153132_1](https://user-images.githubusercontent.com/15934200/40393904-1c7ad5b6-5dd6-11e8-9fe0-f06ce3435476.png)

**Comment by AtheistNMRiH** [comment]
fixed in r8823

**Comment by Winning117** [comment]
Confirmed fixed in src-r4469/dev-r8823.
