### ISSUE TITLE
[dev-r8775] demoui2 crash

### ISSUE THREAD

**Issue by DDysphie** [nmrih/source-game#946]
Client crashes to desktop for me after setting demoui2 to fast forward to a specific time in the progress bar. Below 2 minidumps

[demoui2_minidumps.zip](https://github.com/nmrih/source-game/files/1887289/demoui2_minidumps.zip)

**Comment by felis-catus** [comment]
Unfortunately these dumps point to closed source engine modules that we can't debug. Closing.
