### ISSUE TITLE
[public] Protruding neck hitbox and walk sequences

### ISSUE THREAD

**Issue by Dysphie** [nmrih/source-game#947]
The neck hitbox on zombies is abnormally large and blocks headshots.
Severity varies with walk sequences and it's most noticeable in realism mode.
 
`walk1` to `walk7` are ok in most scenarios:
https://imgur.com/a/56y6O

`walk8` and `walk9` cause trouble:
 https://imgur.com/a/6Taur

`walk10` makes it impossible to headshot zombies from the back:

![walk10](https://user-images.githubusercontent.com/11559683/38496738-f52cc2da-3bd4-11e8-94ae-2aeb89812ec6.gif)

Video (realism enabled): https://www.youtube.com/watch?v=_xKE54oWEtc

Another album by Ryan: https://imgur.com/a/Tfa3R

**Suggestion:** Since resizing the hitbox likely requires recompiling all models I'd suggest simply preventing zombies from using `walk8`, `walk9` and `walk10`, or at the very least just `walk10`.

**Comment by Bubka3** [comment]
We probably have the source of the models so it can be fixed. Disabling the sequences is just a band aid.

**Comment by DDysphie** [comment]
I tried simply resizing the hitbox and it didn't translate properly across all sequences. This is because the current neck hitbox is linked to ValveBiped.Bip01_Head's bone which is too far away from the neck.

Removing Hitbox 0 from ValveBiped.Bip01_Head and adding a new hitbox to ValveBiped.Bip01_Neck01 with an origin of 0.000; 1.000; 0.000 and a size of 4.000; 4.000; 4.000 (XYZ) fixes this problem

Here's a comparison:
![photoshop_2018-06-08_17-39-38](https://user-images.githubusercontent.com/11559683/41179947-f1149dba-6b42-11e8-95cf-a9984ae2b16a.png)

**Comment by Dysphie** [comment]
In case this ever gets done, I have gone ahead and tweaked every zombie hitbox individually.
This involved doing what I mentioned before, removing `Hitbox 0` from `ValveBiped.Bip01_Head` and adding a new hitbox to `ValveBiped.Bip01_Neck01`. Origins vary per model.

Here are the updated hitbox sets to be used in the QC files:
[molotov_infected.txt](https://github.com/nmrih/source-game/files/2407457/molotov_infected.txt)
[national_guard.txt](https://github.com/nmrih/source-game/files/2407458/national_guard.txt)
[officezom.txt](https://github.com/nmrih/source-game/files/2407459/officezom.txt)
[roje_infected.txt](https://github.com/nmrih/source-game/files/2407460/roje_infected.txt)
[runner.txt](https://github.com/nmrih/source-game/files/2407461/runner.txt)
[tammy.txt](https://github.com/nmrih/source-game/files/2407462/tammy.txt)
[toby.txt](https://github.com/nmrih/source-game/files/2407463/toby.txt)
[wally_infected.txt](https://github.com/nmrih/source-game/files/2407464/wally_infected.txt)
[zombiekid_boy.txt](https://github.com/nmrih/source-game/files/2407465/zombiekid_boy.txt)
[zombiekid_girl.txt](https://github.com/nmrih/source-game/files/2407466/zombiekid_girl.txt)
[badass_infected.txt](https://github.com/nmrih/source-game/files/2407467/badass_infected.txt)
[bateman_infected.txt](https://github.com/nmrih/source-game/files/2407468/bateman_infected.txt)
[berny.txt](https://github.com/nmrih/source-game/files/2407469/berny.txt)
[butcher_infected.txt](https://github.com/nmrih/source-game/files/2407470/butcher_infected.txt)
[casual_02.txt](https://github.com/nmrih/source-game/files/2407471/casual_02.txt)
[herby.txt](https://github.com/nmrih/source-game/files/2407472/herby.txt)
[hunter_infected.txt](https://github.com/nmrih/source-game/files/2407473/hunter_infected.txt)
[jive_infected.txt](https://github.com/nmrih/source-game/files/2407474/jive_infected.txt)
[jogger.txt](https://github.com/nmrih/source-game/files/2407475/jogger.txt)
[julie.txt](https://github.com/nmrih/source-game/files/2407476/julie.txt)
[lisa.txt](https://github.com/nmrih/source-game/files/2407477/lisa.txt)
[maxx.txt](https://github.com/nmrih/source-game/files/2407478/maxx.txt)

All required files but the QC can be extracted from existing models without problems.

**Comment by Dysphie** [comment]
Fixed in src-r4686
