### ISSUE TITLE
Walking away from zombies biting you

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#948]
Version: public and src-r4405/dev-r8785

I have noticed some weird behavior with zombies which allowed me to walk away from crawlers while they were biting me without me shoving them (https://www.youtube.com/watch?v=Mz0svwKV9mg). I have also been able to walk away from a shambler that was biting me, but further testing needs to be done to find out what triggers it (https://www.youtube.com/watch?v=tpsziOJs8o8).

**Note:** "I think the issue is related to zombies calling CNMRiH_Player::OnGrabbedEnd even when they don't have the player grabbed. I assume this function is what restores the player's ability to move. After a zombie has grabbed a player, they never forget who they last had grabbed. This means that whenever they are shoved or attempt to grab another player, they call the OnGrabbedEnd function for the original player." -Ryan

**Comment by felis-catus** [comment]
Zombies shouldn't start biting you if you were already being grabbed, fixed this behavior in src-r4421.

**Comment by Winning117** [comment]
Not fixed in src-r4435/dev-r8793.

**Comment by Winning117** [comment]
Multiple zombies can still grab you https://www.youtube.com/watch?v=ymXkTnHD3rM

**Comment by Winning117** [comment]
[Relevant video](https://www.youtube.com/watch?v=7BoKFtKeuDw)

**Comment by Winning117** [comment]
This seems to be a side effect of multiple zombies grabbing you at once which is mentioned in #1112.

**Comment by essbuh** [comment]
This should be fixed by src-r4882

**Comment by Holycrapjimhox** [comment]
Could not reproduce this in r8975. May need more testing though since this issue wasn't very common during normal gameplay.
