### ISSUE TITLE
Main menu appears during loading

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#949]
Version: src-r4405/dev-r8785

Upon starting a server or changing levels on a server the player is put on the main menu for a few seconds while the map is loading. This is different functionality from the public branch which shows a progress bar in the bottom right when the level is changing (though it still goes to the main menu screen). I think that this can be confusing for new players because it seems as though the game has frozen (since you can't click anything) or the player has been kicked from the game. I have a higher-end computer so this process is faster, but I can imagine it takes even longer for lower-end computers.

Video: https://www.youtube.com/watch?v=MfjC9PWmh9A

**Comment by Holycrapjimhox** [comment]
This is also present on the public build of the game, it's not a regression.

**Comment by Bubka3** [comment]
I don't know if I could call this 100% a regression, as the main menu does appear briefly when the client is entering the game regardless of the loading dialog used. The main menu briefly appearing like that happens in all sdk2013 games last I checked.

**Comment by felis-catus** [comment]
Yeah, this isn't a regression. The existing issue is more apparent now that the GameUI loading panel has been replaced.

**Comment by Winning117** [comment]
Ah okay. Is there any way to make it not show the main menu or is that tied to the engine?

**Comment by felis-catus** [comment]
Fixed and confirmed in src-r4418.
