### ISSUE TITLE
nmo_fema errors

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#953]
Version: src-r4405/dev-r8787

Wall of pics as requested by Atheist. I'm sure there are more than this but the map is so huge that I'll go through it again after these issues are fixed.

Note: I'm aware that it looks like the jukebox pics aren't softlocks but the jukebox collision is really weird so the player can't grab it in the areas provided below.

![224260_20180414231044_1](https://user-images.githubusercontent.com/15934200/38776315-e27be638-4049-11e8-98f4-7751568a9004.png)
![224260_20180414231147_1](https://user-images.githubusercontent.com/15934200/38776316-e293102e-4049-11e8-8860-57686db18432.png)
![224260_20180414231226_1](https://user-images.githubusercontent.com/15934200/38776317-e2aa022a-4049-11e8-91f0-03b572b782b2.png)
![224260_20180414231328_1](https://user-images.githubusercontent.com/15934200/38776318-e2bfc86c-4049-11e8-87b5-d060098b2738.png)
![224260_20180414231651_1](https://user-images.githubusercontent.com/15934200/38776319-e2d36e80-4049-11e8-872b-a788461ed135.png)
![224260_20180414231731_1](https://user-images.githubusercontent.com/15934200/38776320-e2eb9eba-4049-11e8-8166-789da3d34e8d.png)
![224260_20180414231759_1](https://user-images.githubusercontent.com/15934200/38776321-e300daa0-4049-11e8-9f17-8d6fe85966fa.png)
![224260_20180414231828_1](https://user-images.githubusercontent.com/15934200/38776322-e32065aa-4049-11e8-934a-fb0967fbc729.png)
![224260_20180414232005_1](https://user-images.githubusercontent.com/15934200/38776323-e3439fc0-4049-11e8-8a9b-61753930a32f.png)
![224260_20180414232135_1](https://user-images.githubusercontent.com/15934200/38776324-e366ed0e-4049-11e8-83a1-6ae7811acffc.png)
![224260_20180414232353_1](https://user-images.githubusercontent.com/15934200/38776325-e38a416e-4049-11e8-8bab-7d5e2d2b561f.png)
![224260_20180414232527_1](https://user-images.githubusercontent.com/15934200/38776326-e3a1e940-4049-11e8-8e02-ebdb7a828b3d.png)
![224260_20180414232655_1](https://user-images.githubusercontent.com/15934200/38776327-e3bcf7f8-4049-11e8-8e00-72d6a8f357fc.png)
![224260_20180414233614_1](https://user-images.githubusercontent.com/15934200/38776328-e3d4d6ac-4049-11e8-923c-6b46cf59dcad.png)
![224260_20180414233712_1](https://user-images.githubusercontent.com/15934200/38776329-e3f007f6-4049-11e8-9421-243d53359249.png)
![224260_20180414233750_1](https://user-images.githubusercontent.com/15934200/38776330-e408a2b6-4049-11e8-8dc9-b59bb92ba22d.png)
![224260_20180414233911_1](https://user-images.githubusercontent.com/15934200/38776331-e43041d6-4049-11e8-8bbf-192edd529ea8.png)
![224260_20180414233946_1](https://user-images.githubusercontent.com/15934200/38776332-e447b820-4049-11e8-8343-acc84c501b44.png)
![224260_20180414234035_1](https://user-images.githubusercontent.com/15934200/38776333-e4627200-4049-11e8-8992-4736094ee6c5.png)
![224260_20180414234932_1](https://user-images.githubusercontent.com/15934200/38776334-e47c72cc-4049-11e8-969c-60a2b416dce6.png)
![224260_20180414235245_1](https://user-images.githubusercontent.com/15934200/38776335-e4995cc0-4049-11e8-82ec-a03f20a37fc7.png)
![224260_20180414235350_1](https://user-images.githubusercontent.com/15934200/38776336-e4b29e6a-4049-11e8-992d-5bcb02698946.png)
![224260_20180414235756_1](https://user-images.githubusercontent.com/15934200/38776337-e4d0287c-4049-11e8-8166-f4c400b9e27a.png)
![224260_20180414235953_1](https://user-images.githubusercontent.com/15934200/38776338-e4ecddc8-4049-11e8-801f-2fe3bd0b4d86.png)
![224260_20180415000040_1](https://user-images.githubusercontent.com/15934200/38776339-e51f9fd8-4049-11e8-9f9b-2553e89704fd.png)
![224260_20180415000221_1](https://user-images.githubusercontent.com/15934200/38776340-e53a600c-4049-11e8-85ed-0733b5cfa6c5.png)
![224260_20180415000302_1](https://user-images.githubusercontent.com/15934200/38776341-e554247e-4049-11e8-8bb6-57d73fcc573b.png)
![224260_20180415000509_1](https://user-images.githubusercontent.com/15934200/38776342-e56ebf96-4049-11e8-8f91-7104b243d95a.png)
![224260_20180415000618_1](https://user-images.githubusercontent.com/15934200/38776343-e58d3160-4049-11e8-938b-35c338c370f1.png)
![224260_20180415000728_1](https://user-images.githubusercontent.com/15934200/38776344-e5af380a-4049-11e8-9374-c117f03400bf.png)
![224260_20180415001035_1](https://user-images.githubusercontent.com/15934200/38776345-e5cb081e-4049-11e8-87fa-efd60769620d.png)
![224260_20180415001258_1](https://user-images.githubusercontent.com/15934200/38776346-e5ebb9a6-4049-11e8-9e6e-a064ddae5c84.png)
![224260_20180415001727_1](https://user-images.githubusercontent.com/15934200/38776347-e60505fa-4049-11e8-87f7-1bc9410295b6.png)
![224260_20180415002109_1](https://user-images.githubusercontent.com/15934200/38776348-e6202d76-4049-11e8-9bb5-6d54368b8237.png)
![224260_20180415003308_1](https://user-images.githubusercontent.com/15934200/38776392-86d63dfa-404a-11e8-8122-8708f6f60346.png)
![224260_20180415003008_1](https://user-images.githubusercontent.com/15934200/38776395-898ed3c2-404a-11e8-818f-4668adb7cd05.png)
![224260_20180415003159_1](https://user-images.githubusercontent.com/15934200/38776396-89a8f7de-404a-11e8-97d5-a0814564a840.png)
![224260_20180415003233_1](https://user-images.githubusercontent.com/15934200/38776397-89c8f200-404a-11e8-8b69-f74e2af267b2.png)
![224260_20180415003344_1](https://user-images.githubusercontent.com/15934200/38776399-8c3cc4a8-404a-11e8-8b46-592167c71148.png)
![224260_20180415004100_1](https://user-images.githubusercontent.com/15934200/38776400-8c590c4e-404a-11e8-8b06-f8b650c66afc.png)
![224260_20180415004203_1](https://user-images.githubusercontent.com/15934200/38776401-8c732d0e-404a-11e8-910c-40d650551bcd.png)
![224260_20180415004414_1](https://user-images.githubusercontent.com/15934200/38776402-8c911cc4-404a-11e8-9aad-25d79251a003.png)
![224260_20180415004849_1](https://user-images.githubusercontent.com/15934200/38776403-8cae983a-404a-11e8-909b-834db1b414f8.png)
![224260_20180415005118_1](https://user-images.githubusercontent.com/15934200/38776404-8cc7b86a-404a-11e8-944d-2f9d9fe86d33.png)
![224260_20180415005253_1](https://user-images.githubusercontent.com/15934200/38776405-8ce2eaf4-404a-11e8-97d8-b7473c3b4415.png)
![224260_20180415005459_1](https://user-images.githubusercontent.com/15934200/38776406-8cf72afa-404a-11e8-82ac-91496721432d.png)

**Update 2 (4/15/18):**
![224260_20180416021853_1](https://user-images.githubusercontent.com/15934200/38853623-c0383c68-41d2-11e8-83a9-6a3a90766f43.png)
![224260_20180416021951_1](https://user-images.githubusercontent.com/15934200/38853624-c058b0c4-41d2-11e8-9140-8500a16051a9.png)
![224260_20180416022140_1](https://user-images.githubusercontent.com/15934200/38853625-c077b3c0-41d2-11e8-9a7a-e0b749fe2327.png)
![224260_20180416022218_1](https://user-images.githubusercontent.com/15934200/38853626-c0934cc0-41d2-11e8-94f6-16088f360cbd.png)
![224260_20180416022229_1](https://user-images.githubusercontent.com/15934200/38853627-c0b2cbcc-41d2-11e8-8a60-8dd5dd5bddd7.png)
![224260_20180416022743_1](https://user-images.githubusercontent.com/15934200/38853628-c0ccae48-41d2-11e8-9426-c4e336237e83.png)
![224260_20180416022931_1](https://user-images.githubusercontent.com/15934200/38853629-c0e94c24-41d2-11e8-9254-43479aadab84.png)
![224260_20180416023040_1](https://user-images.githubusercontent.com/15934200/38853630-c105b2ce-41d2-11e8-8f8f-d688552f16a8.png)
![224260_20180416023350_1](https://user-images.githubusercontent.com/15934200/38853631-c121223e-41d2-11e8-843a-c81d9c54c566.png)
![224260_20180416023507_1](https://user-images.githubusercontent.com/15934200/38853632-c14bfbee-41d2-11e8-8a25-8317b21b12e3.png)
![224260_20180416024030_1 submitted](https://user-images.githubusercontent.com/15934200/38853633-c17521f4-41d2-11e8-96d4-2e10a31e53a4.png)

**Update 3 (4/16/18):**
![224260_20180416230144_1](https://user-images.githubusercontent.com/15934200/38853656-d4ab0090-41d2-11e8-9321-62476e29c87f.png)
![224260_20180416230234_1](https://user-images.githubusercontent.com/15934200/38853657-d4d38682-41d2-11e8-8802-5074f8d01f41.png)
![224260_20180416230555_1](https://user-images.githubusercontent.com/15934200/38853658-d5115264-41d2-11e8-83cf-3e6da6bdf5ae.png)
![224260_20180416231159_1](https://user-images.githubusercontent.com/15934200/38853659-d53cafe0-41d2-11e8-8a54-2e24f7131f57.png)
![224260_20180416231231_1](https://user-images.githubusercontent.com/15934200/38853660-d5654c3e-41d2-11e8-8c8a-a34fd4ce56f5.png)
![224260_20180416231903_1](https://user-images.githubusercontent.com/15934200/38853661-d5911918-41d2-11e8-9741-a4131578211d.png)
![224260_20180416232052_1](https://user-images.githubusercontent.com/15934200/38853662-d5bf3834-41d2-11e8-8e9a-58480b42408c.png)
![224260_20180416232156_1](https://user-images.githubusercontent.com/15934200/38853663-d5ec13b8-41d2-11e8-8061-54a0bbd736bd.png)
![224260_20180416232319_1](https://user-images.githubusercontent.com/15934200/38853664-d616766c-41d2-11e8-870f-28053357aebc.png)
![224260_20180416234027_1](https://user-images.githubusercontent.com/15934200/38853665-d63f8f3e-41d2-11e8-9fad-7294cb612b3e.png)
![224260_20180416234051_1](https://user-images.githubusercontent.com/15934200/38853667-d67a52f4-41d2-11e8-9197-cbe1d7efbe62.png)
![224260_20180416234147_1](https://user-images.githubusercontent.com/15934200/38853668-d6a15020-41d2-11e8-8ea4-ef7004308e78.png)
![224260_20180416234544_1](https://user-images.githubusercontent.com/15934200/38853669-d6cd568e-41d2-11e8-88b7-ad124f056c6a.png)
![224260_20180416235119_1](https://user-images.githubusercontent.com/15934200/38853670-d6f65a2a-41d2-11e8-9764-32eaf4b5192e.png)

**Comment by AtheistNMRiH** [comment]
fixed in r8788

**Comment by Winning117** [comment]
Confirmed fixed in src-r4405/dev-r8788.

**Comment by Winning117** [comment]
Found some out of bounds issues in src-r4405/dev-r8788.

![224260_20180419195749_1](https://user-images.githubusercontent.com/15934200/39029284-e046b950-440f-11e8-9fbb-69e05ee6f53a.png)
![224260_20180419195808_1](https://user-images.githubusercontent.com/15934200/39029285-e08da8f6-440f-11e8-9ed0-9d34f6f92d2c.png)
![224260_20180419195846_1](https://user-images.githubusercontent.com/15934200/39029286-e0d36f8a-440f-11e8-82dc-0ffef7434dba.png)
![224260_20180419200205_1](https://user-images.githubusercontent.com/15934200/39029287-e119ef14-440f-11e8-9b0d-8cfb7139a386.png)
![224260_20180419200403_1](https://user-images.githubusercontent.com/15934200/39029264-d12b1510-440f-11e8-896c-7865d76247f1.png)
![224260_20180419200518_1](https://user-images.githubusercontent.com/15934200/39029265-d148fdbe-440f-11e8-8fdc-d5f6472292b3.png)
![224260_20180419200536_1](https://user-images.githubusercontent.com/15934200/39029266-d16df0ce-440f-11e8-8b37-6498248b63a0.png)
![224260_20180419200902_1](https://user-images.githubusercontent.com/15934200/39029267-d19628be-440f-11e8-8811-b5e82500299e.png)
![224260_20180419200905_1](https://user-images.githubusercontent.com/15934200/39029269-d1bdaf24-440f-11e8-8348-0229571904cf.png)
![224260_20180419200958_1](https://user-images.githubusercontent.com/15934200/39029270-d1e7b210-440f-11e8-8c8a-d49bd819e03a.png)
![224260_20180419201101_1](https://user-images.githubusercontent.com/15934200/39029271-d20f2dc2-440f-11e8-97e8-94685da85d9d.png)
![224260_20180419201814_1](https://user-images.githubusercontent.com/15934200/39029272-d23804c2-440f-11e8-9d84-9d42b9a142aa.png)

**Comment by Winning117** [comment]
Confirmed fixed in src-r4405/dev-r8789.
