### ISSUE TITLE
[public] Getting stuck inside raising bodies

### ISSUE THREAD

**Issue by DDysphie** [nmrih/source-game#954]
npc_nmrih_turnedzombie will block players phasing through when spawned:

![turned](https://user-images.githubusercontent.com/11559683/38863993-b0229d90-420f-11e8-98b2-fe135f6330a4.gif)

**Comment by Fersigal** [comment]
#166

**Comment by felis-catus** [comment]
Fixed and confirmed in src-r4429.

**Comment by dysphie** [comment]
As of src-r4784 you can get stuck if geometry prevents the zombie from being pushed forward:

https://streamable.com/8sjpk

But I would argue this is an okay compromise and unlikely to happen in actual gameplay.
