### ISSUE TITLE
nms_ransack Map Issues

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#958]
Found in src-r4405/dev-r8789.
![224260_20180422011921_1](https://user-images.githubusercontent.com/15934200/39093008-6a69067e-45cd-11e8-9802-7db74f72a55d.png)
![224260_20180422012349_1](https://user-images.githubusercontent.com/15934200/39093009-6a833080-45cd-11e8-9479-b71ce82722ca.png)
![224260_20180422012511_1](https://user-images.githubusercontent.com/15934200/39093011-6a9ea270-45cd-11e8-829a-f34d260e179a.png)
![224260_20180422012839_1](https://user-images.githubusercontent.com/15934200/39093012-6ab9936e-45cd-11e8-885a-99590ba27e13.png)
![224260_20180422013053_1](https://user-images.githubusercontent.com/15934200/39093013-6ad3ad6c-45cd-11e8-9d3f-6c81276584db.png)

**Comment by Fersigal** [comment]
![image](https://user-images.githubusercontent.com/11538773/39096853-391b6ca0-4655-11e8-8cc1-f47bc120df48.png)
Which important items are you actually gonna toss over there ???
![image](https://user-images.githubusercontent.com/11538773/39096859-42aa0e02-4655-11e8-9551-73cdb1a2255b.png)
That's not a map related bug and you're not actually controlling the zone there, someone whose standing there, either is losing the zone or is afking
![image](https://user-images.githubusercontent.com/11538773/39096868-5af01966-4655-11e8-8462-c42fe8209042.png)
You can't kill zombies there
![image](https://user-images.githubusercontent.com/11538773/39096872-70339136-4655-11e8-8004-b700097972b5.png)
That's a very tryharded jump just for getting a zombie there, you'd need A) A teammate or yourself, get infected get there and then you have to stay there, wasting an entirety of time just to get there, This is also far from the zone and the zone will just drop down to 0 regardless if ur staying there, the amount of zombies is less compared to the other fixed spot at the pole, this doesn't actually impact the zone.

**Comment by AtheistNMRiH** [comment]
fixed in r8791

**Comment by Winning117** [comment]
Confirmed fixed in src-r4405/dev-r8791.
