### ISSUE TITLE
(public) weapons lose their glowing from objective boundaries if you dropped them from your inventory

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#959]
not really a big issue but still

1) play a map with highlighted weapon (mainly welder and extinguisher e.g. cabin, lakeside, brooklyn, fema and etc.)
2) pick up weapon and drop it -> it doesn't glow anymore, but compass still show a blip

**Comment by dysphie** [comment]
It would appear that they lose their targetname on pickup, which the game uses to determine glow outlines.

**Comment by felis-catus** [comment]
Fixed in src-r5123.
