### ISSUE TITLE
nms_notld map issues

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#961]
Found in src-r4405/dev-r8792.

![224260_20180427165117_1](https://user-images.githubusercontent.com/15934200/39389542-714c8aa4-4a3e-11e8-8520-2f69171d7080.png)
![224260_20180427165145_1](https://user-images.githubusercontent.com/15934200/39389543-716287c8-4a3e-11e8-98dc-54cc1147950a.png)
![224260_20180427165226_1](https://user-images.githubusercontent.com/15934200/39389544-7179d8c4-4a3e-11e8-8597-7531458ebc0d.png)
![224260_20180427165652_1](https://user-images.githubusercontent.com/15934200/39389545-719170c4-4a3e-11e8-8b5f-6f49267e48dc.png)
![224260_20180427165800_1](https://user-images.githubusercontent.com/15934200/39389546-71b9db40-4a3e-11e8-976b-e1e224dfc6a1.png)
![224260_20180427165905_1](https://user-images.githubusercontent.com/15934200/39389547-71d3548a-4a3e-11e8-90ab-7db3b34bbb8d.png)
![224260_20180427170128_1](https://user-images.githubusercontent.com/15934200/39389548-71f4ea8c-4a3e-11e8-8737-c308bc492102.png)
![224260_20180427170408_1](https://user-images.githubusercontent.com/15934200/39389549-721f02cc-4a3e-11e8-97bf-28d61502240c.png)
![224260_20180427170506_1](https://user-images.githubusercontent.com/15934200/39389550-72479660-4a3e-11e8-82fc-5584630aa295.png)
![224260_20180427170746_1](https://user-images.githubusercontent.com/15934200/39389551-72684c16-4a3e-11e8-9af2-a30212304a73.png)
![224260_20180427171011_1](https://user-images.githubusercontent.com/15934200/39389552-7286747a-4a3e-11e8-8c80-e8e9028a7b9e.png)

**Comment by AtheistNMRiH** [comment]
fixed in r8795

**Comment by Winning117** [comment]
Confirmed fixed in src-r4435/dev-r8795.
