### ISSUE TITLE
nms_isolated map issues

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#962]
Found in src-r4405/dev-r8792.

![224260_20180427171957_1](https://user-images.githubusercontent.com/15934200/39389839-7c64e9ce-4a41-11e8-84c9-8e52b01bc1ca.png)
![224260_20180427172016_1](https://user-images.githubusercontent.com/15934200/39389840-7c866da6-4a41-11e8-9797-b3168d91adc3.png)
![224260_20180427172136_1](https://user-images.githubusercontent.com/15934200/39389842-7ca788ba-4a41-11e8-8d88-e645e3c36e0b.png)
![224260_20180427172238_1](https://user-images.githubusercontent.com/15934200/39389843-7cc78d9a-4a41-11e8-828f-a16bef5b0258.png)
![224260_20180427172431_1](https://user-images.githubusercontent.com/15934200/39389844-7ce577ec-4a41-11e8-98f4-b4e5013470aa.png)
![224260_20180427172513_1](https://user-images.githubusercontent.com/15934200/39389845-7d0d8b60-4a41-11e8-9840-04c9f503c755.png)
![224260_20180427172527_1](https://user-images.githubusercontent.com/15934200/39389846-7d398292-4a41-11e8-9456-f0d197d01264.png)
![224260_20180427172601_1](https://user-images.githubusercontent.com/15934200/39389847-7d648578-4a41-11e8-8c01-e25687af8226.png)
![224260_20180427172626_1](https://user-images.githubusercontent.com/15934200/39389848-7d88738e-4a41-11e8-9562-0f0f7312d93c.png)
![224260_20180427172838_1](https://user-images.githubusercontent.com/15934200/39389849-7dac9232-4a41-11e8-927d-1756153ce200.png)

**Comment by AtheistNMRiH** [comment]
fixed in r8795

**Comment by Winning117** [comment]
Confirmed fixed in src-r4435/dev-r8795.
