### ISSUE TITLE
nms_midwest map issues

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#963]
Found in src-r4405/dev-r8792.

![224260_20180427173944_1](https://user-images.githubusercontent.com/15934200/39390375-bfde4ec8-4a48-11e8-9174-7b6a8bf6b00d.png)
![224260_20180427174015_1](https://user-images.githubusercontent.com/15934200/39390376-bff4f394-4a48-11e8-9ff0-4f31292a0cea.png)
![224260_20180427174135_1](https://user-images.githubusercontent.com/15934200/39390377-c009ea2e-4a48-11e8-96bb-72425b017f57.png)
![224260_20180427174807_1](https://user-images.githubusercontent.com/15934200/39390378-c020053e-4a48-11e8-9846-188f20c2b789.png)
![224260_20180427181357_1](https://user-images.githubusercontent.com/15934200/39390379-c0357b76-4a48-11e8-970c-daab053eef60.png)
![224260_20180427181533_1](https://user-images.githubusercontent.com/15934200/39390380-c0525868-4a48-11e8-90ad-8225a98bf31c.png)
![224260_20180427181858_1](https://user-images.githubusercontent.com/15934200/39390381-c07170fe-4a48-11e8-820f-5c29676335d9.png)
![224260_20180427182541_1](https://user-images.githubusercontent.com/15934200/39390382-c0944eb2-4a48-11e8-8237-437ac6fe544d.png)
![224260_20180427182555_1](https://user-images.githubusercontent.com/15934200/39390383-c0bd5262-4a48-11e8-9b53-e46a42d29a90.png)
![224260_20180427182646_1](https://user-images.githubusercontent.com/15934200/39390384-c0e321e0-4a48-11e8-8510-2511cf77d7b2.png)

**Comment by Bubka3** [comment]
I see you've stepped up your screenshot game. Nice work on these.

**Comment by Winning117** [comment]
Tested in src-r4435/dev-r8797 which targeted this issue, the following issues are still present:

![224260_20180506135226_1](https://user-images.githubusercontent.com/15934200/39677798-fdff6d6a-5135-11e8-9169-7ae771a7e45d.png)
![224260_20180506135404_1](https://user-images.githubusercontent.com/15934200/39677799-fe1c7b4e-5135-11e8-987a-22b1206e98a5.png)
![224260_20180506135652_1](https://user-images.githubusercontent.com/15934200/39677800-fe404a56-5135-11e8-8c78-07631b77dd73.png)

**Comment by Winning117** [comment]
Tested in src-r4469/dev-r8820 which targeted this issue, the following issues are still present:
![224260_20180519125933_1](https://user-images.githubusercontent.com/15934200/40272647-8fd5f464-5b65-11e8-8046-1c4112a6dba9.png)
![224260_20180519125939_1](https://user-images.githubusercontent.com/15934200/40272648-8ff37728-5b65-11e8-91bc-9f677e587ab7.png)
![224260_20180519130033_1](https://user-images.githubusercontent.com/15934200/40272649-901452e0-5b65-11e8-9b07-3c190d111b74.png)

**Comment by Winning117** [comment]
Tested in src-r4469/dev-r8824. Adding 'overclipping' issues so that the player can jump where expected.

![224260_20180530132543_1](https://user-images.githubusercontent.com/15934200/40746259-d43092b6-640e-11e8-9e25-2ccef069509f.png)
![224260_20180530132659_1](https://user-images.githubusercontent.com/15934200/40746260-d44a1dee-640e-11e8-940a-03208fe567c3.png)
![224260_20180530132730_1](https://user-images.githubusercontent.com/15934200/40746261-d46531ba-640e-11e8-8395-e37656e10201.png)
![224260_20180530132846_1](https://user-images.githubusercontent.com/15934200/40746262-d4803ed8-640e-11e8-9bcf-ea13be1fa623.png)
![224260_20180530132908_1](https://user-images.githubusercontent.com/15934200/40746263-d4b338c4-640e-11e8-9cef-51ee9dfd0a6a.png)
![224260_20180530133217_1](https://user-images.githubusercontent.com/15934200/40746264-d4dd0492-640e-11e8-9c74-331e9fddac12.png)

**Comment by Loboo** [comment]
Players with token do not revive in wave 9 and 10.
I'm not sure if the other players respawned.
The server had realism disabled and I had respawned before without problems.
There was no supply drop either. Not even calling him with the flare gun.

![midwest fail](https://user-images.githubusercontent.com/46422135/54328939-88226800-45ee-11e9-8f51-170b5f0ead7c.jpg)

**Comment by Winning117** [comment]
Confirmed fixed in r8878
