### ISSUE TITLE
Shelter, displacements not properly sewn

### ISSUE THREAD

**Issue by DDysphie** [nmrih/source-game#964]
Number 1 actually hurt me a few times, the rest is cosmetic:

1. https://youtu.be/ZKISO0kCIjw

![20180506114422_1](https://user-images.githubusercontent.com/11559683/39674523-9cb189a6-5123-11e8-8a6f-5a9d5d2a1226.png)

2.
![20180506114520_1](https://user-images.githubusercontent.com/11559683/39674534-bfc8ae60-5123-11e8-9abd-89267e291f5a.jpg)

3.
![20180506114533_1](https://user-images.githubusercontent.com/11559683/39674535-bffca63e-5123-11e8-82d1-9006d827bf31.jpg)

4.
![20180506114545_1](https://user-images.githubusercontent.com/11559683/39674536-c023216a-5123-11e8-9f4b-67238d29ad6c.jpg)

**Comment by AtheistNMRiH** [comment]
fixed in r8800
