### ISSUE TITLE
Ammo check with tFg voice says "loads" instead of "rounds"

### ISSUE THREAD

**Issue by Ryan-nmrih** [nmrih/source-game#966]
tFg's ammo check audio files are his reload lines mistakenly renamed. For example, these are the same sounds:

"*I got six loads left!*"
player\reload\tfg\06**loads**_01.wav
player\ammocheck\tfg\06**rounds**_01.wav

The intended audio still exists under `player\ammocheck\alt1`:

"*I only have six rounds\!*"
player\ammocheck\alt1\6rounds1.wav

This issue is present in both the public and dev builds.

**Comment by Bubka3** [comment]
commited dev-8798

**Comment by DDysphie** [comment]
Confirmed fixed in r8799
