### ISSUE TITLE
Items' red/green inventory glow should take priority over their objective glow colour

### ISSUE THREAD

**Issue by Ryan-nmrih** [nmrih/source-game#967]
Highlighted items flicker between their objective colour and their inventory colour. This can cause confusion if the objective colour is similar to the red/green inventory scheme. For example, a flickering green objective glow can be mistaken as indicating the player has room for an item when they really don't.

Here's an example of the flicker effect: https://i.imgur.com/1mgvSB4.gifv

This is a very minor issue present in both builds.

The following screenshots are from nmo_boardwalk. The welder's green objective glow is shown every other frame which makes it look like the welder can be picked up even though the player's inventory is completely full.

![One frame, it's red](https://user-images.githubusercontent.com/37752555/39697465-8f57279e-51e0-11e8-876b-545b3a65b138.jpg)
![The next frame, it's green](https://user-images.githubusercontent.com/37752555/39697475-91e74c0a-51e0-11e8-9e67-aa115644386a.jpg)

**Comment by DDysphie** [comment]
This might be more of a code problem? I've also encountered it in Shelter

**Comment by Ryan-nmrih** [comment]
You're right. It doesn't make sense to tie this issue to a specific map. Perhaps the inventory glow should take priority over the objective glow.

**Comment by Winning117** [comment]
I think map objective items shouldn't even have a green or red glow to avoid confusion.

**Comment by felis-catus** [comment]
Fixed in src-r5114.
