### ISSUE TITLE
[dev-r8815] nmo_brooklyn map bugs

### ISSUE THREAD

**Issue by Holycrapjimhox** [nmrih/source-game#971]
**• Item Softlocks:**

1)
![20180507135640_1](https://user-images.githubusercontent.com/35630284/39716396-a1d6366e-5206-11e8-8419-fa7601afbe41.jpg)
![20180507135708_1](https://user-images.githubusercontent.com/35630284/39716397-a1fb3680-5206-11e8-9dcd-6b3027e5b156.jpg)
![20180507142614_1](https://user-images.githubusercontent.com/35630284/39716468-d50a59ca-5206-11e8-9896-e21225993c5e.jpg)
(you can bug almost any objective item on top of the van)
**FIXED**

2) 
![20180507140802_1](https://user-images.githubusercontent.com/35630284/39716406-a87336b6-5206-11e8-9848-42dd433a60ba.jpg)
![20180507140808_1](https://user-images.githubusercontent.com/35630284/39716407-a899cede-5206-11e8-914b-5dd8ccc0ed6e.jpg)
(you can also probably bug the gascan here)
**FIXED**

3)
![20180507141407_1](https://user-images.githubusercontent.com/35630284/39716420-b2e16bb8-5206-11e8-884c-de6d4b1039f8.jpg)
![20180507141445_1](https://user-images.githubusercontent.com/35630284/39716423-b52dbc50-5206-11e8-9ccb-bb47cc714ef8.jpg)
(the entire shelf should be clipped)
**FIXED**

4) 
![20180507142105_1](https://user-images.githubusercontent.com/35630284/39716438-c21466bc-5206-11e8-9c01-a4a5c3ea056e.jpg)
(all of these blue vending machines allow you to bug items underneath them, all of them should be clipped)
**FIXED**

5)
![20180507143044_1](https://user-images.githubusercontent.com/35630284/39716527-fc6d29d4-5206-11e8-9a4c-dfde424c4e94.jpg)
![20180507143124_1](https://user-images.githubusercontent.com/35630284/39716529-fc90fc60-5206-11e8-9eda-3260cd6a054d.jpg)
![20180507143139_1](https://user-images.githubusercontent.com/35630284/39716530-fcb28c5e-5206-11e8-93d6-eea2259637f8.jpg)
![20180507143301_1](https://user-images.githubusercontent.com/35630284/39716532-fcd3b30c-5206-11e8-9f47-429bb50f9bd7.jpg)
![20180507143413_1](https://user-images.githubusercontent.com/35630284/39716535-fcf74cae-5206-11e8-8182-601576f6c521.jpg)
**FIXED**

**• Errors that could potentially become softlocks:**

1)
![20180507135116_1](https://user-images.githubusercontent.com/35630284/39716556-12d07564-5207-11e8-906f-1d9e4698bf3b.jpg)
(you can get it down from there, but it's tricky)
**FIXED**

2)
![20180507140018_1](https://user-images.githubusercontent.com/35630284/39716574-1f0b86f2-5207-11e8-92d5-4b0dd486b39d.jpg)
(I think that if you jump correctly enough you could bug the hook there, extending the clip wouldn't hurt IMO)
**FIXED**

3)
![20180507140052_1](https://user-images.githubusercontent.com/35630284/39716600-2f982f52-5207-11e8-9d53-3532e07cc91d.jpg)
(most items can be placed there and it's tricky to get them back)
**FIXED**

4)
![20180507143830_1](https://user-images.githubusercontent.com/35630284/39716611-3c9d5722-5207-11e8-9421-ddc2e24610c9.jpg)
(the clip doesn't extend up to the ceiling, so maybe it can cause a softlock if zombie boosting is used)
**FIXED**

5) Kart items loose their glow and disappear from the compass on the "Load up the van" objective, allowing trolls to hide them anywhere and cause a softlock.
![20180507143700_1](https://user-images.githubusercontent.com/35630284/39716793-ac0cedc0-5207-11e8-9c91-5cd8b9706b68.jpg)
![20180507143737_1](https://user-images.githubusercontent.com/35630284/39716794-ac35a350-5207-11e8-8665-45964efbc5b1.jpg)
**FIXED**

**• Visual/gameplay oddities:**

1) Randomly spawned boards appear vertically and clipping with geometry.
![20180507134649_1](https://user-images.githubusercontent.com/35630284/39716707-6f657fc2-5207-11e8-8fe6-175773a0bff4.jpg)
![20180507134828_1](https://user-images.githubusercontent.com/35630284/39716708-6f94be40-5207-11e8-97bd-0245afa0ea9b.jpg)
![20180507135830_1](https://user-images.githubusercontent.com/35630284/39716709-6fb7df60-5207-11e8-825e-c0d3b2209785.jpg)
**NOT FIXED, CODE ISSUE**

2) The fire next to the car crash doesn't appear if you get the Hook scenario.
![20180507135259_1](https://user-images.githubusercontent.com/35630284/39716733-81f993c6-5207-11e8-9e7d-c493c9354230.jpg)
![20180507143438_1](https://user-images.githubusercontent.com/35630284/39717068-8a67b10e-5208-11e8-9813-3b0287f8b349.jpg)
**NOT RELEVANT, CODE ISSUE**

3) The semi-opened drawers don't have collision with anything.
![20180507141319_1](https://user-images.githubusercontent.com/35630284/39716763-995db9a2-5207-11e8-8d54-5f3eb1e58256.jpg)
**NOT RELEVANT**

4) There's some strange shader issue on the floor of this kitchen.
![20180507141535_1](https://user-images.githubusercontent.com/35630284/39716868-ed357bfa-5207-11e8-8d18-56165eae621d.jpg)
![20180507141541_1](https://user-images.githubusercontent.com/35630284/39716869-edcbbc14-5207-11e8-8f3f-d5b957cfa821.jpg)
![20180507141546_1](https://user-images.githubusercontent.com/35630284/39716870-eded8178-5207-11e8-9d4f-2532732d5b68.jpg)
**FIXED**

5) Unnecessary vphysclips that break realism to some degree:
![20180507141710_1](https://user-images.githubusercontent.com/35630284/39716916-1ecd8ff4-5208-11e8-888e-a84212be196c.jpg)
![20180507141715_1](https://user-images.githubusercontent.com/35630284/39716917-1efb4e6c-5208-11e8-89de-8f6d6a799221.jpg)
**NOT FIXED** (If they were to be removed, then several props near spawn should be clipped, like the desktop where the code is, the water dispenser in the interrogation room and maybe a toilet)
 
6) Damage taken for blocking the elevator door should be a lot higher, to stop trolls from stopping the elevator for a long time.
![20180507141915_1](https://user-images.githubusercontent.com/35630284/39716937-28fdf5fe-5208-11e8-8e0d-e95adfcb4089.jpg)
**FIXED**

7) You take fall damage when falling on the glass. This is not present on public build and it can cause bleeding. It's more realistic, but idk if it's a good change gameplay-wise.
![20180507142513_1](https://user-images.githubusercontent.com/35630284/39716972-453f38ea-5208-11e8-9a04-4bbc86166e22.jpg)
**NOT FIXED, CODE REGRESSION**

8) The radio is missing on the Kart scenario.
![20180507143219_1](https://user-images.githubusercontent.com/35630284/39717033-6ee1ca3c-5208-11e8-8dfd-b1a8c9465757.jpg)
**FIXED**

9) You can see the truck spawning out of nowhere when the kart stops.
![20180507143638_1](https://user-images.githubusercontent.com/35630284/39717098-9cd2347c-5208-11e8-87bf-d681367a5078.jpg)
**KINDA FIXED** (you would have to modify the entire programming of the objective to make it look better, I think this is good enough)

**Comment by AtheistNMRiH** [comment]
1) boards probably won't spawn anymore in "ammo" class in random_spawner (reminder for @felis-catus !)
3)
![image](https://user-images.githubusercontent.com/11333747/39718564-d7e5d822-5260-11e8-9083-9029341b9449.png)
not sure if it should be changed because it could lead to undesirable consequences (e.g. god spots)

**Comment by AtheistNMRiH** [comment]
visual oddities 2) probably code bug, I have seen that plenty of times on other maps as well, sometimes info_particle_system doesn't appear
visual oddities 5) I guess they prevent from unnesessary backtracking

other issues are fixed in r8812

**Comment by Holycrapjimhox** [comment]
• More softlocks:
![20180514160949_1](https://user-images.githubusercontent.com/35630284/40133936-76a349a6-5917-11e8-87bf-d33fd781f969.jpg)
![20180514162141_1](https://user-images.githubusercontent.com/35630284/40133937-76c7d0be-5917-11e8-840b-7a1dc8c097cf.jpg)
![20180514162531_1](https://user-images.githubusercontent.com/35630284/40133987-9051db6a-5917-11e8-8682-c7b325fb2f8a.jpg)
![20180514165102_1](https://user-images.githubusercontent.com/35630284/40134007-9cbaf12a-5917-11e8-8003-200fe25ae704.jpg)
![20180514165135_1](https://user-images.githubusercontent.com/35630284/40134008-9cdf6c8a-5917-11e8-889d-11a19009fc5a.jpg)
![20180514165446_1](https://user-images.githubusercontent.com/35630284/40134018-a3b98b3a-5917-11e8-83d0-b4ed0f8d5faf.jpg)
![20180514170256_1](https://user-images.githubusercontent.com/35630284/40134019-a3dfd272-5917-11e8-955f-3c7aff5a4753.jpg)
![20180514170311_1](https://user-images.githubusercontent.com/35630284/40134020-a4010b68-5917-11e8-9cf4-e5eb0a6471d0.jpg)
![20180514170425_1](https://user-images.githubusercontent.com/35630284/40134021-a422ef12-5917-11e8-95ac-112a23589131.jpg)
![20180514170437_1](https://user-images.githubusercontent.com/35630284/40134022-a444ffa8-5917-11e8-82cd-652af9349fb4.jpg)
(the lower part of the fence needs clipping)

• Semi-softlocks (you can get it back but it's tricky):
![20180514161858_1](https://user-images.githubusercontent.com/35630284/40133960-85f5be8e-5917-11e8-9aca-8d12be54250b.jpg)
