### ISSUE TITLE
Zombie melee swing can hurt players standing behind the zombie

### ISSUE THREAD

**Issue by Ryan-nmrih** [nmrih/source-game#972]
Players will take damage from zombies who have their back to the player if the player is close enough. This happens in both the public and dev build.

https://streamable.com/hr0tl
https://streamable.com/nihy5

**Comment by Holycrapjimhox** [comment]
Reported again here with more info and videos: https://github.com/nmrih/source-game/issues/1288
This entry should be closed to avoid confusion.

**Comment by felis-catus** [comment]
Duplicate of #1288
