### ISSUE TITLE
Player models missing physics and flying away

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#973]
Version: public and dev
Video: https://www.youtube.com/watch?v=w9MImju9vhI
Notes: Models found in [nmrih_dev\models\nmr_zombie]

The following player models are missing their .phy file:
badass_infected, butcher_infected, hunter_infected, roje_infected, runner, tammy

**Comment by felis-catus** [comment]
Bumping priority, this causes #1151.

**Comment by felis-catus** [comment]
Bumping priority to severe, likely a common crasher.

**Comment by felis-catus** [comment]
Related issues: #1151, #1226

**Comment by MacReady82** [comment]
I don't know if it's the same problem but when I kill some zombies like Tammy for example, it disappears and after a few seconds it reappears on the floor.

**Comment by felis-catus** [comment]
All models excl. "hunter_infected.mdl" are fixed, his catapulting body isn't related to missing PHY mesh, so I'll close this as resolved.
