### ISSUE TITLE
Losing items to healthcrates

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#974]
Version: public and dev build
Video: https://www.youtube.com/watch?v=CmQ0VM1RYl0

Steps to reproduce:
1) Place healthcrate
2) Drop item into healthcrate

Items dropped inside of a healthcrate can not be retrieved until the healthcrate is depleted. I believe that this could be fixed by having healthcrate stations become solid once the healthcrate is placed, as this would also prevent the player from walking inside of it and seeing through the object.

**Comment by Winning117** [comment]
If this can't be fixed via code I came up with a solution for mappers that can prevent this issue.

![image](https://user-images.githubusercontent.com/15934200/46934085-61461280-d00b-11e8-9336-450abc152654.png)

https://youtu.be/9RGF2HQwb4w

**Comment by felis-catus** [comment]
Going to leave this as is to avoid map breakage, mappers may fix it with the workaround above.
