### ISSUE TITLE
Character select/addon manager screen not closed when starting a game

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#975]
Version: public and dev build
Video: https://www.youtube.com/watch?v=XEpr5oYipAg

Steps to reproduce:
1) Open the character select screen
2) Start a server
3) Open the menu (Press esc) and see the player select screen

This allows the player to change their player model in the middle of the game which is not intended. The change applies as soon as the server changes levels.

**Comment by DDysphie** [comment]
I don't see the problem with this. It doesn't change their model mid-game. Also you can just do `charselect` on console
