### ISSUE TITLE
Item origins messed up

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#976]
Version: public and dev
Notes: these files are found in [nmrih_dev\models\weapons]. I have tried moving the item origins but it displaces the item animations so I believe the animations need to be edited as well.

The following items have their item origin messed up which allows them to spawn underground/be dropped through walls/show up with a red outline even though they can be grabbed:
- w_fa_1911
- w_fa_glock17
- w_fa_mkiii
- w_fa_sv10
- w_fa_sw686
- w_grenade
- w_me_chainsaw
- w_me_cleaver
- w_me_etool
- w_me_etool_pick
- w_me_fubar
- w_me_pickaxe
- w_me_wrench
- w_tool_welder

**Comment by Winning117** [comment]
Fixed in src-r4459/dev-r8813.

**Comment by Winning117** [comment]
Reverted in r8850 because it messed up the spawns in maps, so this issue persists again.

**Comment by felis-catus** [comment]
> because it messed up the spawns in maps

As a result this issue can't be fixed without altering every and each map, closing.
