### ISSUE TITLE
[dev-r8812] Underground, zombies get door stuck

### ISSUE THREAD

**Issue by DDysphie** [nmrih/source-game#978]
I played a round of Underground and had zombies on the other side get this door stuck. They would close it as soon as I tried to open it.

`setpos 6152.338379 3909.474854 1625.031250;setang 5.016012 120.431847 0.000000`

![20180510172738_1](https://user-images.githubusercontent.com/11559683/39893140-42357aa6-5479-11e8-8d33-df8a33c08093.jpg)

**Comment by Holycrapjimhox** [comment]
Oh, I've reported this to Atheist a long time ago. I hope he can fix it.

**Comment by AtheistNMRiH** [comment]
yeah, I thought I fixed it...

**Comment by AtheistNMRiH** [comment]
should be fixed in r8821

**Comment by DDysphie** [comment]
Confirmed fixed as of r8821
