### ISSUE TITLE
[dev-r8812] Underground, dropped items get elevator stuck

### ISSUE THREAD

**Issue by DDysphie** [nmrih/source-game#979]
Elevator got stuck by this dropped weapon, the weapon couldn't be picked up and the gate wouldn't open:
`setpos 3172.826904 4055.439941 1340.404053;setang 12.507946 -179.640045 0.000000`

![20180510170609_1](https://user-images.githubusercontent.com/11559683/39893664-e106ceb8-547a-11e8-9a20-398adad8424b.jpg)

**Comment by AtheistNMRiH** [comment]
fixed in r8821

**Comment by DDysphie** [comment]
Confirmed fixed as of r8821
