### ISSUE TITLE
nmo_brooklyn issues

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#982]
Found in src-r4459/dev-r8812.

![224260_20180511010221_1](https://user-images.githubusercontent.com/15934200/39916125-8925b5bc-54be-11e8-9ca6-0f429503441e.png)
![224260_20180511010229_1](https://user-images.githubusercontent.com/15934200/39916127-8943df42-54be-11e8-9716-828a41b05cfa.png)
![224260_20180511011028_1](https://user-images.githubusercontent.com/15934200/39916128-8960754e-54be-11e8-8ace-6d10803b749f.png)
![224260_20180511011115_1](https://user-images.githubusercontent.com/15934200/39916129-897db56e-54be-11e8-811d-60f565a6db65.png)
![224260_20180511011224_1](https://user-images.githubusercontent.com/15934200/39916130-8999fe7c-54be-11e8-842b-57aefbfcba54.png)
![224260_20180511011328_1](https://user-images.githubusercontent.com/15934200/39916131-89b7d35c-54be-11e8-8c0d-0535230a0d97.png)
![224260_20180511011457_1](https://user-images.githubusercontent.com/15934200/39916132-89dbbd94-54be-11e8-87c2-cc88559f2b6c.png)
![224260_20180511011532_1](https://user-images.githubusercontent.com/15934200/39916133-8a0a226a-54be-11e8-902f-4b8eb860dbef.png)
![224260_20180511011629_1](https://user-images.githubusercontent.com/15934200/39916134-8a3d365a-54be-11e8-989f-51a6c4c7ea0a.png)
![224260_20180511011753_1](https://user-images.githubusercontent.com/15934200/39916135-8a5e9f84-54be-11e8-8ac2-613d92a6ca1f.png)
![224260_20180511011819_1](https://user-images.githubusercontent.com/15934200/39916136-8a85260e-54be-11e8-94ea-ceec78906496.png)
![224260_20180511012630_1](https://user-images.githubusercontent.com/15934200/39916137-8aa660c6-54be-11e8-8b4f-b71ad79ddc1a.png)
![224260_20180511012956_1](https://user-images.githubusercontent.com/15934200/39916139-8ac9b2ec-54be-11e8-98f4-f0a4ee4a9559.png)
![224260_20180511013120_1](https://user-images.githubusercontent.com/15934200/39916140-8aec9118-54be-11e8-8a41-b8c2848e87bd.png)
![224260_20180511013153_1](https://user-images.githubusercontent.com/15934200/39916141-8b0b05bc-54be-11e8-9591-03c9e1b80700.png)
![224260_20180511013222_1](https://user-images.githubusercontent.com/15934200/39916142-8b2c0596-54be-11e8-9a40-6d9d20565ade.png)
![224260_20180511013728_1](https://user-images.githubusercontent.com/15934200/39916143-8b4c1e44-54be-11e8-8f27-fc3656f44039.png)
![224260_20180511013753_1](https://user-images.githubusercontent.com/15934200/39916144-8b6fdd98-54be-11e8-80be-4c0293f7b78a.png)
![224260_20180511013823_1](https://user-images.githubusercontent.com/15934200/39916145-8bc1cbbc-54be-11e8-838e-96105e844444.png)
![224260_20180511013928_1](https://user-images.githubusercontent.com/15934200/39916147-8c1512a4-54be-11e8-881e-454b51a20a69.png)

**Comment by Winning117** [comment]
Fixed in atheist's new version that will be pushed to dev.

**Comment by Winning117** [comment]
Was doing some more testing and found this severe bug, I can't even complete the level if I don't stand in front of the truck (https://www.youtube.com/watch?v=5vUJhYNbdoI)

Also, more softlocks:
![224260_20180514160122_1](https://user-images.githubusercontent.com/15934200/40029470-af143504-5799-11e8-9082-7ce372a8421c.png)
![224260_20180514160656_1](https://user-images.githubusercontent.com/15934200/40029471-af31c614-5799-11e8-84f0-96558c7ba45e.png)
![224260_20180514160749_1](https://user-images.githubusercontent.com/15934200/40029472-af508da6-5799-11e8-8e56-5f3b0e014a02.png)
![224260_20180514161013_1](https://user-images.githubusercontent.com/15934200/40029473-af6b4952-5799-11e8-85c2-989b9b3c8219.png)
![224260_20180514161131_1](https://user-images.githubusercontent.com/15934200/40029474-af883bd4-5799-11e8-95ba-86335d0c3c0d.png)
![224260_20180514161225_1](https://user-images.githubusercontent.com/15934200/40029475-afaae56c-5799-11e8-859b-767df381da18.png)
![224260_20180514161529_1](https://user-images.githubusercontent.com/15934200/40029476-afd40bc2-5799-11e8-9ee0-35ca5b5f041d.png)
![224260_20180514161535_1](https://user-images.githubusercontent.com/15934200/40029477-affb3b20-5799-11e8-963c-b526dd50dc02.png)
![224260_20180514161904_1](https://user-images.githubusercontent.com/15934200/40029478-b0227730-5799-11e8-8874-a21d341c4b4d.png)
![224260_20180514161958_1](https://user-images.githubusercontent.com/15934200/40029479-b04a8162-5799-11e8-991c-bf5269d49551.png)
![224260_20180514162406_1](https://user-images.githubusercontent.com/15934200/40029480-b0744f88-5799-11e8-8d10-0404c2eaa214.png)
![224260_20180514163700_1](https://user-images.githubusercontent.com/15934200/40029482-b09fc7b2-5799-11e8-9c03-3f8d9c44a869.png)
![224260_20180514163928_1](https://user-images.githubusercontent.com/15934200/40029483-b0c8d0d0-5799-11e8-99ed-09c6330dcc19.png)

**Comment by AtheistNMRiH** [comment]
should be fixed in r8816

**Comment by Winning117** [comment]
Confirmed fixed in src-r4463/dev-r8816.
