### ISSUE TITLE
Weapons with variants have the wrong name

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#984]
Version: public and dev build

The SKS has the incorrect name for the variant without a bayonet.
![224260_20180513005231_1](https://user-images.githubusercontent.com/15934200/39965116-1f80e4fc-5648-11e8-8b12-39d60d11c9f3.png)

This affects the SKS (no-bayo), Ruger 10/22 (25mag), and M16A4(carryhandle).

**Comment by Winning117** [comment]
r8883 seems to have resolved this issue even though it wasn't directly trying to fix this issue

**Comment by Texas-C** [comment]
`fa_sks` names "Simonov SKS (Bayonet)"
![sks_1](https://user-images.githubusercontent.com/10080946/73813081-e913e980-4819-11ea-84ee-b3110e98167b.png)

`fa_sks_nobayo` names "Simonov SKS (Bayonet)" too.. ("Simonov SKS(no bayonet)" could be better? O.O)
![sks_2](https://user-images.githubusercontent.com/10080946/73813091-eb764380-4819-11ea-9163-9aac0a9da211.png)

**Comment by Winning117** [comment]
`/resources/nmrih_english.txt` is correct, seems that whatever references the weapon names is set to "Weapon_fa_sks" instead of "Weapon_fa_sks_nobayo" etc.

**Comment by Winning117** [comment]
As pointed out by Dysphie the incorrect files lie within `nmrih_dev\scripts\weapons`

**Comment by felis-catus** [comment]
Fixed in dev-r8957.
