### ISSUE TITLE
(dev) player gets damage when falling on func_breakable

### ISSUE THREAD

**Issue by AtheistNMRiH** [nmrih/source-game#989]
example maps are brooklyn (glass in garage) and fema (vent section)

regression from r8793

**Comment by Winning117** [comment]
Version src-r4487/dev-r8826 partially addressed this issue:
> - Players no longer bleedout from environmental damage (infected water, steam, fall damage, etc.)

Players still take damage but will no longer bleed out from it

**Comment by AtheistNMRiH** [comment]
confirmed fixed in r8874
