### ISSUE TITLE
TNT Glitch Friendly fire

### ISSUE THREAD

**Issue by overmase** [nmrih/source-game#991]
This video was used for reporting by the offender, and only the first 17 seconds you want to see

https://youtu.be/GCAuxxu-GIE

server setting  〉FF-off
player 〉Not infected

Steps to reproduce
1: throw TNT 
2: get out of the game before exploding

I think that the cause of death is "crushed to death" and because it has not been treated as a thrown player, I think it is causing such a thing

This has increased the number of players interfering with the progress of the game

(I'm translating this, sorry for bad english)

**Comment by Winning117** [comment]
Duplicate of [#827](https://github.com/nmrih/source-game/issues/827), needs to be closed.

**Comment by overmase** [comment]
oh..sorry.. It was an existing problem

**Comment by Winning117** [comment]
Yeah it was already fixed in dev build so no need to worry about it. You can close the issue
