### ISSUE TITLE
Chainsaw infinite fuel when used inside a supply drop

### ISSUE THREAD

**Issue by overmase** [nmrih/source-game#992]
Test video
https://youtu.be/SQd-eZFeSV8

Steps to reproduce

1 Start a chain saw

2 Hold attack, open supply box

chainsaw can attack without cons

This Glitch is effective only with nmo_shelter ...

**Comment by Winning117** [comment]
That spot in nmo_shelter has already been patched on dev build, but this may apply to supply drops elsewhere.

**Comment by DDysphie** [comment]
He's not reporting the spot, he's reporting the infinite fuel bug.

**Comment by Winning117** [comment]
I was referring to 

> This Glitch is effective only with nmo_shelter ...

**Comment by overmase** [comment]
can do it with a map where you can get a chainsaw at mns

Keeping the supply box open keeps the open state even if the next supply drop comes

You can push the player in this state and make it stand in front of the entrance or use it

**Comment by felis-catus** [comment]
Fixed in src-r6276.
