### ISSUE TITLE
nmo_toxteth map issues

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#993]
Found in src-r4469/dev-r8821.

![224260_20180428165929_1](https://user-images.githubusercontent.com/15934200/40396120-3f44ad42-5de0-11e8-8b88-76e0738e5c37.png)
![224260_20180428165951_1](https://user-images.githubusercontent.com/15934200/40396121-3f64774e-5de0-11e8-9e1c-d49e957ebd16.png)
![224260_20180428170026_1](https://user-images.githubusercontent.com/15934200/40396122-3f8461ee-5de0-11e8-9e95-e7e4b6b840ad.png)
![224260_20180522160822_1](https://user-images.githubusercontent.com/15934200/40396127-41528988-5de0-11e8-9e8e-a4660172c7ba.png)
![224260_20180428170059_1](https://user-images.githubusercontent.com/15934200/40396130-45f685c0-5de0-11e8-9c73-54569065d96e.png)
![224260_20180428170329_1](https://user-images.githubusercontent.com/15934200/40396141-52535a78-5de0-11e8-8152-9a2c884d460a.png)
![224260_20180428170409_1](https://user-images.githubusercontent.com/15934200/40396142-52867728-5de0-11e8-8fcc-a875ca63de59.png)
![224260_20180428170427_1](https://user-images.githubusercontent.com/15934200/40396143-52b8386c-5de0-11e8-9d66-80a4d4ce22ee.png)
![224260_20180428170521_1](https://user-images.githubusercontent.com/15934200/40396144-52edf9b6-5de0-11e8-8e3b-9dd2ddd7f64c.png)
![224260_20180522161556_1](https://user-images.githubusercontent.com/15934200/40396150-54e10c18-5de0-11e8-94f6-ff632a77b17d.png)
![224260_20180428170659_1](https://user-images.githubusercontent.com/15934200/40396158-5f7ace2a-5de0-11e8-84c4-19c4beed7ace.png)
![224260_20180428171154_1](https://user-images.githubusercontent.com/15934200/40396175-6d9f7122-5de0-11e8-8832-9c53311234ae.png)
![224260_20180428171213_1](https://user-images.githubusercontent.com/15934200/40396176-6dd8f38e-5de0-11e8-845a-8bdb74dbb771.png)
![224260_20180428171231_1](https://user-images.githubusercontent.com/15934200/40396177-6e11f530-5de0-11e8-8971-115ceeb4d690.png)
![224260_20180428171451_1](https://user-images.githubusercontent.com/15934200/40396178-6e5137f4-5de0-11e8-8127-efc6b3c6b7c9.png)
![224260_20180428171603_1](https://user-images.githubusercontent.com/15934200/40396179-6e919182-5de0-11e8-8343-0fd269d74edb.png)
![224260_20180428171749_1](https://user-images.githubusercontent.com/15934200/40396180-6ed0fdcc-5de0-11e8-9889-a21c66e1e7e3.png)
![224260_20180428172641_1](https://user-images.githubusercontent.com/15934200/40396181-6f0f80ec-5de0-11e8-98d7-db396e5c3376.png)
![224260_20180522162040_1](https://user-images.githubusercontent.com/15934200/40396192-79edf930-5de0-11e8-94b3-efc1279ed36a.png)
![224260_20180522162509_1](https://user-images.githubusercontent.com/15934200/40396193-7a5f9d74-5de0-11e8-897b-197dba6cc3ea.png)
![224260_20180522163155_1](https://user-images.githubusercontent.com/15934200/40396195-7ad0c828-5de0-11e8-929a-b763efcf63ae.png)
![224260_20180522163330_1](https://user-images.githubusercontent.com/15934200/40396196-7b48c10c-5de0-11e8-9756-59ef9fdefe5e.png)
![224260_20180522163535_1](https://user-images.githubusercontent.com/15934200/40396198-7bc4c54a-5de0-11e8-9452-4354e2b6445d.png)
![20180530185848_1](https://user-images.githubusercontent.com/15934200/40757714-baf56756-643e-11e8-86ca-18b09f657974.jpg)
![20180530185928_1](https://user-images.githubusercontent.com/15934200/40757715-bb33e3fa-643e-11e8-9440-8c487fa9266d.jpg)
![20180530190036_1](https://user-images.githubusercontent.com/15934200/40757716-bb5a6250-643e-11e8-8a64-44c82a4f9921.jpg)
![20180530190123_1](https://user-images.githubusercontent.com/15934200/40757718-bbc5b83e-643e-11e8-9070-153c575c1768.jpg)
![20180530190142_1](https://user-images.githubusercontent.com/15934200/40757719-bc0931b8-643e-11e8-88a5-d34f1ec6638d.jpg)
![20180530190358_1](https://user-images.githubusercontent.com/15934200/40757720-bc54b0d4-643e-11e8-92f5-2aa91edd5647.jpg)
![20180530190656_1](https://user-images.githubusercontent.com/15934200/40757721-bc7a3656-643e-11e8-8174-175ec9727a38.jpg)
![20180530190811_1](https://user-images.githubusercontent.com/15934200/40757722-bcac8b42-643e-11e8-8fe3-a7420d79ba12.jpg)

**Comment by AtheistNMRiH** [comment]
fixed some of issues in r8879

**Comment by Winning117** [comment]
Important issues fixed in r8879 :D
