### ISSUE TITLE
nmo_zephyr map issues

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#994]
Found in in src-r4469/dev-r8821.
Note: please change brushes to use item/player clip instead of using invisible brushes when possible. It makes it much harder to test oob and softlocks when we can't see what the boundaries are.

![224260_20180529173148_1](https://user-images.githubusercontent.com/15934200/40693018-067e4420-636a-11e8-8046-9f0bff4ea1e4.png)
![224260_20180529173327_1](https://user-images.githubusercontent.com/15934200/40693019-0699275e-636a-11e8-8c61-648fb0d17a79.png)
![224260_20180529174147_1](https://user-images.githubusercontent.com/15934200/40693072-450cb9f6-636a-11e8-9322-82b56ce6cb97.png)
![224260_20180419233127_1](https://user-images.githubusercontent.com/15934200/40398805-bffd46a2-5dee-11e8-9ee2-82d75eb1bcb2.png)
![224260_20180419233233_1](https://user-images.githubusercontent.com/15934200/40398806-c02a9abc-5dee-11e8-9d1d-84f026598e46.png)
![224260_20180419233333_1](https://user-images.githubusercontent.com/15934200/40398808-c05f0360-5dee-11e8-874b-058889cce754.png)
![224260_20180419233454_1](https://user-images.githubusercontent.com/15934200/40398810-c08f4246-5dee-11e8-9db3-b5066307b37e.png)
![224260_20180419233934_1](https://user-images.githubusercontent.com/15934200/40398811-c0c1ccc0-5dee-11e8-97d2-09beb62ce12b.png)
![224260_20180529173848_1](https://user-images.githubusercontent.com/15934200/40693106-7cd514d2-636a-11e8-96f5-a1d6accd90d6.png)
![224260_20180529173822_1](https://user-images.githubusercontent.com/15934200/40693108-839955f8-636a-11e8-8a16-f688d30a7ec1.png)
![224260_20180529174430_1](https://user-images.githubusercontent.com/15934200/40693114-8f999d5e-636a-11e8-8807-8f20ab38fbe3.png)
![224260_20180522174424_1](https://user-images.githubusercontent.com/15934200/40398817-c58f8152-5dee-11e8-95ea-c97d0bd15808.png)
![224260_20180529174539_1](https://user-images.githubusercontent.com/15934200/40693143-aa3f9668-636a-11e8-8da1-7b5c5598b9fe.png)
![224260_20180529174624_1](https://user-images.githubusercontent.com/15934200/40693150-b615041e-636a-11e8-9e9b-1d81eef4d695.png)
![224260_20180529174749_1](https://user-images.githubusercontent.com/15934200/40693151-b6332e26-636a-11e8-9dda-eaad52c60d00.png)
![224260_20180529174841_1](https://user-images.githubusercontent.com/15934200/40693152-b6533db0-636a-11e8-987b-4ba4280c478e.png)
![224260_20180522180814_1](https://user-images.githubusercontent.com/15934200/40398822-c68b90e6-5dee-11e8-9742-deabcc0baae0.png)
![224260_20180522180826_1](https://user-images.githubusercontent.com/15934200/40398824-c6bf6f06-5dee-11e8-875f-b701ce4ab251.png)
![224260_20180522181130_1](https://user-images.githubusercontent.com/15934200/40398826-c707e3b2-5dee-11e8-8638-7fd7f2efca37.png)
![224260_20180522181350_1](https://user-images.githubusercontent.com/15934200/40398827-c73b3fc8-5dee-11e8-875e-ceff2ff1de65.png)

**Comment by Winning117** [comment]
Tested in src-r4469/dev-r8824, some of the above issues were not fixed and I found some more issues.

![40693040-1b57aed6-636a-11e8-9eea-b12f2aabcb86](https://user-images.githubusercontent.com/15934200/40749940-8a294f6c-641a-11e8-9e67-5867056afd59.png)
![20180530144209_1](https://user-images.githubusercontent.com/15934200/40749962-97c1ff16-641a-11e8-9caa-88662379a165.jpg)
![20180530144132_1](https://user-images.githubusercontent.com/15934200/40749974-a015d084-641a-11e8-9379-a514e27d53a9.jpg)
![40693048-276a0340-636a-11e8-906b-9c0bbf5545b1](https://user-images.githubusercontent.com/15934200/40749980-a464053e-641a-11e8-9c98-77700bb13ace.png)
![20180530143824_1](https://user-images.githubusercontent.com/15934200/40750008-b46c7268-641a-11e8-89ec-059054471594.jpg)
![20180530143956_1](https://user-images.githubusercontent.com/15934200/40750009-b63568fc-641a-11e8-8acd-e61080a69b94.jpg)
![20180530143530_1](https://user-images.githubusercontent.com/15934200/40750036-ccaaa156-641a-11e8-8c46-397167190533.jpg)
![20180530142932_1](https://user-images.githubusercontent.com/15934200/40750044-d05903f6-641a-11e8-972a-fb9bbdb9620a.jpg)
![20180530144813_1](https://user-images.githubusercontent.com/15934200/40750048-d331476e-641a-11e8-8d7b-0e8f984a001a.jpg)
![20180530141814_1](https://user-images.githubusercontent.com/15934200/40750055-d9af5748-641a-11e8-9be1-a93a5d01f85d.jpg)
![40693106-7cd514d2-636a-11e8-96f5-a1d6accd90d6](https://user-images.githubusercontent.com/15934200/40750061-dd2af6b6-641a-11e8-9e43-6be170f9a78d.png)
![20180530144410_1](https://user-images.githubusercontent.com/15934200/40750064-e0581cc4-641a-11e8-920e-ea1619ed798f.jpg)
![20180530144340_1](https://user-images.githubusercontent.com/15934200/40750066-e3421ba6-641a-11e8-9a7d-27e89d5d96f9.jpg)
![20180530142240_1](https://user-images.githubusercontent.com/15934200/40750114-09ac19a4-641b-11e8-9b87-fad04e157819.jpg)
![20180530142450_1](https://user-images.githubusercontent.com/15934200/40750070-e61972f2-641a-11e8-82f6-196898f7da16.jpg)
![20180530142802_1](https://user-images.githubusercontent.com/15934200/40750072-e906101a-641a-11e8-823b-2d892e19e95d.jpg)

**Comment by DDysphie** [comment]
> https://user-images.githubusercontent.com/15934200/40749940-8a294f6c-641a-11e8-9e67-5867056afd59.png

To call this a stretch would be an understatement.
Could we please restrict reports to spots that affect the game's flow and integrity?

**Comment by Winning117** [comment]
It’s already a softlock spot, it takes the mapmaker a second to make it no longer a god spot.

**Comment by Winning117** [comment]
Supposedly fixed in r8824, need to check.

**Comment by Winning117** [comment]
Not fixed in r8824.

**Comment by Winning117** [comment]
The following still need to be fixed in r8966

![image](https://user-images.githubusercontent.com/15934200/74630930-80c5e180-5110-11ea-834e-6c45b5d6b01e.png)
![image](https://user-images.githubusercontent.com/15934200/74630897-7277c580-5110-11ea-9e7f-fd696a4bfe72.png)
![image](https://user-images.githubusercontent.com/15934200/74630948-88858600-5110-11ea-9e30-307d277c4dc3.png)
![image](https://user-images.githubusercontent.com/15934200/74631079-eade8680-5110-11ea-85aa-0692252818c3.png)
![image](https://user-images.githubusercontent.com/15934200/74631132-12355380-5111-11ea-836e-443006704fe2.png)

**Comment by Winning117** [comment]
Confirmed fixed by r8967 + r8972
