### ISSUE TITLE
nmo_broadway2 map issues

### ISSUE THREAD

**Issue by Winning117** [nmrih/source-game#995]
Found in src-r4469/dev-r8821. I'll check it again after these get fixed because god this map has so many softlocks.

![224260_20180529153510_1](https://user-images.githubusercontent.com/15934200/40690567-8ecb7b9e-635c-11e8-8e6b-4aeeb10ec83d.png)
![40406511-cad434f6-5e15-11e8-890d-6982309cc8a9](https://user-images.githubusercontent.com/15934200/40690594-92cfcd62-635c-11e8-84ee-358cbfbd5485.png)
![224260_20180529152653_1](https://user-images.githubusercontent.com/15934200/40690559-8dad6394-635c-11e8-8fae-0e0d348deeb7.png)
![224260_20180529153550_1](https://user-images.githubusercontent.com/15934200/40690568-8ef9e362-635c-11e8-8583-001d59bd3dd4.png)
![224260_20180529152902_1](https://user-images.githubusercontent.com/15934200/40690560-8dca4d38-635c-11e8-8151-7c5460dd816f.png)
![224260_20180529152947_1](https://user-images.githubusercontent.com/15934200/40690561-8de67f6c-635c-11e8-8cbb-e02ef479ccb1.png)
![224260_20180529153020_1](https://user-images.githubusercontent.com/15934200/40690562-8e07a11a-635c-11e8-9f2e-06c2607c992f.png)
![224260_20180529153111_1](https://user-images.githubusercontent.com/15934200/40690563-8e2451c0-635c-11e8-90cd-943c2c6061a4.png)
![224260_20180529153120_1](https://user-images.githubusercontent.com/15934200/40690564-8e486420-635c-11e8-8fbd-9902975ac60a.png)
![224260_20180529153302_1](https://user-images.githubusercontent.com/15934200/40690565-8e75f7c8-635c-11e8-8517-65f65f99cb75.png)
![224260_20180529153401_1](https://user-images.githubusercontent.com/15934200/40690566-8ea11c78-635c-11e8-9ec0-c110df4e0032.png)
![224260_20180529153622_1](https://user-images.githubusercontent.com/15934200/40690569-8f252ab8-635c-11e8-80bc-6a517a74f624.png)
![224260_20180529153641_1](https://user-images.githubusercontent.com/15934200/40690570-8f52eca0-635c-11e8-8b10-5f2296dae306.png)
![224260_20180529153654_1](https://user-images.githubusercontent.com/15934200/40690571-8f7f1e7e-635c-11e8-969b-6bbcf77cb3c9.png)
![224260_20180529153804_1](https://user-images.githubusercontent.com/15934200/40690572-8f99d692-635c-11e8-9efc-694c8445fe44.png)
![224260_20180529153816_1](https://user-images.githubusercontent.com/15934200/40690573-8fe4319c-635c-11e8-979b-e15b6a78d31e.png)
![224260_20180529154051_1](https://user-images.githubusercontent.com/15934200/40690574-900d5658-635c-11e8-911b-4511a23e77e8.png)
![224260_20180529154128_1](https://user-images.githubusercontent.com/15934200/40690575-903ca174-635c-11e8-9e90-03382737763c.png)
![224260_20180529154146_1](https://user-images.githubusercontent.com/15934200/40690576-906c4adc-635c-11e8-95e0-3d990e8ab738.png)
![224260_20180529154224_1](https://user-images.githubusercontent.com/15934200/40690577-9088db34-635c-11e8-8507-cb51f7ab7a92.png)
![224260_20180529154241_1](https://user-images.githubusercontent.com/15934200/40690578-90b6c8be-635c-11e8-9946-6f39ba3b503c.png)
![224260_20180529154255_1](https://user-images.githubusercontent.com/15934200/40690579-90e4cc96-635c-11e8-89f8-f9e5b5aaf5fb.png)
![224260_20180529154307_1](https://user-images.githubusercontent.com/15934200/40690580-9110cb3e-635c-11e8-89ee-edd1323cf991.png)
![224260_20180529154334_1](https://user-images.githubusercontent.com/15934200/40690581-913c8922-635c-11e8-86ec-ea14034b1f42.png)
![224260_20180529154350_1](https://user-images.githubusercontent.com/15934200/40690582-91677b46-635c-11e8-92f9-df8e2f095237.png)
![224260_20180529154711_1](https://user-images.githubusercontent.com/15934200/40690586-9194828a-635c-11e8-9e7a-c6bd020ed39f.png)
![224260_20180529154842_1](https://user-images.githubusercontent.com/15934200/40690587-91b5a5a0-635c-11e8-8910-1686ebfaecc4.png)
![224260_20180529155227_1](https://user-images.githubusercontent.com/15934200/40690588-91e31a30-635c-11e8-9cec-f517eb43b3d5.png)
![224260_20180529155326_1](https://user-images.githubusercontent.com/15934200/40690589-92161dc2-635c-11e8-969b-43853cfb1072.png)
![224260_20180529155352_1](https://user-images.githubusercontent.com/15934200/40690590-9249a25a-635c-11e8-9e3e-c6f203805365.png)
![224260_20180529155409_1](https://user-images.githubusercontent.com/15934200/40690592-9275e112-635c-11e8-818b-7e0a90aeb882.png)
![224260_20180529155550_1](https://user-images.githubusercontent.com/15934200/40690593-92a1923a-635c-11e8-8b9d-8b5caca490f9.png)
![40406513-cb094646-5e15-11e8-9632-34e251323e8a](https://user-images.githubusercontent.com/15934200/40690595-92fd193e-635c-11e8-9a81-5ed8bd51548f.png)
![40406515-cb585ff6-5e15-11e8-919a-fcfece3cee59](https://user-images.githubusercontent.com/15934200/40690596-932a0692-635c-11e8-8291-ea95fc9e1054.png)
![40406517-cbae4f56-5e15-11e8-8496-d848f7edabec](https://user-images.githubusercontent.com/15934200/40690597-935856d2-635c-11e8-9237-e5656e468cf2.png)
![40406518-cbd85d14-5e15-11e8-885a-f14a6048891e](https://user-images.githubusercontent.com/15934200/40690598-93836ea8-635c-11e8-9def-77497ef4729f.png)
![40406522-cc6d9aaa-5e15-11e8-8675-e3c84c3698f1](https://user-images.githubusercontent.com/15934200/40690599-93aee650-635c-11e8-8d1c-c614979d1964.png)
![40406524-cce9dc32-5e15-11e8-8dce-7a90f9fe2843](https://user-images.githubusercontent.com/15934200/40690600-93d8d14a-635c-11e8-94f1-c7e3960b7372.png)
![40406525-cd0a4062-5e15-11e8-852a-731e7beea75e](https://user-images.githubusercontent.com/15934200/40690601-940501e8-635c-11e8-862d-b7eb8b246cfa.png)
![40406526-cd38900c-5e15-11e8-89ab-cce5c3a7b59d](https://user-images.githubusercontent.com/15934200/40690602-9431156c-635c-11e8-9c5a-444e64f26ab4.png)
![40406527-cd586918-5e15-11e8-8396-be084b26dd53](https://user-images.githubusercontent.com/15934200/40690603-944d4dfe-635c-11e8-950f-0ca8e5491b12.png)
![40406528-cd7cbf7a-5e15-11e8-92f7-8b5145cc5993](https://user-images.githubusercontent.com/15934200/40690604-947ae85e-635c-11e8-9e39-de7176ba747d.png)
![40406530-cde8dc28-5e15-11e8-84e6-0679f62e855b](https://user-images.githubusercontent.com/15934200/40690605-94a5df14-635c-11e8-8a20-f9b209971c24.png)
![40406532-ce147810-5e15-11e8-9451-533d0ba8f4e7](https://user-images.githubusercontent.com/15934200/40690607-94d83f9a-635c-11e8-89e1-d529b0873693.png)
![40406533-ce3fe5ae-5e15-11e8-8dbf-a1432d25be9b](https://user-images.githubusercontent.com/15934200/40690609-95070816-635c-11e8-8446-66d0bde574b8.png)
![40406534-ce6a9c04-5e15-11e8-8264-e1baeea5aa4e](https://user-images.githubusercontent.com/15934200/40690610-95320b7e-635c-11e8-8a50-89bab2269e3f.png)
![40406535-ce9322d2-5e15-11e8-9c3a-b6a66560ebc8](https://user-images.githubusercontent.com/15934200/40690611-95625cb6-635c-11e8-9650-94f5eed5f27c.png)
![40406536-cec037b8-5e15-11e8-8b5a-393867336126](https://user-images.githubusercontent.com/15934200/40690612-958eebc8-635c-11e8-80d1-b098f57c5d95.png)
![40406537-ceff60aa-5e15-11e8-8b92-e6b2c457834b](https://user-images.githubusercontent.com/15934200/40690613-95bae08e-635c-11e8-9e45-63c868f5bb50.png)

**Comment by Holycrapjimhox** [comment]
First two out of bounds are impossible to do in a legit playthrough without using cheats. Zombies never spawn on the stairs and can't get on them by any means. I suggest removing those two cause it doesn't make sense to report them.

**Comment by Winning117** [comment]
Infected player dies -> zombie on stairs. Sure it’s not easy to do but it’s not “impossible to do in a legit playthrough.”

**Comment by AtheistNMRiH** [comment]
most bugs fixed in r9006
