### ISSUE TITLE
Player's camera jitters when standing on prop_ragdoll

### ISSUE THREAD

**Issue by Ryan-nmrih** [nmrih/source-game#997]
https://streamable.com/rz489

Some custom maps use prop_ragdolls which cause the player's view to shake violently up and down when stood on. The shaking is worse with higher latency. It is difficulty to fight or push zombies during this seizure as many of the player's actions don't seem to register on the zombie. This happens in both public and dev builds.

**Comment by felis-catus** [comment]
Revision src-r4888 adds `prop_ragdoll_multiplayer` that spawns a client-side ragdoll instead (it has no player collisions). This does not replace the existing `prop_ragdoll` entity, so I recommend using maphacks to patch the community maps.

**Comment by Ryan-nmrih** [comment]
Awesome, thank you felis!
